.github/PULL_REQUEST_TEMPLATE.md, .gitignore, CONTRIBUTING.md
*Before* this PR:
No PR template, no gitignore, not CONTRIBUTING guidelines
*After* this PR:
Provide the default setup using files in the tools repository:
* gitignore
* PR template
* CONTRIBUTING
=> feat(setup): Adds pull request template and contributing file

.travis.yml
⚠️  Depends on #1
The root repository won't run any CI tasks.
The repository run CI tasks.
=> chore(CI): Adds travis Ci basic builds

README.md
=> docs: add containers

README.md
icons isn't imported into Talend/ui.
icons is imported into Talend/ui.
=> docs(cmf): Updates cmf import documentation

packages/icons/src/svg/folder-closed.svg
updated viewbox, added empty code line at the bottom
=> fix: update folder-closed.svg

packages/icons/src/svg/folder.svg
updated the viewbox, minor changed on path
=> fix: update folder.svg

packages/components/src/SidePanel/SidePanel.scss, packages/components/stories/Layout.js
=> fix(SidePanel): toggle icon size

.travis/after_success_deploy.sh, .travis/after_success_static.sh
Branch `master` has no showcases
Generated showcases from brach `master` will be deploy to [talend.surge.sh](http://talend.surge.sh) each time that a pull request will be merged.
=> chore: deploy master to Surge

packages/components/.storybook/head.html, packages/components/stories/List.js
Custom styles that is applied to all stories when it is used to demonstrate a particular feature.
The custom styles are scoped and the scope className is applied to the target stories.
=> chore(Components): List stories more scoped

packages/forms/__tests__/Form.test.js, packages/forms/__tests__/__snapshots__/Form.test.js.snap, packages/forms/src/Form.js, packages/forms/stories/index.js
The actions onClick don't receive the state.
The actions onClick receive the state as a second argument.
=> feat(forms): Adds form state to action onClick

output/cmf.eslint.txt, output/components.eslint.txt, packages/components/src/List/List.component.js, packages/components/src/List/List.scss, packages/components/src/List/List.test.js, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/stories/List.js
When List items are empty, there is only a blank field.
We have now a `No result found` message
=> feat(Components): No Result Found in List when items are empty

packages/forms/src/Form.js
JavaScript was throwing an error in case of action without onClick.
No more errors.
=> fix(forms): onClick error on submit action

packages/forms/src/widgets/DatalistWidget/DatalistWidget.scss
If blur is triggered with unknown value, datalist will be reset to blank
If blur is triggered with unknown value, datalist will be reset to the last known valid value
In addition, datalist widget style uses Bootstrap theme variables instead
That PR will be merged to #134
=> patch(forms): datalist

packages/components/src/Notification/Notification.scss, packages/components/yarn.lock
The icon size is 20px
The icon size is 16px as defined on Frontify:
http://guidelines.talend.com/document/92132#/messaging-communication/toast-in-notification
=> fix(Notification): fix icon size

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/cmf/src/__snapshots__/cmfConnect.test.js.snap, packages/cmf/src/cmfConnect.js, packages/cmf/src/cmfConnect.test.js, packages/cmf/src/componentState.js, packages/cmf/src/componentState.test.js
The state is update with undefined state, so in fact it's kept.
The state is removed at unmount;
=> fix(cmf/componentState): delete the state (really)

packages/components/e2e/component-objects/pom.xml
Maven for Components-object is currently not able to push packaged artifacts to Talend Nexus.
Maven for Components-object is now able to push packaged artifacts to Talend Nexus.
=> chore(components-object): provide Nexus deployment capability to components-objects

.surge/index.html
Add CMF docs and coverage links
=> docs(surge): update index links

output/containers.eslint.txt, packages/containers/__mocks__/react-talend-components.js, packages/containers/src/HomeListView/HomeListView.test.js, packages/containers/src/List/List.container.js, packages/containers/src/Notification/Notification.container.js, packages/containers/src/SidePanel/SidePanel.container.js
Lots of warnings during the tests.
No warnings at all:
=> chore(containers): remove warnings in tests

packages/components/.storybook/config.js, packages/components/package.json, packages/components/stories/Action.js
We have to write each story by thinking of all cases
Stories are generated with all cases combinations
https://github.com/evgenykochetkov/react-storybook-addon-props-combinations
=> chore(components): introduces react-storybook-addon-props-combinations

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap, packages/forms/src/widgets/EnumerationWidget/utils/utils.js, packages/forms/src/widgets/EnumerationWidget/utils/utils.test.js
- Possible to edit multiple values at the same time
- Header "Edit a value" when editing an item no more displayed
- Not Possible to edit multiple values at the same time
- Header "Edit a value" when editing an item displayed
=> fix(component/forms): Enumeration widget : fix blur and header when edit

output/components.eslint.txt, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/HeaderBar.scss, packages/components/src/HeaderBar/HeaderBar.snapshot.test.js, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap, packages/components/src/HeaderBar/__snapshots__/config.js, packages/components/src/HeaderBar/index.js, packages/components/src/index.js, packages/components/stories/HeaderBar.js, packages/components/stories/index.js
No HeaderBar component
Frontify: http://guidelines.talend.com/document/92132#/navigation-layout/app-header
=> feat(Components/HeaderBar): create HeaderBar component

packages/components/src/SidePanel/SidePanel.scss
Link to Frontify: http://guidelines.talend.com/document/92132#/navigation-layout/side-panel
=> fix(components/SidePanel): fix toggle icon for SidePanel

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Search state is not loading when aborted
searchcriteria is not well passed to component
call handler when search is aborted
=> fix(enumeration): search state

packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap, packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap, packages/components/stories/HeaderBar.js, packages/components/yarn.lock, packages/icons/src/svg/environment.svg
=> feat(icons/environment): add icon for environment

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
ids are not keep in item in constructor
ids on each item is now well kept in state
=> fix(enumeration): keep ids in items

.travis/after_success_git.sh, output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt
If you push before the CI have ended the job, you loose your job.
The ci is doing push force.
The CI do not push force BUT
it will no update the current branch with the lint and screenshots;
=> chore: remove push force from travis

packages/components/src/Badge/Badge.scss
Badges are not aligned with our guidelines
Badges render is closer to guidelines
=> fix(components): align badge style with guidelines

packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap, packages/icons/src/svg/sliders.svg
=> feat(icons/sliders): add sliders icon

packages/components/src/SidePanel/SidePanel.scss
SidePanel component differ from Frontify description
SidePanel component follow the Frontify description
Frontify: http://guidelines.talend.com/document/92132#/navigation-layout/side-panel
=> feat(components/SidePanel): fix style in accordance with Frontify

output/components.eslint.txt, packages/components/src/List/Toolbar/Pagination/Pagination.component.js, packages/components/src/List/Toolbar/Pagination/Pagination.scss, packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap, packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap, packages/components/src/List/__snapshots__/List.test.js.snap
add ability to specify custom icons
Icons are hardcoded to be font-awesome
Icons can be specified by handy api
=> feat(components/list): pagination icons customization

packages/components/src/TabBar/TabBar.component.js, packages/components/src/TabBar/TabBar.scss, packages/components/src/TabBar/TabBar.snapshot.test.js, packages/components/src/TabBar/TabBar.test.js, packages/components/src/TabBar/__snapshots__/TabBar.snapshot.test.js.snap, packages/components/src/TabBar/__snapshots__/config.js, packages/components/src/TabBar/index.js, packages/components/src/index.js, packages/components/stories/TabBar.js, packages/components/stories/index.js, packages/components/yarn.lock
No components for Tabs
Added a component for Tab and TabBar
Frontify: http://guidelines.talend.com/document/92132#/navigation-layout/tabs
=> feat(components/TabBar): add TabBar component

output/components.eslint.txt, packages/components/src/List/DisplayTable/DisplayTable.component.js, packages/components/src/List/DisplayTable/DisplayTable.snapshot.test.js, packages/components/src/List/DisplayTable/__snapshots__/DisplayTable.snapshot.test.js.snap, packages/components/stories/List.js
If you try and render a list with an item set to 0. The item won't be
displayed.
You can now display zeros properly.
=> fix(components/List): Can't render zeros

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/src/List/ItemTitle/ItemTitle.scss
Flex shorthand is different for IE11
Flex shorthand is not used anymore
Will fix https://jira.talendforge.org/browse/TDP-3727
=> fix(components/List): ellipsis for items title for IE11

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap, packages/forms/stories/json/enumerationImport.json
Add a import mode in the enumerationWidget
Inverse add/Search button to respect the guidelines
=> feat(forms/enumeration-widget): allow upload

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/src/TabBar/TabBar.component.js, packages/components/yarn.lock
Warning about missing key property in child components
Violation fixed
=> fix(components/TabBar): fix key absence violation

output/forms.eslint.txt, packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js
Before we were just using the first attribute of the array as a value, now we send the whole array.
=> fix(forms): manage a list of value with coma separator

packages/components/src/Enumeration/Items/Items.scss
Horizontal scrollbar appears on the enumeration components
=> fix(components/enumeration): remove horizontal scrollbar

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js, packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
remove form nested. Only one form is authorized
=> fix(forms/enumeration-widget): remove form nested

packages/components/src/ActionBar/ActionBar.component.js, packages/components/stories/ActionBar.js
Dropdowns can't be added to the ActionBar.
Adds Dropdowns to the ActionsBar renderers.
=> feat(components): Adds Dropdown to ActionBar

packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.test.js, packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap, packages/components/stories/Drawer.js
There is no possibility to add TabBar to Drawer
TabBar is added to Drawer
=> feat(components/Drawer): add TabBar to Drawer

output/components.sasslint.txt, packages/components/src/HttpError/HttpError.scss
` 3:31  error  Hex values should use the shorthand format - 3 characters where possible  hex-length`
=> style(components/httperror): fix sasslint warn

output/components.sasslint.txt, packages/components/src/Progress/Progress.component.js, packages/components/src/Progress/Progress.scss, packages/components/src/Progress/Progress.test.js, packages/components/src/Progress/__snapshots__/Progress.test.js.snap, packages/components/stories/Progress.js
- Impossible to add a progress in a container
- Impossible to display an infinite progress
- Prop `contained` added to remove the CSS `fixed` property
- CSS keyframes to animate an infinite progress
=> feat(components): infinite and contained progress

packages/components/src/Layout/Layout.component.js, packages/components/src/Layout/Layout.test.js, packages/components/src/Layout/OneColumn/OneColumn.component.js, packages/components/src/Layout/TwoColumns/TwoColumns.component.js, packages/components/src/Layout/__snapshots__/Layout.test.js.snap, packages/components/stories/Layout.js
When add TabBar inside Layout content it can be scrolled out
TabBar component is added to Layout and became out of scroll
=> feat(components/Layout): add TabBar

packages/components/src/Layout/OneColumn/OneColumn.component.js, packages/components/src/Layout/OneColumn/__snapshots__/OneColumn.test.js.snap, packages/components/src/Layout/TwoColumns/TwoColumns.component.js, packages/components/src/Layout/TwoColumns/__snapshots__/TwoColumns.test.js.snap, packages/components/src/Layout/__snapshots__/Layout.test.js.snap, packages/components/src/WithDrawer/withDrawer.scss
The PR code was complicated and hard to maintain
Revert lot of files to have the same result
=> fix(Component/Layout) : make the code easier

packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap, packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
If there is no suggestion, get error
Avoid undefined access error
=> fix(forms/datalist): avoid undefined access error

packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
items can be null
test items before it length
=> fix: avoid undefined reference

packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
Ctrl click was needed to unselect an item.
It can now me done with a click.
=> fix(forms): unselect item on click in enumeration

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/forms/src/widgets/DatalistWidget/DatalistWidget.js, packages/forms/src/widgets/DatalistWidget/DatalistWidget.test.js, packages/forms/stories/index.js, packages/forms/yarn.lock
Datalist trigger onchange even if value does not change.
Check value before trigger onchange
=> fix(forms/datalist): do not trigger onchange if value does not change

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/src/List/DisplayTable/DisplayTable.component.js, packages/components/src/List/DisplayTable/DisplayTable.scss, packages/components/src/List/List.component.js, packages/components/src/List/List.scss, packages/components/src/List/List.test.js, packages/components/src/List/__snapshots__/List.test.js.snap
keeping the display of columns even if no items to display
move the message inside the rendering of Table display
=> fix(component/list/TFD-1033): keep columns with empty list

output/containers.eslint.txt, packages/containers/src/Actions/Actions.test.js, packages/containers/src/List/List.test.js
`✖ 15 problems (14 errors, 1 warning)`
`✖ 13 problems (12 errors, 1 warning)`
=> chores(containers): fix proptypes and lint errors

output/components.eslint.txt, packages/components/src/ObjectViewer/JSONLike/index.js, packages/components/src/ObjectViewer/Table/Table.test.js, packages/components/src/VirtualizedList/CellTitle/CellTitleInput.component.js
`✖ 16 problems (16 errors, 0 warnings)`
`✖ 12 problems (12 errors, 0 warnings)`
=> chores(components): fix proptypes and lint errors

output/cmf.eslint.txt, packages/cmf/src/Dispatcher.js, packages/cmf/src/UIRouter.js, packages/cmf/src/cmfConnect.js, packages/cmf/src/route.js, packages/cmf/src/settings.js
`✖ 17 problems (16 errors, 1 warning)`
`✖ 2 problems (1 error, 1 warning)`
=> chores(cmf): fix proptypes and lint errors

output/cmf.eslint.txt, packages/cmf/__tests__/__snapshots__/componentState.test.js.snap, packages/cmf/__tests__/componentState.test.js, packages/cmf/src/componentState.js, packages/cmf/src/reducers/componentsReducers.js
WARNING : This is supposed to be merged on `feat/cmf/improve-redux-action-on-component` branch
Just try to reduce code.
=> Reduce code a little

packages/forms/src/widgets/DatalistWidget/DatalistWidget.js, packages/forms/src/widgets/DatalistWidget/__snapshots__/DatalistWidget.test.js.snap, packages/forms/stories/index.js, packages/forms/yarn.lock
https://github.com/Talend/ui/issues/489
Add placeholder to datalist
=> feat(forms/DatalistWidget): add placeholder

packages/forms/src/UIForm/UIForm.connect.js, packages/forms/src/UIForm/UIForm.container.js, packages/forms/src/UIForm/fields/Button/Button.component.js, packages/forms/src/UIForm/fields/Button/Buttons.component.js, packages/forms/src/UIForm/fields/Button/SingleButton.component.js, packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js, packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js, packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js, packages/forms/src/UIForm/fields/Radios/Radios.component.js, packages/forms/src/UIForm/fields/Select/Select.component.js, packages/forms/src/UIForm/fields/Text/Text.component.js, packages/forms/src/UIForm/fields/TextArea/TextArea.component.js
PropTypes are not accurate anough
Improve propTypes adding the required ones and missing ones
=> chore(UIForms): fix proptypes

packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.scss
The JSONSchemaRenderer fields style isn't following the guidelines.
**What is the chosen solution to this problem?** 
Fixes the fields style according the the guidelines.
=> fix(JSONSchemaRenderer): Fixes style

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/stories/Enumeration.js
The storybook on Enumeration component is changing a ref for 1 story so it is applied to all stories.
Immutability
=> fix(Enumeration): fix a ref change

package.json
After the travis improvement (#589), package.json is not aligned anymore
Fix the travis script call
=> chore: adapt package.json to new travis changes

packages/components/.storybook/webpack.config.js, packages/containers/.storybook/webpack.config.js, packages/forms/.storybook/webpack.config.js
Docs build time takes almost 6 minutes on Travis.
Removing the uglify step from the docs building process cuts build time
by 4x. Plus it adds better debugging capabilities.
=> chore(docs): Improve docs build time

output/forms.eslint.txt, packages/components/stories/Notification.js, packages/forms/src/widgets/DatalistWidget/DatalistWidget.js, packages/forms/src/widgets/ListViewWidget/ListViewWidget.handlers.js, packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
This reverts commit dddd57506db7a7f1ebe67ab18245847717a5974b.
ListView broken
Revert
=> Revert "fix(all): dangerous setState usage in components (#507)"

packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss, packages/components/stories/TreeView.js, packages/components/yarn.lock
The paddings between actions is too small
The paddings between actions is ok
Jira for it: https://jira.talendforge.org/browse/TIPAAS-10750
=> fix(components/TreeView): fix padding between actions

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/src/Enumeration/Enumeration.component.js, packages/components/src/Enumeration/Enumeration.scss, packages/components/src/Enumeration/Enumeration.snapshot.test.js, packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap, packages/components/stories/Enumeration.js, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
https://jira.talendforge.org/browse/TMC-11003
The Enumeration component should display the text "The list is empty", if the list is empty. 
font style is the hint style (placeholder) on the forms;
Also after search/ filter done, if there is no result there should be a text "No results"
render EmptyListPlaceholder when there's no item in list.
=> feat(components): Enumeration - empty list

packages/forms/src/widgets/DatalistWidget/DatalistWidget.js, packages/forms/src/widgets/DatalistWidget/DatalistWidget.scss, packages/forms/stories/index.js
=> fix(forms/datalist): ie blur issue

packages/components/src/SidePanel/SidePanel.component.js, packages/components/src/SidePanel/SidePanel.scss, packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
Updated hover and selected colors of items on the sidebar
http://guidelines.talend.com/document/92132#/navigation-layout/left-side-panel
Also toggle button now has title instead of tooltip
Updated styles, toggle tooltip replaced with title.
=> feat(SidePanel/TSCH-56): update colors and toggle button title

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
=> fix(List): item title display

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/theme.sasslint.txt, packages/components/src/List/List.component.js, packages/components/src/List/Toolbar/Toolbar.component.js
A lot of warning: 
The prop `products.t` is marked as required
Fixed poptypes definitions
=> fix(List): fix proptypes warnings

packages/cmf-cqrs/README.md, packages/cmf/README.md, packages/components/README.md, packages/containers/README.md, packages/icons/README.md, packages/logging/README.md, packages/theme/README.md
@talend organization is not taken in account in readme
@talend organization is taken in account in readme
=> doc: fix informations in readme

packages/generator/generators/react-cmf/templates/package.json, version.js
The version script was not considering the new sagas packages.
Do what needs to be done : ie update the script to get some references to the sagas package
=> fix(version): Add sagas package

packages/components/src/Icon/Icon.component.js, packages/components/stories/ActionDropdown.js, packages/components/stories/ActionSplitDropdown.js, packages/theme/example/index.html, packages/theme/screenshots.config.json, packages/theme/src/theme/_dropdowns.scss
add css to customize the behavior  when we expand to the up
=> feat(theme): dropup

packages/components/src/List/Display/Display.propTypes.js, packages/components/src/List/DisplayLarge/DisplayLarge.component.js, packages/components/src/List/DisplayTable/DisplayTable.component.js, packages/components/src/List/DisplayTile/DisplayTile.component.js, packages/components/src/List/List.component.js, packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap, packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js, packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap, packages/components/src/VirtualizedList/ListTable/ListTable.component.js, packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap, packages/components/src/VirtualizedList/NoRows/NoRows.component.js, packages/components/src/VirtualizedList/NoRows/__snapshots__/NoRows.test.js.snap, packages/components/src/VirtualizedList/PropTypes.js, packages/components/src/VirtualizedList/RendererSelector.component.js, packages/components/src/VirtualizedList/VirtualizedList.component.js, packages/components/src/VirtualizedList/VirtualizedList.test.js, packages/components/src/VirtualizedList/__snapshots__/RendererSelector.test.js.snap, packages/components/src/VirtualizedList/__snapshots__/VirtualizedList.test.js.snap, packages/components/stories/List.js, packages/components/stories/config/i18n.js
List (and VirtualizedList) content are not i18n ready
Be able to internationalize (Virtualized)List content
=> feat(i18n): list content can be internationalized

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
Missing separator on help block
=> fix(HeaderBar): add missing separator

packages/components/src/VirtualizedList/ListGrid/ListGrid.scss, packages/components/src/VirtualizedList/ListTable/ListTable.scss
There is an outline on focus on the list
=> fix(Virtualized): remove outline on focus

packages/components/src/VirtualizedList/ListGrid/ListGrid.scss, packages/components/src/VirtualizedList/ListTable/ListTable.scss
=> Revert "fix(Virtualized): remove outline on focus"

.travis.yml, .travis/after_success_git.sh
Firefox seems to be unreachable from Travis CI
Disable screenshots system for now
=> chore: disable screenshots

packages/containers/src/index.js
=> feat(containers): remove module undefined

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.component.js, packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.scss, packages/components/src/VirtualizedList/CellTextIcon/__snapshots__/CellWithIcon.test.js.snap, packages/components/stories/List.js
Css problem with line height on the large list mode and icon cell renderer
fix css + new story
=> fix(List): fix CellRenderer for showing icon on the Large list mode

packages/cmf-cqrs/package.json, packages/cmf/__tests__/middlewares/error.test.js, packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap, packages/icons/src/svgs.js, packages/sagas/package.json
Unit tests do not pass on windows.
Correction of package.json. 
roots for jest pointed to a directory that does not exist.
=> fix: windows unit tests

packages/components/src/ListView/Items/Item/Item.component.js, packages/components/src/ListView/Items/Items.component.js, packages/components/src/ListView/Items/__snapshots__/items.snapshot.test.js.snap, packages/components/src/ListView/ListView.component.js, packages/components/stories/ListView.js, packages/forms/src/UIForm/fields/ListView/ListView.component.test.js, packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
Make posible to use switch selector for checkboxes in the ListView
New props isSwitchBox is added
=> feat(ListView/TPSVC-4033): add ability to use switch selectors

packages/cmf/scripts/cmf-settings.js
The script is not importing json source files
Import them
=> fix(cmf/script): load json files

BREAKING_CHANGES_LOG.md, output/containers.eslint.txt, packages/containers/.storybook/config.js, packages/containers/src/SidePanel/SidePanel.container.js, packages/containers/src/SidePanel/__snapshots__/SidePanel.test.js.snap, packages/containers/src/register.js, packages/generator/generators/react-cmf/templates/src/app/configure.js, packages/generator/generators/react-component/templates/src/full.container.js
SidePanel raise the folliwing error since 0.139.0 :
```
main.js:21 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `SidePanel`. Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `SidePanel`.
at invariant (invariant.js:42)
at instantiateReactComponent (instantiateReactComponent.js:72)
at instantiateChild (ReactChildReconciler.js:42)
at ReactChildReconciler.js:69 …
```
=> fix(containers): register all containers BREAKING CHANGE

packages/cmf/README.md, packages/cmf/scripts/cmf-settings.js, packages/cmf/scripts/utils/index.js
the script had a really bad behaviour on node 6 :-/
+ It's working now on node 6 ( thx to a dead trailing coma )
+ Not recursive by default but we can pass it an -r option to do so
+ you can specify path to json, not only folders
=> fix(cmf): cmf-settings to run on node 6 and improvements

output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/src/CircularProgress/CircularProgress.component.js, packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js, packages/forms/src/UIForm/fields/Button/SingleButton.component.js
Some PropTypes are not correct
Fix them
=> fix: propTypes oneOf/oneOfType

packages/cmf/howto/how-to-manage-collections.md
examples were using the old deprecated long redondant api
examples use the new shorter api
=> chore(cmf/doc): Update how-to-manage-collections

packages/components/src/Actions/Action/Action.component.js, packages/components/src/Actions/Action/Action.test.js, packages/containers/.storybook/config.js, packages/containers/examples/ExampleActionIconToggle.js, packages/containers/examples/index.js, packages/containers/src/Action/Action.connect.js, packages/containers/src/Action/__snapshots__/Action.test.js.snap, packages/containers/src/ActionButton/ActionButton.connect.js, packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js, packages/containers/src/ActionIconToggle/ActionIconToggle.connect.md, packages/containers/src/ActionIconToggle/ActionIconToggle.test.js, packages/containers/src/ActionIconToggle/__snapshots__/ActionIconToggle.test.js.snap, packages/containers/src/ActionIconToggle/index.js, packages/containers/src/index.js
We recently introduced icon toggles. But it was only the component.
Add the container
=> feat(Containers/Actions): icon toggle

packages/components/src/ConfirmDialog/ConfirmDialog.component.js, packages/components/src/List/Toolbar/Pagination/Pagination.component.js, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/VirtualizedList/PropTypes.js, packages/forms/src/Form.js, packages/forms/src/templates/ArrayFieldTemplate.js
Fix some prop-types and add some keys, that cause warnings in console
=> fix: fix warnings in console

packages/components/src/index.js
missing import for the skeleton
=> fix(components): missing Skeleton import

packages/components/src/PieChartButton/PieChartButton.component.js, packages/components/src/Skeleton/Skeleton.component.js, packages/components/src/Skeleton/Skeleton.md, packages/components/src/Skeleton/index.js, packages/components/stories/Skeleton.js
Const difficult to access
Move it with the component & add doc
=> chore(components): change const in skeleton & add doc

output/cmf-webpack-plugin.eslint.txt, output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/datagrid.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/e2e/component-objects/pom.xml, packages/components/e2e/component-objects/src/main/java/org/talend/component/SidePanel.java, packages/components/e2e/component-objects/src/test/java/org/talend/component/SidePanelTest.java
SidePanel e2e tests are broken since last release.
Repair it and add UTs
=> fix(components/sidepanel): fix e2e tests

packages/components/src/HeaderBar/HeaderBar.scss, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap, packages/components/src/Typeahead/Typeahead.component.js, packages/components/src/Typeahead/Typeahead.component.renderers.js, packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap, packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
=> fix(components/headerbar): search results container width

packages/components/src/Actions/Action/Action.component.js, packages/components/src/Actions/Action/Action.test.js, packages/components/src/Inject/Inject.component.js
If `getComponent` is undefined, an error is thrown.
Use `Inject` instead.
=> fix(components/actions): handle undefined getcomponent

output/cmf-webpack-plugin.eslint.txt, output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/datagrid.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/HeaderBar.scss, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
HeaderBar component transforms the user lastname to uppercase.
But the strategy of user inputs is not to transform them, display them as user typed it.
In [guideline](http://guidelines.talend.com/document/92132#/design-principles/font-styles)
```
All other UI elements, if not in this list, are displayed in lower case, or with the original case coming out from their source (database, etc.)
```
(The username is not in the exception list)
Remove the extra elements and style to perform the text transformation
=> fix(HeaderBar): remove username text transformation

output/cmf-webpack-plugin.eslint.txt, output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/datagrid.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt, packages/components/src/Actions/ActionButton/ActionButton.test.js, packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap, packages/components/src/Breadcrumbs/Breadcrumbs.component.js, packages/components/src/utils/getPropsFrom.js
I can't pass title attribute to Action component anymore
Add title to our white list
=> fix(components/action): title attribute

.travis/after_success_lint.sh, output/cmf-webpack-plugin.eslint.txt, output/cmf.eslint.txt, output/components.eslint.txt, output/components.sasslint.txt, output/containers.eslint.txt, output/datagrid.eslint.txt, output/forms.eslint.txt, output/forms.sasslint.txt, output/logging.eslint.txt, output/sagas.eslint.txt, output/theme.sasslint.txt
Skip the two first lines when writing the lerna report.
=> chore(ci): skip first line on lerna reports to avoid useless diff

packages/theme/src/theme/_colors.scss
New Color in [guideline](https://company-57688.frontify.com/document/92132#/design-principles/colors-in-ui)
Add the color in theme
=> feat(color): add $lochmara

.prettierrc, .travis/after_success_git.sh, .travis/after_success_prettier.sh
Use prettier on json file format with tabs
update prettierrc
=> chore(ui): prettier format with json files

packages/html-webpack-plugin/package.json
It was private
It becomes public on npm
=> chore(html-webpack-plugin): set public package

packages/cmf/scripts/cmf-settings.merge.js, packages/cmf/scripts/index.md
=> fix(cmf): fix typo

packages/cmf/scripts/cmf-settings.merge.js
Missing onError callback, so in some cases the error is thrown that it is not defined,
faced this issue already few times
Pass onError callback
=> fix: small fix in cmf settings scripts

packages/cmf-cqrs/package.json, packages/components/__mocks__/react-addons-css-transition-group.js, packages/components/src/Layout/Layout.test.js, packages/components/src/Layout/__snapshots__/Layout.test.js.snap, packages/components/src/List/Toolbar/Pagination/Pagination.component.js, packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js, packages/components/src/SubHeaderBar/SubHeaderBar.test.js, packages/components/stories/List.js, packages/containers/.storybook/webpack.config.js, packages/containers/src/ActionDropdown/ActionDropdown.test.js, packages/containers/src/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap, packages/forms/src/Form.js
There are several issues
* proptypes : incorrect proptypes
* lint : incorrect formatting
* snapshots : wrapper logged instead of the element
* invalid html in storybooks
Fix those. I added some comments in the file changes to explain
=> chore: several fixes on snapshot, lint, proptypes

packages/containers/src/AppLoader/AppLoader.md, packages/containers/src/AppLoader/AppLoader.saga.js, packages/containers/src/AppLoader/AppLoader.saga.test.js
Currently, we can't wait for some action to be dispatched between two steps
Add a way to do that with the takeAction
=> feat(containers/AppLoader): add takeAction support

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js, packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js, packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
Actions with availables to false was filtered by ActionButton, as they are dropdownItems now, it don't work anymore
Filter them before adding them to the dropdown
=> fix(components): Handle available in List's dropdown button

packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js, packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap, packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap, packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap, packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap, packages/theme/src/theme/_navbar.scss
https://jira.talendforge.org/browse/TUI-153
On IE, buttons have their text not aligned
Set line-height to the size of the bar
=> fix(HeaderBar): buttons and link content placement

packages/components/src/Inject/Inject.component.js, packages/components/src/Inject/Inject.md, packages/components/src/Inject/Inject.test.js
Inject has been merged with failling tests, 🙏  sorry
Add the corner case into tests with better handling of wrong types.
=> test: fix Inject tests

packages/datagrid/stories/datagrid.component.js, packages/theme/example/index.html, packages/theme/src/theme/_tooltip.scss, packages/theme/src/theme/theme.scss
When the text in the tooltip overflow the max-width, the text is truncated.
fix that with an overflow-wrap: break-word.
=> fix(theme): overflow wrap the tooltip

packages/cmf/src/Inject.component.js
=> fix(cmf): Inject log error #1301

packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js, packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap, packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js, packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.md, packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js, packages/components/src/DateTimePickers/pickers/TimePicker/__snapshots__/TimePicker.test.js.snap, packages/components/src/DateTimePickers/pickers/TimePicker/index.js, packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.md, packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js, packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js, packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
Implement the time picker.
Do it, in the same way of year picker.
=> feat(component/step5): time management

.travis.yml
surge token is rejected so all PR are blocked
we have removed E2E test at the moment which need surge to works
=> chore: remove surge from travis

.travis.yml
This reverts commit 9b90205e85ae1e255d2242274672ed1e0b3298f7.
Waiting for travis to fix the issue. See #1548 for details
Revert temp deactivation.
=> Revert "chore: remove surge from travis (#1548)"

packages/components/src/PieChartButton/PieChartButton.component.js, packages/components/src/PieChartButton/PieChartButton.scss, packages/components/stories/PieChartButton.js, packages/containers/examples/ExamplePieChartButton.js, packages/theme/src/theme/_datagrid.scss
Current color for quality is silver-chalice, it should be dove-gray
change the sass file involved
=> fix(quality): apply dove-gray on empty quality

packages/components/src/Table/Header/TableHeader.js, packages/components/src/Table/Header/__snapshots__/TableHeader.test.js.snap, packages/components/src/Table/Row/TableRow.js, packages/components/src/Table/Row/__snapshots__/TableRow.test.js.snap, packages/components/src/Table/Table.js, packages/components/src/Table/TestData.js, packages/components/src/Table/__snapshots__/Table.test.js.snap, packages/components/stories/Table.js
Table component a11y :
* no caption
* no links between cells and headers
* add caption with title as content
* add required id on th
* add headers with column id on td
=> feat(Table): improve a11y

output/forms.eslint.txt, packages/forms/src/Form.test.js, packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js, packages/forms/src/UIForm/utils/templates.js, packages/forms/src/fields/CollapsibleFieldset.test.js, packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.js
ESLint raises some errors that can be simply fixed.
Fix linting errors
=> chore(Form) Simple linting error fixes

packages/components/e2e/component-objects/src/main/java/org/talend/component/ActionList.java
IgnoreCase for getting menu label
Replacing equals by equalsIgnoreCase
=> Add ignore case for menu labels

output/forms.eslint.txt, packages/containers/sandbox/mockBackend/kit.js, packages/containers/sandbox/mockBackend/mock/kit/titleMap.json, packages/containers/src/ComponentForm/ComponentForm.component.js, packages/containers/src/ComponentForm/ComponentForm.md, packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap, packages/containers/src/ComponentForm/kit/defaultRegistry.js, packages/containers/src/ComponentForm/kit/defaultRegistry.md, packages/containers/src/ComponentForm/kit/defaultRegistry.test.js
The backend can t create a trigger to change values in the form.
Add a new `update` trigger in the defaultRegistry.
Add demo in the sandbox
Demo: http://recordit.co/tcKasOLKE6
=> feat(containers/TUI-189): add trigger to update properties

packages/theme/src/theme/_colors.scss
New color
https://company-57688.frontify.com/document/92132#/design-principles/colors-in-ui
Add it
=> feat(theme): new jaffa color

.travis.yml
Every branch CI fails on react 15 build request `yauzl` is missing.
it fails during `npm install commander`.
This command is in the before_install.
So that means we were trying to install UI before the versions.js script was applied. (install react 16 then apply versions then re install)
Proof:
```
$ yarn why yauzl
yarn why v1.9.4
[1/4] 🤔  Why do we have the module "yauzl"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "yauzl@2.4.1"
info Reasons this module exists
- "_project_#puppeteer#extract-zip" depends on it
- Hoisted from "_project_#puppeteer#extract-zip#yauzl"
info Disk size without dependencies: "24MB"
info Disk size with unique dependencies: "60MB"
info …
```
=> chore: fix react 15 build

packages/scripts/package.json, packages/scripts/preset/config/test/test-setup.js
At the moment if you generate a react-cmf project and you launch the tests you will have the following logs:
```$ yarn test
yarn run v1.9.4
$ talend-scripts test
CONFIGURATION -------------------------------------------------------------------------------------
Running command: test With options:
Talend scripts mode : production
Talend scripts configuration file found and loaded
RUN -----------------------------------------------------------------------------------------------
PASS  src/backend/analytics/index.test.js (8.622s)
● Console
console.error node_modules/schedule/cjs/schedule.development.js:295
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills …
```
=> chore: add raf dependency and set in test-setup

packages/components/package.json, packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
Since the zone has changed a wrong commit has appear on master.
Replay the tests to revert the change.
Add TZ to yarn tests command.
Remove most of warnings during tests
Make the console.warn happens only once (less noises during tests)
=> test(components): revert snapshot introduced by #1740

packages/components/src/AboutDialog/AboutDialog.component.js, packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap, packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/stories/Action.js, packages/components/stories/ActionFile.js, packages/components/stories/Layout.js, packages/components/stories/RichTooltip.js
many people badly use bsStyle.
By definition bsStyle should be one of
```["success","warning","danger","info","default","primary","link"]```
But with the new btn-inverse we just have added btn-inverse to the bsStyle.
So it s not a style its a class. You can t have multiple style. Its defined by react-bootstrap.
switch to className="btn-primary btn-inverse"
Bonus: fix most of proptypes in the following stories:
* AboutModal (the first one)
* Action
List of all fixed console error:
```
Warning: Failed prop type: Invalid prop `bsStyle` of value `default btn-inverse` supplied to `Button`, expected one of ["success","warning","danger","info","default","primary","link"].
```
```
Warning: Failed …
```
=> fix(TUI-204): remove bad use Action bsStyle

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss, packages/components/src/VirtualizedList/RowLarge/RowLarge.scss, packages/components/stories/List.js
=> fix(components/list): actions background on large display

.travis.yml, .travis/before_install.sh, README.md, output/components.sasslint.txt, output/containers.eslint.txt
- there are 2 variables to github token
- there is an npm token that is not really used
- yaml indentation is incorrect
- merge the 2 variables for github token
- remove the npm configuration that use the token
- fix the indentation
=> chore(Travis): restore ci and remove useless configuration

packages/components/src/Progress/Progress.scss
Infinite progress animation is too fast
Decrease speed
=> fix(components/progress): decrease infinite progress speed

packages/components/src/VirtualizedList/ListTable/ListTable.scss
There was border on the checkbox's column & uppercased titles
Align with the guidelines to remove the border on checkbox columns & remove the uppercased title
=> fix(components/List): remove border on checkbox & uppercase on title

packages/components/package.json, yarn.lock
Test task declaration in `package.json` is not cross env (it fails on Windows for example).
Use `cross-env` library and adapt tasks.
=> chore(tests): cross env unit test fix

packages/containers/src/HeaderBar/HeaderBar.container.js
@jmfrancois has pointed a missing entry in PropTypes in #1785
Add it.
=> fix(containers): PropTypes for app switcher

npm-audit/package-lock.json, npm-audit/package.json, packages/components/package.json, versions/dependencies.js, yarn.lock
rc-tootip, shipped a bugfix version, with accessibility improvement (role = tooltip).
Upgrade the version
No other change that touch the DOM
=> chore: upgrade rc-tooltip

packages/scripts/package.json
Security issue on adm-zip.
Upgrade version
=> chore(scripts): upgrade lib to avoid security issue

packages/scripts/index.js, packages/scripts/internationalization/README.md, packages/scripts/internationalization/common/error.js, packages/scripts/internationalization/scripts/to-github.js, packages/scripts/package.json
Next step in i18n target: upload to github
Implement that + doc about how the locales repo is managed
=> feat(Scripts): i18n to github

packages/components/src/ObjectViewer/Table/Table.component.js, packages/components/src/ObjectViewer/Table/Table.test.js, packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap, packages/components/stories/ObjectViewer.js
https://jira.talendforge.org/browse/TFD-5516
long story short, in flat mode the header generation was expected to find every possible key available in the dataset.
But it was building the table header only by checking recursively the first row of the dataset.
Leading to the following issues:
- if a row after the first one did contain a new key it was not displayed nor its associated value on the right row.
- if a row after the first one did add a key with associated with an array and contained more items, this was not displayed.
for each row recursively find keys and build an unique array of key.
note for huge heterogeneous dataset this method may be slow.
**Please check if the PR fulfills …
=> fix(component): ObjectViewer flat table mode head

npm-audit/audit.json, packages/forms/src/UIForm/fields/Button/Buttons.component.js, packages/forms/src/UIForm/fields/Button/Buttons.component.test.js, packages/forms/src/UIForm/fields/Button/__snapshots__/Buttons.component.test.js.snap
Buttons component does not forward `className` information to its `SingleButton` child (provided in the actions).
Forward it.
=> fix(forms/Buttons): Not forwarded className

packages/components/src/ResourcePicker/Resource/Resource.component.js, packages/components/src/ResourcePicker/Resource/Resource.scss, packages/components/src/ResourcePicker/Resource/Resource.snap.test.js, packages/components/src/ResourcePicker/Resource/__snapshots__/Resource.snap.test.js.snap, packages/components/stories/ResourcePicker.js
Flags are not implemented
Add it as specified here : http://guidelines.talend.com/document/92132#/navigation-layout/embedded-list
=> feat(component/resourcepicker) : add status flags

packages/cmf/src/bootstrap.md
Registry property is missing in the documentation.
Add it.
=> doc(cmf/bootstrap): add registry info

packages/containers/.storybook/config.js, packages/containers/sandbox/package.json, packages/containers/src/index.js, packages/router/package.json, packages/router/src/index.js
The SidePanel doesn t work as expected in 2.0
The ActionList component do not receive the getComponent props and
the router do not initialize the redux middleware to handle the `action.cmf.router[Replace|Push]`.
So even when the SidePanel dispatch the action no middleware treat it.
This is why I have put the two changes in the same PR.
fix the connect of ActionList to add getComponent props.
Add router middleware init.
=> fix(containers): SidePanel and router

packages/containers/src/ComponentForm/kit/createTriggers.js
I tried to use merge security config with undefined properties
Keep non-undefined properties only
=> fix(containers/Forms): CSRF headers

packages/components/src/List/Toolbar/Toolbar.scss, packages/components/stories/List.js
We have uppercase on each word in the sort by component
Apply uppercase only on the first letter
=> fix(List): Apply Title case to sort by in the list

packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.scss
Missing scooter on hover of the year/month
Adding it
=> fix(DatePicker): scooter when hovering month year button

npm-audit/package-lock.json, packages/containers/src/index.js
Dialog used from container do not have anymore connected Actions
This has been break during 2.0 release
add withComponentRegistry for Dialog
=> fix(containers/Dialog): use getComponent

package.json, packages/datagrid/i18next-scanner.config.js
No i18n extraction on datagrid
Add it
=> chore(i18n): extract datagrid i18n file

packages/cmf/src/onEvent.js
PR #2081 is a breaking change
Revert until new major release
=> Revert "fix(cmf): remove automatic event from onEvent [BC]"

packages/icons/src/svg/mongodb.svg
Icon for Mongo DB component was requested
https://jira.talendforge.org/browse/TUX-763
Icon for Mongo DB component was created
=> feat(icons): Mongo DB

output/components.sasslint.txt, packages/components/src/GuidedTour/GuidedTour.scss
Style has not been validated by our visual designer
Style is now [validated](http://guidelines.talend.com/document/135457#/pages/guided-tour) and fixed
=> fix(components/GuidedTour): style

packages/components/src/GuidedTour/GuidedTour.component.js
By editing HTML, I screw up JSX 
Fix JSX
=> fix(components/GuidedTour): valid jsx

output/containers.eslint.txt, packages/containers/src/Notification/Notification.sagas.js, packages/containers/src/Notification/index.js
this comes from #2093 
add missing sagas + fix lint error
=> fix(containers/Notification): add missing saga

packages/containers/src/Form/Form.container.js
Since the change in #2170, we had problem with some of our forms in TMC.
Some of them generate a [json/ui]Schema depending of the formData and with the current code we have circular update of the state due to the generation of a new instance of props and schema.
Add a deep compare after the existing test.
In a second time, some refactoring will need to be done in tmc to fix that but we don't have time to do it before the release.
=> fix(container/Form): use deep equal check in derivedStateFromProps

packages/components/src/List/Toolbar/Toolbar.scss
UX designer requires changing  "sort by" label color to $dove-gray.
https://jira.talendforge.org/browse/TMC-16846?focusedCommentId=667238&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-667238
* [] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
=> fix(components/List/SortBy): change "sort by" label color to $dove-gray

packages/components/stories/HeaderBar.js
=> chore: set talend intercom dev workspace in story

output/components.eslint.txt, packages/components/src/GridLayout/Grid.component.js
passing vertical compact as props so we can choose whether we want it or not
=> fix(GridLayout): verticalCompact as props

.travis.yml
I pushed by mistake some travis command removal. Now the demo is not built and published.
Revert that
=> chore: revert unwanted commit, removing the demo deployment

packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.scss, packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
=> fix(components/list): iconactiontoggle misaligned on ie

packages/components/src/ActionIntercom/Intercom.component.js, packages/components/src/ActionIntercom/Intercom.component.test.js, packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
Labels could be more precise
Update the label with Talend messages
=> fix(intercom): change default values on open/close

packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.scss, packages/components/src/Drawer/Drawer.test.js, packages/components/src/EditableText/EditableText.scss, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js, packages/components/stories/Drawer.js
Drawer title can't be edited
Drawer title can be edited and legacy behavior is still available
=> feat(components): editable drawer title

packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js, packages/components/src/DateTimePickers/DateTime/date-extraction.js, packages/components/src/DateTimePickers/DateTime/date-extraction.test.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js, packages/components/src/DateTimePickers/Time/Context.js, packages/components/src/DateTimePickers/Time/Input/Input.component.js, packages/components/src/DateTimePickers/Time/Input/index.js, packages/components/src/DateTimePickers/Time/Manager/Manager.component.js, packages/components/src/DateTimePickers/Time/Manager/Manager.component.test.js, packages/components/src/DateTimePickers/Time/Manager/__snapshots__/Manager.component.test.js.snap, packages/components/src/DateTimePickers/Time/Manager/index.js, packages/components/src/DateTimePickers/Time/Picker/Picker.component.js, packages/components/src/DateTimePickers/Time/Picker/index.js, packages/components/src/DateTimePickers/Time/error-messages.js, packages/components/src/DateTimePickers/Time/index.js, packages/components/src/DateTimePickers/Time/time-extraction.js, packages/components/src/DateTimePickers/Time/time-extraction.test.js, packages/components/src/DateTimePickers/hooks/useInputPickerHandlers.js, packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js, packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js, packages/components/stories/DatePicker.js
Handle time change from input picker.
=> feat(TimePicker): Handle time input/picker change

output/components.sasslint.txt, output/forms.eslint.txt, packages/forms/src/UIForm/utils/array.js, packages/forms/src/UIForm/utils/array.test.js
JIRA link: [https://jira.talendforge.org/browse/TUI-343](https://jira.talendforge.org/browse/TUI-343)
When we try to merge a schema that have an single array of select items (example key: `colors[]`), schema is not clone in nested schema.
To be clear, all works with key like `colors[]name` because `name` is an accessible property in `lookup`.
We need to provide a specific condition in merge function to handle that.
In part of script that extend the form data (second arg of `merge` signature), we now check that if we have a key like `colors[]`, we create a property `schema` with all data from `schema.items`.
**_As jscf in a dependancy of UIForms, you need to use `yarn link` and launch …
=> fix(form/TUI-343): Pass schema from items in array

packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
Toolbar right render every children event the false / undefined one
Add a condition on the children map
=> fix(Component): Render child ListToolbar Right

packages/forms/src/UIForm/utils/array.js, packages/forms/src/UIForm/utils/array.test.js
If we build a form with a select array, it will be empty.
Select widget need a titleMap props to create options, and it's not provide in schema.
Like this PR #2369 (same problem, but with schema property), we just need to get titleMap from array schema and push it in field schema.
If you want to test by yourself, go to Form storybook and put this schema in playground (FYI, titleMap is provided by jsfc with enum property):
```json
{
"jsonSchema":{
"type":"object",
"properties":{
"Color":{
"type":"array",
"items":{
"type":"string",
"enum":[
"White",
"Lemon"
]
}
}
}
},
"uiSchema":[
{
"key":"Color",
"type":"array",
"items":[
{
"key":"Color[]",
"type":"select"
}
]
}
],
"properties":{
"Color":[] …
```
=> fix(UIForm/array): Add titleMap to schema if it exist

packages/cmf/src/onError.js
=> chore: refactor

packages/components/src/Slider/Slider.component.js, packages/components/src/Slider/Slider.snap.test.js, packages/components/src/Slider/__snapshots__/Slider.snap.test.js.snap, packages/components/stories/Slider.js
Slider can not render a range
Slider should accept a range as value
=> feat(components/slider): range

packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss, packages/components/stories/DatePicker.js
http://guidelines.talend.com/document/92132#/ui-controls/date-time-picker-1561102408
set the min-width and min-height
=> feat(TCCUI-65/date picker): set min-height min-width

packages/datagrid/src/constants/avro-type.constant.js
missing constants. The console shows the errors: Warning: Invalid argument supplied to oneOf, expected an instance of array.
fix that
=> fix(datagrid): missing constant

packages/components/src/TabBar/TabBar.component.js
https://jira.talendforge.org/browse/TPSVC-11545
Icon for selected element is fixed
Add icon for selected element
=> fix(TPSVC-11545): add missing icon for selected element

packages/eslint-config/api-app-angular.yaml, packages/eslint-config/api-app.yaml
In the API Designer we reworked the way we imported our deps and we don't want to have angular and lodash as global from eslint anymore.
Remove lodash and angular as globals on api eslint config file.
* [] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
=> chore(eslint-config) update eslint api config to remove globals for lodash and angular

packages/components/src/DateTimePickers/Date/Manager/Manager.component.test.js, packages/components/src/DateTimePickers/Date/date-extraction.js, packages/components/src/DateTimePickers/Date/date-extraction.test.js, packages/components/src/DateTimePickers/DateTime/datetime-extraction.js
fix & refactor of date-extraction.
=> fixes: date-extraction

packages/components/src/DateTimePickers/Date/Manager/Manager.component.js, packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js, packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js, packages/components/src/DateTimePickers/DateTime/datetime-extraction.js, packages/components/src/DateTimePickers/DateTime/datetime-extraction.test.js
=> fix & refactor datetime manager

packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js, packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.scss, packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.scss, packages/components/src/DateTimePickers/shared/error-messages.js, packages/components/stories/DatePicker.js
=> fix for the input pickers

packages/faceted-search/package.json, packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js, packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
import are not optimize for code splitting
make them
=> chore(faceted-search): change import

packages/components/src/DateTimePickers/Date/Manager/Manager.component.js, packages/components/src/DateTimePickers/Date/Manager/Manager.component.test.js, packages/components/src/DateTimePickers/index.js, packages/components/stories/DatePicker.js, packages/forms/src/UIForm/fields/Date/Date.component.js, packages/forms/src/UIForm/fields/Date/Date.utils.js, packages/forms/src/UIForm/fields/Date/Date.utils.test.js, packages/forms/src/UIForm/fields/Date/DateTime.component.js, packages/forms/src/UIForm/fields/Date/DateTime.component.test.js, packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap, packages/forms/src/UIForm/fields/Date/__snapshots__/DateTime.component.test.js.snap, packages/forms/stories-core/json/fields/core-date.json
=> fix current wrapper of date/datetime

packages/faceted-search/CHANGELOG.md, packages/faceted-search/package.json
- [Fixed](https://github.com/Talend/ui/pull/2520): Tql error on empty value array
- [Fixed](https://github.com/Talend/ui/pull/2513): Invert action basic <> advanced
- [Fixed](https://github.com/Talend/ui/pull/2510): Disable resize on textarea
- [Fixed](https://github.com/Talend/ui/pull/2509): Filter badge by label, not attribute
- [Fixed](https://github.com/Talend/ui/pull/2501): Tql error on checkboxes badge*What is the chosen solution to this problem?**
=> chore(FacetedSearch): add change log and update to 0.2.2

output/components.sasslint.txt, packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.scss, packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap, packages/components/stories/Drawer.js, packages/forms/src/FormSkeleton.js, packages/forms/src/FormSkeleton.scss, packages/forms/src/UIForm/UIForm.scss, packages/forms/src/UIForm/fields/Button/Buttons.scss, packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap, packages/forms/stories-core/layouts.js
=> Revert "feat(components/drawer): style"

packages/cmf/src/cmfConnect.md
The link to react-redux connect is available.
Give a correct one.
=> chore: correct link

output/components.sasslint.txt, output/theme.sasslint.txt, packages/components/src/ActionBar/ActionBar.scss, packages/components/src/ActionList/ActionList.scss, packages/components/src/CollapsiblePanel/CollapsiblePanel.scss, packages/components/src/HttpError/HttpError.scss, packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss, packages/components/src/Table/TitleBar/TitleBar.scss, packages/components/stories/GuidedTour.js, packages/forms/src/UIForm/UIForm.scss, packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.scss, packages/forms/src/deprecated/templates/ArrayFieldTemplate.scss, packages/forms/stories-core/customDisplayMode.js, packages/forms/stories-core/customErrors.js, packages/forms/stories-core/customUpdating.js, packages/forms/stories-core/json/fields/core-keyValue.json, packages/forms/stories-core/json/fieldsets/core-arrays-complex.json, packages/forms/stories-core/json/fieldsets/core-arrays-with-custom-options.json, packages/forms/stories-core/json/fieldsets/core-arrays.json, packages/theme/src/theme/_forms.scss, packages/theme/src/theme/_navbar.dropdown.scss, packages/theme/src/theme/_navbar.scss, packages/theme/src/theme/_navs.scss
Some fixed labels such as titles are forced to uppercase.
We want to embrace sentence case everywhere. 
- Remove the uppercases, except buttons for now
- Parts of components that are buttons, but styled differently are not in uppercase anymore
- There are still text transform for parts where we want sentence case but variables are displayed. For example, list sort elements in dropdown.
- Fix form schemas to have correct labels in the stories
=> feat: remove uppercase for fixed labels (#2627)

packages/components/src/GuidedTour/GuidedTour.scss, packages/theme/src/theme/_variables.scss
The notification showed above the guided tour
I move z-index like a modal for the guidedTour.
=> feat(guidedTour): move z-index in GuidedTour

packages/components/src/GuidedTour/GuidedTour.scss
Guidelines: http://guidelines.talend.com/document/92132#/specific-features/guided-tour
=> fix(GuidedTour): Width does not follow guidelines

output/components.eslint.txt, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/HeaderBar.scss, packages/components/src/HeaderBar/HeaderBar.stories.js, packages/components/src/HeaderBar/HeaderBar.test.js
There is some stuff broken in the header bar style
Fix it
=> fix(components/headerbar): style

packages/theme/src/theme/_colors.scss
Rebranding is in progress
Two new colors have been added.
http://guidelines.talend.com/document/92132#/design-principles/colors-theme-in-apps
=> feat(theme): rebranding colors

packages/components/src/AppGuidedTour/AppGuidedTour.component.js
=> fix(components/AppGuidedTour): Change header i18n key

packages/components/src/AppGuidedTour/AppGuidedTour.component.js
The same i18n key is used twice
=> fix(app-guided-tour): Invalid i18n key

packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap, packages/components/src/Notification/__snapshots__/Notification.test.js.snap, packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap, packages/components/src/PieChart/__snapshots__/PieChart.test.js.snap, packages/components/src/PieChart/__snapshots__/PieChartButton.test.js.snap, packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap, packages/components/src/ResourceList/Toolbar/__snapshots__/Toolbar.snap.test.js.snap, packages/components/src/Stepper/__snapshots__/Stepper.component.test.js.snap, packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap, packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap, packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap, packages/components/src/VirtualizedList/CellBadge/CellBadge.test.js, packages/components/src/VirtualizedList/CellBadge/__snapshots__/CellBadge.test.js.snap, packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap, packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap, packages/components/src/VirtualizedList/NoRows/__snapshots__/NoRows.test.js.snap, packages/components/src/VirtualizedList/RowCollapsiblePanel/__snapshots__/RowCollapsiblePanel.test.js.snap, packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
Components tests must be adapted to talend/scripts jest/enzyme/mock versions
Fix a part of them: some snapshots
=> fix(Components): adapt tests for @talend/scripts

packages/components/.eslintrc, packages/components/package.json, packages/components/src/AboutDialog/AboutDialog.component.js, packages/components/src/ActionBar/ActionBar.component.js, packages/components/src/Actions/Action/Action.component.js, packages/components/src/Actions/Action/Action.test.js, packages/components/src/Actions/Action/index.js, packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js, packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js, packages/components/src/Actions/ActionFile/ActionFile.component.js, packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js, packages/components/src/Actions/wrapOnClick.js, packages/components/src/Actions/wrapOnClick.test.js, packages/components/src/ResourceList/ResourceList.component.js, packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js, packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js, packages/components/src/VirtualizedList/VirtualizedList.stories.js, packages/forms/package.json, yarn.lock
_WARNING: this is to merge to jsomsanith/chore/talend_scripts because of eslint rules at root. It conflicts with talend/scripts config and breaks the lint. Let's move all packages to @talend/scripts before the merge to master._
Components lint ouputs a lit for errors
Fix a part of them
=> fix(Components): linter errors with @talend/scripts

output/components.eslint.txt, packages/components/src/AppSwitcher/AppSwitcher.component.js, packages/components/src/AppSwitcher/AppSwitcher.component.test.js, packages/components/src/AppSwitcher/AppSwitcher.scss, packages/components/src/AppSwitcher/__snapshots__/AppSwitcher.component.test.js.snap, packages/components/src/AppSwitcher/index.js, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/HeaderBar.stories.js, packages/components/src/HeaderBar/HeaderBar.test.js
We want a AppSwitcher component
=> feat(components): create AppSwitcher component

.gitignore, .travis.yml, .travis/after_success_lint.sh, package.json, packages/containers/package.json, packages/forms/package.json, packages/icons/package.json, packages/icons/webpack.config.js, packages/theme/babel.config.js, packages/theme/package.json, yarn.lock
_WARNING: this is to merge to jsomsanith/chore/talend_scripts because of eslint rules at root. It conflicts with talend/scripts config and breaks the lint. Let's move all packages to @talend/scripts before the merge to master._
On the @talend/scripts branch, CI fails for demo and lint goals
Provide a fix. See comments for details
=> chore: make eslint and demo works

packages/faceted-search/babel.config.js, packages/faceted-search/package.json, packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js, packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js, packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.test.js, packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.test.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js, packages/faceted-search/talend-scripts.json, packages/faceted-search/yarn.lock
Custom tooling
Use @talend/scripts for build/test/lint
=> chore(faceted-search): use @talend/scripts

packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js, packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.js, packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.test.js, packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
https://jira.talendforge.org/browse/TFD-11033
Some data structure, like enums or unions, were not well supported by the RecordsViewer.
Add support by adding new ways to discover types.
=> fix(components): Add support to some Avro data structure

packages/components/src/DateTimePickers/InputDatePicker/DatePicker.stories.js, packages/components/src/DateTimePickers/InputDateRangePicker/DateRangePicker.stories.js, packages/components/src/DateTimePickers/InputDateTimePicker/DateTimePicker.stories.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js
1. The UI gets laggy when click on calendar date.
2. The icons of date picker is missing(left/right arrow).
https://www.loom.com/share/153c5616890b4af78595871a738315f7
1. For storybook's action, arguments which are passed to the action call will have to be serialized while be "transferred" over the channel. This can cause lag when large objects are being logged.
To fix this we can configure a maximum depth.
https://github.com/storybookjs/storybook/tree/master/addons/actions#configuration
2. Add the icons back.
=> fix(components/DatePicker): laggy storybook example

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v5.12.0
Release v5.12.0
=> chore: release v5.12.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Need to release v5.13.0
Bump version
=> chore: release v5.13.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.14.0

.travis/after_success_demo.sh
No way to test the Faceted Search without cloning the git branch and building it locally.
Deploy demo on Surge
=> chore(faceted-search): publish demo on surge

packages/containers/src/HeaderBar/HeaderBar.sagas.js
In TMC we have a feature which let user to specify the url when switch to TDS by AppSwitcher.
Previously we don't check for javascript protocol in user's input and it leads to vulnerability of XSS attack - user can input malicious javascript in url and get executed when switch to TDS (https://jira.talendforge.org/browse/TMC-22401)
We have made a fix on TMC UI to forbid javascript protocol in url input. I added this PR for case that malicious url has already saved in database.
=> fix(containers/HeaderBar): Not open url with javascript protocol

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 5.18.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.19.0

packages/cmf/website/package.json, packages/cmf/website/yarn.lock
security issue reported by github
update deps and check build is still ok
=> chore: fix high security issue in cmf website deps

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: realease v5.20.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.21.0

packages/components/.npmignore, packages/html-webpack-plugin/.npmignore, packages/local-libs-webpack-plugin/.npmignore, packages/sagas/.npmignore
currently dist folder are not pushed into npm release
remove them from ignore file to get them in release (UMD compliant track)
=> chore: remove dist from npm ignore

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.22.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.23.0

packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.scss, packages/components/src/Status/Status.component.js, packages/components/src/Status/Status.scss, packages/components/src/Status/Status.stories.js, packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap, packages/theme/src/theme/_colors.scss
https://jira.talendforge.org/browse/TMC-22913
=> feat(TMC-22913/Status): enhancing status component

packages/datagrid/package.json, packages/datagrid/src/components/DataGrid/DataGrid.component.js, yarn.lock
current datagrid implementation use @ag-grid scoped package which are not available as UMD.
Use the original ag-grid-community package which is available as UMD.
No impact the code under the hood is the same.
You can find the UMD and take a look at it: https://unpkg.com/browse/ag-grid-community@24.0.0/dist/ag-grid-community.js 
=> chore: refactor to use ag-grid umd compliant

lerna.json, output/components.eslint.txt, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.24.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.25.0

packages/faceted-search/CHANGELOG.md, packages/faceted-search/src/dictionary/operator.dictionary.js, packages/faceted-search/src/queryClient/tql.js, packages/faceted-search/src/queryClient/tql.test.js
Suuport of complies/wordComplies TQL operators is missing
=> feat(faceted-search): Add pattern operators

.gitignore, lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.26.0

output/components.eslint.txt, packages/containers/package.json, packages/containers/src/SidePanel/SidePanel.connect.js, packages/containers/src/SidePanel/SidePanel.test.js, packages/router/package.json, packages/router/src/selectors.js, packages/router/src/selectors.test.js, packages/router/yarn.lock, yarn.lock
Side Panel doesn't support hash based route.
TDP reconnect the Side Panel container with the support in their app.
Make the side panel container support hash based route
=> feat(SidePanel): container support active route with hash

packages/components/src/IconsProvider/IconsProvider.component.js
Wrong function name in IconProvider 
Fix function name
=> fix(IconsProvider): function name

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.27.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.28.0

packages/stepper/src/index.js
Stepper index doesn't export all the constants
Export them
=> chore(Stepper): export constants

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.29.0

output/components.eslint.txt, output/forms.eslint.txt, packages/components/src/MultiSelect/index.js, packages/containers/sandbox/package.json, packages/containers/sandbox/src/app/ComponentFormSandbox.js, packages/containers/sandbox/src/app/index.js, packages/containers/sandbox/src/assets/settings.json, packages/containers/sandbox/talend-scripts.json, packages/containers/sandbox/yarn.lock, packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
sandbox do not work because of undefined element and really outdated build stack
* use ui-script to build the sandbox
* fix the import
=> fix(containers): update sandbox / fix imports of MultiSelect

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.30.0

output/components.eslint.txt, packages/components/src/DateTimePickers/Date/Input/Input.component.js, packages/components/src/DateTimePickers/DateRange/Input/Input.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js, packages/components/src/DateTimePickers/InputTimePicker/TimePicker.stories.js, packages/components/src/DateTimePickers/Time/Input/Input.component.js
same as : https://github.com/Talend/ui/pull/2998 
but making it work for datetime range and time
=> chore(DateTime/Time): adding minWidth support for datetime range and time

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v5.31.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.3.0

packages/containers/src/Notification/Notification.connect.js, packages/containers/src/Notification/Notification.test.js
https://jira.talendforge.org/browse/TDC-5037
Do not throw error when notification is not found
=> fix(container/notification): fix strange error with delete

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: prepare release 6.4.0

packages/components/src/DateTimePickers/index.js
We want to use datepicker outside of its popover 
Export Picker and Manager components
=> chore(DatePicker): Export picker & manager components

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.5.0

.github/workflows/release.yml
=> chore(ci): Trigger release action on maintenance branch

.github/workflows/release.yml, lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.5.1

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
* ac582f80c  2020-12-28 TPSVC-15539: add data-* attributes to datalist (#3144)
* f3db8f0ce  2020-12-24 feat(component/ratiobar): optionally hide label (#3136)
* d4d05cffe  2020-12-23 chore(components): use d3 instead of d3-shape (#3130)
* 1c87bfcac  2020-12-23 feat(icon): add tableau.svg (#3134)
* 461c34b93  2020-12-22 chore(ci): Trigger release action on maintenance branch (#3142)
* ba5141d49  2020-12-22 chore: trigger webhook to update cdn content after a release (#3137)
* 61224ba5e  2020-12-22 fix(DatePicker): Missing root export (#3141)
=> chore: prepare release 6.6.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
* 2ed79456a  2021-01-08 feat(components/headercheckbox): add intermediate state (#3155)
* 4ddb90b4e  2021-01-07 feature(TDP-9660) : Add menu dropdown on quality bar component (#3140)
* dc6cde455  2021-01-06 fix(Collapsible): tooltip only when label is there for element (#3154)
* 8fa04d4f6  2021-01-06 fix(TDS-5773/Enumeration): msgs placement and behavior (#3153)
=> chore: prepare release

packages/icons/package.json, packages/icons/scripts/typescript.js
The list of icons is unknown
Generate a typescript definition file in order to be able to have the autocompletion of the IDE
=> feat(icons): TS definition

packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
=> fix(EnumerationWidget): fix index check

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.9.0

.travis/after_success_umd.sh
we want to have the theme so we can test PR in testenv
copy theme in static folder to be published on surge
=> chore: copy bootsrap theme on surge

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.10.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json, yarn.lock
Release v6.11.0
Release v6.11.0
=> chore: release v6.11.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.12.0

.github/workflows/umd-size-checker.yml, .travis/after_success_umd.sh
We are blind when our UMD are heavier!
Now, there is a GH action that will check that for us.
Look at the example below
=> chore: UMD size checker

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.13.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
release v6.14.0
release v6.14.0
=> chore: release v6.14.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.15.0
Release v6.15.0
=> chore: release v6.15

.surge/index.html
Surge still reference faceted search
Remove it.
=> chore(Surge): remove faceted search links

packages/components/package.json, packages/components/src/VirtualizedList/CellTitle/CellTitle.scss, packages/icons/scripts/docs.js, packages/icons/src/filters/grayscale.svg, yarn.lock
Reverts Talend/ui#3246
The issue comes from https://github.com/Talend/design-system/pull/26/files#diff-8396e1c7c68d6f22196bf630f8d40abd3a8e5b7398c394fc8096e38ad8d16f2aR78
=> Revert "fix(icons): grayscale filter"

packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
when we use form enumeration and we use value with comma
we can not change this value if this value is same as previous value
Do a verification when first value is same, we check if all value with comma is same
=> fix(forms/enumeration): enumeration form value deffect with comma

output/components.eslint.txt, yarn.lock
We are on ui-scripts 9.4.1
An important fix of ui-scripts came with 9.6.2.
upgrade using yarn upgrade command and check ui-scrripts is in 9.6.2
=> chore: upgrade deps

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.16.0
Release v6.16.0
=> chore: release v6.16.0

.travis/after_success_demo.sh
Theme demo content has moved and some Storybook rely on it
Duplicate the content on Surge because the previous folder hierarchy is non-sense!
=> chore(theme): theme folder output for demo

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.17.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.18.0
Release v6.18.0
=> chore: release v6.18.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
release v6.19.0
release v6.19.0
=> chore: release v6.19.0

output/components.eslint.txt, packages/components/package.json, packages/components/src/Stepper/Stepper.component.js, packages/components/src/Stepper/Stepper.stories.js, yarn.lock
we need to use the new form stepper : https://deploy-preview-65--gifted-tesla-96fe2e.netlify.app/?path=/docs/components-stepper-overview--vertical
export coral form stepper
=> feat(components/stepper): export coral form stepper

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: prepare release 6.20.0

packages/cmf/package.json, packages/cmf/website/package.json, packages/cmf/website/yarn.lock, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/dataviz/package.json, packages/dataviz/yarn.lock, packages/forms/package.json, packages/stepper/package.json, packages/theme/package.json, yarn.lock
We have lots of security issues on this repositories.
Mainly has been touch:
* theme: major upgrade of css webpack plugin
* cmf: major upgrade of node-fetch just used in tests
* global yarn upgrade so not much risk
> Upgrade is-svg to version 4.2.2 
not found after yarn upgrade
> Upgrade xmldom to version 0.5.0
=> Found "xmldom@0.5.0"
info Reasons this module exists
- "_project_#@talend#icons#webfonts-loader#@vusion#webfonts-generator#svg2ttf" depends on it
- Hoisted from "_project_#@talend#icons#webfonts-loader#@vusion#webfonts-generator#svg2ttf#xmldom"
> Upgrade node-fetch to version 2.6.1
used in CMF tests only => major upgrade ok but
=> Found "node-fetch@2.6.1"
- Hoisted from …
=> chore(security): upgrades

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.21.0
Release v6.21.0
=> chore: release v6.21.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.22.0

yarn.lock
Update DS common lib to latest
yarn updatee
=> chore(deps): upgrade Design System

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.23.0
Release v6.23.0
=> chore: release v6.23.0

packages/components/src/QualityBar/QualityRatioBar.scss
the chosen yellow is not the correct color for "quality NA"
change to alto
=> workItem(TRR-395) : change quality NA color

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.24.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
release v6.25.0
release v6.25.0
=> chore: release v6.25.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
last changes (CMF and icons) needed by project
weekly release
=> chore: release 6.26.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
prepare for the next release
https://github.com/Talend/ui/wiki/Release#prepare-a-new-release
=> chore: release 6.27.0

packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
=> feat(TDS-6025) : add data-feature on collapsiblePanel

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.28.0
Release v6.28.0
=> chore: release v6.28.0

packages/cmf-router/CHANGELOG.md, packages/cmf-router/package.json, packages/cmf-router/yarn.lock
cmf-router dependencies contains dependencies of react-cmf.
This is an old bug of ui-script.
update ui-script and create a new release
After update here is the content of the dependencies.json
```
jmfrancois@LT-C02WN2D6HTDF ~/github/talend/ui/packages/cmf-router (jmfrancois/fix/arch-343-update-ui-script)$ more dist/TalendReactCmfRouter.js.dependencies.json
{
"@talend/react-cmf": {
"name": "@talend/react-cmf",
"var": "TalendReactCmf",
"version": "6.28.0",
"path": "/dist/TalendReactCmf.js"
},
"prop-types": {
"name": "prop-types",
"var": "PropTypes",
"version": "15.7.2",
"path": "/prop-types.js"
},
"react": {
"name": "react",
"var": "React",
"version": "16.14.0",
"path": …
```
=> fix(arch-343/cmf-router): upgrade dependencies.json

packages/http/package.json
=> chore: release http v1.1.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.29.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.30.0

packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Fix CI
Update snapshot, forgotten by previous PR: https://github.com/Talend/ui/pull/3345
=> fix(ActionButton): update forms snapshot

packages/forms/.storybook/config.js, packages/forms/package.json, packages/forms/src/UIForm/Message/Message.component.js, packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap, packages/forms/src/UIForm/Widget/Widget.component.test.js, packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap, packages/forms/src/UIForm/fields/Enumeration/__snapshots__/EnumerationWidget.test.js.snap, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap, packages/forms/src/rhf/fields/Input/Input.test.js, packages/forms/src/rhf/fields/Select/Select.test.js, packages/forms/src/rhf/fields/TextArea/RHFTextArea.test.js, packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.component.js, packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.test.js, packages/forms/src/widgets/templates/FieldTemplate/__snapshots__/FieldTemplate.test.js.snap, yarn.lock
Inline message in forms use bootstrap markup
Let's use Coral ones for consistency reasons
=> chore(forms): Coral InlineMessage

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release v6.32.0

packages/utils/package.json, packages/utils/src/date/README.md
After updating the dates utilities (https://github.com/Talend/ui/pull/3358), I forgot to update the corresponding readme.
And I need a release.
=> feat(dates): update readme

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.33.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.34.0

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
=> chore: release 6.35.0

packages/components/package.json, packages/components/src/Stepper/Stepper.stories.js, packages/forms/package.json, yarn.lock
There's been minor versions of @talend/design-system that have been released.
Bump to latest version.
Also added a case for horizontal stepper in the stories.
=> chore(components+forms): Bump @talend/design-system to 1.3.2

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Release v6.36.0
Bump minor version.
=> chore: release v6.36.0

.storybook/addons.js, .storybook/config.js, packages/components/.storybook/addons.js, packages/components/.storybook/config.js, packages/components/package.json, packages/containers/.storybook/addons.js, packages/containers/.storybook/config.js, packages/containers/package.json, packages/datagrid/.storybook/addons.js, packages/datagrid/.storybook/config.js, packages/datagrid/package.json, packages/dataviz/.storybook/preview.js, packages/dataviz/package.json, packages/dataviz/yarn.lock, packages/forms/.storybook/addons.js, packages/forms/.storybook/config.js, packages/forms/package.json, packages/forms/stories-core/index.js, packages/stepper/.storybook/config.js, packages/stepper/package.json, packages/stepper/stories/stepper.component.js, packages/storybook-cmf/package.json, packages/theme/package.json, yarn.lock
lots of security issues came from storybook 5
* upgrade to storybook 6
* drop `node-sass` which is replace by `sass` (dart port native JS)
* drop `storybook-addon-i18next`
* drop `@storybook/addon-info`
* drop `@storybook/addon-knobs`
The plan is to merge it as it is to then re introduce equivalent for features for i18next and knobs in forms.
=> chore: upgrade storybook

.changeset/wise-monkeys-jump.md
Related to #3268 
Changeset was not hit
Generate a changeset  file for #3268 
=> chore(changeset): forms style

.changeset/calm-suns-fly.md, packages/components/package.json, packages/forms/package.json, yarn.lock
A new version of @talend/design-system has been released.
https://github.com/Talend/design-system/pull/227
Upgrade the library in the @talend/ui packages that are using it
=> chore(components+forms): Bump @talend/design-system

.changeset/sharp-rats-smoke.md, packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.scss
=> fix(list): align checkbox in list component

.changeset/little-carpets-stare.md, .github/workflows/before-surge.sh, .github/workflows/lerna-ci.yml, packages/components/package.json, packages/components/src/RadarChart/__snapshots__/RadarChart.test.js.snap, packages/dataviz/.eslintrc, packages/dataviz/package.json, packages/dataviz/src/components/BarChart/ColoredBar/ColoredBar.component.tsx, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.scss, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.test.tsx, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.tsx, packages/dataviz/src/components/BarChart/TooltipCursor/TooltipCursor.component.tsx, packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.scss, packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.tsx, packages/dataviz/src/components/BarChart/_bar-chart.scss, packages/dataviz/src/components/BarChart/useBarChart.hook.tsx, packages/dataviz/src/components/GeoChart/GeoChart.scss, versions/dependencies.json, yarn.lock
recharts 1 is on d3 5.x, while components and dataviz is based on d3 6.x
* update to recharts 2
* https://github.com/recharts/recharts/pull/2684
* check yarn list --pattern d3 list is flat
* remove @types/recharts package because recharts 2 is typescript based
* ensure all demo are working well
test and compare the entire storybook :
* [dataviz PR](http://3470.talend.surge.sh/dataviz) vs [dataviz master](http://talend.surge.sh/dataviz)
* [radarchart PR](http://3470.talend.surge.sh/components/?path=/story/data-dataviz-radarchart--radar-chart-single) vs [radarchar master](http://talend.surge.sh/components/?path=/story/data-dataviz-radarchart--radar-chart-single)
I think the master storybook …
=> chore(dataviz&components): major upgrade recharts 2

.changeset/thirty-roses-cheer.md, packages/design-system/src/components/InlineEditing/InlineEditing.stories.mdx, packages/design-system/src/components/InlineEditing/InlineEditing.stories.tsx, packages/design-system/src/components/InlineEditing/InlineEditing.style.ts, packages/design-system/src/components/InlineEditing/InlineEditing.tsx
We can't specify placeholders
Add placeholder support
=> feat(InlineEditing): add placeholder support

packages/design-system/CONTRIBUTING.md, packages/design-system/DOCTEMPLATE.md, packages/design-system/README.md
=> chore(design-system): Contribution guidelines

packages/design-system/adr/composition-vs-api.md
We need to document the direction we take on building components inside of a shared library.
We think components with closed APIs are a better way to ensure consistent UI and UX, which is our main objective. 
The reasons why composition may be chosen instead are also outlined in the ADR.
=> chore(ADR): Added ADR on using closed component APIs or composition

.changeset/grumpy-ears-wonder.md, packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx, packages/design-system/src/components/Form/Field/Input/Input.File.tsx, packages/design-system/src/components/HeaderBar/HeaderBar.tsx, packages/design-system/src/components/Layout/Footer.tsx, packages/design-system/src/components/Layout/SkipLinks/SkipLinks.tsx, packages/design-system/src/components/Menu/Menu.tsx, packages/design-system/src/components/Modal/Modal.tsx, packages/design-system/src/components/ThemeProvider/ThemeSwitcher/ThemeSwitcher.tsx
There is some remaining hardcoded strings in some component.
I tried to find them all and fix them using i18next.
=> fix(design-system): i18n

.changeset/blue-phones-hide.md, .changeset/few-pigs-jam.md, packages/components/src/MultiSelect/ItemOption.scss, packages/components/src/MultiSelect/MultiSelect.scss, packages/components/src/Typeahead/Typeahead.scss, size.json
Everything is a bit misplaced 
=> fix(components): MutliSelect component style

.changeset/tender-stingrays-wink.md, packages/flow-designer/src/reducers/flow.reducer.ts
Some components are get from the store (whaaat)
Theses components are not at the same level in the hierarchy with the new redux integration
=> fix(flow-designer): handle some component position

packages/design-system/.eslintrc.js, packages/design-system/package.json, packages/design-system/src/components/Button/Button.test.js, packages/design-system/src/components/Dropdown/Dropdown.spec.tsx, packages/design-system/src/components/IconsProvider/IconsProvider.test.tsx, packages/design-system/src/components/Link/Link.test.js, packages/design-system/src/components/Link/Link.tsx, yarn.lock
We've got lint errors in tests since the move to react-testing-lib was made
Fix the errors we can fix
=> chore(design-system): Fixing linting errors on tests

.changeset/odd-snails-rush.md, .gitignore, packages/dataviz/i18next-scanner.config.js, packages/dataviz/package.json, packages/dataviz/src/components/GeoChart/GeoChart.utils.ts, packages/dataviz/tsconfig.json, packages/design-system/i18next-scanner.config.js, packages/design-system/package.json, packages/playground/package.json, packages/playground/src/app/components/Dataviz.js, packages/playground/src/app/index.js, packages/playground/src/assets/settings.json, packages/playground/webpack.config.dev.js, yarn.lock
current build is broken on 1.0.4 because the code use dynamic import and since we have removed ts-loader the results of the build is different and do not work anymore:
https://unpkg.com/browse/@talend/react-dataviz@1.0.3/dist/
https://unpkg.com/browse/@talend/react-dataviz@1.0.4/dist/
ts-loader has been removed between both release so now ts code is transpiled with babel.
ts was changing dynamic import into static one (knowing all possible combinations).
Note: diff on size change do not notify about new file created 🤦 
During the fix I had the following error at build:lib time:
```
ts5069: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration' or option 'composite'.
```
**What is the chosen solution to …
=> fix(ARCH-432/dataviz): remove dynamic import

.changeset/chilled-goats-arrive.md, packages/http/src/http.types.ts
=> chore(http): typings for error calls

packages/design-system/src/components/InlineEditing/InlineEditing.stories.mdx
=> doc(design-system): Figma illustrations to InlineEditing doc

.changeset/rich-ants-rhyme.md
The PR(https://github.com/Talend/ui/pull/3704) missing the change for the component package
Add changeset for "@talend/react-components"
=> fix(utils/date): convertToTimeZone function with specific timezone and summer time

.github/workflows/semgrep.yml
=> chore(semgrep): remove sync with gh alert tab

.github/workflows/pr-lint.yml, .husky/pre-commit, .prettierignore, package.json, prettier.sh, yarn.lock
Prettier changes were not committed anymore,
Due to the list of changed files not being generated.
Use [Husky](https://github.com/typicode/husky) to be sure that matches our guidelines, before pushing anything.
Keep Prettier (and ESlint) GH Action for generated Pull Request from outside, even if it means losing all your Github Checks.
=> chore: Husky 🐶 

yarn.lock
Talend/scripts has been fixed to 
- include @talend cdn packages from umd/apps build
- exclude @talend cdn packages from storybook 
Upgrade 
=> chore: update @talend/scripts

.changeset/stupid-yaks-heal.md, fork/dynamic-cdn-webpack-plugin/package.json
#3843 introduce issue: src is not released
add src to the release
=> fix: add missing src files to release

.changeset/ninety-candles-push.md, fork/module-to-cdn/modules.json
module-to-json test failed:
```
Expected: "expect(received).toBe(expected) // Object.is equality·
Expected: true
Received: false: https://unpkg.com/@sentry/browser@6.19.5/bundles/bundle.min.js"
Received: false
```
the path do not exists in that version
=> fix: sentry browser

.changeset/young-frogs-walk.md, packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/VirtualizedList/ListTable/ListTable.component.js, packages/components/src/VirtualizedList/ListTable/ListTable.scss, packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
We use tc-list-item in some components to display hovers (for sharing/certification/favorites cell renderer)
Add it back
=> fix(list): make hover work again with tc-list-item

.changeset/violet-moles-roll.md, packages/components/src/AboutDialog/AboutDialogTable.component.js
Text component return nothing in some cases and react really don't like it
=> fix(AboutModal): rendering issue while empty table

.github/workflows/design-system-visual-testing.yml
=> chore(design-system): Action for visual testing on PR ready

.github/workflows/tests-cron.yml, fork/module-to-cdn/index.test.js, fork/module-to-cdn/modules.test.js, fork/module-to-cdn/package.json, package.json
[module-to-cdn modules.json](https://unpkg.com/@talend/module-to-cdn/modules.json) file is crucial for us.
Every new release may break a build and can be hard for developers to understand what happens.
Current tests are runned only on next versions not on range edge versions which mean we do not cover the current range configuration.
* Fix the tests to be runned
* Move them to a dedicated file
* use a dedicated test command for it because thoses takes 2 minutes to run with cache and can be 30 minutes without cache.
* create a cron workflow that will create an issue if test fails
...
=> test(ARCH-497/module-to-cdn): fix tests and move them to cron

.changeset/silver-buckets-allow.md
=> chore: Fix changelog

.changeset/fluffy-cups-push.md
during #3910 I forgot to add changeset
add it
=> chore: add missing changeset

packages/design-tokens/supernova-exporter/src/exportSCSS/scss-tokens-with-path.pr, packages/design-tokens/supernova-exporter/src/exportTS/ts-dictionnary-with-path.pr
Naming mistakes 😬
Fixing the mistakes 😬
=> feat(design-tokens): Fix exporter

packages/design-system/.eslintrc.js
=> chore(design-system): fix eslint config

.changeset/cool-cups-invite.md, packages/flow-designer/src/components/node/AbstractNode.component.tsx
Node position is updated with the old one.
Fix it by aligning implementation with the right method signature
=> fix(TFD-14185/FlowDesigner): node position

SECURITY.md
no docs as reported in #3549 
add one
=> doc: add security doc

.changeset/twelve-masks-heal.md, fork/dynamic-cdn-webpack-plugin/src/find.js
on master we have issues introduced by #4028 on the playground which is not able to find packages developed inside the repo
```
DynamicCdnWebpackPlugin ERROR: 
❌ @talend/react-cmf addDependencies() couldn't load this lib because it has not been found by require.resolve
DynamicCdnWebpackPlugin ERROR: 
❌ @talend/react-cmf addDependencies() couldn't load this lib because it has not been found by require.resolve
DynamicCdnWebpackPlugin ERROR: 
❌ @talend/react-components addDependencies() couldn't load this lib because it has not been found by require.resolve
DynamicCdnWebpackPlugin ERROR: 
❌ @talend/react-forms addDependencies() couldn't load this lib because it has not been found by require.resolve
DynamicCdnWebpackPlugin ERROR: 
❌ …
```
=> fix(dynamic-cdn-webpack-plugin): findPackage follow symlink

packages/design-system/src/index.ts
=> fix(design-system): SkeletonInput is not exported

.changeset/rotten-carrots-sell.md, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js, packages/faceted-search/stories/badgesDefinitions.js
Expose a new property to `BadgeCheckboxes` badge component named `filterBarPlaceholder`.
This new property makes filter input placeholder in overlay customizable. 
=> feat(TDC-5462): customizable checkbox badge filter placeholderin faceted search

.changeset/rude-cobras-grow.md, packages/storybook-docs/package.json, yarn.lock
we have two versions of DS and a yarn.lock not up to date.
align ds usage
=> chore(ARCH-537): align DS usage

.changeset/fifty-snails-roll.md, packages/components/src/FormatValue/FormatValue.component.js, packages/components/src/FormatValue/FormatValue.test.js, packages/components/src/FormatValue/__snapshots__/FormatValue.test.js.snap
Using value as a key was not a good idea, at it represent a single character: we can have duplicates
=> fix(FormatValue): Key attribute can be duplicated

.changeset/fluffy-glasses-accept.md, packages/design-system/src/components/Tag/Tag.stories.mdx, packages/design-system/src/components/Tag/Tag.stories.tsx, packages/design-system/src/components/Tag/Tag.tsx, packages/design-system/src/components/Tag/index.ts, packages/design-system/src/components/Tag/variations/TagBeta.module.scss, packages/design-system/src/components/Tag/variations/TagBeta.tsx, packages/design-system/src/components/Tag/variations/index.ts, packages/design-system/src/index.ts
To highlight some beta feature, there is a tag for it.
Figma link
https://www.figma.com/file/hMYM9HGXajJpWdGwRb5ITR/branch/k657EbCvTs3rivkkvdi3Kb/Coral?node-id=128%3A1788
- [ x The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
=> feat(design-system): add BetaTag

.changeset/chilled-readers-flow.md, packages/design-system/src/components/Button/Primitive/ButtonPrimitive.tsx, packages/design-system/src/components/ButtonIcon/Primitive/ButtonIconPrimitive.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/Primitive/DropdownButton.tsx, packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixButton.tsx, packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixReadOnly.tsx, packages/design-system/src/components/Icon/Icon.tsx, packages/design-system/src/components/Icon/SizedIcon.tsx, packages/design-system/src/components/InlineMessage/Primitive/InlineMessagePrimitive.tsx, packages/design-system/src/components/Link/Link.tsx, packages/design-system/src/components/Linkable/Linkable.tsx, packages/design-system/src/components/Modal/Modal.tsx, packages/design-system/src/components/Status/Primitive/StatusPrimitive.tsx, packages/design-system/src/components/Stepper/Step/Step.tsx, packages/icons/.gitignore, packages/icons/package.json, packages/icons/scripts/typescript.js, packages/icons/tsconfig.json
we have a .d.ts in icons which do not follow the current bundle.
let's generate the ts file and call tsc to create an other file with both runtime and type aligned
=> feat: generate ts and compile it

packages/design-system/src/components/Switch/docs/Switch.stories.mdx
Edited the introductory sentence in the section to make it clear to use only one word in the labels placed inside the switch.
=> Switch content guidelines

.changeset/thirty-llamas-act.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js
The entry in Data list is updated only if value has changed
When the title map is asynchronously loaded, for example, depending on value of another Data list, 
the name of entry can be the same as value (when the title map has changed, but the value is still old one, and there is not entry with this value in new title map, by default, for some time, the name will be the same as value)
So, this condition won't be true https://github.com/Talend/ui/blob/master/packages/components/src/Datalist/Datalist.component.js#L150 , as the value won't equal to filter value, and so, it won't update filter value, and previous filter value (from previous title map) will be displayed, although there will be a new value selected from new title map (the …
=> fix(Datalist/TDOPS-2632): update data list entry if name is not the same

.changeset/nice-moles-serve.md, packages/assets-api/src/index.ts
assets-api has an annoying log in tests
=> fix(assets-api): Remove annoying log

.changeset/plenty-otters-switch.md, packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.component.tsx, packages/datagrid/src/components/PlaygroundCellEditor/ApplyToIdenticalValues.component.tsx, packages/datagrid/src/components/PlaygroundCellEditor/PlaygroundCellEditor.component.tsx, packages/datagrid/src/components/RichCellEditor/components/CellEditorDatalist.component.tsx, packages/datagrid/src/components/RichCellEditor/components/CellEditorTextarea.component.tsx
It's difficult to get type & title in e2e tests
=> feat(datagrid): Add data-testid and data-feature

.changeset/little-suns-sparkle.md, packages/datagrid/src/constants/column-definition.constants.ts
=> fix(datagrid): Improve colDef typings

.changeset/strong-teachers-drive.md, packages/design-system/src/components/WIP/Popover/Popover.module.scss, packages/design-system/src/components/WIP/Popover/Popover.stories.mdx, packages/design-system/src/components/WIP/Popover/Popover.stories.tsx, packages/design-system/src/components/WIP/Popover/Popover.tsx, packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Padding styles were not applied where they should be. 
Stories had been broken.
Fixing it.
=> feat(design-system/NO-TICKET): Fixing Popover stories and styles

.changeset/seven-chefs-design.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
=> fix(faceted-search): infinite loop with initialBadges

.changeset/ninety-clocks-drum.md, package.json, yarn.lock
`trim` dependency has a security issue in version 0.0.1 (currently used in the repository). A fix has been released since 0.0.2 for that.
`trim` is only needed by the `eslint` talend-script package as shown above.
I had to force the resolution of the package as no newest package of eslint-mdx package is updating the `trim` dep unfortunately... so we have to handle it by ourself for now.
According to the [release note](https://github.com/Trott/trim/blob/main/CHANGELOG.md) of `trim` we can move directly to the lastest 1.0.1 version as no breaking apparently.
Only a release of talend-script-eslint is required for the fix to be applied. …
=> fix(talend-scripts-eslint): force trim bump for better security

.changeset/giant-rice-end.md, packages/playground/src/app/components/DataGrid.js
=> fix: playground datagrid

.changeset/afraid-ads-vanish.md, tools/scripts-config-storybook-lib/.storybook-templates/msw/mockServiceWorker.js, tools/scripts-config-storybook-lib/package.json
same as #4343 
re generate setup of the worker after msw upgrade
=> fix(storybook config): msw setup update

.changeset/big-papayas-wave.md, packages/components/src/VirtualizedList/CellTitle/CellTitleActions.module.scss
=> fix(List): separator alignment for persistent actions

.changeset/proud-mails-heal.md, packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js, packages/components/src/CollapsiblePanel/CollapsiblePanel.test.js, packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap, packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/DateTimeView.component.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/DateTimeView.test.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap, packages/components/src/DateTimePickers/views/DateView/DateView.component.js, packages/components/src/DateTimePickers/views/DateView/DateView.test.js, packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap
=> fix(Collapsible/LegacyDatePicker/DatePicker): using design system ButtonIcon

packages/playground/src/settings/settings.json
current playground is broken
regression introduced by #4477
fix the settings
=> fix: playground

.changeset/four-tomatoes-develop.md, packages/components/src/List/List.component.js, packages/components/src/List/Toolbar/SelectAll/SelectAll.component.js
pass translator function as property to select all
=> fix(TDS-5962): not translated "Select All"

.changeset/four-tomatoes-develop.md, packages/components/src/List/List.component.js, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.component.js
Not translated "Select all" in HeaderCheckBox component
Add translator function using useTranslate hook in the component
=> fix(TDS-5962): fix not translated "Select All"

packages/components/src/AppLoader/AppLoader.stories.js
In the context of get a better documentation I propose here to start simplify stories using argument control panel available.
Give an example with the AppLoader:
=> doc(components/AppLoader): simplify story using argTypes and remove all stories

.eslintrc.js, tools/scripts-config-eslint/package.json, tsconfig.json, yarn.lock
forget to commit this on #4511  so eslint do not work on master
commit the eslint fix
=> chore(ARCH-669): fix eslintrc config of the repository

package.json
on every commit I have the following error:
```
jean@LT-7MWFCK3:~/github/talend/ui (jmfrancois/chore/try-esm)$ git commit -am 'chore: remove console.log'
> lint-staged
> lint-staged
✔ Preparing lint-staged...
❯ Running tasks for staged files...
❯ package.json — 1 file
❯ *.{js,jsx} — 1 file
✖ eslint --quiet --fix [SIGABRT]
↓ *.{ts,tsx} — no files [SKIPPED]
✔ *.{json,md,mdx,html,js,jsx,ts,tsx} — 1 file
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
✖ eslint --quiet --fix:
<--- Last few GCs --->
[228869:0x63837f0]    28914 ms: Scavenge 4037.1 (4113.9) -> 4035.6 (4114.4) MB, 9.7 / 0.0 ms  (average mu = 0.858, current mu = 0.650) allocation failure …
```
=> chore: fix husky lint-staged config

SECURITY.md
=> doc: update SECURITY.md

.changeset/purple-bugs-chew.md, tools/scripts-config-react-webpack/config/webpack.config.common.js, tools/scripts-config-react-webpack/config/webpack.config.js, tools/scripts-config-react-webpack/config/webpack.config.umd.js
Styles dont get updated in dev mode when a sass file is changed
=> fix(TDOPS-3569/webpack): fix sass hmr on file change

.changeset/wild-seahorses-approve.md, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.module.scss, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.test.js, packages/faceted-search/src/dictionary/operator.dictionary.js, packages/faceted-search/stories/badgesDefinitions.js, packages/faceted-search/stories/facetedSearch.stories.js
Faceted search new operators and select all function
=> feat(TDOPS-421): faceted search new operators and select all function

.changeset/chilled-jars-fix.md, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js, packages/faceted-search/src/components/Badges/BadgeDate/BadgeDate.component.js, packages/faceted-search/src/components/Badges/BadgeDate/BadgeDateForm.component.js, packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js, packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js, packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js, packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js, packages/faceted-search/src/components/Badges/BadgeTags/BadgeTagsForm.component.js, packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js, packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js, packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/QuickSearchInput/QuickSearchInput.component.js, packages/faceted-search/src/helpers/usage.helpers.js, packages/faceted-search/src/helpers/usage.helpers.test.js, packages/faceted-search/stories/badgesDefinitions.js, packages/faceted-search/stories/facetedSearch.stories.js
Pass data attributes to faceted search components
=> feat(TDOPS-421): Pass data attributes to faceted search components

.changeset/new-cups-eslint.md
https://github.com/Talend/ui/actions/runs/4606080992/jobs/8138936487#step:5:24
edit changeset file with valid package name
=> chore: fix changeset file with invalid package

.changeset/tame-donkeys-leave.md, tools/scripts-locales/README.md, tools/scripts-locales/package.json
=> fix(script-locales): add missing dep

.changeset/empty-donkeys-march.md, packages/components/src/ResourceList/Resource/Resource.module.scss
In Figma: 
Currently :
After the Fix:
=> fix(ResourceList): alignment issue

.changeset/great-chicken-cheer.md, packages/cmf-cqrs/package.json, packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js, packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.test.js
we target react 18.
* rewrite tests using RTL
* refactor ACKDispatcher as function component with new context API
=> chore(ARCH-458): refactor cqrs

.changeset/little-dolphins-worry.md, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
=> fix(storybook): forward for msw

.changeset/grumpy-cars-teach.md, packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.module.scss, packages/faceted-search/stories/facetedSearch.stories.js
=> fix(faceted-search): badge overlap with button

.changeset/great-sheep-exercise.md, packages/design-system/src/components/RichRadioButton/RichRadioButton.component.tsx
=> fix(design-system): add data attr to RichRadioBtn

packages/design-system/src/components/Combobox/Combobox.tsx, packages/design-system/src/components/Divider/Divider.tsx, packages/design-system/src/components/Tabs/Primitive/TabPanel.tsx, packages/design-system/src/components/Tabs/Primitive/TabState.ts, packages/design-system/src/components/Tabs/Tabs.stories.tsx, packages/design-system/src/components/Tabs/variants/TabsKit.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx, packages/design-system/tsconfig.json, packages/storybook/.storybook/docs/tokensDocHelpers/ColorCompositions/ColorCompositions.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/TokensBreakpoint.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/TokensColor.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/TokensColorCharts.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/TokensMeasure.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/TokensTypes.ts, packages/storybook/.storybook/docs/tokensDocHelpers/TokensTypography.tsx, packages/storybook/.storybook/docs/tokensDocHelpers/components/DefinitionList/DefinitionListColors.tsx, packages/storybook/custom.d.ts, packages/storybook/src/design-system/Accordion/Accordion.stories.mdx, packages/storybook/src/tokens/ThemeWithTokens.tsx, packages/storybook/src/tokens/types.ts
Fix regressions removing reakit
**PR based on this one : https://github.com/Talend/ui/pull/4751**
So this has to be merged in branch on which it is based before merging the base one.
========
> Fixed (import to update)
> Fixed (rework state management)
> Fixed (rework state management)
> Fixed (udpate style)
> Fixed (add onBlur event listener)
> Fixed (add onClick event listener)
> Fixed (add default orientation value)
**Component has been removed. Clone has to be developed (action from jmfrancois)**
**TODO**
**TODO**
**TODO**
**TODO**
**TODO**
**TODO**
========
=> Jmainguy/chore/ds no reakit/fixes

.changeset/ninety-badgers-rescue.md, packages/components/src/GridLayout/Grid.module.scss, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.module.scss
=> fix: GridLayout and Subheader css changes

fork/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss, packages/components/src/TooltipTrigger/TooltipTrigger.module.scss, packages/storybook/src/design-system/Elevation/Elevation.stories.mdx, packages/storybook/src/design-system/Elevation/Elevation.stories.tsx
[TUI] Wrong colors or styles
- Story added for Elevation
- zIndex variables updated  in fork/bootstrap-sass
=> fix(TDOPS-4875): elevation improvements and added story in DS

.changeset/smooth-taxis-compete.md, packages/theme/src/theme/_buttons.scss
fix various border issues with bootstrap buttons
=> fix(ARCH-720): fix various border issues with bootstrap buttons

.changeset/flat-pots-study.md, packages/forms/src/UIForm/index.js, packages/forms/src/index.ts
=> chore: export component code

.changeset/popular-bobcats-wink.md, packages/components/src/FilterBar/FilterBar.component.js, packages/components/src/ResourceList/Toolbar/NameFilter/NameFilter.component.js, packages/components/src/ResourceList/Toolbar/NameFilter/__snapshots__/NameFilter.snap.test.js.snap, packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap, packages/theme/src/theme/_buttons.scss, packages/theme/src/theme/_navbar.scss
Improve hover and active color for bootstrap button
=> fix(ARCH-720): Improve hover and active color for bootstrap button

.changeset/large-beers-change.md
Add missing changeset for https://github.com/Talend/ui/pull/4853
=> feat(TDOPS-4488): Add missing changeset

.changeset/early-clouds-appear.md
=> feat(tdc-7256): add missing changeset

.changeset/new-adults-compare.md, packages/forms/src/UIForm/fields/Code/Code.component.tsx
=> fix(components/Code): undefined value while mounting

.changeset/happy-bees-walk.md, packages/forms/src/UIForm/fields/Code/Code.component.test.tsx, packages/forms/src/UIForm/fields/Code/Code.component.tsx
=> feat(TFD-15931) components/Code: add flag to show/hide instructions div

packages/dataviz/talend-i18n.json, packages/faceted-search/talend-i18n.json
fix extract path for translation jenkins job
=> chore(ARCH-662): fix extract path for translation jenkins job

.changeset/strong-trees-grin.md, packages/design-system/src/components/Icon/index.ts
import issues in Layout component tests
export specific types in Icons component to resolve js reference issues
=> fix(TDOPS-5534/dependencies): proper export of Icon enums

.changeset/nervous-plums-drop.md, packages/design-system/src/components/Form/Affix/variations/AffixSelect.tsx, packages/design-system/src/components/Form/Field/Datalist/Datalist.tsx, packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx, packages/design-system/src/components/Form/Field/Input/Input.File.tsx, packages/design-system/src/components/Form/Field/Input/Input.tsx, packages/design-system/src/components/Form/Field/Select/Select.tsx, packages/design-system/src/components/Form/Field/Textarea/Textarea.tsx, packages/design-system/src/components/Form/__snapshots__/Form.test.tsx.snap
=> fix(design-system): binding in forms

.changeset/few-vans-beam.md, packages/design-system/src/components/Popover/Popover.module.scss
=> fix(design-system): Add z-index to Popover module

.changeset/afraid-ways-relate.md, packages/components/src/DateTimePickers/DateRange/Picker/__snapshots__/Picker.component.test.js.snap, packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/DateTimeView.component.js, packages/components/src/DateTimePickers/views/DateView/DateView.component.js
fix tooltip on date time range picker
=> fix(TDOPS-5671): fix tooltip on date time range picker

.changeset/mighty-shoes-jam.md, .prettierrc.js, tools/babel-plugin-import-d3/src/index.test.js, tools/babel-plugin-import-from-index/src/index.test.js, tools/scripts-config-prettier/.prettierrc.js
=> fix: prettier configuration for sort imports

.changeset/wicked-panthers-film.md, packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx
=> Fix(design-system): issue with theme provider

package.json, packages/dataviz/cypress.config.js, packages/dataviz/cypress.d.ts, packages/dataviz/cypress/support/commands.ts, packages/dataviz/package.json, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.cy.tsx, packages/design-system/cypress.config.js, packages/design-system/package.json, yarn.lock
=> fix: cypress not working with config in ts

fork/module-to-cdn/README.md, fork/module-to-cdn/jsonschema.json, tools/babel-plugin-assets-api/README.md, tools/eslint-plugin/README.md, tools/scripts-cmf/README.md, tools/scripts-config-babel/README.md, tools/scripts-config-cdn/modules.json
=> doc: update all documentation

.changeset/gold-pets-remain.md, packages/design-system/src/components/Message/Primitive/MessagePrimitive.tsx, packages/design-system/src/components/Message/Primitive/MessageStyles.module.scss, packages/design-system/src/stories/messaging/Message.stories.tsx
=> fix(design-system): Messages adjustments

.changeset/nice-schools-cry.md, packages/cmf/__tests__/settings.test.js, packages/cmf/src/settings.js
=> fix(): Fix security issue on regular expression

.changeset/clean-frogs-check.md, packages/utils/src/date/index.ts
=> fix(): Reduce package size by fixing date-fns import

.changeset/blue-students-invent.md, packages/design-system/src/components/Skeleton/Primitive/Skeleton.Primitive.tsx, packages/design-system/src/components/Skeleton/Skeleton.tsx, packages/design-system/src/components/Skeleton/index.ts, packages/design-system/src/components/Skeleton/variations/SkeletonButton.tsx, packages/design-system/src/components/Skeleton/variations/SkeletonButtonIcon.tsx, packages/design-system/src/components/Skeleton/variations/SkeletonHeading.module.scss, packages/design-system/src/components/Skeleton/variations/SkeletonHeading.tsx, packages/design-system/src/components/Skeleton/variations/SkeletonInput.tsx, packages/design-system/src/components/Skeleton/variations/SkeletonParagraph.module.scss, packages/design-system/src/components/Skeleton/variations/SkeletonParagraph.tsx, packages/design-system/src/components/Skeleton/variations/SkeletonSized.module.scss, packages/design-system/src/components/Skeleton/variations/SkeletonSized.tsx, packages/design-system/src/stories/feedback/Skeleton.mdx, packages/design-system/src/stories/feedback/Skeleton.stories.tsx
There is some limitation when designing skeletons
- Add new width for header and paragraph skeletons
- Add new SkeletonSized that can be shaped for any needs
=> feat(design-system): Skeleton update

.changeset/stale-cars-battle.md, packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js, packages/forms/src/UIForm/fieldsets/Array/ArrayItem.module.scss, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
fix form arrayitem widget design and alignment
=> fix(TDOPS-5706): fix form arrayitem widget design and alignment

.changeset/cyan-moons-yell.md, packages/components/src/HeaderBar/HeaderBar.module.scss, packages/containers/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap, packages/design-tokens/src/qlik-light/_index.scss, packages/design-tokens/src/qlik-light/dictionary.ts, packages/design-tokens/src/qlik-light/index.ts
=> fix: adjustments for qlik-light theme

.changeset/cuddly-kings-melt.md, packages/components/src/HeaderBar/HeaderBar.module.scss, packages/design-system/package.json
=> fix: help icon color in the header bar

.changeset/plenty-dodos-tan.md, packages/components/src/HeaderBar/HeaderBar.module.scss
=> fix: elevation layer on headerbar

.changeset/real-spoons-shop.md, fork/bootstrap-sass/assets/stylesheets/bootstrap/_scaffolding.scss
=> feat: Remove font-size override in _scaffolding.scss

.changeset/swift-beers-play.md
I forgot some changeset in a previous PR...
... add them.
=> fix: missing changeset for new rem values

.changeset/mean-fireants-sip.md, packages/design-system/src/components/Message/Primitive/MessagePrimitive.tsx, packages/design-system/src/components/Message/Primitive/MessageStyles.module.scss, packages/design-system/src/components/Message/__snapshots__/Message.test.tsx.snap
=> fix: font-color for children element in Messages component

.changeset/eighty-files-clean.md, packages/components/src/DateTimePickers/DateRange/Picker/__snapshots__/Picker.component.test.js.snap, packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.component.js, packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.test.js, packages/components/src/DateTimePickers/views/DateView/DateView.component.js, packages/components/src/DateTimePickers/views/DateView/DateView.test.js, packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap, packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js, packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.module.scss, packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.test.js, packages/components/src/DateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap, packages/faceted-search/src/components/Badges/BadgeDate/__snapshots__/BadgeDateForm.component.test.js.snap, packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap
Enhance date picker to reduce clicks needed
=> feat(TDOPS-448/Components): Enhance date picker to reduce clicks needed

.changeset/tiny-buttons-roll.md, packages/design-system/src/components/Stack/StackHorizontal.tsx, packages/design-system/src/components/Stack/StackItem.tsx, packages/design-system/src/components/Stack/StackVertical.tsx
=> feat: remove restrictions on stacks for height and width

.changeset/giant-dodos-clean.md, packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
https://jira.talendforge.org/browse/DFD-629
Add tooltip label
=> fix(DFD-629): Add array item delete button tooltip

.changeset/slimy-shrimps-remain.md, packages/components/src/ListView/Items/Item/Item.component.js, packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap, packages/components/src/ListView/Items/Items.component.js, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
fix ListView vlist calculation with many items
=> fix(components): fix ListView vlist calculation with many items

packages/storybook-one/.storybook/main.js
=> fix(storybook): add ui form root stories

.changeset/afraid-avocados-beam.md, packages/components/src/Typeahead/Typeahead.module.scss
=> fix: Datalist highlighted element (keyboard navigation)

.changeset/poor-papayas-grab.md, packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js, packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.module.scss, packages/faceted-search/src/components/AdvancedSearch/__snapshots__/AdvancedSearch.component.test.js.snap, packages/faceted-search/stories/facetedSearch.stories.js
=> refactor: Update AdvancedSearch component to use design system text input

.changeset/fresh-hats-juggle.md, packages/design-system/src/components/Form/Primitives/InputWrapper/InputWrapper.module.scss, packages/design-system/src/components/Form/Primitives/_mixins.scss
=> fix(design-system): height for input wrapper

.changeset/orange-fishes-applaud.md
changeset for "switch components dates to use design system inputs"
=> chore(components): changeset

.changeset/fuzzy-nails-battle.md, packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.component.js
=> Fix tooltip alignment for buttons in list component

.changeset/pretty-knives-judge.md, fork/dynamic-cdn-webpack-plugin/package.json, fork/dynamic-cdn-webpack-plugin/test/helpers/clean-dir.js, package.json, packages/jsfc/package.json, packages/theme/package.json, tools/scripts-build-cdn/build.js, tools/scripts-build-cdn/clean.js, tools/scripts-build-cdn/package.json, tools/scripts-core/__tests__/index.test.js, tools/scripts-core/package.json, tools/scripts-core/src/scripts/build-lib.js, tools/scripts-publish-local/package.json, tools/scripts-publish-local/src/npm.js, tools/scripts-publish-local/src/verdaccio.js, tools/upgrade-deps/tests/cli-security.test.js, tools/upgrade-deps/tests/cli.test.js, tools/upgrade-deps/tests/utils.js
Goal is to upgrade rimraf to the latest version
=> chore: Upgrade rimraf

.changeset/tame-toes-ring.md, .github/workflows/design-system-component-testing.yml, packages/design-tokens/package.json, packages/icons/package.json
=> fix(TMC-28189): cypress need esm

.changeset/wise-dancers-smash.md, .github/workflows/design-system-component-testing.yml, packages/design-tokens/package.json, packages/icons/package.json
Improve changes made for cypress
=> fix(TMC-28189): cypress need esm (improvements)

.changeset/shaggy-weeks-rule.md, packages/forms/package.json
Fix export in react-forms to be able to import things using /lib/...
=> fix(TMC-28189): fix exports config in react-forms

.changeset/modern-nails-impress.md, packages/components/package.json, packages/containers/package.json, packages/design-system/package.json, packages/utils/package.json
=> Revert "fix: Fix exports to allow deep imports"

.changeset/polite-items-add.md, fork/module-to-cdn/modules.json
=> fix: update ag-grid module to use the right path

.github/workflows/demo.yml
=> fix: Fix branch for demo action

.changeset/fuzzy-frogs-arrive.md, packages/containers/package.json, packages/design-docs/package.json, packages/forms/package.json, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js, packages/forms/src/UIForm/fields/ListView/ListView.component.js, packages/forms/src/UIForm/fields/ListView/ListView.component.test.js, packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js, packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js, packages/playground-vite/package.json, packages/playground/package.json, packages/storybook-one/package.json, yarn.lock
Enhance translation on Enumeration and ListView widget
=> fix(TMC-861): enhance translation on Enumeration and ListView widget

.changeset/chatty-rules-kick.md, packages/containers/package.json
Upgrade cmf in react-containers
=> chore(containers): upgrade cmf

.github/workflows/changeset.yml, yarn.lock
=> upgrade axios to 0.30.0

.changeset/moody-candies-feel.md, packages/components/package.json, yarn.lock
We revert simplebar from 6.3.1 to 6.2.7 because of some issues on ui-dataset storybook build, "getOptions undefined"
=> chore(deps): Bump simplebar-react@^3.3.1 simplebar@6.2.7

.changeset/pink-cobras-give.md, fork/dynamic-cdn-webpack-plugin/package.json, packages/icons/package.json, packages/storybook-docs/package.json, packages/theme/package.json, tools/scripts-config-react-webpack/package.json, yarn.lock
=> chore(deps): Bump webpack-cli@6.0.1
