packages/components/src/HeaderBar/HeaderBar.scss
#3064 added a scoping for logo svg color, but it turned the global selector into a css module which is not applied anymore.
Set back the global selector
=> fix(HeaderBar): logo color

packages/components/src/DataViewer/Virtualized/TreeCellMeasurer/TreeCellMeasurer.component.js
remove the undefined props key
=> fix: remove key props

packages/components/src/Badge/Badge.component.js, packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
We have lots of logs during tests in some project because Badge has no displayName
We can t create a new Array template in forms because we don t have access to the ArrayItem.
* add displayName to Badge
* expose ArrayItem
=> fix(forms): expose arrayitem

packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
internal onSubmit will be overwritten by props.onSubmit when spread props to ColumnChooserButton.
omit onSubmit when spread props.
=> fix(ColumnChooser): do not overwrite onSubmit

packages/forms/.storybook/config.js
current forms storybook are blank because all stories are wrapped in IconsProvider and we revert this need in #3071 but forgot to fix all storybooks
Unwrap stories
=> fix(forms/storybook): unwrap IconsProvider

packages/components/src/VirtualizedList/CellDatetime/DatetimeColumn.component.js
Compute value is usefull in order to create the extended view
Expose it with the datetime column
=> fix: add missing export

output/forms.eslint.txt, packages/components/src/ListView/Items/Item/Item.component.js, packages/components/src/ListView/Items/Items.scss, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
listView styles issue
-Add class to set display: flex only for item with an icon
=> fix(ListView): add class to set display: flex only for item with icon

output/forms.eslint.txt, packages/forms/src/UIForm/Message/Message.component.test.js, packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap, packages/forms/src/UIForm/UIForm.component.js, packages/forms/src/UIForm/UIForm.container.js, packages/forms/src/UIForm/UIForm.container.test.js, packages/forms/src/UIForm/Widget/Widget.component.js, packages/forms/src/UIForm/Widget/Widget.component.test.js, packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap, packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap, packages/forms/src/UIForm/context.js, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js, packages/forms/src/UIForm/fields/ListView/ListView.component.js, packages/forms/src/UIForm/fields/ListView/ListView.component.test.js, packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js, packages/forms/src/UIForm/fields/Radios/Radios.component.js, packages/forms/src/UIForm/fields/Text/Text.component.test.js, packages/forms/src/UIForm/fieldsets/Array/Array.component.js, packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js, packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.component.js
This PR is a cherry-pick from TUI 6.
Today in UIForms widgets are rendered by Widget component which recieve custom widgets by props and import default ones.
UIForm import './Widget/Widget.component';
Widget import '../utils/widgets';
utils/widgets import import '../fieldsets/Array';
Array import '../../utils/widgets';
Circular dependencies !
* Make widgets registry accessible only by context inside UIForm widgets code base.
* update all tests
* fix all lints errors
=> chore(forms): break circular dependencies (#3084)

packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
You can't define your own column list definition since #3076 
Fix this by spreading props after the default column list management in the `ColumnChooser`
=> fix(List/ColumnChooser): let's defined its own columns

packages/forms/src/UIForm/fields/File/File.component.js, packages/forms/src/UIForm/fields/File/File.component.test.js, packages/forms/stories-core/jsonStories.js
The current atob() method used to decode base64 file names for the file upload component does not support multi-byte characters (e.g. `ć, è`). This results in parsing errors when the file name is displayed in the input value (e.g. `cÌ.xlsx`).
The decoding function is improved based on the SO discussion linked below. This solution includes additional decoding steps to reduce the content to a byte stream and re-encode it to produce the original string. Initial tests indicate that this approach is flexible enough to service multiple base64 encoding approaches and as such should not result in a breaking change if the components is provided a string encoded using simply `window.btoa()`.
In …
=> fix(TDC-3764/File): Support base64 encoded file names with multi-byte characters

packages/components/src/ListView/Items/Items.scss
Add margin-left to item with an icon
=> fix(ListView): add margin-left to item with icon

packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.scss
default value makes timepicker with seconds not nice : 
making it a little bit bigger by default 
=> fix(TimePicker): default width should be slightly bigger

output/components.eslint.txt, packages/forms/src/rhf/fields/Input/Input.stories.js, packages/forms/src/rhf/fields/Input/Input.test.js, packages/forms/src/rhf/fields/Input/RHFInput.component.js
with UMD build react-hook-form/dist/ie11 is not umd so it is embed in the UMD
on the project side this is the same.
but having rhf embed on both bundle make the provider different.
The side effect of this is useFormContext function call return null like if the context was not provided.
Remove ie11 dist import to rely on umd so the code is shared.
```diff
-import { useFormContext } from 'react-hook-form/dist/index.ie11';
+import { useFormContext } from 'react-hook-form';
```
=> fix(forms): remove ie11 support to be umd compliant

packages/theme/src/theme/_navs.scss
`line-height` was fixed to 1
No reason to be hard coded, let's remove it.
=> fix(theme): remove line-height on nav items

packages/components/src/TabBar/TabBar.scss
#3021 has introduce a regression on the tabs rendererd. (5.28 -> 5.29)
Since 5.29 the ul of tabs do not take full width. 
add flex: 1;
=> fix(tabbar): make tabs take full space

output/components.eslint.txt, packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.stories.js, packages/components/src/WithDrawer/WithDrawer.component.js
Since #2958 we have a regression on unmounted Drawer components which stay there.
* Spread the props from TransitionGroup to Transition has mentionned in the documentation
* Add story so we can play with it
=> fix(drawer): spread props to  Transition

packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.js, packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.js, packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js
"Select all" option in the lists' column choser should apply to shown columns (e.g. those shown when the user filters the list of columns)
Integrate filtering into the column chooser manager and update the manager's behavior accordingly, example :
- Given a list with 3 columns, "_First name_", "_Last name_", "_Login_", all 3 checked (so "_Select all_" is also checked)
- User types in "_name_" in the filter (only "_First name_" and "_Last name_" appear in the list) **→** Unchecks "_Select all_" **→** Apply
- Only "_Login_" column is shown in the list
=> fix(List/ColumnChooser): "Select all" and columns list filter

packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/error-messages.js, packages/components/src/DateTimePickers/shared/error-messages.js
https://jira.talendforge.org/browse/TMC-23816
after importing t directly, there is issue in TMC, t is run not in context of i18n object, so this is not defined
binding context will lead to importing default export anyway
=> fix(DateTimePickers/TMC-23816): revert import from i18next

packages/containers/src/ComponentForm/index.js
nameresolver is not exposed in ComponetnForm
When you want to create specific widget for tacokit this is needed
expose it
=> fix(ComponentForm): export name resolver

.github/workflows/release-variables.sh, .github/workflows/release.yml
set-env is deprecated using GH Action
use set-output instead 
=> chore: release using GH action

packages/components/src/Enumeration/Items/Item/Item.scss
The checkbox is not align with the text
fix the heigh value in the css
=> fix(components/enumeration): Fix checkbox position

packages/components/src/VirtualizedList/HeaderResizable/HeaderResizable.scss
Wrong position for the order icon with the resizable column
align text and icon
=> fix(components/list composition): wrong position for the order icon with resizable column

packages/theme/package.json
In a new install, we have a peer dependency issue. Theme v6 requires an icon package v5.
Make it require icons >=6
=> chore(theme): flexible icon peer dep

packages/components/src/Datalist/Datalist.scss, packages/components/src/Emphasis/Emphasis.scss, packages/components/src/Typeahead/Typeahead.component.js, packages/components/src/Typeahead/Typeahead.component.renderers.js, packages/components/src/Typeahead/Typeahead.scss, packages/components/src/Typeahead/Typeahead.stories.js, packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap, packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Our Typeahead component is a bit outdated : 
Align it to the new guidelines : http://guidelines.talend.com/document/92132#/ui-controls/typeahead
- A new `manageNavigation` prop has been added in order to optionally let the component manage the up/down nav (currently, every projects has to reimplement it).
- A new `hint` boolean can be set to `true` in the sections. The section will render has a... hint : 
=> feat(components/typeahead): align to guidelines

packages/forms/src/rhf/fields/Select/RHFSelect.component.js, packages/forms/src/rhf/fields/Select/Select.stories.js, packages/forms/src/rhf/fields/Select/Select.test.js, packages/forms/src/rhf/fields/Select/index.js, packages/forms/src/rhf/index.js, packages/forms/src/widgets/fields/Select/Select.component.js, packages/forms/src/widgets/fields/Select/Select.test.js, packages/forms/src/widgets/fields/Select/index.js, packages/forms/src/widgets/fields/index.js
Forms validation in Talend UI are now available through React Hook Forms, but we only have one input wrapper for now.
To help us building forms in app faster, i propose to add the Select.
Add the Select field wrapper for React Hook Form, add the select widget, with the stories related
=> feat(forms): Add Select widget in React Hook Form

output/components.sasslint.txt, packages/cmf-cqrs/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/http/package.json, packages/router/package.json, packages/sagas/package.json, packages/stepper/package.json
Copylib is kind of broken and it's a way to separate the umd build for prod and for dev
=> chore: update build commands

packages/components/src/Drawer/Drawer.component.js, packages/components/src/WithDrawer/WithDrawer.component.js
Before #2958 drawer receive a transitioned props.
Since then the props do not exists anymore
add it back once transition is done.
=> fix(Drawer): add transitioned props for BCompat

output/components.eslint.txt, packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.js, packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.test.js
Replace the function body of DefaultSort to use Intl.Collator(...).compare()
Doc to Intl.Collator : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Intl/Collator
=> fix(components): ListComposition/DefaultSort - simplify body of defaultSort function

.github/workflows/dataviz-autopublish.yml, .github/workflows/release.yml
When a Talend/ui release is done, CDN content should be updated manually
Once the packages are on NPM, let's trigger the Github Action from [Talend/cdn-content](https://github.com/Talend/cdn-content/actions?query=workflow%3A%22Download+CDN+content+to+git%22) in order to create or update the PR
=> chore: trigger webhook to update cdn content after a release

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/BarChart/ColoredBar/ColoredBar.component.tsx, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.test.tsx, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.tsx, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.stories.tsx, packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.tsx, packages/dataviz/src/components/TooltipContent/TooltipContent.component.scss, packages/dataviz/src/components/TooltipContent/TooltipContent.component.tsx, packages/dataviz/src/components/TooltipContent/TooltipContent.stories.tsx, packages/dataviz/src/components/TooltipContent/__snapshots__/TooltipContent.component.test.tsx.snap, packages/dataviz/src/types/index.ts
Tooltip values are blue, which doesn't match with the "orange" pattern charts
Provide a chartStyle prop to the tooltip content and add color support
=> feat(Dataviz): Add pattern color in tooltip

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/RangeFilter/input-fields/NumberInputField.component.test.tsx, packages/dataviz/src/components/RangeFilter/input-fields/useRangeInputField.hook.ts
onChange is triggered when leaving the field without changing the value
=> fix(Dataviz): Unnecessary onChange triggered

packages/components/src/index.js
https://github.com/Talend/ui/pull/3138 was missing root level exports
=> fix(DatePicker): Missing root export

packages/dataviz/CHANGELOG.md, packages/dataviz/src/components/BarChart/barChart.tooltip.ts, packages/dataviz/src/components/RangeFilter/RangeFilter.component.tsx, packages/dataviz/src/constants.ts
i18n namespace is not used in charts components, keys are not translated in apps
=> fix(dataviz): Missing i18n namespace

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/constants.ts
Dataviz is using faceted search namespace...
=> fix(dataviz): Wrong i18n namespace

packages/forms/src/UIForm/fields/Datalist/Datalist.component.js, packages/forms/stories-core/json/fields/core-datalist.json
Following https://github.com/Talend/ui/pull/2959, I need to add `data-*` attributes to the datalist component to ease the automated test.
Update UIForms to add the `data-*` properties available in the `uiSchema` to the generated HTML elements.
```
{
"key": "simpleDatalist",
"title": "Simple Datalist",
"description": "This datalist accepts values that are not in the list of suggestions",
"widget": "datalist",
"data-test": "datalist.simple"
},
```
Will result in
`<input data-test="datalist.simple" type="text" id="simpleDatalist" value="Pine[apple]" ...>`
=> feat(TPSVC-15539): add data attributes to the forms

packages/containers/src/DeleteResource/sagas.js
Currently DeleteResource will redirect to configured url regardless of result of delete request. it will redirect no matter delete is successful or not.
only redirect when delete is successful
=> fix(containers/DeleteResource): Redirect only when delete is successful

packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
when adding a line using the validate and add button, the input is not refocused so that we can continue typing in not connected mode
force focusing it
=> fix(EnumerationWidget): focus input on validate add when not connected

lerna.json, packages/cmf-cqrs/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/generator/package.json, packages/icons/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json
Following changes are not released
* 57ff3c2e3  2021-01-04 feat(cmf): add http error attributes from RFC 7807 (#3128)
* dfd39a46f  2021-01-04 fix(EnumerationWidget): focus input on validate add when not connect..
* 048fef6b4  2021-01-04 fix(container/deleteresource): redirect only when delete is successf..
Release them
=> chore: release 6.7.0

packages/components/src/Enumeration/Enumeration.scss, packages/components/src/Enumeration/Items/Item/Item.scss, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
some display issue when dupplicate on edit mode and also editing a value and retyping the exact one ends in error, 
everything is described here : 
* When re-typing an exact same value, warning "This term is already in the list"
* "This term is already in the list" is misplaced
* Icons for Validate and Remove are displaced a little bit upwards and not aligned anymore
Can be check in the forns/field/Enumeration story
Fix placement and behavior.
Just edit value using the same value as previous in http://3153.talend.surge.sh/forms/?path=/story/uiform-v2-core-fields--core-enumeration
=> fix(TDS-5773/Enumeration): msgs placement and behavior

output/components.eslint.txt, packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js, packages/components/src/CollapsiblePanel/CollapsiblePanel.stories.js, packages/components/src/CollapsiblePanel/CollapsiblePanel.test.js
tooltip on actions inside custom element are messed up
have the TooltipTrigger around the custom element only when label or tooltipLabel is passed in props
=> fix(Collapsible): tooltip only when label is there for element

packages/components/src/ActionBar/ActionBar.component.js, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.component.js, packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.scss, packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.test.js, packages/components/src/VirtualizedList/HeaderCheckbox/__snapshots__/HeaderCheckbox.test.js.snap
Intermediate state is not implemented in the HeaderCheckbox
add it
=> feat(components/headercheckbox): add intermediate state

packages/components/src/FocusManager/FocusManager.component.js
In react <17, persist() had to be called when using a SyntheticEvent asynchronously
=> fix(FocusManager): Persist syntheticevent

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/TooltipContent/TooltipContent.component.scss
=> fix(Dataviz): Reset tooltip line margin

versions/dependencies.json
Fix vulnerability
Update axios version to 0.21.1
=> chore: update axios version in the dependencies.json

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.component.test.tsx, packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.component.tsx, packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.stories.tsx
When provided data does not contain filtered value, all bars are grey
```
{
key: { min: 2500, max: 2600 },
label: '[2500, 2600[',
value: 400,
filteredValue: undefined
},
```
Don't set 0 (no filtered occurences) but keep undefined (no filter)
=> fix(Dataviz): Bars without filter should be blue when in range

packages/components/src/QualityBar/QualityRatioBar.scss, packages/theme/src/theme/_datagrid.scss
invalid colour shloud no longer be representated by jaffa. chestnut-rose should be used instead
change it in the datagrid and in the qualitybar component
=> fix(theme): chesnut-rose is the new black

packages/components/src/InlineMessage/InlineMessage.scss
The '$' sign before the css variable's name is missing
adding the missing '$' sign
=> chore(components): fix small typo in InlineMessage component css

packages/components/src/ListView/Items/Items.component.js, packages/components/src/ListView/ListView.component.js, packages/components/src/ListView/ListView.stories.js
When a parent changes the `showToggleAll` prop in its `ListView` component, nothing happens because actual effect is the result of prop computation that happens in component's construct, not at render time.
Move computation at render time. Also, expose the component's various display modes and remove an intermediate component that does nothing.
=> fix(components/ListView): showToggleAll prop change

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.tsx, packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.tsx
Tooltip is getting out of the viewport
Keep tooltip inside the view:
=> fix(Dataviz): Fix truncated/misplaced tooltip

packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
Currently, the tooltip label is shown in the CollapsiblePanel header instead of the label.
Keep the tooltip label for the tooltip.
=> fix(TPSVC-16945): fix label in CollapsiblePanel

packages/components/src/IconsProvider/IconsProvider.component.js
The `IconsProvider` component allow to define several icon bundles to fetch.
When an icon try to render, it use the provider to search the right icon in all bundles. To do that, it waits all bundles to have been fetched. If one of the bundle take an anormal amount of time to load, it delays all icons display.
For example, if you go to pipeline designer, processors icons can take 3s to load (depends on the number of engine and processor you can access to). So the page loads without any icons for almost 4s.
Instead of waiting all bundles to be loaded, try to display the icon everytime a new bundle is loaded.
To do that, the `Promise.all` made on bundles is replaced by `Promise.any`.
**Please …
=> chore(components): IconsProvider wait for all bundles

.travis/after_success_lint.sh, output/forms.eslint.txt, output/router.eslint.txt
When the linter give an empty scan, the file is not updated
Remove the folder in the ci process in order to have the file removed if there is no lint to report for a package
=> fix: eslint empty report is not updated

.github/workflows/release-variables.sh
Releases are done automatically via GH Actions on master or any branche like maintenance branches.
During the process, it generates the changelog, by requesting the logs from last release. But this works only on master because it requests the logs from last release **to master**.
On maintenance branches, it results in error
```
fatal: ambiguous argument 'v6.10.0..master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
My guess is that actions pulls only the wanted branch, and master doesn't exist on the run environment.
Change it to request logs from last release to **HEAD**. …
=> chore: gh action release note content

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/RangeFilter/RangeFilter.component.scss, packages/dataviz/src/components/RangeFilter/RangeFilter.component.stories.tsx, packages/dataviz/src/components/RangeFilter/handlers/DateRangeHandler/DateRangeHandler.test.tsx, packages/dataviz/src/components/RangeFilter/handlers/DateTimeRangeHandler/DateTimeRangeHandler.test.tsx, packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberRangeHandler.test.tsx, packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberRangeHandler.tsx, packages/dataviz/src/components/RangeFilter/handlers/slider-ticks.utils.ts
Edge case when min and max label are the same but not the actual values: the min label is missing
Expected 
Also, number size computation was not taking ponctuation and decimals into account 
=> fix(Dataviz): Range ticks edge cases

output/components.eslint.txt, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
It's not possible to use SubHeaderBar title edition without storing the `editMode` in the consumer app.
https://user-images.githubusercontent.com/58977230/106452398-1c6a7200-6488-11eb-84b2-7b5fd4c2eca9.mp4
Pass down the `editMode` flag stored in the component
https://user-images.githubusercontent.com/58977230/106452520-4b80e380-6488-11eb-8d4e-309710d5d39b.mp4
=> fix(SubHeaderBar): EditMode is not passed to EditableText

output/components.eslint.txt, packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/src/FilterBar/FilterBar.component.js, packages/components/src/FilterBar/FilterBar.test.js
QA wants to target reset button easily
Add a data-test and a data-feature prop that will end up in data-test and data-feature attribute in html elements
=> feat(components): add data-test & data-feature props to reset btn

output/theme.sasslint.txt, packages/forms/src/rhf/fields/TextArea/RHFTextArea.component.js, packages/forms/src/rhf/fields/TextArea/RHFTextArea.test.js, packages/forms/src/rhf/fields/TextArea/TextArea.stories.js, packages/forms/src/rhf/fields/TextArea/index.js, packages/forms/src/widgets/fields/TextArea/TextArea.component.js, packages/forms/src/widgets/fields/TextArea/TextArea.test.js, packages/forms/src/widgets/fields/TextArea/index.js, packages/theme/src/theme/_forms.scss
RHF integration miss some basic inputs
adding a rhf registered textarea
=> feat(forms): add textarea RHF component

packages/components/src/Enumeration/Enumeration.stories.js, packages/components/src/Enumeration/Items/Item/Item.component.js, packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap, packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Currently Enumeration Item support custom actions, but with no overlay.
Overlay related props for Action are discarded.
Pass overlay related props to Action component.
=> feat(components/EnumerationItem): action with overlay

lerna.json, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.stories.js, packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.js, packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js
In column chooser, column config `locked` doesn't take effect.
Currently it only support to lock the first N columns. N is specified by `nbLockedLeftItems`.
Use user's config of locked if set.
=> fix(components/ColumnChooser): locked is not working for single column

packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
Ticket: https://jira.talendforge.org/browse/TDC-5216
When we are on dataset preparation semantic type is lowercase instead of case as type in semantic type option
update style of header description type datagrid
=> fix(datagrid): The semantic type case is not retained

packages/components/src/EditableText/EditableText.component.js, packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
change edit pencil label from "edit" to "rename"
=> chore(i18n): change from edit to rename in EditableText

packages/components/src/DateTimePickers/shared/styles/mixins.scss
This bug was raised on TDS side : https://jira.talendforge.org/browse/TDS-5775
The issue is that focusing the global div opens the picker
making the global div fit the content so that click outside of the div doesnt trigger an opening of the piker
=> fix(RangePicker): make the global div fit the content

output/components.eslint.txt, packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js, packages/components/src/DateTimePickers/InputDateRangePicker/DateRangePicker.stories.js, packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js, packages/components/src/DateTimePickers/InputTimePicker/TimePicker.stories.js, packages/components/src/DateTimePickers/hooks/useInputPickerHandlers.js
disable date picker in some mode are not managed
=> chore(DatePickers): disabled mode

packages/forms/src/rhf/index.js
RHFTextArea export is missing in the rhf folder index.js
adding it 
=> fix(RHFTextArea): export missing in rhf index

packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js, packages/components/src/VirtualizedList/CellDatetime/__snapshots__/CellDatetime.test.js.snap
Currently not possible to format to specific timezone using CellDatetime
Implement possibility to format to specific timezone in CellDatetime
=> feat(components/CellDatetime): handling timezone

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json
dataviz is not served from CDN because of peer dep
remove peer deps for non UMD dependencies
=> fix(dataviz): remove locale as peer dep

packages/components/src/Typeahead/Typeahead.component.js
Using `MultiSelectTag` with a long list can hide `Typeahead` overflow
http://talend.surge.sh/forms/?path=/story/uiform-v2-core-fields--core-multiselecttag
Fix its max-height computation
http://3227.talend.surge.sh/forms/?path=/story/uiform-v2-core-fields--core-multiselecttag
=> fix(components/Typeahead): fit in viewport

.github/workflows/dataviz-autopublish.yml, .github/workflows/release.yml
CDN related GitHub action name has changed
Update its name
=> chore(release): trigger GitHub Action after release

output/components.eslint.txt, packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap, packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
On date selection in date picker, there is an error because the reference are not defined.
In fact the references in the component are not clear, there are duplications and only one of the duplications is set. That causes the problem of null object because all of them are used in parts of the code.
Remove the duplications, set only 1 ref for the input et 1 ref for the popper div.
=> fix(DatePicker): ref error

packages/components/src/VirtualizedList/VirtualizedList.scss
Got issues on my local webpack with this unnecessary fix 🙂
what about remove it ?
=> chore: remove scss ie11 fix

packages/components/src/Badge/Badge.scss
Read-only badges should have the default cursor, but as it is, pointer cursor is shown when hovering parent element.
Only apply pointer cursor on non ".readonly" badges
=> fix(components/Badge): Readonly badge cursor

packages/components/.storybook/config.js, packages/containers/.storybook/config.js, packages/forms/.storybook/config.js, packages/stepper/.storybook/config.js
Icon bundle URL is hardcoded (with the version) which it's hard to maintain
Use unpkg to retrieve the last version before thinking of a better way to achieve it
=> chore(Storybook): use latest icons

packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Styled components used in the Design System have a better ponderation (<style> vs <link>)
Increase the weight of the icon on the `SubHeaderBar`
=> fix(components/SubHeaderBar): icon style ponderation

packages/components/src/Typeahead/Typeahead.component.js, packages/components/src/Typeahead/Typeahead.component.renderers.js, packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap, packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
typehead can not display
add min height to display it
=> feat(components/typeahead): add minimum height on typehead

output/components.eslint.txt, packages/components/src/DateTimePickers/DateRange/Input/Input.component.js, packages/components/src/DateTimePickers/DateRange/Input/__snapshots__/Input.component.test.js.snap, packages/components/src/DateTimePickers/InputDateRangePicker/DateRangePicker.stories.js, packages/components/src/DateTimePickers/InputDateRangePicker/InputDateRangePicker.component.js, packages/components/src/DateTimePickers/InputDateRangePicker/InputDateRangePicker.scss, packages/components/src/DateTimePickers/InputDateRangePicker/README.md, packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.test.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.scss, packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap, packages/components/src/DateTimePickers/shared/styles/mixins.scss
TMC needs a rang picker displayed in `inline` mode.
We have defined an `inline` type Date Range Picker in guidelines but not implemented yet: 
https://company-57688.frontify.com/document/92132#/ui-controls/date-time-picker-1561102408
This PR is to implement inline display mode.
Add `props.display="inline"` for display Date Range Picker inline.
=> feat(Components/DateRangePicker): add inline display mode

packages/cmf-cqrs/package.json, packages/generator/package.json, yarn.lock
polyfills should be decided at project level.
The current owner of polyfills is ui-scripts.
> warning @talend/react-cmf-cqrs > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Lets remove babel-polyfill which create unwanted warnings at install
=> chore: remove unused polyfills

packages/dataviz/CHANGELOG.md, packages/dataviz/package.json
404 happens on project using dataviz in dev mode.
Add dataviz umd for dev
=> fix(dataviz): add dev umd

packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js, packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.test.js
For DateTimeRange Picker, the style of range start is broken when select any time other than 00:00.
Use `startOfDay(startDate)` when checking if a date is in range.
=> fix(components/DatePicker): Fix style for start of range

packages/components/src/Emphasis/Emphasis.component.js, packages/components/src/Emphasis/Emphasis.test.js
https://jira.talendforge.org/browse/TMC-24631
If value is not a string, and not in title map, Datalist throws an error when opening it
Convert value to string before escaping
=> fix(Emphasis/TMC-24631): error in datalist when value is not a string

output/components.sasslint.txt, packages/components/src/QualityBar/QualityBar.component.js, packages/components/src/QualityBar/QualityBar.component.test.js, packages/components/src/QualityBar/QualityBar.stories.js, packages/components/src/QualityBar/QualityRatioBar.component.js, packages/components/src/QualityBar/QualityRatioBar.scss
adding another metric in the quality bar which is not applicable see : https://jira.talendforge.org/browse/TDS-5711
adding it 
=> feat(components/QualityBar): not applicable

packages/containers/src/actionAPI.js
we have on some event handler the following error:
context.store.dispatch is not a function
This is due to the call to the old actionAPI script in a mapstatetoprops.
Yes we don t have store.dispatch in mapstatetoprops.
There is no risk here because the code were not working before so we just get ride of that uncaught JS error.
Check if we have context.store.dispatch before adding onclick
=> fix(container): context.store.dispatch not a function

.github/workflows/surge-cleanup.yml
Demo on surge is never removed, unless we do it manually
Remove the demo on surge when PR is closed or merged
=> chore: remove demo when PR is closed

output/components.eslint.txt, packages/components/src/Typeahead/Typeahead.component.js
When popper make positioning of the items at the top of input, if using search, the item length changes but the position of the items is unchanged which leads to : 
making adding items as dependency of memoized function withInViewport
items is not used in the function but i guess its needed as a dep anyway ...
=> fix(Typeahead): update position when items list changes

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss, packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss, packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
A piece of shadow appears when hover on selected row.
https://jira.talendforge.org/browse/TMC-18091
This is because safari doesn't support some format in linear-gradient. 
- use rgba color instead of string
- use `90deg` instead of `to right`
=> fix(components/List/CellActions): fix safari compatibility issue for linear-gradient

output/components.eslint.txt, packages/components/src/ResourceList/ResourceList.component.js
i18n domain is not provided to the resourcelist component
provide it
=> fix(components/resourceslist): i18n domain is not provided

output/components.eslint.txt, packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js, packages/components/src/Actions/ActionDropdown/ActionDropdown.scss, packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js, packages/components/src/Actions/ActionDropdown/Dropdown.stories.js, packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap, packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js, packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss, packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
the ellipsis display mode is inside list but we need it elsewhere
add a ellipsis prop to the action dropdown
=> feat(component/actiondropdown): add ellipsis mode

packages/components/src/translate.js, packages/containers/src/translate.js, packages/datagrid/src/translate.js, packages/forms/src/translate.js, packages/stepper/src/translate.js
createInstance is not export like that anymore in i18next last versions.
This causes issue like :   `Uncaught TypeError: (0 , _i18next.createInstance) is not a function` 
Fix the import in all packages
=> fix(i18n): Fix createInstance import

output/components.eslint.txt, packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.js
Responsive vertical layout not work anymore
fix the condition for showing vertical layout
=> fix(components/DateTimeRange): display in vertical layout when there's not enough space

packages/http/src/http.common.js, packages/http/src/http.common.test.js
Payload is not resquested when a call fails
=> feat(http): Get response payload on error

packages/icons/webpack.umd.js
Icons is often the first dependency to be loaded.
But it's manifest add react in dev mode.
https://unpkg.com/browse/@talend/icons@6.26.0/dist/TalendIcons.min.js.dependencies.json
Switch to manifest prod in webpack.
=> fix(icons): build prod mode

output/components.eslint.txt, packages/components/src/TreeView/FolderTreeView.stories.js, packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js, packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss, packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
The common component should be updated:
- to update the style of the active state, hover state
- and introduce the disabled state style
More details: https://jira.talendforge.org/browse/TDOPS-14
Link to frontify: https://company-57688.frontify.com/document/92132#/ui-controls/tree-view
Fixed css
=> feat(TDOPS-14/FolderTreeView): added disabled list item state

packages/components/package.json, packages/components/src/DateTimePickers/Date/date-extraction.js, packages/components/src/DateTimePickers/Date/date-extraction.test.js, packages/components/src/DateTimePickers/DateTime/datetime-extraction.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js, packages/components/src/utils/date.js, packages/components/src/utils/date.test.js, packages/http/src/http.common.js, packages/http/src/http.common.test.js, yarn.lock
`timezone-support` is a dependency of UI/components while only a single method is used in Talend/UI (to check if a timezone exists).
`date-fns-timezone` uses `timezone-support`.
`timezone-support` is the heaviest dependency of UI/components.
`timezone-support` and `date-fns-timezone` haven't been maintained for years.
Leverage `timezone-support` and `date-fns-timezone` duties to [`Intl.DateTimeFormat`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat), add tests, drop `timezone-support`.
=> chore(DateTime/components): Remove timezone-support/date-fns-timezone

output/components.eslint.txt, packages/components/src/DateTimePickers/Date/date-extraction.js, packages/components/src/DateTimePickers/DateTime/datetime-extraction.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/date-extraction.js, packages/components/src/utils/date.js, packages/components/src/utils/date.test.js
/home/travis/build/Talend/ui/packages/components/src/DateTimePickers/Date/date-extraction.js
7:1  error  Dependency cycle detected  import/no-cycle
move convertToUTC in global date util
=> chore(Date): remove cycle deps

packages/components/src/HeaderBar/HeaderBar.component.js
Current Header does not allow to use a custom component for notifications.
Like Intercom, add a new props to allow to use a custom component.
=> feat(components/HeaderBar): Accept custom AppNotification component

versions/dependencies.json
Add min version of react-router-dom to 5.2
Add min version of react-router-dom to 5.2
=> chore: add react-router-dom in dependencies.json

packages/utils/package.json
@talend/utils is not public.
Explicitely make it public.
=> fix(utils): Make @talend/utils public

packages/components/src/FormatValue/FormatValue.component.js, packages/components/src/FormatValue/FormatValue.scss, packages/components/src/FormatValue/FormatValue.stories.js, packages/components/src/FormatValue/__snapshots__/FormatValue.test.js.snap
- Multiple whitespaces are preserved only at the start/end of the string and collapsed otherwise: 
<pre> Show special    chars and newline</pre>
- Preserve whitespace inside the text 
=> fix(FormatValue): Preserve whitespaces

packages/dataviz/.storybook/preview.js, packages/dataviz/CHANGELOG.md, packages/dataviz/package.json, packages/dataviz/src/components/TooltipContent/TooltipContent.component.tsx, packages/dataviz/src/components/TooltipContent/TooltipContent.stories.tsx, packages/dataviz/src/components/TooltipContent/__snapshots__/TooltipContent.component.test.tsx.snap
- Tooltip doesn't show special/blank chars:
<pre>  5   0  </pre>
- Use `FormatValue` component (already used in bars)
=> fix(Dataviz): Show special chars in tooltip

packages/utils/package.json, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
`getUTCOffset` is not exposed, but it can be helpful.
Expose it. Add tests.
=> feat(utils/date): Expose getUTCOffset

packages/utils/package.json, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
There's no common way to transform for humans timezone offsets (+00:00, -06:00 ...).
Expose helper.
=> feat(utils/date): Provide UTC offset format function

packages/utils/package.json, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
- When using `convertToTimeZone`, input date is always considered as locale.
- Using date-fns's format `[]` to add static strings in formats doesn't work well with timezones.
- Support sourceTimeZone in convertToTimeZone so that caller can specify which timezone the input date is from
- Update regex that matches timezone tokens in date format string to ignore such tokens when they are preceed with `[` (using negative lookbehind)
=> feat(date/utils): Conversion source timezone + token parsing

packages/containers/examples/ExampleList.js, packages/containers/src/List/selector.js
sorting on number is messed up because of one condition (0 = false)
checking that the value is not undefined
=> fix(TDS-6053) : Sorting on number not working

packages/components/src/RatioBar/RatioBar.component.js, packages/components/src/RatioBar/RatioBar.component.test.js, packages/components/src/RatioBar/RatioBar.scss, packages/components/src/RatioBar/RatioBar.stories.js, packages/components/src/RatioBar/RatioBarLines.component.js
We need to display the erros count in a ratio bar
Add a new `errors` prop
=> feat(components/ratiobar): add errors count

packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.component.test.js, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.js, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.test.js, packages/forms/src/UIForm/fields/TimezoneList/__snapshots__/TimezoneList.component.test.js.snap
Timezone dropdown options are supposed to display "UTC" as a prefix before showing the UTC offset of the timezone.
Add it
=> feat(forms/TimezoneList): Add 'UTC' prefix to timezone dropdown options

packages/components/src/FilterBar/FilterBar.test.js, packages/components/src/List/ListComposition.stories.js, packages/components/src/List/ListComposition/collection.js, packages/components/src/VirtualizedList/CellQualityBar/CellQualityBar.component.js, packages/components/src/VirtualizedList/CellQualityBar/CellQualityBar.test.js, packages/components/src/VirtualizedList/CellQualityBar/QualityBarColumn.component.js, packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap, packages/components/src/VirtualizedList/CellQualityBar/index.js, packages/components/src/VirtualizedList/VirtualizedList.stories.js, packages/components/src/VirtualizedList/index.js
Add a Cell quality bar renderer to be reused.
Direct demo link: http://3351.talend.surge.sh/components/?path=/story/data-list-list-composition--default
=> feat(VirtualizedList): add CellQualityBar renderer

.github/workflows/dependencies.yml, .github/workflows/lerna-ci.yml, .github/workflows/yarn-deduplicate.yml, packages/cmf/package.json, yarn.lock
yarn.lock is never upgraded.
when someone add a dependency it create duplicate
add two jobs:
* one to upgrade once a week
* one to remove duplicate if someone touch a package.json
do a yarn upgrade to update dependencies to modify the yarn.lock and test the CI
=> chore(CI): add dedupe and upgrade GH actions

packages/components/src/AboutDialog/AboutDialog.scss
=> fix(components): style in about dialog

packages/components/src/List/ListComposition.stories.js, packages/components/src/List/ListComposition/collection.js, packages/components/src/VirtualizedList/CellLabel/CellLabel.component.js, packages/components/src/VirtualizedList/CellLabel/CellLabel.test.js, packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap, packages/components/src/VirtualizedList/VirtualizedList.stories.js
CellLabel's bstyle is by default info and it can't be changed
adding support for an object for cellData in order to pass bstyle
=> chore(List/CellLabel): specify bstyle for cellLabel

packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
The dates are not well translated.
Could be great to have a common way of translating the dates.
Provide a common way to translate the dates using Intl
=> feat(Dates): translate date formats using Intl

packages/utils/package.json, packages/utils/src/date/index.ts
I forgot to export the list of date formats :man_facepalming:
=> feat(dates): export FORMAT

packages/components/src/Actions/ActionButton/Button.stories.js, packages/theme/src/theme/_buttons.scss, packages/theme/src/theme/_visual-helpers.scss
When a button is `btn btn-info btn-inverse`, the background is wrong while hovering it
Be more precise to override bootstrap-sass properties
http://3365.talend.surge.sh/components/?path=/story/buttons-button--combinations
=> fix(theme): hover disabled buttons

packages/components/src/TreeView/FolderTreeView.stories.js, packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js, packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
In TMC we use FolderTreeView for a failed plan rerun dialog and we have some specific state of plan steps, we need a way to highlight deleted and added tasks and change cursors for them. It's too specific to add cursors and background customization directly in the TreeViewItem, so it's better to do it on the TMC app.
Added ability to pass className to a TreeViewItem
=> feat(TDOPS-14/TreeView): added ability to pass className for a TreeViewItem

packages/utils/package.json, packages/utils/src/date/index.ts
Function `formatTimeZoneTokens` uses regex with lookbehind identifier, which Safari currently doesn't support.
Use lookahead instead.
=> fix(utils/dates): fix formatTimeZoneTokens function for Safari

packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/src/Actions/ActionButton/ActionButton.test.js
ActionButton - Tooltip label is not displayed if the tooltip property is not set
Caused by:
https://github.com/Talend/ui/pull/3345/files#diff-5d480c14248b485032c877f7aba5d51b71b554e753287e1155af4cd96e149e07R211
show tooltip when the tooltipLabel is set even if the tooltip property is not set
https://jira.talendforge.org/browse/TDOPS-756
=> fix(TDOPS-756/ActionButton) - show tooltip when the tooltipLabel is set

yarn.lock
http://talend.surge.sh/components/?path=/story/* isn't working is Safari due to an incompatible regex in Safari.
Update @talend deps especially @talend/utils to get the Safari regular expression fix.
=> chore(deps): bump @talend deps

packages/theme/src/theme/_colors.scss
`$pale-cyan` is absent from tui
add it and its shades
=> feat(theme): add $pale-cyan and its shades

packages/components/src/Enumeration/Enumeration.component.js, packages/components/src/Enumeration/Enumeration.snapshot.test.js, packages/components/src/Enumeration/Enumeration.stories.js, packages/components/src/Enumeration/Items/Item/Item.component.js, packages/components/src/Enumeration/Items/Item/Item.scss, packages/components/src/Enumeration/Items/Items.component.js, packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
For the `Enumeration` component, currently we can set actions of item with `props.acitonsDefault`, but default actions are hidden, only appear on hover.
add new actions group `props.actionsDefaultPersistent`, actions of this group will be always visible.
=> feat(components/Enumeration): Add persistent actions group

packages/components/src/Notification/Notification.component.js
Code using `Notification` component can use several notification types that are handled internally.
Use constants instead of _magic strings_ for this and expose them.
=> feat(components/Notifications): Expose notifications types

packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js, packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
We need a way to pass down props to `<h1 />` and `<small />` elements rendered (by default) by `SubHeaderBar`.
Spread new props (`titleProps` and `subTitle`) where they belong.
Reorganized tests (merged `describe()`)
=> feat(components/SubHeaderBar): Support custom props for title and subtitle

packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.test.js, packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap
There's no way to pass a prop to the label in the field template
Support `labelProps` in `Label` props — that can be passed via the schema, via field compnoent — that is spread into `Label`
Factorize tests default props
=> feat(forms/FieldTemplate): Support extra custom props for label

.github/workflows/security-scan.yml
No way to trigger a security scan manually
Add the `workflow_dispatch` event
=> chore(actions): enable manual security scan

packages/containers/src/ComponentForm/ComponentForm.component.js
It's not possible to use onChange/onSubmit props with the containers component, which is needed for some use case where we don't want to rely on sagas
add support for props.onSubmit and props.onChange in the container
=> feat(containers/ComponentForm): Call onChange/onSubmit props

packages/containers/src/ComponentForm/ComponentForm.component.js, packages/forms/src/FormSkeleton.js, packages/forms/src/FormSkeleton.test.js, packages/forms/src/FormSwitcher.js, packages/forms/stories-core/layouts.js
We have use-cases where buttons are not displayed inside the form (like Stepper forms).
=> feat(FormSkeleton): Support skeleton without buttons

packages/forms/src/UIForm/UIForm.component.js, packages/forms/src/UIForm/UIForm.component.test.js, packages/forms/src/UIForm/__snapshots__/UIForm.container.test.js.snap
It's not possible to use an UIform as part of another form as nesting form is not allowed in HTML
Support custom html tag when rendering the form
=> feat(UIForm): Support custom root tag

.github/workflows/security-scan.yml
Security scan are done on dev deps too
Set production mode to check code that will hit production only.
=> chore: set security scan prod mode

packages/components/src/VirtualizedList/CellMappedData/CellMappedData.component.js, packages/components/src/VirtualizedList/CellMappedData/CellMappedData.component.test.js, packages/components/src/VirtualizedList/CellMappedData/MappedDataColumn.component.js, packages/components/src/VirtualizedList/CellMappedData/__snapshots__/CellMappedData.component.test.js.snap, packages/components/src/VirtualizedList/CellMappedData/index.js, packages/components/src/VirtualizedList/VirtualizedList.stories.js, packages/components/src/VirtualizedList/index.js, packages/components/src/VirtualizedList/utils/dictionary.js
When, in a VirtualizedList, we need to transform a field in the objects of a collection to a human-readable name, we currently have only 2 options:
- Iterate over the collection to transform the value in evey object to the HR name (inefficient)
- Define a custom cell renderer (which can be a bit cumbersome)
Create a new cell renderer `MappedCellData` (couldn't come up with something nicer, open to suggestions) that accepts a map of values in `columnData` so that value conversion is done at render time.
The cell also accepts arrays as values; in that case values are sorted.
=> feat(components/VirtualizedList): MappedCellData

packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap, packages/components/src/Status/Status.component.js, packages/components/src/Status/Status.stories.js, packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
Jira -> https://jira.talendforge.org/browse/TCCUI-221
This part is the sequel of that item https://jira.talendforge.org/browse/TDOPS-113
We need to have tooltips for all list parts. Status is the last missing part
https://talend365.sharepoint.com/:p:/g/departments/rd/EdHLTiIIiDhAvaKgIjrVE7ABrY_eX1U17uCSSE5PEEPHxQ?e=SfvRM6&nav=eyJzSWQiOjI5OCwiY0lkIjoyODE2NTM4MDgyfQ
Add custom tooltip for status column
=> feat(TCCUI-221): Add tooltip for Status component

.changeset/blue-rings-fetch.md, .changeset/fair-dodos-remain.md, .changeset/flat-planes-help.md, .changeset/new-mangos-smell.md, .changeset/real-mayflies-fetch.md
We have just merged changeset to switch to lerna independant mode for release.
The current PR release do not reflect last change since 6.36.
use changeset for each commits which are not a chore.
git log:
```
* 153bf07ca  2021-08-23 chore: init changelog using changeset                                 
* fe4af8c5d  2021-08-20 chore(ARCH-364): use changeset to release (#3328)                     
* d7e8249a9  2021-08-20 feat(components/VirtualizedList): MappedCellData (#3393)              
* 15ab4a140  2021-08-20 chore(theme): add yarn.lock for secu scan (#3397)                     
* 4bd87cc91  2021-08-20 chore: remove deprecated talend generator (#3396)                     
* e0d71858e …
```
=> chore: init changelog using changeset

.github/workflows/security-scan.yml
Making it able to trigger the GH action manually cancelled the cron somehow.
Let's restore the cron by removing the manual trigger.
=> chore: restore security scan cron

.github/workflows/pr-demo.yml, workspace-run.js
we suffer from buffer exceed error on test:demo script (because of the deprecation warning from sass).
So we do not have anymore surge demos.
switch to spawn which do not buffer reponse.
bonus: fix github action workflow which build dataviz and cmf-router twice.
=> chore: fix test:demo script

.github/workflows/changeset.yml, .github/workflows/lerna-ci.yml, .github/workflows/pr-demo.yml, package.json, packages/cmf-cqrs/package.json, packages/cmf-router/package.json, packages/cmf-webpack-plugin/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/dataviz/package.json, packages/eslint-config/package.json, packages/forms/package.json, packages/http/package.json, packages/icons/package.json, packages/jsfc/package.json, packages/local-libs-webpack-plugin/package.json, packages/router-bridge/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, packages/theme/package.json, packages/utils/package.json, workspace-run.js
changeset ci fails because of prepublishOnly npm script.
`npm publish --json` is execute which execute prepublishOnly script with --json option.
Webpack output change and become a json payload, but changeset want the json payload from npm publish so it fails.
move prepublishOnly into a new pre-release script which is not known by npm.
trigger it from the CI
=> chore: remove prepublishOnly script

.changeset/slimy-pears-cross.md, packages/theme/src/theme/_modals.scss
Modals heights are limited to 80% of the viewport's height. This is problematic when modal content overflows, the content container gets a scrollbar.
Remove limitation.
=> feat(theme/modals): Remove modal max height

.changeset/healthy-cats-cover.md, packages/components/src/DataViewer/DataViewer.stories.js, packages/components/src/DataViewer/ModelViewer/Leaf/ModelViewerLeaf.component.js, packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap, packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js, packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss, packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap
To be homogeneous with other renders, we got to show the asterisk for the not null field aside the type and not the semantic type.
(i like to) Move it move it 🎶 
=> feat(components): update semantic awareness display

packages/forms/.storybook/config.js
Since Storybook upgrade,  the way we  filter per story names has changed
To apply a decorator except to certain stories, fix the filter fn
=> chore(forms): Storybook layout related stories

.changeset/quick-colts-join.md, packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js, packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js
When using a NestedListView component in a form, if we change the values passed as a prop outside of a user interaction, the component won't take it into account.
Add to the component _componentDidUpdate_ lifecycle a condition to check if the props have been changed and does not match the internal values
=> fix(forms/NestedListView): Component should now detect props change

.changeset/great-panthers-wink.md, packages/theme/src/theme/_forms.switch-nested.scss
On firefox , the chevron used in Forms/NestedListView is disappearing when using css rotation on it
=> fix(theme): Fix chevron rotation on firefox

packages/cmf-cqrs/.npmignore, packages/cmf-router/.npmignore, packages/cmf-webpack-plugin/.npmignore, packages/cmf/.npmignore, packages/components/.npmignore, packages/containers/.npmignore, packages/datagrid/.npmignore, packages/dataviz/.npmignore, packages/forms/.npmignore, packages/router-bridge/.npmignore, packages/sagas/.npmignore, packages/stepper/.npmignore, packages/storybook-cmf/.npmignore, packages/theme/.npmignore
Our release contains too much useless files
https://unpkg.com/browse/@talend/react-components@6.37.0/
Remove the following in every packages:
```
.babelrc.json
eslint-report.json
i18next-scanner.config.js
stylelint-report.json
talend-scripts.json
```
I do not need a release here.
=> chore: add some entries in npmignore

.changeset/good-years-rush.md, packages/http/package.json, packages/http/src/config.js, packages/http/src/csrfHandling.js, packages/http/src/http.common.js, packages/http/src/http.constants.js, yarn.lock
Lodash can't be used in service worker due to current ui-scripts config: lodash is expected as an external but it's not there
Config should be fixed but we can also remove lodash as it's not really needed
=> chore(http): Drop lodash dependency

.changeset/khaki-pets-know.md, packages/theme/webpack.config.js
Theme doesn't resolve font url during build because file-loader consider any require() as esmodule. So the result is an object with default as expected value.
In the compiled css, we end up with `url([object Module])`
Set the theme file-loader option `esModule` to false
=> fix(theme): resolve font url

.changeset/sharp-spoons-rule.md, .surge/index.html, packages/cmf-cqrs/package.json, packages/cmf-router/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/datagrid/package.json, packages/forms/package.json, packages/http/package.json, packages/router-bridge/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/theme/package.json
All packages fail to build with release scripts due to a unknown webpack option.
Remove the option.
=> fix(pre-release): remove display=none option

.changeset/quiet-crews-sit.md, workspace-run.js
UMD Builds depends on inner deps `*.dependencies.json` for `@talend` deps.
But those `*.dependencies.json` are generated during the build. It means the inner deps mus be built before.
The run-workspace script doesn't control the build order.
Sort the packages by dependencies to ensure that the `*.dependencies.json` files are generated before they are needed.
=> chore(build): order packages on pre-release hook

.changeset/clever-poems-tan.md, workspace-run.js
`workspace-run.js` oder the commands depending on the packages workspace dependencies.
But the run takes them from the last to first.
Fix the order, run the first command first.
=> fix(workspace-run): package run order

packages/forms/package.json, packages/router-bridge/package.json
Forms: react-ace is an optional peer dep.
Router-bridge: react-router and connected-react-router are optional peer deps.
Optional peer deps should be declared as optional, so npm doesn't output a warning if they are not installed.
Moreover, talend/scripts now support `peerDependenciesMeta` optional values for cdn libs management.
Set the `peerDependenciesMeta` optional value.
=> fix(form/router-bridge): declare peer deps meta for optional deps

yarn.lock
Lots of those warnings
```
WARNING in Conflict: Multiple assets emit different content to the same filename xxx.dependencies.json
```
Upgrade `@talend/dynamic-cdn-webpack-plugin` that fixed the issue
=> chore: remove build warning

.changeset/rich-cows-jog.md, fork/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss, fork/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss, fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid-framework.scss, fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid.scss, fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-divider.scss, fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss, packages/theme/src/theme/_variables.scss
In previous PR to remove math.div, there were missing instances.
Replace the math.div with calc
=> fix(boostrap-sass): use calc instead of math.div

.changeset/gold-ghosts-laugh.md, packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss, packages/components/src/Drawer/Drawer.scss, packages/components/src/ObjectViewer/JSONLike/JSONLike.scss, packages/components/src/Slider/Slider.scss
With the switch from division to calc, there are some sass variables not interpreted.
It results in css output like `calc($btn-size / 2)` which is invalid css.
Interpret the var to output the value in resulting css
=> fix(IconToggle/Drawer/Slider/ObjectViewer): calc with sass vars

.gitignore, package.json, packages/components/package.json, packages/components/talend-i18n.json, packages/containers/package.json, packages/containers/talend-i18n.json, packages/datagrid/package.json, packages/datagrid/talend-i18n.json, packages/forms/package.json, packages/forms/talend-i18n.json
TUI i18n handles 4 packages that are now independants.
**What is the chosen solution to this problem?*
Split the TUI workflow into 4 parts.
=> chore: adapt i18n workflow to independant packages

.changeset/spicy-weeks-flash.md, packages/components/src/Badge/Badge.component.js, packages/components/src/ListView/Items/Item/Item.component.js, packages/components/src/ListView/Items/Item/Item.propTypes.js, packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap, packages/components/src/ListView/Items/Item/item.snapshot.test.js, packages/components/src/ListView/Items/Items.component.js, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap, packages/components/src/ListView/Items/items.test.js, packages/components/src/ListView/ListView.component.js, packages/components/src/ListView/ListView.stories.js, packages/components/src/MultiSelect/MultiSelect.stories.js, packages/forms/src/UIForm/fields/ListView/ListView.component.js, packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js, packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js, packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap, packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js, packages/forms/src/UIForm/fields/NestedListView/__snapshots__/NestedListView.test.js.snap, packages/forms/stories-core/json/fields/core-multiSelectTag.json, packages/forms/stories-core/json/fields/core-nestedListView.json
Add custom xpath props support for listView, MultiselectTag, Bage components
https://jira.talendforge.org/browse/TDOPS-659
Add a new property -  dataTest
=> feat(components): add custom xpath props support

.changeset/angry-bobcats-promise.md, packages/containers/src/SidePanel/SidePanel.connect.js, packages/router-bridge/src/router/index.js
This is part of the changes to allow apps to be served on a common domain with a different basename (`http://my-domain/appName`).
- Router bridge
Some apps use router bridge to be compatible with react-router v3 and v5. In v5 mode, history is created at file import/execution. But we need to pass the route basename at history creation.
- Side panel
The container check which route is the current one. But it is only based on the router conf, and not the basename.
- Router bridge
Use window.basename that the apps will init.
- Side panel
Container takes window.basename to build the url to compare
=> feat(router-bridge/SidePanel): support route basename

.changeset/witty-beds-rhyme.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
fix a bug where initialbadges update affect the current filter
remove dependencies from a useeffect
=> fix(faceted-search): initialbadges updates should not affect current filter

.changeset/young-spoons-attack.md
https://github.com/Talend/ui/pull/3509 changest was missing
=> chore(icons): Add changeset for restart icon

.changeset/khaki-clocks-cry.md, packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js, packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
in french, there sould be a space before colon, but we can't do that because it's hard-coded now instead translation.
add translation for colon
=> fix(components/ObjectViewer): i18n - add translation for colon

.changeset/hot-terms-buy.md, packages/dataviz/src/components/GeoChart/GeoChart.component.tsx
`??` operator is breaking AngularJS tests when updating to latest version of the dataviz lib
Replace `??` by `||` while we don't officially support it by a babel config.
=> fix(GeoChart): remove the use of ?? which break karma

.changeset/perfect-pens-boil.md, packages/design-system/src/components/Form/Field/Input/Input.Checkbox.tsx, packages/design-system/src/components/Form/Field/Input/Input.Switch.tsx, packages/design-system/src/components/Form/Field/Input/hooks/useCheckboxState.tsx, packages/design-system/src/components/Form/docs/Input.checkbox.stories.mdx, packages/design-system/src/components/Form/docs/Input.switch.stories.mdx
Changes to `checked` prop are not taken into account
This feels like a dirty fix and I guess we'll have the same issue in other components using the `useCheckboxState`... 
We could put the `useEffect` in `useCheckboxState` but it would break the "`useXXState` first param is a default state" convention
=> feat(design-system/Checkbox): Support controlled checked state

.changeset/light-walls-smash.md, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
Formatted date in CellDatetime is not translated.
Pass locale object to datefns format function
=> fix(components/List): add translation for CellDatetime

.changeset/early-cooks-collect.md, packages/design-system/src/components/InlineEditing/InlineEditing.spec.tsx, packages/design-system/src/components/InlineEditing/InlineEditing.tsx
enter key should not submit in multiline mode
a fix
=> fix(InlineEditing): enter key should not submit in multiline mode

.changeset/healthy-carrots-stare.md, yarn.lock
There is a issue in version 9.7.3 of `@talend/module-to-cdn`: the recharts path for prod version is wrong.
The releases of react-components and react-dataviz have the wrong path in their prod dependencies.json.
Upgrade `@talend/module-to-cdn` and release fix versions
=> fix(TDOPS-1376/components/dataviz): recharts path in dependencies.json

packages/design-system/adr/css-modules.md
DS uses Styled components right now, which imposes a ThemeProvider and it's not aligned with the rest of Talend/ui
Since we've drop IE11 support, we can now use  CSS custom properties for theming purpose and CSS modules 🚀 
=> chore(design-system/ADR): CSS modules

.github/workflows/components-testing.yml
After migration, Cypress components testing on PR was not run anymore
Re-enable it
=> chore(design-system): components testing gh action

.github/workflows/components-testing.yml, packages/design-system/src/components/InlineEditing/InlineEditing.stories.mdx
Cypress CT does not run on DS
Limit the GH Action to the DS package
=> chore(CI): fix cypress error

.github/workflows/design-system-deploy.yml, packages/design-system/README.md
We can't rely on Surge to deploy design.talend.com for some HA and SSL reasons.
We have to keep using Netlify for that.
Each commit on master where the design system has changed must deploy a new version of the documentation on Netlify.
=> chore(design-system): deploy gh action

packages/dataviz/.storybook/preview.js, packages/dataviz/src/components/GeoChart/GeoChart.stories.tsx
The SB API used for dynamically create story not longer exists
=> chore(dataviz): Fix Geochart stories

.github/workflows/design-system-component-testing.yml, .github/workflows/desing-system-visual-testing.yml, packages/design-system/README.md
DS GitHub Actions must respect a naming convention to not be generalized
Adapt existing workflows and add badges on README to get a clear status
=> chore(design-system): gh actions naming convention

.github/workflows/lerna-ci.yml
Without a minimum threshold, UMD size checks give "false positives" since you can have some changing bytes
According to https://github.com/preactjs/compressed-size-action#increasing-the-required-threshold
Let's  imagine that we want to be aware only if the diff is equal or greater than `100b`
=> chore(CI): minimum threshold for UMD size check

.changeset/short-cheetahs-drive.md, packages/design-tokens/.npmignore
Storybook config and stories are embedded into the NPM package
Exclude them all
=> chore(design-tokens): exclude Storybook stuff from NPM package

.changeset/tidy-guests-do.md, packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/__snapshots__/RowCheckbox.component.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/__snapshots__/SelectAllColumnsCheckbox.component.test.js.snap, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap, packages/components/src/Toggle/Toggle.component.js, packages/components/src/Toggle/__snapshots__/Toggle.snapshot.test.js.snap
`switch checkbox` classes are provided to the Toggle component as default value, but as soon as a `className` prop is provided, those disappear which breaks the component, rendering it as a checkbox.
Add them as base value for classes rather than default values
=> fix(components/Toggle): Default class

.changeset/wet-elephants-fetch.md, packages/design-system/src/components/Link/Link.spec.tsx, packages/design-system/src/components/Link/Link.stories.tsx, packages/design-system/src/components/Link/Link.test.js, packages/design-system/src/components/Link/Link.tsx, packages/design-system/src/components/Link/docs/Link.stories.mdx
The title "open in a new tab" should be related to the target attribute and not the detection of external link
=> fix(design-system/Link): fix title related to target attribute

.changeset/green-swans-lick.md, packages/design-system/src/components/Button/variations/Button.base.tsx
busy buttons have a `progress` cursor
busy buttons should have default cursor
=> fix(design-system/buttons): default cursor for busy buttons

.changeset/mighty-colts-clap.md, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
In `CellDatetime`, date strings are not translated.
Enrich `formatToTimeZone` function of utils package, so it can format date in specified locale.
Pass locale in options when calling date-fns' format
=> feat(utils/date): format date in specified locale

.changeset/nasty-turkeys-flow.md, packages/datagrid/src/components/DataGrid/DataGrid.component.js, packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js, packages/datagrid/src/components/DataGrid/DataGrid.test.js, packages/datagrid/src/components/datagrid.component.stories.js
Datagrid focused column can't be set from outside the grid.
Add a `focusedColumnId` prop
=> feat(DataGrid): Set focused column from props

.changeset/empty-seals-work.md, packages/components/src/Inject/Inject.component.js, packages/components/src/Inject/Inject.test.js
Some components are cmf connected only to get renderers from the registry
Example: 
```
import DataGrid from '@talend/react-datagrid/containers';
<DataGrid     
headerRenderer="DataGridHeaderRenderer" // name of the component in the registry
/>
```
Would be nice to be able to use the component like this
```
import DataGrid from '@talend/react-datagrid/components'; 
<DataGrid     
headerRenderer={DataGridHeaderRenderer} // actual component
/>
```
Update`Inject` to return the prop if it's a composant and look for the componentId in the registry otherwise
=> feat(Inject): Support components as props when not cmfConnected

packages/components/src/Layout/Layout.scss
We have a complex z-index problem in Data Preparation: In some screens, we can't see dropdowns in header (App switcher, User profil).
Here is a screenshot of the problem:
This page have some specificity:
- A Layout with a stepper and a Drawer that contain a form with a Typeahead
- This Typeahead have a button that open another Drawer
To hide the typeahead opened popin, we need to have at least a `z-index` set to `1035`.
But with that, we hide the dropdown that have a `z-index` set to `110` (more additional infos at bottom)
With that in mind, we have a dilemma with our layout `z-index`:
- Be higher than `1035` to hide connection typehead
- Be smaller than `110` to show menu dropdown
The …
=> feat(TDP-10570): Increaser Layout header z-index

.github/workflows/design-system-deploy.yml
Design tokens related Storybook must be included into design.talend.com
Deploy  Design tokens' Storybook on Netlify, in addition of the Design System documentation.
=> chore(design-tokens): deploy on Netlify

.changeset/blue-phones-hide.md, packages/components/src/Typeahead/Typeahead.scss, size.json
Search icon is not aligned, it's because there is a margin bottom. I don't see usage of this margin (it's coming from bootstrap)
=> fix(component): typehead icon is not aligned

.changeset/light-insects-boil.md, packages/design-system/package.json, packages/design-system/src/components/Stack/StackHorizontal.stories.tsx, packages/design-system/src/components/Stack/StackVertical.stories.tsx
DS uses Design Tokens with the monorepo's workspace, so it depends on the build you've done before
DS will now rely on the real tokens
=> fix(design-system): build with design tokens

packages/components/.storybook/preview-head.html, packages/containers/.storybook/preview-head.html, packages/forms/.storybook/preview-head.html, packages/stepper/.storybook/preview-head.html, size.json
`window` should use loose augmentation pattern with `process` to be able to run with UMDs
Add it to every preview head HTML files of Storybook
=> chore(Storybook): resolve process with hoistNonReactStatics

packages/flow-designer/CHANGELOG.md, packages/flow-designer/package.json
rename react-flow-designer by @talend/react-flow-designer to manage it like others
=> chore(package):rename react-flow-designer to @talend/react-flow-designer

package.json
Using `yarn` on Windows fails at post install.
```
yarn
....
$ EXECUTE_PARALLEL=true node workspace-run.js build:lib
'EXECUTE_PARALLEL' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.  
error Command failed with exit code 1.
```
Use `cross-env`.
=> fix(scripts): env var in npm scripts for windows

.github/workflows/design-system-deploy.yml, .github/workflows/pr-demo.yml
Surge does not include Figma preview
Let's build  using  the Figma token
=> chore(Surge): DS build

.changeset/brown-impalas-attack.md, packages/design-system/src/components/Form/Field/Input/Input.File.tsx
There was hardcoded string left in the `getFileSize` function.
=> fix(design-system): remove hardcoded string in the input file component

.github/workflows/design-system-visual-testing.yml
Chromatic GH Action needs to build design-tokens at first because it's owned by the monorepo.
Build the package  before publishing it to Chromatic
=> chore(design-system): Chromatic GH Action

.changeset/violet-icons-rule.md, packages/design-system/tsconfig.json
last two releases 1.13 and 1.14 do not have index.d.ts which makes ts projects fails to compile.
add [rootDir](https://www.typescriptlang.org/tsconfig#rootDir) config to tsconfig
source: https://stackoverflow.com/a/58941798
=> fix(design-system): add tsconfig rootDir

.changeset/funny-pandas-swim.md, packages/design-system/src/components/Switch/Switch.tsx
The "blue bubble" is no longer correctly positioned when selecting a value
https://design.talend.com/?path=/docs/components-switch--default-story&globals=theme:light
Regression from: https://github.com/Talend/ui/pull/3605
=> fix(Switch): Animation is broken

packages/design-system/src/components/InlineMessage/InlineMessage.stories.tsx, packages/design-system/src/components/InlineMessage/docs/InlineMessage.stories.mdx
No variant in demo means return nothing and Chromatic failed
Return the primitive of InlineMessage instead
=> chore(design-system): Usage story was not rendering

.changeset/afraid-keys-mate.md, packages/design-system/package.json
@talend/design-token dependency doesn't contain tokens required by `ButtonIcon`
=> fix(design-system): Missing design tokens

.changeset/kind-pigs-brush.md, packages/components/src/WithDrawer/WithDrawer.component.js, packages/components/src/WithDrawer/withDrawer.scss
With this z-index, some elements behind the drawer can still be renderer above it
Add a z-index
=> fix: update withDrawer z-index

.changeset/young-beans-deny.md, packages/components/src/WithDrawer/WithDrawer.component.js
`WithDrawer` doesn't have animation when mounted with drawers
`<WithDrawer drawers={[<Drawer/>]}/>`
The `TransitionGroup` is overriding `Drawer.Animation`props with `undefined`
https://github.com/Talend/ui/blob/master/packages/components/src/Drawer/Drawer.component.js#L32
Forward appear props to the transition group
=> feat(WithDrawer): Support appear/exit animations

.github/workflows/design-system-component-testing.yml, packages/design-system/README.md
Cypress executes tests using Electron, that's sad since it's designed to be run through real web browsers!
Run E2E tests on Chrome and Firefox in parallel 💯 
=> chore(design-system): browser matrix for Cypress

.changeset/clean-forks-juggle.md, packages/http/src/async.ts
PUT calls can have empty payloads
=> typings(http): allow empty PUT payload

.changeset/poor-windows-fetch.md, packages/design-system/.storybook/docs/Badge.tsx, packages/design-system/.storybook/docs/BadgeStorybook.tsx, packages/design-system/.storybook/docs/StatusTable.tsx, packages/design-system/.storybook/main.js, packages/design-system/src/components/Button/docs/Button.stories.mdx, packages/design-system/src/components/Toggle/docs/Toggle.stories.mdx
Toggle and Button.Icon will be merged into ButtonIcon in the next release
Deprecated them from our single source of truth right now
=> chore(design-system): deprecate Button.Icon and Toggle

.changeset/three-starfishes-count.md, packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx, packages/design-system/src/components/Form/docs/Input.copy.stories.mdx
In a new screen for API sharing, we need a prefix parameter on the Copy component.
=> fix(APIC-751): add a prefix parameter to the copy component

.github/workflows/dependencies.yml
changesets on upgrade generates too much release without real changes.
unplug it at the moment
=> chore(ARCH-432/CI): remove changeset from upgrade

.changeset/wet-carrots-relax.md, packages/datagrid/src/components/DataGrid/DataGrid.component.js, packages/datagrid/src/components/DataGrid/DataGrid.test.js
Contolled mode doesn't work when initially rendered with an empty selection
Set the initial state to `null` instead of `undefined` to better handle props changes:
- `focusedColumnId = null`: force empty controlled selection, user can't click on a cell
- `focusedColumnId = undefined`: empty uncontrolled selection, user can click on a cell
=> fix(Datagrid): Support empty selection in controlled mode

.github/workflows/design-system-visual-testing.yml
Chromatic is now available through a GH application
Thanks to @gjou-tlnd, we can run visual testing gh action on demand
=> chore(design-system): visual testing on demand

.github/workflows/surge-cleanup.yml
GH action to teardown surge at PR closing fails with 
```
Dependencies lock file is not found in /home/runner/work/ui/ui. Supported file patterns: package-lock.json,yarn.lock
```
This seems to be the npm cache configuration that fails, if we see [this post](https://github.community/t/github-ci-actions-for-nodejs-says-error-dependencies-lock-file-is-not-found/189354) or [this one](https://stackoverflow.com/questions/68527897/how-to-specifiy-path-for-actions-setup-node-in-github)
We don't need npm cache, we have npm just to use npx. Remove the cache config
=> chore(surge): teardown workflow without npm cache

.changeset/eleven-steaks-promise.md, packages/components/src/WithDrawer/withDrawer.scss
Switcher button text is rendered above drawer
=> fix(WithDrawer): Drawer is rendering below Switcher buttons

.changeset/nine-cheetahs-wonder.md, packages/dataviz/src/components/GeoChart/GeoChart.scss
z-index doesn't seem to me needed and I can't remenber why I added it
http://talend.surge.sh/dataviz/?path=/story/dataviz-geochart--continent
=> fix(Dataviz): Remove useless z-index on zoom buttons

packages/playground/package.json, packages/playground/src/app/components/DataGrid.js, packages/playground/src/app/index.js, packages/playground/src/assets/settings.json, packages/playground/webpack.config.dev.js
In the context of the CDN api I need to enforce testing.
Let's add a datagrid playground.
=> test(ARCH-349): add datagrid playground

packages/playground/package.json, packages/playground/src/app/components/FacetedSearch.js, packages/playground/src/app/index.js, packages/playground/src/assets/settings.json, packages/playground/webpack.config.dev.js
In the context of CDN API I want to check all UMDs and make it easy to smoke tests all our Talend/ui libs
Add faceted search playground
=>  test(ARCH-349): add faceted search playground

.changeset/ten-cups-drive.md, packages/design-system/src/components/Form/Field/Field.style.ts
When an input get focus with tab, there is the default outline and our border focus indicator shown.
As Safari [doesn't respect border-radius](https://bugs.webkit.org/show_bug.cgi?id=20807) on outline property for now, we need to keep the border implementation for now.
=> fix(design-system): default outline still displayed on Firefox using kbd

.changeset/stale-hairs-give.md, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
When calling “convertToTimeZone” function with specific timezone (Europe/Berlin) and summer time, it returns a wrong date.
More details please check https://jira.talendforge.org/browse/TDOPS-1233
Pass an optional "date" object to "getUTCOffset" function instead of the default current time to get the right time offset.
=> fix(utils/date): convertToTimeZone function with specific timezone and summer time

.semgrepignore
Tests are not in a /test folder and semgrep does not ignore these .js / .tsx files by default
This is to prevent false positives in scans
This is to prevent the CI scans from flagging lots of tests and unrelated code
https://semgrep.dev/docs/semgrep-ci/overview/#ignoring-files
=> chore(security): Add .semgrepignore file

packages/design-system/talend-scripts.json
pre-release script exit in error.
```
```
which cause demo to be broken.
The error is 
```
ERROR in unable to locate '/Users/jmfrancois/github/talend/ui/packages/design-system/src/icons' glob
```
Remove icons from copy config
=> fix(ds): remove icons from config

.changeset/weak-mails-poke.md, packages/router-bridge/package.json
ui is a public repository.
but https://unpkg.com/@talend/router-bridge is 404.
* set visilibility to public.
* update license to Apache-2.0 as the other packages
=> fix(ARCH-432/router-bridge): set visibility to public

.github/workflows/changeset.yml
Changeset PRs status stays on pending because the GH action to build and test doesn't run.
Supposition made is that it doesn't run because of the user (generic github token passed in action).
Set our bot's PAT to push the changeset branch?
=> chore(changeset): set proper PAT to create changeset PR

.github/workflows/changeset.yml
Workflow are not triggered when the release PR is updated
See discussion here: https://github.com/changesets/action/issues/70
trying to use `setupGitUser`
=> chore(ci): Trigger build on release PR update

packages/dataviz/.storybook/main.js, packages/dataviz/.storybook/preview-head.html, packages/dataviz/.storybook/preview.js, packages/dataviz/.storybook/webpack.config.js, packages/dataviz/package.json
Dataviz still has its own configuration
Use talend/scripts to run storybook
=> chore(ARCH-466/Dataviz): storybook via ui-scripts

.changeset/silent-ties-jam.md, packages/design-tokens/package.json, packages/design-tokens/talend-scripts.json, yarn.lock
In `dist` and in `lib`, the output of the `index.scss` file for design-tokens should not be treated as CSS Modules with hashed classes and keyframes. These are all globals.
Fix the config for this.
=> feat(design-tokens): Disabled CSS Module hashing for design-tokens build

packages/design-system/.storybook/main.js
The remark plugin is used to provide the default value of a design token if its name is found in the documentation. 
It leans on previous values of the design tokens.
=> doc(design-system): remove remark plugin

.changeset/sixty-mirrors-chew.md, packages/design-tokens/package.json, packages/design-tokens/scripts/umd.test.js, packages/design-tokens/src/index.ts, packages/design-tokens/src/index.umd.ts, packages/design-tokens/webpack.config.js
Current playground is broken.
UMD of design-tokens was not used before DS 2.0 (with Input field)
The current UMD reprensent two modules (index.js + index.scss) which is not supported by UMD.
fix design-token umd by using a single entry.
add css import to obtain the good output.
UMD mean one global variable which reprensent the src/index.js
add tests to not repeat this in the future
=> fix(ARCH-465/design-tokens): umd are not well defined

.changeset/proud-games-dream.md, packages/components/src/DateTimePickers/DateTime/datetime-extraction.test.js
Two unit tests rely on one of the USA's timezone since they change their time twice a year, known as DST.
https://www.timeanddate.com/time/change/usa
I've modified these tests to now rely on Caracas' timezone, Venezuela is one of the countries which never changes.
http://www.webexhibits.org/daylightsaving/g.html
https://symbolhunt.com/venezuela/date-format/
=> test(components): avoid tests over timezone with DST

.changeset/rare-waves-promise.md, packages/design-system/src/components/Stepper/Step/Step.spec.tsx, packages/design-system/src/components/Stepper/Step/Step.tsx, packages/design-system/src/components/Stepper/docs/Stepper.step.stories.mdx
It's not possible to display tooltip on (disabled) steps.
Add an optional `tooltip` prop
=> feat(Step): Add tooltip support

.changeset/bluh-bluh-bluh.md, packages/design-system/src/components/Linkable/Linkable.tsx
Href is spread here: https://github.com/Talend/ui/blob/master/packages/design-system/src/components/Linkable/Linkable.tsx#L31
but not forwarded to the actual `a`  https://github.com/Talend/ui/blob/master/packages/design-system/src/components/Linkable/Linkable.tsx#L71
=> fix(Link): Href attribute is ignored

.changeset/mighty-melons-melt.md, packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.scss, packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js, packages/faceted-search/stories/facetedSearch.stories.js
Context: [JIRA 6189](https://jira.talendforge.org/browse/TDC-6189)
It updates Layout of Badge with slider popin in order to fix input width.
It handles large intergers and decimals.
It also handles with or without icon.
You can play with these two parameters in added story `Basic Search With Slider Popin` (2 dedicated boolean controls `withIcon` and `decimals`).
Splitting flex row in 2 when icon is present and adjust alignment.
=> fix(faceted-search): input width in badge with slider popin

.changeset/eight-mugs-obey.md, packages/cmf/__tests__/middlewares/http.test.js, packages/cmf/src/middlewares/http/middleware.js
cmf tests fail in node 16 because of un unhandled promise rejection.
This is due to http error with a text that is not in json. Cmf tries to parse it as json.
Catch the error, and doesn't take care of it as the response is already set as raw response.
=> fix(cmf): test in node 16

.changeset/silent-hornets-collect.md, packages/design-system/package.json, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.component.test.js, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.test.js, packages/forms/src/UIForm/fields/TimezoneList/__snapshots__/TimezoneList.component.test.js.snap
i18next peer deps doesn't match
- DS dev dep (https://github.com/Talend/ui/blob/master/packages/design-system/package.json#L88)
- other TUI packages peer/dev deps
(also, fixing unit tests failing beacuse of DST)
=> fix(DS): Update i18next version to match other packages

package.json, packages/design-system/package.json, yarn.lock
Minor version of prettier will make Cypress tests fail
Lean on a new version `2.6.1`
https://github.com/prettier/prettier/blob/main/CHANGELOG.md#make-artifact-friendly-for-webpack-12485-12511-by-fisker
=> fix(design-system): prettier

.github/workflows/design-system-visual-testing.yml
Chromatic is not run on push in a pr with the "need visual label"
=> chore(ci): Trigger chromatic on push

.changeset/tame-beds-promise.md, packages/components/src/AboutDialog/AboutDialog.component.js, packages/components/src/AboutDialog/AboutDialogTable.component.js
Modal table is full of useless `<div>` cluttering snapshots
Removing the div when rendering a text
=> fix(AboutModal): Unnecessary div in markup

.changeset/kind-olives-tease.md, packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap, packages/components/src/List/__snapshots__/List.test.js.snap, packages/components/src/VirtualizedList/ListTable/ListTable.component.js, packages/components/src/VirtualizedList/ListTable/ListTable.scss, packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
A `box-shadow` css property was added to each list item, breaking list style. 
I get back old selector for header, in order to prevent `box-shadow` to apply.
=> fix(ListTable): remove box-shadow on each item

.changeset/twelve-nails-exercise.md, packages/containers/.storybook/preview.js, packages/containers/src/ComponentForm/ComponentForm.component.js, packages/containers/src/Form/Form.stories.js
Deprecated lifecycle in ComponentForm
Remove deprecated lifecycle
=> chore(ARCH-482/ComponentForm): remove deprecated lifecycle

.github/workflows/design-system-component-testing.yml
Cypress bin was not installed anymore since we hit `yarn --ignore-scripts`
Force at least Cy installation with `yarn cypress install` addition
=> chore(cypress): github action

.github/workflows/changeset.yml
Temporary fix for the release action
=> chore(ci): Bringing back release action

.changeset/small-bugs-melt.md, packages/containers/src/ComponentForm/ComponentForm.component.js
componentDidUpdate set states when properties have changed. But the comparison is ko when there is no properties passed, as it takes a new Map by default.
Compare the properties properly without default values to check if they have changed
=> fix(ComponentForm): infinite rendering because of new Map ref everytime

.changeset/spicy-papayas-battle.md
changeset didn't push the release with the given fix of 10.0.1
https://www.npmjs.com/package/@talend/dynamic-cdn-webpack-plugin
re-trigger the release
=> chore: retrigger release

.changeset/shaggy-ravens-beg.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js, packages/faceted-search/src/components/QuickSearchInput/QuickSearchInput.component.js, packages/faceted-search/stories/facetedSearch.stories.js
onSelect is using the unfiltered facets array, leading to incorrect selection
=> fix(faceted-search): Quick search does not select correct facet when using filter

.changeset/wise-beers-wonder.md, packages/components/src/MultiSelect/MultiSelect.container.js, packages/components/src/MultiSelect/MultiSelect.stories.js
We don't see the message that display there is no record to show
=> fix(multiselect): add height when no option

.github/workflows/design-system-visual-testing.yml
=> chore(ci): Trigger visual NR on push

.github/workflows/design-system-visual-testing.yml
=> qchore(ci): Broken github action

.changeset/flat-tables-prove.md, packages/design-system/package.json
Storybook can't be started on Windows, `cross-env` is required to set environment variables.
Add it.
=> fix(design-system/storybook): Broken Storybook on Windows

.github/workflows/design-system-visual-testing.yml, packages/design-system/CONTRIBUTING.md, packages/design-system/DOCTEMPLATE.md
Doc was slightly out of date
I updated it
=> doc(design-system): Updating template and guidelines

.github/workflows/design-system-visual-testing.yml
=> chore(ci): Don't run chromatic on PR without changes on DS

.changeset/tall-bags-boil.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js
In datalist, when we have other elements in the suggestions box like categories title or custom children, we should not close the suggestions box when we click on them as they are inside the box.
This is due to a double blur management:
- onBlur is passed to react-autowhatever, which hides the box on input blur
- focus manager that delays the blur event callback in case we focus on anotherpart of the box
The first one prevent the second one to do the job.
Remove onBlur callback passed to react-autowhatever
=> fix(Datalist): keep suggestions when clicking inside the suggestion box

.changeset/cyan-kiwis-relax.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js
Storybook preset can't be used on apps as it's loading app's index.html 
- remove conflicting plugins 
=> feat(storybook-preset): Support apps

packages/design-system/src/components/Form/docs/Input.copy.stories.mdx
Input Copy story used a random default value that fails on Chromatic each new commit.
Default value is now static.
=> doc(design-system): Updating Copy story with static default value

.changeset/eight-pillows-search.md, packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixButton.tsx, packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixReadOnly.tsx
PropsType naming is inconsistent in some components, the sooner it's fixed the better 😬 
Use `~PropsType` since it's used everywhere else.
Considered breaking because types are exported.
=> chore(design-system): PropsType naming

.changeset/cool-months-help.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js
When used in `restricted` mode, the datalist cannot be reset to an empty value, unless that empty value is explicitly an option in the `titleMap`.
Allow the reset of the value in restricted mode by simply cleaning the input, and persist the change (i.e. call the onChange props).
=> chore(Datalist): Allow reset to empty in restricted mode

.changeset/silver-buckets-allow.md, packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.component.js, packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.test.js, packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/DefaultValueRenderer.test.js.snap, packages/components/src/FormatValue/FormatValue.component.js, packages/dataviz/src/components/TooltipContent/__snapshots__/TooltipContent.component.test.tsx.snap
FormatValue is exporting an `hasWhiteSpaceCharacters` for conditional rendering., this logic is duplicated in every component usage
Handle the case inside the component
=> fix(FormatValue): Handle string without whitespaces

.changeset/lemon-timers-invite.md, packages/components/src/Datalist/Datalist.component.js
https://jira.talendforge.org/browse/TDOPS-963
After updating to the latest tui version, there's an error inside Datalist component for triggers.
Sometimes values inside entry may be number type. so toLowerCase fails.
More details inside jira ticket comments
Convert values to string before calling toLowerCase()
=> fix(TDOPS-963/Management): fix Datalist component error

.changeset/olive-cooks-boil.md, tools/upgrade-deps/src/npm.js
The npm view command is returning an empty result on Windows: 
```bash
> npm view @talend/react-components@'^6.44.0' version --json
SyntaxError: Unexpected end of JSON input
```
Removing the quotes solves the issue.
but we need to support space 
`npm view @talend/react-components@'<5 || ^6.44.0' version --json`
double quote works
=> fix(upgrade-deps): npm view command on windows

.changeset/shy-buses-search.md, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
Preset is not importing ThemeProvider
Add both Icons & Theme provider
=> feat(storybook-preset): Add design-system decorator

.changeset/mighty-ghosts-sing.md, packages/components/src/List/ListComposition.stories.js, packages/components/src/List/ListComposition/VList/VList.component.js, packages/components/src/List/ListComposition/VList/VList.component.test.js
When VList is instanciated without column definition as children, it was crashing trying to `filter` on `undefined` object.
Add possibility to have `undefined` children with `?` operator
=> fix(VList): handle VList without columns

packages/design-system/package.json, packages/design-system/src/components/Tooltip/Tooltip.spec.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx, yarn.lock
When we want to test with snapshot a component containing a Design-system `Tooltip` (Reakit), its id is computed (and different) at each build and id generator function can't be mocked. Leading to unstable and failing tests.
I've re-used the [`TooltipTrigger`](https://github.com/Talend/ui/blob/master/packages/components/src/TooltipTrigger/TooltipTrigger.component.js#L115) (old component) behaviour for id computation using `uuid.v4` function. 
Id generation for `Tooltip` component is `uuid.v4` (which can be mocked in tests) but can be overwritten with `baseId` property of `Tooltip`
=> feat(Tooltip): compute a uuid v4 baseId if not provided

.github/workflows/visual-testing.yml, packages/datagrid/.storybook/preview.js, packages/datagrid/package.json, packages/datagrid/src/components/datagrid.component.stories.js, packages/dataviz/.storybook/preview.js, packages/dataviz/package.json, packages/dataviz/src/components/BoxPlot/BoxPlot.stories.tsx, packages/dataviz/src/components/RangeFilter/RangeFilter.component.stories.tsx
We want to enable chromatic UI tests on packages other then design-system.
Monorepos are not supported OOTB (https://www.chromatic.com/docs/monorepos), this is a first quick iteration to support datagrid package which we is going to change a lot in the next few weeks
=> chore(ci): Setup chromatic on datagrid & dataviz

.changeset/honest-goats-drum.md, packages/design-system/src/components/Tooltip/Tooltip.spec.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx
See #3952 for context.
I've replaced uuid by reakit native id computation.
See #3952 
=> feat(Tooltip): use reakit useId as default baseId

.changeset/curvy-balloons-jog.md, packages/assets-api/src/index.test.ts, packages/assets-api/src/index.ts
`Talend.getCDNUrl` is doing a concatenation of both `base` url and `CDN_URL` env variable.
In most of our apps, base is set to `/` and `CDN_URL` is set to `/cdn` which leads to `//cdn/etc` 
The browser then fails to call the resource due to double slashes
Prevent the getCDNUrl to return an url starting with a double slash.
=> fix(assetApi): prevent getCdnUrl to start with double slash

.changeset/heavy-jobs-appear.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js
When updating the titleMap of a datalist, the value does not get updated
It has been detected on TMC side : https://jira.talendforge.org/browse/TDOPS-2240
=> fix(components): Datalist should update its value when the titleMap changes

.changeset/two-ears-doubt.md, tools/scripts-config-eslint/.eslintrc
Storybook & friends are imported by our presets and are not listed in project dependencies
=> fix(eslint): Disable no-extraneous-dependencies for stories & tests

.changeset/healthy-maps-report.md, .changeset/wicked-badgers-rest.md, packages/assets-api/package.json, packages/playground/webpack.config.dev.js, tools/scripts-config-cdn/modules.json
assets-api has been fixed in #3969 but the fix can be deployed project side because the code is embeded in all UMD (forms, ds, datagrid)
* distribute assets-api in UMD
* add it to cdn config
* ask for release of packages
=> feat: distribute assets-api in UMD

.github/workflows/visual-testing.yml
Execution condition was unfortunately removed 
=> chore(ci): Restore chromatic label condition

packages/design-system/src/components/Switch/docs/Switch.stories.mdx
The current Switch component has a lot of false positives on Chromatic
Disable the chromatic tests for the component before its planned redesign
=> chore(design-tokens): Disable Chromatic tests on legacy Switch before redesign

.changeset/gentle-beds-yawn.md, packages/design-system/src/components/Dropdown/Dropdown.spec.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx
Currently, we have no way to close the dropdown other than click outside.
While the user has made his selection in the dropdown, the menu should close itself when actionned
Close automatically the menu while clicking on a button or a link.
For the link part, i was asking myself if it's required but for some use cases of internal routing, if the dropdown stays in the view, it could have some purprose.
=> fix(Dropdown): Close on button or link click

.github/actions/sourceclear/Dockerfile
Security scan action runs apk add to install jq on the docker env.
But the docker env is based on `node:16` docker image which does not have apk.
Use node-alpine
=> chore(ci): use alpine node to have apk

.github/actions/sourceclear/Dockerfile
Security scan gh action uses curl but it is not installed on `node:16-alpine` by default
Install it via apk
=> chore(ci): install curl for security scan action

.github/actions/sourceclear/Dockerfile
jq not found while trying to install it in security scan workflow
`apt-get update`
=> chore(ci): update apt-get to install jq in security scan action

.github/actions/sourceclear/entrypoint.sh, .github/workflows/security-scan.yml
Security scan script now list the packages and loop over this list.
But it still has the old configuration managing a comma-separated list.
Remove the custom separator configuration to loop over the packages list properly
=> chore(ci): security scan fix

.github/actions/sourceclear/entrypoint.sh
Secu scan fails because srcclr script can't read the symlink to yarn.lock that is created under root user.
The symlink read doesn't work, which is weird as we have all the rights on it (777). But it's possible that the link is stored somewhere in owner's home that we don't have access.
Copy the yarn.lock instead.
=> chore(ci): secu scan cp yarn.lock instead of symlink

.changeset/fluffy-games-press.md, packages/components/src/List/ListComposition/VList/VList.component.js
```
[Error] Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received an object at index 1.
printWarning (prop-types.js:196)
createUnionTypeChecker (prop-types.js:550)
./src/List/ListComposition/VList/VList.component.js (TalendReactComponents.js:27373)
__webpack_require__ (TalendReactComponents.js:73021)
./src/List/ListComposition/VList/index.js (TalendReactComponents.js:27396:94)
__webpack_require__ (TalendReactComponents.js:73021)
./src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.js (TalendReactComponents.js:26424:84)
__webpack_require__ (TalendReactComponents.js:73021)
./src/List/ListComposition/LazyLoadingList/index.js (TalendReactComponents.js:26527:104) …
```
=> fix(Components/Vlist): proptypes 

packages/design-system/.storybook/main.js, packages/design-system/.storybook/mdx/groupBy.js, packages/design-system/.storybook/mdx/groupByDetails.js
We can't wrap documentation sections into tabs, accordions, or anything else.
Let's bring a solution to do that using a custom Remark plugin.
```mdx
Lorem ipsum
Lorem ipsum
Extra content here  
```
=> chore(design-system): remark plugin into Storybook

.changeset/five-kiwis-reply.md, packages/cmf-webpack-plugin/package.json, packages/cmf-webpack-plugin/talend-scripts.json, workspace-run.js
there is a circular dependencies which break nx and also workspace run since we have imported scripts in the repository.
It has some side effect like building design-system after react-componnets
* rewrite the workspace run to compute the order before get the cmd to make it more simple to understand and fail if there is a circular dependnecies inside the repository
* fix the circular dependencies
=> chore(ARCH-515): fix order in workspace-run.js

.changeset/eight-camels-notice.md, packages/components/src/Notification/Notification.component.js
Remaining `this` in a functional component
Remove `this`
=> fix(Notification): remove this in functional component

packages/design-system/src/components/Form/Form.stories.tsx
Missing gap in story
https://design.talend.com/?path=/docs/components-form-form--form-skeleton&globals=theme:light#skeleton
=> doc(design-system): Add gaps in form skeleton story

.changeset/gentle-spoons-build.md, tools/upgrade-deps/README.md, tools/upgrade-deps/src/index.js, tools/upgrade-deps/src/npm.js
today if you want to try next storybook release you have to do it by hand (change all the package.json version to point to 6.5.0-beta.8 for example)
add the option so final it goes on
`talend-scripts upgrade:deps --scope=@storybook --next`
=> feat(upgrade:deps): add --next support

.changeset/quiet-radios-clap.md, packages/components/src/Datalist/Datalist.component.js
When we have a titlemap in a datalist with multiple items with the same name, we select the 2nd duplicate item in the list.
But when onBlur is triggered, we call `updateValue` again with the value from `getEntryFromValue` which will select the first item in the list of duplicates.
If an item is selected and has the same name as the filter value , we don't need to call `updateValue` again, it's already selected.
=> fix(components): datalist blur persist value when one is selected

.changeset/short-chefs-drive.md, fork/dynamic-cdn-webpack-plugin/src/find.js, fork/dynamic-cdn-webpack-plugin/src/find.test.js, fork/dynamic-cdn-webpack-plugin/src/index.js, fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
in the case you have storybook and react-cmf-router yarn may install you the history into different possible context.
require.resolve(history) will return you the one closest to the provided webpack context.
```
const resolvePkg = require('@talend/dynamic-cdn-webpack-plugin/src/resolve-pkg');
resolvePkg('history', {cwd: './node_modules/@talend/react-cmf-router'})
// '/Users/jmfrancois/github/talend/data-processing-pipeline-designer/webapp/node_modules/history/main.js'
```
but that is history 5 !! and not history 3 (so the one for storybook).
so we ends with 404 on the cdn request.
* add check on semver.major from the dependencies.json and throw exception if it do not match
* use …
=> fix(ARCH-515/cdn): use findPackage instead of require.resolve

.changeset/small-tables-roll.md, packages/datagrid/src/components/DefaultIntCellRenderer/DefaultIntCell.scss
Int cell renderer doesn't display text align right
Update Int cell renderer style
=> fix(datagrid) int cell doesn't display text align right

.changeset/plenty-cobras-fix.md, packages/datagrid/src/components/DataGrid/DataGrid.component.js, packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js, packages/datagrid/src/components/DefaultCellRenderer/index.js, packages/datagrid/src/components/DefaultHeaderRenderer/index.ts, packages/datagrid/src/components/PinHeaderRenderer/PinHeaderRenderer.component.tsx, packages/datagrid/src/components/PinHeaderRenderer/index.ts
Keep cleaning up datagrid api, to stick as much as possible to ag-grid documentation.
https://www.ag-grid.com/react-data-grid/column-properties/
=> chore(datagrid): Cleanup internal renderer API

tools/codemods/rb-to-talend-rb/README.md, tools/codemods/rb-to-talend-rb/index.js
This goes with the fork of react-bootstrap to make v0.33 compatible with react 18.
This codemod replaces imports from `react-bootstrap` to `@talend/react-bootstrap`
=> feat(codemod): react-boostrap to @talend/react-bootstrap

.changeset/hot-swans-explode.md, tools/scripts-config-react-webpack/config/webpack.config.js, tools/scripts-config-react-webpack/config/webpack.config.prod.js
The source-maps for apps built with prod mode are invalid.
Change `devtool` to another source-map type which Terser plugin will support.
Tested under playground. can see the original source code:
=> fix(ui-scripts): invalid source-maps for apps built with prod mode

.github/workflows/icons.yml
Icons from Figma have been pushed manually
They must come from a Github Action, because why not.
=> chore(icons): Github Action to download icons from Figma

.changeset/eighty-buses-search.md, packages/components/src/Typeahead/Typeahead.component.renderers.js, packages/components/src/Typeahead/Typeahead.test.js
Datalist selection by ID should allow all types, not only string
=> fix(TDOPS-2364/components): datalist selection by id should allow all types

.changeset/odd-falcons-yawn.md, packages/assets-api/src/index.test.ts, packages/assets-api/src/index.ts
current meta is resolved as null because the attribute value do not exists so current compiled version is used. ..
use meta content attribute to get the real value
=> fix(assets-api/ARCH-537): use correct meta attribute

.changeset/fast-ducks-stare.md, packages/containers/package.json
`react-dom` doesn't appear in containers' [dependencies.json](https://unpkg.com/browse/@talend/react-containers@7.2.0/dist/TalendReactContainers.js.dependencies.json)
Add react-dom in peer dep
=>  fix(Containers): add react-dom as peer dep

.changeset/spicy-lemons-rhyme.md, packages/components/src/Datalist/Datalist.stories.js, packages/components/src/Typeahead/Typeahead.component.renderers.js
When we render a custom datalist dropdown (with extra components) we want to be able to close dropdown on extra component interaction. 
Datalist now passes a new parameter to children rendering function : the input reference. 
In this way, we'll be able to blur input focus.
=> feat(TDC-6235): pass input reference to datalist rendering function

.github/workflows/visual-testing.yml, packages/forms/package.json
Add the forms package to chromatic project
=> chore(ci): Enable chromatic on react-forms

.changeset/odd-suns-check.md, packages/router-bridge/src/redux/index.js, packages/router-bridge/src/router/index.js, packages/router-bridge/src/router/router-legacy-mode.test.js, packages/router-bridge/src/router/router-rr5-mode.test.js
Props are spread into the Router component exposed by router bridge.
This is not working well as we have to pass a new prop (location) with react router v6
Write the component to spread the props and not an array
=> fix(router-bridge): Router props not passed

.changeset/light-roses-pretend.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js, packages/components/src/Datalist/Datalist.stories.js
Cherry-picking https://github.com/Talend/ui/pull/4094 on maintenance branch
=> fix(Datalist): keep user filter when suggestion changes (#4080)

packages/forms/src/FormSkeleton.js, packages/forms/src/FormSkeleton.scss, packages/forms/src/FormSkeleton.test.js
FormSkeleton is using deprecated TUI Skeleton
=> feat(forms): Use design-system skeleton in FormSkeleton

.changeset/cool-apples-joke.md, packages/components/src/RatioBar/RatioBarComposition.component.js, packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
RatioBarLine uses the _old_ tooltip implem, which is not really accessible
Use the DS one
=> fix(TDC-6341): RatioBarLine should use Tooltip from DS

.changeset/violet-cherries-repeat.md, packages/components/src/RatioBar/RatioBarComposition.component.js, packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
ratiobarcomposition items does not contains the tooltip label
add it as sr-only : it will also be appreciated by qa guys for their auto ui tests
=> fix(TDC-6341): improve RatioBarComposition accessibility

.changeset/two-tables-eat.md, fork/react-bootstrap/package.json
current bootrap fork is not accessible without npm token
add publish access config and trigger a new release
=> fix(ARCH-537/fork/bootstrap): add publish access config

.changeset/slimy-swans-scream.md, packages/forms/README.md, packages/forms/build-utils.js, packages/forms/package.json, packages/forms/webpack.ace.config.js, packages/playground/webpack.config.dev.js
since code widget is lazy the way to add modes has been restricted to copy them into your app assets.
Before that it was possible by using import like this
```javascript
import 'brace/mode/json';
```
This was an issue as it force your app to have ace editor even if you don't use it.
* copy modes json, sql and python also theme chrome and snippets into forms/dist
* add utils to configure webpack
* use them in the playground
=> fix(ARCH-537/Forms): build and configure modes

.github/workflows/design-system-component-testing.yml, .github/workflows/design-system-deploy.yml, .github/workflows/visual-testing.yml
Storybook build was failing on github action
Fixing the build by...building the requisite dependancy 
=> chore: build icons from github actions

packages/datagrid/package.json, packages/datagrid/src/components/DataGrid/DataGrid.component.js, packages/datagrid/src/components/PlaygroundCellEditor/ApplyToIdenticalValues.component.tsx, packages/datagrid/src/components/PlaygroundCellEditor/ApplyToIdenticalValues.scss, packages/datagrid/src/components/PlaygroundCellEditor/PlaygroundCellEditor.component.tsx, packages/datagrid/src/components/PlaygroundCellEditor/index.ts, packages/datagrid/src/components/RichCellEditor/RichCellEditor.component.scss, packages/datagrid/src/components/RichCellEditor/RichCellEditor.component.tsx, packages/datagrid/src/components/RichCellEditor/components/CellEditorDatalist.component.scss, packages/datagrid/src/components/RichCellEditor/components/CellEditorDatalist.component.tsx, packages/datagrid/src/components/RichCellEditor/components/CellEditorTextarea.component.scss, packages/datagrid/src/components/RichCellEditor/components/CellEditorTextarea.component.tsx, packages/datagrid/src/components/RichCellEditor/index.ts, packages/datagrid/src/components/datagrid.component.stories.js, packages/datagrid/src/components/index.ts, packages/datagrid/src/types/index.ts, yarn.lock
Custom cell editor is not shared between projects.
Expose it here.
- `PlaygroundCellEditor` is the editor specific to the playground (it requires methods to fetch semantic types as editor parameters)
- It relies on `RichCellEditor` which allows to dynamically switch between an inline textarea editor and an editor with a dropdown (Datalist)
=> feat(DataGrid/cell-renderer): PlaygroundCellEditor

.github/workflows/icons.yml
Workflows can't trigger other workflow events when using default token, we need a PAT for this
https://github.com/peter-evans/create-pull-request#action-inputs
=> chore(icons): Build & test action is not triggered

.changeset/shiny-foxes-refuse.md, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
new Icons do not work in stories
remove the bundles override in default storybook config.
assets api should take the lead and use unpkg by default.
=> fix: remove bundles attributes

.changeset/curvy-games-suffer.md, packages/design-system/src/components/Popover/Popover.module.scss
Transparency is a good thing in life in general.
But when it comes to popover, it provide some weird behaviours
We can specify a background for the content but still the padding will not be impacted and will remain transparent.
Add white background to the popover
=> fix(design-system): Popover transparent background

packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.tsx, packages/design-system/src/components/Form/Primitives/Field/Field.tsx, packages/design-system/src/components/Form/Primitives/Input/Input.tsx, packages/design-system/src/components/Form/Primitives/InputWrapper/InputWrapper.tsx, packages/design-system/src/components/Form/Primitives/Label/Label.tsx, packages/design-system/src/components/Form/Primitives/Primitives.stories.mdx, packages/design-system/src/components/Form/Primitives/Primitives.stories.tsx, packages/design-system/src/components/Form/Primitives/Radio/Radio.tsx, packages/design-system/src/components/Form/Primitives/Textarea/Textarea.tsx, packages/design-system/src/components/Form/Primitives/_mixins.scss
Field is primitive wrapper component that handles the label, description, link and error logic for all text components. Previous `Field` did not use the tokens not Stack. 
It's only going to be used to build the public components. You won't use `Field` in your code. You will use `InputText` for instance that underneath is a composition of `Field` and `Input`. 
Use the tokens and stack.
=> feat(design-system/TUX-1081): private Field component

.changeset/silver-wolves-serve.md, .changeset/weak-beers-worry.md, packages/design-system/src/components/Popover/Popover.stories.mdx, packages/design-system/src/components/Popover/Popover.stories.tsx, packages/design-system/src/components/Popover/Popover.tsx
We can have button into a popover that close the popover at the end of the day (like setting up stuff inside the popover)
To allow the popover content to close the popover, we would like to access to the popover state that is contained into the component.
Here the integration is allowing to pass children as before if we don't have to handle this kind of use case and we can also provide children as function if we want to access the popover in the content
=> feat(design-system): allow to control popover

.changeset/cool-pots-invite.md, packages/components/src/List/ListComposition/VList/VList.component.js
When we define only one column in our `VList` (e.g  bellow example), component couldn't be rendered and crashed with an error. 
```
<List.Manager id="my-list" collection={simpleCollection}>
<List.VList id="my-vlist" {...props}>
<List.VList.Text label="Id" dataKey="id" />
</List.VList>
</List.Manager>
```
Caused by the call `children?.filter` where `children` is an object when only one element and an array when multiple. 
Do not filter when only one children (no-sense to hide all columns).
=> fix(AMG-202): VList with single column crash

.changeset/flat-rivers-wait.md, fork/dynamic-cdn-webpack-plugin/src/index.js, fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
dependency error: history in 404 of in bad URL (5.0.0 instead of 3.3.0)
react-cmf-router has a dependencies.json which request history
current webpack plugin use require.resolve from react-cmf-router to find history.
why ?
```
- history v5
- @talend/react-cmf-router
- react-router v3
- history
```
in this context dynamic cdn plugin is doing the following actions
```
cd node_modules/@talend/react-cmf-router
node
> require.resolve('history')
```
so it will give us 5.0.0
use find first then fallback to require.resolve to keep existing working code based on context only
=> fix(ARCH-537): dynamic-cdn use find instead of require.resolve

.changeset/nasty-chairs-push.md, packages/components/src/ActionList/ActionList.component.js, packages/components/src/ActionList/ActionList.stories.js, packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/src/SidePanel/SidePanel.stories.js
What about having beta features in a sidepanel !? 😉
=> feat(compoments): add beta tag for sidepanel

tsconfig.json
Tsconfig is only including `src` folder, which is making linter fails when we change a root level file (webpack.config.js)
Trying to correct the linter config 
=> feat(tools): Fixing eslint and Husky rules

.changeset/smart-birds-wash.md, packages/utils/src/date/date.test.ts, packages/utils/src/date/index.ts
We couldn't format a locale date with only day and month
add a new formatting type `MD` 
=> feat(TDC-6345): add MD date formatter

.changeset/forty-tools-rest.md, tools/scripts-cmf/package.json
current cmf-settings bin is not installed by the package because of a wrong path
fix the path to main script
```
$ ls -lh node_modules/.bin/cmf-settings 
node_modules/.bin/cmf-settings -> ../../tools/scripts-cmf/cmf-settimgs.js
```
=> fix(scripts-cmf): path to bin

fork/react-bootstrap/package.json, yarn.lock
```
The package colors after 1.4.0 are vulnerable to Denial of Service (DoS) that was introduced through an infinite loop in the americanFlag module. Unfortunately this appears to have been a purposeful attempt by a maintainer of colors to make the package unusable, other maintainers' controls over this package appear to have been revoked in an attempt to prevent them from fixing the issue. Vulnerable Code js for (let i = 666; i < Infinity; i++;) { Alternative Remediation Suggested * Pin dependancy to 1.4.0
```
remove colors as it is not used
=> chore(security/react-bootstrap): remove colors from dev deps

.changeset/wild-owls-warn.md, packages/dataviz/src/formatters/formatters.ts, tools/scripts-config-jest/test-setup.js
current test fail of dataviz fails on my os because my locale is en and i18next.language is undefined during test.
```
expect(received).toEqual(expected) // deep equality
- Expected  - 3
+ Received  + 3
Object {
-   "131035911": "131,035,911",
-   "500000000": "500,000,000",
-   "831035920": "831,035,920",
+   "131035911": "131 035 911",
+   "500000000": "500 000 000",
+   "831035920": "831 035 920",
}
62 |              });
63 |
> 64 |              expect(ticks).toEqual({
|                            ^
65 |                      '131035911': '131,035,911',
66 |                      '500000000': '500,000,000',
67 |                      '831035920': '831,035,920',
```
add missing language …
=> fix(ARCH-537): add language attribute to i18next mock

.changeset/old-socks-obey.md, packages/components/src/ActionList/ActionList.scss, packages/components/src/ActionList/ActionList.stories.js, packages/components/src/Actions/ActionButton/ActionButton.component.js, packages/components/src/Actions/ActionButton/Button.stories.js, packages/components/src/SidePanel/SidePanel.scss
Allow to use the new icons in ord buttons (mainly for existing migration and sidepanel)
Allow to pass a props to mount a SizedIcon instead of an Icon
=> feat(components): new icons in old buttons

.changeset/wise-lizards-sell.md, packages/components/src/SidePanel/SidePanel.scss, packages/components/src/SidePanel/SidePanel.stories.js
New icons and old one's are not aligned
Put the margin back
=> fix(components): align icons in sidepanel

packages/design-system/.storybook/docs/Icons.tsx, packages/design-system/.storybook/preview.js, packages/design-system/src/components/Icon/Icon.stories.mdx, packages/design-system/src/components/Icon/Icon.tsx, packages/design-system/src/components/Icon/Icons.stories.mdx, packages/design-system/src/components/Icon/SizedIcon.stories.mdx, packages/design-system/src/components/Icon/SizedIcon.stories.tsx, packages/design-system/src/components/Icon/SizedIcon.tsx, packages/design-system/src/components/IconsProvider/IconsProvider.tsx
SizedIcon component is not clearly documented, nor is its difference with Icon.
Document it. 
=> feat(design-system/TUX-1191/SizedIcon): Document SizedIcon component in DS

.changeset/rude-rules-sneeze.md, packages/design-system/src/index.ts
TooltipPlacement is not exported, it can only be retrieved using typeof Tooltip
=> feat(design-system): Expose TooltipPlacement

.changeset/fluffy-items-applaud.md, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/Primitive/DropdownShell.module.scss
zIndex for dropdown was in the JSX
Styles should be as much in possible in CSS modules.
=> fix(design-system/Dropdown): Default styles should be in CSS module

.changeset/silent-cheetahs-count.md, fork/module-to-cdn/package.json, tools/babel-plugin-import-d3/package.json, tools/babel-plugin-import-from-index/package.json, tools/cypress-api-mock-plugin/package.json, tools/scripts-build-cdn/package.json, tools/scripts-config-babel/package.json, tools/scripts-config-eslint/package.json, tools/scripts-config-jest/package.json, tools/scripts-config-ng-webpack/package.json, tools/scripts-config-prettier/package.json, tools/scripts-config-react-webpack/package.json, tools/scripts-config-storybook-lib/package.json, tools/scripts-config-stylelint/package.json, tools/scripts-config-typescript/package.json, tools/scripts-core/package.json, tools/scripts-preset-react-lib/package.json, tools/scripts-preset-react/package.json, tools/upgrade-deps/package.json
lots of url point to ui-scripts repository which was a private repo.
point to this repository
=> chore(ARCH-537): udpate github url in package.json

.changeset/two-years-sell.md, packages/cmf/src/components/ErrorBoundary/ErrorBoundary.component.js, packages/cmf/src/components/ErrorBoundary/ErrorBoundary.component.test.js
Exceptions caught by ErrorBoundary need to report to Sentry
report exceptions to Sentry when it's caught.
=> feat(cmf/ErrorBoundary): Sentry: capture exceptions caught by ErrorBoundary

.changeset/real-walls-relax.md, packages/cmf-router/src/UIRouter.js, packages/cmf-router/src/index.js
Currently, the RootComponent of the cmf-router is only usable when loading a route coming from the settings.
To be compatible with a composition approach, if the `routes` entry of the settings is empty, the render of the sub component would be the children instead of creating route components driven by the settings.
=> feat(cmf-router): allow children with composition

.changeset/quick-tomatoes-shake.md, packages/components/src/Emphasis/Emphasis.component.js, packages/components/src/Emphasis/Emphasis.stories.js, packages/components/src/Emphasis/Emphasis.test.js
Give the capacity to emphasis multiple words ou substring into a string
add capacity for `Emphasis` component to get an array as `value` parameter and emphasis each token in array.
=> feat(TDC-6337): allow multiple values in Emphasis

.changeset/serious-bulldogs-hug.md, packages/components/src/SubHeaderBar/SubHeader.stories.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
no ellipsis on long subheaderbar titles
ellipsis on long subheaderbar titles
=> fix(TDC-6368): no ellipsis on long subheaderbar titles

.changeset/odd-bobcats-jump.md, packages/design-system/src/components/ButtonIcon/Primitive/ButtonIcon.module.scss
In Mapper, clicking on the Icon does not actually fire the button's onClick event.
**What is the chosen solution to this problem?**|
Remove pointer events from the SVGs
=> fix(design-system/buttonIcon): SVG in ButtonIcon does not register click anymore

.changeset/honest-houses-wave.md, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
ThemeProvider is undefined
Bad merge happens on webpack 5 PR
import ThemeProvider
=> fix(ARCH-537/storybook): add ThemeProvider import

.changeset/pink-gorillas-hug.md, packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
RowData can contain children prop 🙄 
=> fix(component): don't pass rowdata to cell title

.changeset/happy-moons-switch.md, packages/cmf-router/src/sagas/documentTitle.js, packages/cmf-router/src/sagas/documentTitle.test.js
documentTitle saga fails and make all the sagarouter fail
handle the case where no routes.path from the config
=> fix(cmf-router): no routes from config

packages/design-system/.storybook/main.js
Some crucial options got removed during the webpack 5 config. 
Put them back in.
=> fix(design-system/Conf): Restoring TS check in storybook watch mode

packages/design-system/src/Welcome.stories.mdx, packages/design-system/src/themes/docs/Themes.stories.mdx, packages/design-system/src/tokens/docs/Tokens.stories.mdx
URLs for tokens and components docs were KO
Fix the URLs
=> doc(design-system/welcome): Fixing links

.github/workflows/pr-lint.yml, merge-report.js, packages/components/src/Datalist/Datalist.component.js
Fix the github annotations from the eslint github action
Use the `tj-actions/changed-files@v23.1` github action for the file diff
=> chore(eslint/ci): fix eslint annotation

.changeset/unlucky-trees-look.md, packages/design-system/src/components/IconsProvider/IconsProvider.spec.tsx, packages/design-system/src/components/IconsProvider/IconsProvider.tsx
In Pipeline Designer (at least), we load additional icons bundles. We should not declare default bundle anymore, but if we only keep additional ones, it overrides the default config and we lost default icons.
Add a new `additionalBundles` props to the `IconsProvider` component and concat it with the `bundle` props.
=> fix(design-system): Allow additional bundles for IconsProvider

.github/workflows/design-system-deploy.yml
ci master fails to deploy ds
we have to assume a circular dependency with storybook-docs which is here:
storybook-docs need build:lib of design-system and design-tokens
storybook-docs is a dependency to build test:demo of both
=> chore: fix ds deploy ci master

.github/workflows/pr-lint.yml, packages/components/src/Drawer/Drawer.component.js
There is some false positive warnings on imports for eslint
Add the build scripts to the yarn install command so import on /lib are resolved
=> chore(eslint/ci): fix eslint false positive on imports

.changeset/shaggy-bees-matter.md, tools/scripts-config-cdn/cdn.js
the copy has multiple time the same libs.
remove it
=> fix(cdn): do not copy the same assets multiple times

.changeset/big-zoos-relate.md, tools/scripts-config-jest/jest.config.js
Some libs are now exposing `.mjs` files and we currently don't apply transformations on them.
Add a configuration to now transform those files.
=> feat: Support .mjs files transform

.changeset/modern-ladybugs-sell.md, packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx
When the inputValue of the inputCopy change, the state of the hook `useCopyToClipboard` is not reset.
Preventing errors and copy message to be hidden.
Since we cannot reset the state of the hook manualy, the solution is to transfer the state of the hook to a custom local state.
Se we can reset this state when the value of the input change.
=> fix(APIC-827): reset input copy state when input value change

.changeset/calm-feet-bathe.md, .changeset/chilled-eels-own.md, packages/playground/src/app/foo.html, packages/playground/src/app/index.js, packages/playground/webpack.config.dev.js, tools/scripts-config-react-webpack/config/webpack.config.js, tools/scripts-config-react-webpack/package.json, yarn.lock
* html-loader has been upgrade during webpack 5 PR but never tested.
start using it create a webpack error;
```
ERROR in ./src/app/foo.html
Module build failed (from ../../node_modules/html-loader/dist/cjs.js):
ValidationError: Invalid options object. HTML Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'collapseWhitespace'. These properties are valid:
object { preprocessor?, sources?, minimize?, esModule? }
at validate (/home/jean/github/talend/ui/node_modules/schema-utils/dist/validate.js:105:11)
at Object.getOptions (/home/jean/github/talend/ui/node_modules/webpack/lib/NormalModule.js:585:19)
at Object.loader …
```
=> fix(webpack-config): html-loader config + test + upgrade

.changeset/neat-tigers-melt.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js
Storybook preset is using the preset-react config, with all its slow plugins.
Add a slow plugin to exclude list
=> feat(storybook-preset): Disable bundle-analyzer plugin

.changeset/sour-readers-cough.md, tools/scripts-config-jest/jest.config.js
In some of TMC's unit tests, we reference `jsdom` as global variable, it was working well but after upgrade to Jest 28, we need to config `testEnvironment: jest-environment-jsdom-global` for keep `jsdom` global.
Change jest config `testEnvironment` from 'jsdom' to 'jest-environment-jsdom-global'
=> fix(scripts/jest): expose jsdom as global variable in jest environment

.changeset/tame-gorillas-drive.md, packages/design-system/src/components/Switch/Switch.style.ts
When you use switch component in multiple containers, switch font inherits from parent, leading to inconsistent UI. 
Set a `paragraph-m-bold` font on switch label to prevent inheritance.
=> feat(design-system): set switch font to prevent inheritance

.changeset/tender-candles-hunt.md, packages/forms/src/UIForm/UIForm.component.js
When running test with React Test library, it throws the error " t is not function",  the "t" prop is injected with jest mock, but it is overwrited in the https://github.com/Talend/ui/blob/d6fe79807fb51e5897a9a9cdb8e758508ac93ac5/packages/forms/src/UIForm/UIForm.component.js#L427
This cause when calling CustomFormats function, the "t" is undefined. 
The fix only affect the unit test, for the webapp, there is no defaultProp for the I18NUIForm
append defaultProps for the I18NUIForm.
=> fix(UIForm): keep defaultProps created by withTranslation

.changeset/proud-shoes-admire.md, tools/scripts-config-storybook-lib/package.json, yarn.lock
Storybook interaction testing is out
https://storybook.js.org/addons/@storybook/addon-jest
=> feat(storybook-preset): Add storybook-jest

.changeset/spicy-clocks-cry.md, packages/forms/src/UIForm/UIForm.container.js, packages/forms/src/UIForm/index.js
On project side, tsc complains on 
`const Code = Forms.UIForm.utils.widgets.code;`
that
`Property 'utils' does not exist on type 'typeof UIForm'.ts(2339)`
this is because it is attached dynamically to the UIForm and so it can't be discovered by typescript compiler
Attach it properly: statically.
=> fix(forms): move code to let tsc build correct types

.changeset/clean-chefs-clap.md, packages/datagrid/README.md, packages/datagrid/src/components/DataGrid/DataGrid.test.tsx, packages/datagrid/src/components/DataGrid/DataGrid.tsx, packages/datagrid/src/components/DataGrid/DataGrid.utils.ts, packages/datagrid/src/components/DataGrid/Datagrid.stories.tsx
We want to be able to persist the column sizes to local storage, so the user don't have to resize it's every time
=> feat(datagrid): Add column size persistence to local storage

.changeset/great-cycles-hope.md, packages/datagrid/jest.setup.js, packages/datagrid/src/components/DataGrid/DataGrid.module.scss, packages/datagrid/src/components/DataGrid/DataGrid.test.tsx, packages/datagrid/src/components/DataGrid/useColumnSelection.hook.ts, packages/datagrid/src/constants/column-definition.constants.ts, packages/datagrid/src/constants/datagrid.constants.ts, packages/datagrid/src/serializers/__snapshots__/datasetSerializer.test.ts.snap
When focusing a cell, other cell in the same column with the same values should be highlighted
=> feat(datagrid): Highlight cells with the same values

.changeset/lucky-birds-study.md, packages/playground/src/app/components/DataGrid.js
Datagrid props changed in the last version
=> fix(playground): Handle datagrid breaking changes

.changeset/slow-mirrors-help.md, packages/datagrid/README.md, packages/datagrid/src/components/DataGrid/DataGrid.test.tsx, packages/datagrid/src/components/DataGrid/DataGrid.tsx, packages/datagrid/src/components/DataGrid/Datagrid.stories.tsx, packages/datagrid/src/serializers/__snapshots__/datasetSerializer.test.ts.snap, packages/datagrid/src/serializers/datasetSerializer.test.ts, packages/datagrid/src/serializers/datasetSerializer.ts, packages/datagrid/src/types/index.ts
Lazy loading requires a row identifier, which was missing.
Add it and document use case
=> fix(datagrid): Lazy loading use case

.changeset/nine-adults-play.md, packages/components/src/AppSwitcher/AppSwitcher.component.js, packages/components/src/AppSwitcher/AppSwitcher.component.test.js, packages/components/src/AppSwitcher/AppSwitcher.scss, packages/components/src/AppSwitcher/__snapshots__/AppSwitcher.component.test.js.snap, packages/components/src/HeaderBar/HeaderBar.component.js, packages/components/src/HeaderBar/HeaderBar.stories.js
Following the removal of theme scss styles from webpack , we need the possibility to add icons in SidePanel and HeaderBar components
Add an `appSwitcherIcon` props to HeaderBar component
=> feat(components): possibility to add icon in HeaderBar

.changeset/late-dancers-sneeze.md, package.json, packages/components/package.json, packages/datagrid/package.json, packages/faceted-search/package.json, packages/forms/package.json, yarn.lock
* current DS breaking change lead to major release of packages even when this is not the case.
* DS is under heavy dev so we can expect more breaking change
* DS is a singleton (need to have only one version because of React ThemeProvider
* move to easy to manage peerDependency
* breaking change will be detected by typescript at build time
=> fix: design-system is a peerDependency

.changeset/warm-horses-tap.md, packages/datagrid/src/components/PlaygroundCellEditor/PlaygroundCellEditor.component.tsx, packages/datagrid/src/types/index.ts
When submitting a new cell value, we don't have direct access to it's rowIndex, we need to get the focused column.
Add a third param with the context
=> feat(datagrid): Add cell context to editor onSubmit callback

.changeset/lucky-insects-kiss.md, tools/scripts-config-react-webpack/config/webpack.config.js
the sentry release version is not same with the one in initiator
use the same release version when build release.
=> fix(scripts/sentry): fix inconsistent sentry release version

.changeset/neat-birds-sleep.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js
angular xlts packages can't be fetched from unpkg.com
=> fix(preset-storybook): angular xlts packages can't be fetched from unpkg.com

.changeset/short-needles-wave.md, .gitignore, packages/cmf-router/src/UIRouter.js
`cmf-router` takes all routes and set an `Inject`, but if a route is juste a route that groupe sub-routes, with no components, it will display a banner with non-found component `undefined` in registry.
We don't put the Inject automatically, but only if we have a component property.
=> fix(cmf-router): wrong convertion from settings to routes for simple parent routes

.changeset/old-rockets-smell.md, packages/datagrid/src/components/DataGrid/DataGrid.module.scss
CSS used `!important` to override hover color, which makes custom styling difficult on app side, use css variable instead
=> fix(datagrid):  Unnecessary css important rule use

.changeset/beige-bottles-arrive.md, packages/cmf-router/src/UIRouter.js
In cmf router, there is a useEffect that register a listener on history to sync with redux.
But it unregister at action and location change. So everytime there is a new history push/replace change or location change, it unregister, rerender and register again.
But everything is not synchronous and we end up with time without listener.
A problematic usecase: we go to a route, and the component useEffect triggers an action (redux) that replaces the route, injecting an id. After the url replacement, the component rerenders and uses the id in parameter.
What happens:
- push action to go on the route
- cmf-router useEffect unregisters the history listener because action changed
- route component useEffect triggers the route replace
- the …
=> fix(cmf-router): no history listener unregister on new action

.changeset/wicked-peas-destroy.md, packages/cmf-router/src/UIRouter.js
Error in the api of history.listen
Fix it
=> fix(cmf-router): history listener

.changeset/lemon-turkeys-relax.md, packages/datagrid/src/components/DataGrid/DataGrid.test.tsx, packages/datagrid/src/components/DataGrid/DataGrid.tsx, packages/datagrid/src/components/DataGrid/Datagrid.stories.tsx, packages/datagrid/src/components/DataGrid/useColumnSelection.hook.ts, packages/datagrid/src/types/index.ts
Ag grid ref is not set directly on mount, meaning we can execute the effects and have an `undefined` api.
Use a state instead of a ref to get api objects, so we can react when they are set
=> fix(datagrid): Controlled selection is ignored on mount

.changeset/stale-carpets-wait.md, tools/scripts-config-jest/README.md, tools/scripts-config-jest/jest.config.js, tools/scripts-config-jest/utils.js
this configuration in your jest.config will break config related to d3
```javascript
transformIgnorePatterns: [
'/node_modules/(?!PKG_NAME)$',
],
```
because it is a double negation (ignore !d3 || ignore !PKG_NAME) so this one will make d3 ignored!
add API to be able to concat pkgs to that DO NOT ignore pattern
=> feat: addToIgnorePatterns

.changeset/spicy-beds-study.md, packages/datagrid/src/components/PlaygroundCellEditor/PlaygroundCellEditor.component.tsx
Grid data is mutated when cancelling cell edition,
`stopEditing` provided in props does not behave as the one from API
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/core/src/ts/rendering/cell/cellCtrl.ts#L560
=> fix(datagrid): Cell value is persisted when canceling edition

packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/BreakpointScale/BreakpointScale.tsx, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/ColorScale/ColorScale.tsx, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/DefinitionListItem/CopyValue.tsx, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/DefinitionListItem/useCopyValue.tsx, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/SizingScale/SizingScale.tsx, packages/storybook-docs/src/globalStyles.scss
Copy behavior was duplicated in the tokens doc pages
Write it as a single hook
=> feat(design-system/TUX-1175): Use a single hook for every ClickToCopy element

.changeset/eighty-crabs-work.md, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.test.js
The split feature of the enumeration component needs to be disable for some use cases
=> chore(TDS-6666): disable split

.changeset/four-items-train.md, packages/design-system/src/components/WIP/Tabs/Primitive/TabStyles.module.scss
We can't use `Tab` component from design-system v4 with Talend scripts because of this import : 
`@use '@talend/design-tokens/lib/tokens';`
This notation [requires sass-loader v11+ and webpack 5 to work](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#1100-2021-02-05).
To be compatible with webpack 4, which is still used in our libs and apps, we have to keep the `~` character during sass imports to tell webpack to look into `node_modules` folder.  
Otherwise, it crashes with the following error : 
```
SassError: Can't find stylesheet to import.
╷
2 │ @use '@talend/design-tokens/lib/tokens';
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
```
Put back the `~` character …
=> fix(TDP-11258): get back tilde character for sass imports 

.changeset/quick-lizards-yawn.md, packages/dataviz/src/components/LineChart/LineChart.scss, packages/dataviz/src/components/LineChart/LineChart.stories.tsx, packages/dataviz/src/components/LineChart/LineChart.types.ts, packages/dataviz/src/components/LineChart/LineChartLegend.component.tsx
It's a bit broken if we try to insert JSX
Use the Design System
=> feat(dataviz): allow to build custom legend

.changeset/popular-schools-remember.md, packages/design-system/src/components/Tag/Tag.tsx, packages/design-system/src/components/Tag/index.ts
To allow JS component to add customizable Tag as part of it, it requires to be able to define available tag variations in component prop type definition
Export available tag variations as string array
=> feat(CDM-237) Add const to export Tag variations through string array

.github/workflows/visual-testing.yml, packages/design-system/src/components/Accordion/Accordion.tsx
Visual testing github actions is failing due to storybook-docs package.
See https://github.com/Talend/ui/runs/8135110867?check_suite_focus=true
Build the package alongside the other while running the action.
=> fix(ci): build storybook docs for visual testing github action

.changeset/twelve-kangaroos-carry.md, packages/components/package.json, packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.stories.js, packages/components/src/Drawer/Drawer.test.js, packages/datagrid/package.json, packages/faceted-search/package.json, packages/forms/package.json, packages/storybook-docs/package.json, yarn.lock
Drawer's subtitle tag is not customizable (style)
Allow to specify which component tag from DS we can use
=> feat(CDM-237) Allow to customize drawer's subtitle tag

.changeset/fresh-items-pull.md, packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.component.tsx, packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.scss
Firefox does not display the burger menu icon
http://talend.surge.sh/datagrid/?path=/story/components-headercellrenderer--with-menus
Use the new DS icon
=> fix(datagrid): Header menu icon not rendering on firefox

.changeset/unlucky-ghosts-add.md, packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss, packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx, packages/design-system/src/components/Stack/StackHorizontal.stories.tsx, packages/design-system/src/components/Stack/StackHorizontal.tsx
Would be nice to be able to provide a height to the `StackVertical` component
Add a prop allowing only tokens + 100%
=> feat(StackVertical): Add a height prop

.changeset/large-days-breaking.md
Latest changes on talend scripts are breaking and we want to make the app updates them when they want.
Add a major bump for breaking change for the presets
=> chore(presets): add breaking change for talend scripts presets

.changeset/calm-poets-talk.md, packages/design-system/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/design-system/src/components/EmptyState/primitive/EmptyStatePrimitive.tsx, packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx, packages/design-system/src/components/Form/Field/Input/Input.File.tsx, packages/design-system/src/components/Form/Field/Input/hooks/useRevealPassword.tsx, packages/design-system/src/components/InlineEditing/InlineEditing.tsx, packages/design-system/src/components/Layout/Footer.tsx, packages/design-system/src/components/Layout/SkipLinks/SkipLinks.tsx, packages/design-system/src/components/Link/Link.tsx, packages/design-system/src/components/LinkAsButton/LinkAsButton.tsx, packages/design-system/src/components/Stepper/Progress/Progress.tsx, packages/design-system/src/components/ThemeProvider/ThemeSwitcher/ThemeSwitcher.tsx, packages/design-system/src/components/WIP/FormPrimitives/Input/Input.tsx, packages/design-system/src/components/WIP/HeaderBar/HeaderBar.tsx, packages/design-system/src/components/WIP/Menu/Menu.tsx, packages/design-system/src/components/constants.ts
DS components are not localised
https://jira.talendforge.org/browse/TDOPS-1735
use DS namespace for translations
=> fix(TDOPS-1735/designSystem) - use DS namespace for translations

.changeset/olive-taxis-joke.md, packages/playground/package.json
Playground icons is broken:
`/playgroundassets/svg/logo-645fcf40b9b6e3f25843.svg`
missing backslash
`/playground/assets/svg/logo-645fcf40b9b6e3f25843.svg`
Fix it
=> fix(playground): display playground icons

.changeset/odd-horses-wonder.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js
When titleMap is updated asynchronously AND input has no value set, you lost filter value on promise resolved. 
This bug causes E2E instabilities with cypress. 
Simply test if there is a filter before updating it with empty value.
Now your filter is not changed after titleMap has been updated 
=> fix(TDP-11342): do not reset Datalist filter on titleMap change

.changeset/new-mirrors-leave.md, packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js, packages/faceted-search/src/components/AddFacetPopover/AddFacetPopoverRow/AddFacetPopoverRowItem/AddFacetPopoverRowItem.component.js
Categories is not filled the same as the other rows
=> fix(TDC-6514): Faceted Search - locators

packages/design-system/i18next-scanner.config.js, packages/design-system/package.json, packages/design-system/src/components/Form/Field/Input/Input.File.tsx
Translations are not well extracted on the CI
Prevent build with native TSC and use i18next-scanner-typescript
=> chore(design-system): fix translations extraction

.changeset/wild-garlics-marry.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js
Storybook is now collecting some info.
Disabled it from talend-scripts config following documentation.
https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out
=> chore(talend-scripts): disable storybook telemetry

.changeset/breezy-jars-argue.md, packages/faceted-search/package.json, packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
Switch is not exported by the DS in the Form
=> fix(faceted-search): handle DS breaking changes (Switch to ToggleSwitch)

.changeset/brown-mayflies-swim.md, packages/components/src/DataViewer/Core/Tree/Tree.scss, packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.component.js, packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.scss, packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.test.js, packages/components/src/DataViewer/Icons/TreeBranchIcon/__snapshots__/TreeBranchIcon.test.js.snap, packages/components/src/DataViewer/RecordsViewer/Branch/RecordsViewerBranch.component.js, packages/components/src/DataViewer/RecordsViewer/RecordsViewer.scss
Sub levels of hierarchical data rendered with the DataViewer component cannot be opened by clicking on the branch/leaf icon.
It was possible before.
https://jira.talendforge.org/browse/TFD-14580
Fix it.
=> fix(TFD-14580): Fix DataViewer click on icons

.changeset/slow-swans-approve.md, packages/components/src/SidePanel/SidePanel.scss, packages/design-system/.storybook/docs/tokensDocHelpers/components/CompositionList/CompositionListItem.module.scss, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/ColorScale/ColorScale.module.scss, packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/SizingScale/SizingScale.module.scss, packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.module.scss, packages/design-system/src/components/Form/Primitives/Radio/Radio.module.scss, packages/design-system/src/components/InlineMessage/Primitive/InlineMessagePrimitive.module.scss, packages/design-system/src/components/WIP/Tabs/Primitive/TabStyles.module.scss
I see many logs during build: 
```
(35:3) start value has mixed support, consider using flex-start instead
```
use flex-start
=> fix: use flex-start

.changeset/twelve-apricots-end.md, packages/design-system/src/components/EmptyState/EmptyState.stories.mdx, packages/design-system/src/components/EmptyState/EmptyState.stories.tsx, packages/design-system/src/components/EmptyState/variants/EmptyStateMedium.tsx
The EmptyState component in its medium size does not expect a CTA.
However in some cases designer found out it could offer a better layout than having a CTA and underneath an action-less EmptyState. 
Opening up the action prop from the Primitive to the EmptyStateMedium component.
=> feat(no ticket): Action in EmptyState size M

.changeset/cuddly-pants-suffer.md, .changeset/dull-squids-press.md, packages/theme/src/theme/variations/_mdm.scss, packages/theme/src/theme/variations/_portal.scss, packages/theme/src/theme/variations/_tdc.scss, packages/theme/src/theme/variations/_tdp.scss, packages/theme/src/theme/variations/_tds.scss, packages/theme/src/theme/variations/_tfd.scss, packages/theme/src/theme/variations/_tic.scss, packages/theme/src/theme/variations/_tmc.scss, tools/scripts-config-react-webpack/config/webpack.config.common.js
in  #4360 we have fixed our scss files but as mentionned in comment anyone can add a file without it and so introduce an issue. 
remove the implicit sass data injected by our talend-scripts.
=> fix(ARCH-631/tools): remove sass data

.changeset/tiny-cooks-stare.md, packages/design-system/src/components/WIP/ErrorState/ErrorState.tsx
ErrorState doesn't render "link" prop when it is provided as a React element
Fix the test in the component
=> fix(design-system): Link from ReactElement in ErrorState

.changeset/cool-socks-repeat.md, packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss, packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx, packages/design-system/src/components/Stack/StackHorizontal.stories.tsx, packages/design-system/src/components/Stack/StackVertical.tsx
For some layout, we find the need to wrap this component with a container that have a width of 100%
Have the size to 100% available in the stack horizontal component
=> feat(design-system): add isFullWidth to StackH

.changeset/twenty-horses-brush.md, tools/scripts-config-jest/jest.config.js
We have the following error on a project without d3:
` Error: Cannot find module 'd3'`
remove require.resolve on d3 pkgs
=> fix(TFD-14627): jest config

.changeset/hip-cars-invite.md, packages/design-system/package.json, yarn.lock
I am on a POC where I work with create-react-app which is react 18.
I think we can open the DS to be used with it.
NOte: react-is is part of react mono repository it should be possible to align it to react.
=> fix(ARCH-607/DS): add react-18 as possible usage

.changeset/cold-toys-tickle.md, packages/components/src/QualityBar/QualityBar.component.js, packages/components/src/QualityBar/QualityBar.stories.js
In the current split mode, if the result of the percentage for a given category is 0, we will not have the representation for it.
We would like to have the quality bar telling that the indicator is set to 0 instead of having maybe only 1 or 2 splited part
=> fix(components): quality bar in split mode

.changeset/real-pugs-run.md, packages/design-system/src/components/WIP/Tabs/Primitive/Tab.tsx
Tabs use a button element with no type, which defaults to "submit" in a form. 
Set it forever as "button" because ew.
=> fix(ARCH-607/design-system): DS Tabs must be of type button

packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap, packages/design-system/src/components/Icon/Icon.module.scss, packages/design-system/src/components/Icon/Icon.tsx, packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap, packages/faceted-search/src/components/AdvancedSearch/__snapshots__/AdvancedSearch.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeOperator/__snapshots__/BadgeOperatorPopover.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap, packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
we don't want styled-component anymore.
rewrite using css module
=> chore(design-system): remove styled component

.changeset/empty-maps-swim.md, packages/cmf-router/package.json, packages/design-system/package.json, packages/router-bridge/package.json, yarn.lock
we spot a change in exposed internals of react-router in latest release. 
in the doubt for the moment I prefer to pin it to 6.3
=> chore(ARCH-658): pin react router

.changeset/loud-cameras-smile.md, tools/scripts-config-react-webpack/config/webpack.config.js
globalObject has been set by mistake to this instead of self
Follow webpack documentation: this for lib and self for web app
https://webpack.js.org/configuration/output/#outputglobalobject
> When targeting a library, especially when libraryTarget is 'umd', this option indicates what global object will be used to mount the library. To make UMD build available on both browsers and Node.js, set output.globalObject option to 'this'. Defaults to self for Web-like targets.
=> fix(TDOPS-2998): Replace globalObject value to self

.changeset/modern-rocks-arrive.md, .changeset/purple-pugs-share.md, packages/design-system/.storybook/preview-head.html, packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx, tools/scripts-config-storybook-lib/.storybook-templates/preview-head.html
Bundle wasn't exporting app fonts anymore, leading to CORS errors in chromatic and font not loaded. 
https://www.chromatic.com/build?appId=62022f03c6654e003a637b65&number=714
Get back font import
=> fix: missing fonts in exposed bundle

.changeset/fifty-lemons-beam.md, packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx
`ThemeProvider` theme property has been set as mandatory here https://github.com/Talend/ui/pull/4403/files#diff-f0f2d9658ff5eabd7c9296a2c246e54ad0b76c6cffdb3bb673b560f9273d0f56R8
But it has a default value in its implementation (https://github.com/Talend/ui/pull/4403/files#diff-f0f2d9658ff5eabd7c9296a2c246e54ad0b76c6cffdb3bb673b560f9273d0f56R11)
Switch prop to optional
=> fix: ThemeProvider optional theme property

.changeset/beige-kings-deliver.md, packages/dataviz/src/components/LineChart/LineChart.component.tsx, packages/dataviz/src/components/LineChart/LineChart.stories.tsx
Currently, nothing is displayed as it's only the "Line" that is displayed
=> fix(dataviz): render dot in LineChart when there is only one value

.changeset/tricky-seas-beam.md, packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.component.tsx
In the grid header renderer, when `0` is provided as the number of DQ rules applied, current rendering code shows "0" (first value of conditional rendering is falsy but not null/undefined so the value is rendered).
Enforce value testing.
=> fix(datagrid/HeaderCellRenderer): DQ icon and 0 rules

.changeset/happy-wombats-dance.md, packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/Validation.component.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/Validation.component.test.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/__snapshots__/Validation.component.test.js.snap
Having submit button when two form are encapsulated results in a weird redirect.
So when having the date picker in a form and clicking on "done" a submit is done and the page reloaded ...
remove the submit type and use onclick
=> fix(TDS-6837): not using submit button

.changeset/large-radios-pretend.md, .changeset/large-radios-pretend2.md, packages/components/src/SubHeaderBar/SubHeader.stories.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.module.scss, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js, packages/design-system/src/components/InlineEditing/InlineEditing.stories.tsx, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
In the context of https://jira.talendforge.org/browse/TDS-6839 we had issues with the `EditableText` and to fix the problem and to move forward with DS usage I choose to replace the `EditableText` by the `InlineEditing` component.
=> fix(SubHeaderBar): replace EditableText to InlineEditing

.changeset/blue-dodos-impress.md, .changeset/gold-waves-drum.md, packages/components/package.json, packages/components/src/Datalist/Datalist.component.js, packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/tsconfig.json, packages/datagrid/src/types/types.d.ts, packages/dataviz/src/components/BarChart/ColoredBar/ColoredBar.component.tsx, packages/dataviz/src/types/types.d.ts, packages/forms/stories/Playground.stories.tsx, packages/jsfc/package.json, yarn.lock
we use more and more TS but react-components do not expose typings
* add the bare minimum configuration and tools to generate typings in `@talend/react-components` package.
It means from this release react-components will contains a lib/index.d.ts in the release.
You can still use `declare module '@talend/react-components';` in your package but you should try to remove it to see if current typings are working well. Here it has been possible for datagrid but not for dataviz.
This came from the fact the new types are inferred by typescript from the javascript code so this is far from perfect.
But with this we will be now able to use ts and tsx files in place of javascript files and so be …
=> feat(ARCH-661): add typings to react-components

.changeset/slimy-moles-move.md, tools/scripts-config-storybook-lib/package.json
our storybook doc rely on a preset which is not in a dependency
Usage create the following error:
```
info => Loading presets
WARN   Failed to load preset: {"options":{"cssLoaderOptions":{"modules":true}},"type":"presets"} on level 1
ERR! TypeError: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:372:5)
ERR!     at validateString (node:internal/validators:120:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:998:3)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (/home/jean/github/talend/ui-dataset/node_modules/@storybook/core-common/dist/cjs/presets.js:17 …
```
=> fix(ARCH-658): add missing dep

.changeset/loud-dolphins-drum.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js
I have the following error this morning:
```
Generated code for /home/.../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[11].use[1]!/home/.../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[11].use[2]!/home/.../node_modules/typeface-source-sans-pro/index.css
1 | throw new Error("Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\nError: PostCSS plugin autoprefixer requires PostCSS 8.\nMigration guide for end-users:\nhttps://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users\n    at Processor.normalize (/home/.../node_modules/postcss/lib/processor.js:153:15)\n    at new Processor (/home/.../node_modules/postcss/lib/processor.js:56:25)\n    at postcss …
```
=> chore(ARCH-658): simplify webpack from sb

.changeset/breezy-bees-act.md, .changeset/twenty-tomatoes-ring.md, packages/theme/package.json, tools/scripts-config-react-webpack/package.json, yarn.lock
We have the following error in some projects:
```
-- inner error --
Error: Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```
postcss-loader do not enforce any version  it can run with both 7 and 8.
But we use autoprefixer 10 which require postcss 8. https://github.com/postcss/autoprefixer/releases/tag/10.0.0
Current app fix this pb by adding postcss 8 as dependency.
Remove the need to add this dependency by adding it to the preset.
**[ ] This PR introduces a …
=> fix(ARCH-658): add postcss 8 dependency

.changeset/smart-suns-think.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js, tools/scripts-config-storybook-lib/.storybook-templates/preview.js, tools/scripts-config-storybook-lib/.storybook-templates/utils.js, tools/scripts-config-storybook-lib/index.js
Storybook doesn't start on Windows with this config because of unresolved backslashed paths.
Prevent Windows paths with backslashes to be used.
=> chore(storybook-lib): Broken Windows filepath

.changeset/tender-cows-deliver.md, .changeset/witty-apes-brake.md, packages/components/__mocks__/uuid.js, packages/components/package.json, packages/components/src/Actions/ActionFile/ActionFile.component.js, packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js, packages/components/src/Breadcrumbs/Breadcrumbs.component.js, packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js, packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js, packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/TimePicker/TimePicker.component.js, packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js, packages/components/src/List/ListComposition/SortBy/SortBy.component.js, packages/components/src/List/Toolbar/Pagination/Pagination.component.js, packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js, packages/components/src/Toggle/LabelToggle/LabelToggle.component.js, packages/components/src/TooltipTrigger/TooltipTrigger.component.js, packages/components/src/Typeahead/Typeahead.component.js, tools/scripts-config-jest/test-setup.js
uuid is a tiny lib but there is a native API to do that: https://caniuse.com/mdn-api_crypto_randomuuid
as we use only v4 and v4 is using native when available it means uuid.v4 lib is not a lib but a polyfill.
remove it from components
=> chore(ARCH-658): remove uuid dependency on components

.changeset/lovely-trainers-yell.md, tools/scripts-core/scripts/build-lib.js, tools/scripts-core/scripts/build-ts-lib.js
In the context of #4445 we need to watch and rebuild libraries.
But `talend-scripts build:ts:lib --watch` doesn't work.
As babel do not exit copy never happens.
Same for `talend-scripts build:lib` it will not work.
* add the --watch option support in build:ts:lib.
* align build-lib.js script to use same patterns as in build-ts-lib so it supports --watch
The main difference is the copy is happening in parallel of babel and typescript
- [x ] Docs have been added / updated (for bug fixes / features)
=> feat(TDOPS-3184): add --watch support on build:lib and build:ts:lib

.changeset/real-hornets-suffer.md, packages/design-system/src/components/Form/Primitives/Input/Input.tsx
On primitive inputs, passed `onBlur` property is not called
=> fix(TDOPS-3267): fix onBlur on primitive input

.changeset/ten-feet-tell.md, packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.module.scss
=> fix(datagrid): header cell width

.changeset/long-days-vanish.md, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Component InlineEditing always handles key enter event even when not editing text
Check if component is in edition mode
=> fix(TFD-14833) InlineEditing : fix enter key always handled

.changeset/bright-apples-think.md, packages/components/src/Datalist/Datalist.component.js, packages/components/src/Datalist/Datalist.component.test.js, packages/components/src/Datalist/Datalist.stories.js
If the value is not existing, we have only "no result found" and no way to understand that we can add a value in the datalist
On the datalist, new props called 
- `allowAddNewElements` can be passed to let the user create new value with a hint to tell him that the value was not existing in the current titlemap.
- `allowAddNewElementsSuffix` allow to override the "(new)" suffix by another one.
=> fix(TDP-11600): allow to add new value in datalist

.changeset/light-numbers-tan.md, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Using this component in Data Prep, i can't use RTL tests to select the buttons and as there is no label on them, i don't find a "good way" to select them. The other way could be to make a find all and take a index of the array but i would like to select it with a clear selector.
As data-test is not supported out of the box by RTL, i want to provide a data-testid which is compliant.
I wanted also to migrate the associated test from cypress to RTL but i would like to not change the toolchain on this PR. Currently the test suite is launched by cypress component testing (not jest itself) and we would like to have both tests suite (ct and rtl) the time of the migration or going to migrate all …
=> fix(design-system): add data-testid to InlineEdit

.changeset/stale-needles-think.md, packages/forms/src/UIForm/UIForm.component.js, packages/forms/src/UIForm/lang.js, packages/forms/src/UIForm/utils/validation.js, packages/jsfc/src/lib/validate.js, packages/jsfc/src/lib/validate.spec.js
Firefox & edge -> allows non-integers in an input field with type='integer' with no error message on invalid input
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
validate input value for integer fields
https://jira.talendforge.org/browse/TDOPS-3372
=> fix(TDOPS-3372/taskParams): validate input value for integer fields

.changeset/stupid-knives-cross.md, packages/design-system/src/components/Modal/Modal.module.scss
sync modal header x padding with spec to have aligned content.
Use x padding `xl` instead of `l` 
=> fix(design-system/Modal): sync header x padding with spec

.changeset/warm-ducks-eat.md, packages/components/src/HeaderBar/HeaderBar.module.scss
Following the removal of old scss theme files , one style was missing on the headerbar on hover
=> fix(TDOPS-3399/Components): Fix HeaderBar button style on hover

packages/design-system/package.json, packages/storybook/package.json, packages/storybook/src/design-system/Form/Field/Input/Input.Copy.stories.tsx, packages/storybook/src/design-system/Form/Field/Input/Input.Radio.stories.tsx, packages/storybook/src/design-system/Form/Field/Input/Input.ToggleSwitch.stories.tsx, packages/storybook/src/design-system/Form/Fieldset/FormFieldset.stories.tsx, yarn.lock
Some stories are using `react-hook-form` v7 from a devDependency on the design-system package. We have another version used in the react-forms packages so it's conflicting and breaks some stories. 
And all Talend apps use `react-hook-form` v6 actually because it is imported from react-forms dependecies.
- Go back to `react-hook-form` v6 on all packages
- Move dependency from design-system package to the storybook
=> fix(storybook): fix stories around RHF and downgrade to v6

.changeset/loud-suns-sip.md, tools/scripts-config-storybook-lib/.storybook-templates/preview.js, tools/scripts-config-storybook-lib/index.js
on a current project I do not have react-cmf installed and I try to use storybook.
It fails to start asking for storybook.
This came from the require('./cmf') which happens during compile time.
* remove cmf.js file if no react-cmf installed
* try/catch the require of the file
Note: this is impossible to fix here, so I copy/paste the new file in my project and it now it starts
=> fix(ARCH-669): storybook config without cmf

.changeset/fair-eagles-look.md, .changeset/strong-weeks-pretend.md, .eslintrc.js, package.json, packages/design-system/src/components/WIP/Accordion/Primitive/CollapsiblePanel.tsx, tools/scripts-config-react-webpack/README.md, tools/scripts-config-react-webpack/config/webpack.config.js
Working on a small project I already suffer from huge lag when change a bit of code.
The page is reloaded after 5 to 10 secondes.
Also looking at the index.html page which is generated I found all meta are present twice.
Latest issue I have a cdn folder copied even if I set the option `dynamic-cdn-webpack-plugin` to false.
Also eslint was broken makes it impossible to commit with husky pre commit hook.
* fix eslint config on the repo and the husky config
* Playing with the configuration I have discovered the analytics webpack plugins are the root cause.
unplug them but let them available with just the `--env analyze` flag as they are still usefull.
* Do not copy assets in /cdn if no cdn …
=> fix(webpack): improve performance for dev experience

.changeset/khaki-worms-rest.md, packages/components/src/WithDrawer/withDrawer.module.scss
In some case, when multiple WithDrawer components, the highter one hides its content. This issue only occurs on safari. 
Do not hide WithDrawer overflow
=> fix(TDP-11750): WithDrawer content hidden on safari due to hidden overflow

.changeset/rare-monkeys-try.md, packages/design-system/src/components/Badge/Badge.spec.tsx, packages/design-system/src/components/Badge/button/BadgeButton.tsx, packages/design-system/src/components/Badge/primitive/BadgePrimitive.tsx, packages/design-system/src/components/Badge/variants/BadgeDropdown.tsx, packages/design-system/src/components/Badge/variants/BadgePopover.tsx, packages/design-system/src/components/Dropdown/Dropdown.spec.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/Primitive/DropdownButton.tsx, packages/storybook/src/design-system/Badge/Badge.stories.mdx, packages/storybook/src/design-system/Badge/Badge.stories.tsx
`BadgeDropdown` is uncontrolled, so it does not allow to change the value externally.
Remove the internal state and let it be controlled.
As a bonus, some `data-testid` have been added.
=> feat(TFD-14857): BadgeDropdown is now controlled

.changeset/khaki-moose-deny.md, packages/design-system/src/components/WIP/Popover/Popover.spec.tsx, packages/design-system/src/components/WIP/Popover/Popover.tsx, packages/storybook/src/design-system/Popover/Popover.stories.tsx
Props passed to a popover disclosure where not properly handled like `onClick`
=> fix(TDOPS-3536): Design system fix on popover disclosure props

.changeset/chilly-emus-sit.md, tools/cmf-webpack-plugin/src/index.js, tools/scripts-cmf/cmf-settings.i18n.js, tools/scripts-cmf/cmf-settings.merge.js
cmf-settings write file to disk
webpack in dev mode build output in memory.
current project rely on both so ask webpack to watch dist folder which doesn't make sens.
* add option to cmf-settings to not write file to FS.
* make cmf-webpack-plugin emit RawSource
=> feat(ARCH-662/cmf/settings): do not write settigns to disk

.changeset/curly-squids-wave.md, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/WIP/Tabs/variants/Tabs.tsx
unable to pass data-feature & data-testid to Dropdown items ans Tabs
add new data-feature & data-testid capabilities
=> feat(Tabs&Dropdown): add new data-feature & data-testid capabilities

.changeset/great-oranges-jump.md, tools/scripts-core/src/utils/storybook.js
if you start it require storbyook pakage to be installed
move access into function calls
=> chore(ARCH-662): make storybook optional

.github/workflows/changeset.yml, .github/workflows/pr-demo.yml, .github/workflows/pr-lint.yml, .github/workflows/pr-playground.yml, .github/workflows/pr-test.yml, .github/workflows/visual-testing.yml, .github/workflows/yarn-deduplicate.yml, README.md
current CI continue to run if you push again on same branch which lead to unnecessary work.
lets cancel previous run
=> chore(CI): cancel previous GHA run if push again on the branch

.changeset/warm-tools-live.md, .changeset/wicked-pumpkins-visit.md, tools/scripts-config-storybook-lib/.storybook-templates/msw/mockServiceWorker.js, tools/scripts-config-storybook-lib/package.json, tools/scripts-utils/package.json, yarn.lock
`@talend/scripts-utils` is not public
`@talend/scripts-config-storybook-lib` ask for msw ^0.49.2 but provide a configuration which works with 0.49.0
make scripts-utils it public 
fix msw dep management.
=> fix(ARCH-662/scripts-utils): make it public

package.json, yarn.lock
Same fix as https://github.com/Talend/ui-ee/pull/773
`trim-newlines 1.0.0` has vulnerabilities that are fixed in `trim-newlines 3.0.1`.
```
=> Found "default-browser-id#trim-newlines@1.0.0"
info Reasons this module exists
- "_project_#@talend#notification-center#@storybook#react#@storybook#core#@storybook#core-server#x-default-browser#default-browser-id#meow" depends on it
- Hoisted from "_project_#@talend#notification-center#@storybook#react#@storybook#core#@storybook#core-server#x-default-browser#default-browser-id#meow#trim-newlines"
```
It's fixed in the last minor version of `x-default-browser`.
Add `x-default-browser ^0.5.2` to the resolutions.
**Please check if the PR fulfills these …
=> fix(CVE-2021-33623): Add x-default-browser to resolutions

.changeset/large-planes-pull.md, tools/scripts-config-react-webpack/config/webpack.config.js
meta are not added by html-webpack-plugin if inject is set to false.
add meta in case inject is false
=> fix(ARCH-662/config-webpack): add meta in head if inject is false

.changeset/long-hounds-exercise.md, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.test.js, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.module.scss, packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap
change form hint popover to use DS and be aligned
=> fix(TDOPS-3655): change form hint popover to use DS and be aligned

.changeset/afraid-onions-sleep.md, packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js, packages/forms/stories/json/concepts/hint.json
Forms - UI Form hint can now change position to fixed with a new **overlayIsFixed** parameter
=> fix(TDOPS-3655): UI Form hint can now be position fixed

.changeset/smart-hats-yell.md, packages/storybook/src/design-system/Popover/Popover.stories.tsx, tools/scripts-config-jest/test-setup.js
Popover disclosure in jest test is not rendered
Add the disclosure next to children in the jest mock
=> chore(ARCH-662): add popover disclosure to rendered unit test

.changeset/mean-emus-kneel.md, tools/scripts-config-storybook-lib/.storybook-templates/main.js, tools/scripts-config-storybook-lib/package.json
Current storybook default config do not support the following syntax:
```
import './Component.scss';
```
since with preset we have also removed also the merge of scripts-config-react-webpack this behavior is broken in current project as the scss is imported with css module in mind.
remove scss config from storybook and add our configuration (same as create-react-app)
=> fix(ARCH-658/storybook): add support for import scss file

packages/icons/stories/Icon.tsx
To share icons with pre-sales / other teams, we would like to make the icons downloadable (without having to go to github)
(could be also a link to the icon in github, could be fine for me)
=> doc(icons): allow to download icons on doc

.changeset/khaki-jars-juggle.md, packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js
Faceted search will trigger onSubmit too often especially on component creation 
And badges don't get updated when definition changes for values and operator
=> fix(TDOPS-421/facetedsearch/Badge): check if value has changed before setState

.changeset/dry-impalas-bow.md, packages/components/src/VirtualizedList/ListTable/ListTable.component.js, packages/components/src/VirtualizedList/RendererSelector.component.js, packages/components/src/VirtualizedList/VirtualizedList.component.js
- ReactVirtualized table list has a fixed height
- Added parameters to allow the developer to choose between controlling the height of the table list manually or let ReactVirtualized dependency handle it
=> fix(TDP-11751): VirtualizedList allowing height control

.changeset/young-poets-cheer.md, packages/design-system/src/components/Modal/Modal.spec.tsx, packages/design-system/src/components/Modal/Modal.tsx, packages/storybook/src/design-system/Modal/Modal.stories.tsx
Modal could not have footer for blocking modal
https://www.figma.com/file/0Jolh2prAAdfO5224n3OU3/Modal?node-id=0%3A43&t=jC711zj8e1yDtQDu-1
Use the current prop to display or not the cancel button
=> feat(design-system): Modal with no close button

.github/workflows/pr-test.yml
we do not have coverage report in pr
add it
=> test(ARCH-658): add coverage report

.changeset/strong-adults-divide.md, packages/containers/src/HeaderBar/HeaderBar.connect.js, packages/containers/src/HeaderBar/HeaderBar.test.js
TypeError: Assignment to constant variable.
=> fix(container): header bar assignment error

.changeset/clean-grapes-invite.md, tools/scripts-publish-local/package.json, tools/scripts-publish-local/src/cmd.js, tools/scripts-publish-local/src/git.js, tools/scripts-publish-local/src/npm.js, tools/scripts-publish-local/src/verdaccio.js, yarn.lock
request 2.88.0 in Talend/​ui/​tools/​scripts-publish-local. Comes from verdaccio 5.20.1. There is no fixed version
* use npx so verdaccio is installed in its latest version only if the script is used
=> fix(ARCH-662): request security issue

.changeset/ninety-walls-lay.md, packages/cmf/src/mock/provider.js, packages/cmf/src/mock/rtl.js, packages/containers/src/HeaderBar/HeaderBar.test.js, packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
we have no easy to use API to use RTL with CMF.
Let's add the API
=> feat(ARCH-662/CMF): provide API for RLT

.changeset/four-eyes-draw.md, packages/design-system/src/components/Button/Primitive/ButtonStyles.module.scss, packages/storybook/src/design-system/Button/Button.stories.tsx
=> fix(design-system): Button style while compacted by parent layout

.changeset/happy-snakes-grab.md, packages/utils/src/date/index.ts
Tests are failing without the export of individual date generator util function
export dateUtil generator functions
=> fix(TDOPS-4043/dateUtils): export dateUtil generator functions

packages/storybook/src/design-system/Icon/SizedIcon.stories.tsx
The possibility to use the icon prop is not describe in the documentation
Add the doc for this purpose
=> doc(design-system): color option  for the icon

.changeset/stupid-bears-march.md, packages/cmf-cqrs/src/index.ts, packages/cmf-cqrs/src/useWebSocket.hook.test.ts, packages/cmf-cqrs/src/useWebSocket.hook.ts
We can only pass a denylist to useWebsocket while passing a function to filter the even we want to have would be a better API for this hook.
=> feat(cmf-cqrs): useWebsocket & filter the events

.changeset/eleven-weeks-begin.md, packages/design-system/src/components/Modal/Modal.module.scss, packages/design-system/src/components/WIP/Drawer/variants/FloatingDrawer/FloatingDrawer.module.scss
Modal have an elevation of 4.
Drawer have an elevation of 16.
But when you have a Drawer displayed, and open a Modal, the modal backdrop is under the Drawer, which is not expected.
Update the elevation as follow :
- Modal => 8
- Drawer => 4
- Tooltips => 16 (not modified)
=> fix(TFD-15547): Drawer is under Modal

.changeset/honest-icons-laugh.md, packages/a11y/package.json, packages/cmf-cqrs/package.json, packages/cmf-router/package.json, packages/cmf/package.json, packages/components/package.json, packages/containers/package.json, packages/dataviz/package.json, packages/faceted-search/package.json, packages/flow-designer/package.json, packages/forms/package.json, packages/sagas/package.json, packages/stepper/package.json, packages/storybook-cmf/package.json, tools/scripts-config-jest/package.json
We are working hard to rewrite all tests using RTL.
We don't want to block project to move forward.
Unlock react 18, but know the following libraries are not testing against react 18
=> feat(ARCH-482): remove react < 18.0.0 from peerdep

.changeset/clever-coats-wonder.md, packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js, packages/forms/src/UIForm/fields/NestedListView/NestedListView.utils.js
Nested list in forms expands by default
Expand list based on the schema options
=> fix(TDOPS-4264/NestedList): expand list based on the schema options

.changeset/quiet-goats-cough.md, packages/dataviz/src/index.ts
This PR adds `ChartEntry` to `dataviz` exported types to avoid deep imports on other packages like:
```
import { ChartEntry } from '@talend/react-dataviz/lib/components/BarChart/barChart.types';
```
=> chore: add ChartEntry to dataviz exported types

.changeset/fluffy-pillows-wink.md, packages/http/src/config.test.ts, packages/http/src/csrfHandling.ts, packages/http/src/http.common.test.ts, packages/http/src/http.common.ts, packages/http/src/http.constants.test.ts
Improve @talend/http code covering percentage
Add unit tests
=> chore(http): Improve code covering

.changeset/lucky-lemons-jam.md, packages/design-system/src/components/Status/Primitive/Status.module.scss, packages/design-system/src/components/Status/Status.tsx, packages/design-system/src/components/WIP/Accordion/Accordion.cy.tsx, packages/design-system/src/components/WIP/Accordion/Primitive/CollapsiblePanel.tsx, packages/design-system/src/components/WIP/Accordion/Primitive/CollapsiblePanelHeader.module.scss, packages/design-system/src/components/WIP/Accordion/Primitive/CollapsiblePanelHeader.tsx, packages/storybook/src/design-system/Accordion/Accordion.stories.mdx, packages/storybook/src/design-system/Accordion/Accordion.stories.tsx
Adding the status variant to an Accordion header instead of simple string title
Figma:
- https://www.figma.com/file/o8mVcWTKrRF99ze5Y59r3C/Control-Flows?type=design&node-id=2236-62870&t=UsV5THoQtIjRLffH-0
- https://www.figma.com/file/CDfr4jLz1m6Ud2RNi4qpQJ/Accordion?type=design&node-id=2006-49458&t=C94f4Sg0w7YXIpOV-0
Add an optionnal status property that takes variant values ('successful', 'failed', 'inProgress', 'warning', 'canceled')
=> feat(TFD-15534): Add status to accordion header

.changeset/thin-hairs-flow.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
Not having a custom attributes on the faceted basic search component
Adding a parameter to pass custom attributes to the faceted basic search component
=> chore: Added custom attributes to the faceted basic search

.changeset/fluffy-forks-argue.md, packages/design-system/src/components/Badge/variants/BadgeDropdown.tsx
Not having a data attributes on the BadgeDropdown component
Extending the DataAttributes interface to allow those attributes to be passed forward
=> chore: added data attributes to the BadgeDropdown component

.changeset/thick-parrots-attend.md, tools/scripts-config-react-webpack/config/webpack.config.js
We need to build a webapp with publicPath: 'auto'.
With the base tag forced this is not possible
Do not add a base tag if we are not in CDN mode.
AKA: remove any fancy things if no CDN
=> feat(ARCH-702): support publicPath: auto

.changeset/fixme-again-foo.md, packages/forms/src/UIForm/fields/Toggle/displayMode/TextMode.component.js
during rewrite of tests with have this jest unmock in runtime code :facepalm: 
remove it
=> fix(ARCH-458/forms): remove jest from TextMode.component.js

.github/workflows/changeset.yml, .github/workflows/dependencies.yml, .github/workflows/design-system-component-testing.yml, .github/workflows/icons.yml, .github/workflows/pr-demo.yml, .github/workflows/pr-lint.yml, .github/workflows/pr-playground.yml, .github/workflows/pr-test.yml, .github/workflows/surge-cleanup.yml, .github/workflows/tests-cron.yml, .github/workflows/visual-testing.yml, .github/workflows/yarn-deduplicate.yml
nodejs 16  end of life [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/)
upgrade to node 18
=> chore(ARCH-658): upgrade nodejs

.changeset/popular-icons-agree.md, tools/scripts-core/src/scripts/build-lib.js
Currently build lib is not compatible with yarn v3.6.0
Change a bit the code to use npx instead of try to access to the binary of babel or tsc)
=> fix(script-core/build-lib): make it compatible with yarn v3.6.0

.changeset/violet-suns-relate.md, tools/scripts-config-cdn/cdn.js, tools/scripts-config-cdn/package.json, yarn.lock
yarn.lock file change between v1 and v3
With v3 we need to use fonction to read yaml
Make the code compatible with v1 and v3
=> fix(script-config-cdn): make it compliant with yarn v3.X

.changeset/good-radios-push.md, packages/http/src/config.test.ts, packages/http/src/config.ts, packages/http/src/http.common.ts, packages/http/src/index.ts
We don't have a global interceptor stuff yet
For some use cases, it could be nice to handle some behaviour at only one place, like logout for instance
Add a local context to http package
=> feat(http): add global interceptors

.changeset/grumpy-baboons-breathe.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/QuickSearchInput/QuickSearchInput.component.js, packages/faceted-search/stories/facetedSearch.stories.js
Faceted search configurable quick search min length
=> feat(TDOPS-4704): faceted search configurable quick search min length

.changeset/red-readers-leave.md, packages/design-system/src/components/RichRadioButton/RichRadioButton.component.tsx
Radio card "checked" attribute only saves the initial "checked" value in the DOM, making it difficult for automated tests to understand which card is selected.
Added data-checked attribute so automated tests can select the checked card
=> feat(tdc-7258): added data-checked attribute 

.changeset/five-files-join.md, packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js, packages/faceted-search/src/components/QuickSearchInput/QuickSearchInput.component.js, packages/faceted-search/stories/facetedSearch.stories.js
Allow faceted search configurable input text length
=> feat(TDOPS-4704): faceted search configurable input text length

.changeset/pink-llamas-cheer.md, packages/design-system/src/components/Stepper/Progress/variations/Progress.horizontal.module.scss, packages/design-system/src/components/Stepper/Progress/variations/Progress.vertical.module.scss, packages/design-system/src/components/Stepper/Step/Primitive/Step.module.scss, packages/design-system/src/components/Stepper/Stepper.cy.tsx, packages/design-system/src/components/Stepper/Stepper.tsx, packages/storybook/src/design-system/Stepper/Stepper.stories.mdx
Stepper's progress was not being updated as the user moved to the next step
Added a parameter to control which is the active step allowing the progress to be according to where the user is 
=> feat(TDC-7254): Stepper progress updating according to current step

.changeset/fast-hornets-run.md, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx, packages/design-system/src/components/InlineEditing/variations/InlineEditing.textarea.cy.tsx
Design System to allow maxlength on InlineEdit field
=> feat(TDOPS-4682): Design System to allow maxlength on InlineEdit field

.changeset/orange-lobsters-poke.md, packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js, packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.test.js
Forms checkbox widget can disable a single value in list
=> feat(TDOPS-4687): checkbox widget can disable a single value in list

.changeset/shaggy-islands-grow.md, packages/storybook/.storybook/preview.js, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
we are using tokens more and more but the storybook config do not let us change it.
add it as a feature of the configuration
Result:
=> feat(ARCH-720): add storybook toolbar for DS tokens

.changeset/hungry-parrots-mate.md, packages/components/src/List/ListComposition/Toolbar/ListToolbar.module.scss, packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.module.scss, packages/components/src/List/Toolbar/Toolbar.module.scss, packages/components/src/Rich/Layout/RichLayout.module.scss, packages/components/src/VirtualizedList/ListTable/ListTable.module.scss, packages/components/src/VirtualizedList/RowLarge/RowLarge.module.scss
[Fix List colors taken from tokens
](https://jira.talendforge.org/browse/TDOPS-4856)
- **$coral-color-neutral-border** replaced with **$coral-color-neutral-border-weak**
=> fix(TDOPS-4856): List colors used from DS tokens

.changeset/quiet-pens-boil.md, packages/dataviz/tsconfig.build.json, packages/dataviz/tsconfig.json
`Could not find a declaration file for module '@talend/react-dataviz'` since the 3.0 
fix tsconfig
=> fix(dataviz): bundle typings

.changeset/large-carpets-film.md, packages/components/src/SubHeaderBar/SubHeaderBar.component.js, packages/components/src/SubHeaderBar/SubHeaderBar.module.scss, packages/components/src/SubHeaderBar/SubHeaderBar.test.js, packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap, packages/containers/src/SubHeaderBar/SubHeaderBar.test.js, packages/containers/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
Icons are in a strong black mode
=> fix(components): accent color in subheader actions

.changeset/tiny-paws-build.md, tools/scripts-core/src/scripts/build-lib.js
Since TMC is a monorepo, it's not possible to build it on windows.
See https://jira.talendforge.org/browse/TDOPS-4938
Add `shell: true` in the options of the `spawn` command when using windows to force the use of a shell.
See: https://nodejs.org/api/child_process.html#child_processspawncommand-args-options
=> fix(TDOPS-4938): force windows to use a shell

.changeset/shy-baboons-argue.md, packages/components/src/FormatValue/FormatValue.module.scss
Format value with whitespace was a bit too dark compared to previous value so we use a lighter token.
before
after
=> fix(TDP-12557): use lighter gray for format value whitespace

.changeset/lucky-jobs-flash.md, packages/components/src/HeaderBar/HeaderBar.module.scss
use elevation token for headerbar
=> fix(ARCH-720): use elevation token for headerbar

.changeset/serious-shrimps-obey.md, packages/components/src/FilterBar/FilterBar.component.js, packages/components/src/FilterBar/FilterBar.module.scss, packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
Fix FilterBar in VList having wrong style on hover
=> fix(TDOPS-5081): fix FilterBar in VList having wrong style on hover

.changeset/five-balloons-tell.md, packages/forms/package.json, yarn.lock
we have pinned ace-builds but not react-ace.
=> fix: react-ace

.changeset/green-cars-mate.md, packages/components/src/VirtualizedList/CellLink/CellLink.component.js, packages/components/src/VirtualizedList/CellLink/CellLink.test.js, packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
VList can handle data attributes for Link column
=> fix(TDOPS-4488): VList can handle data attributes for Link column

.changeset/olive-eyes-brake.md, packages/theme/src/theme/_guidelines.scss
The notification is covered by detail drawer.
https://jira.talendforge.org/browse/TDOPS-5103
The z-index of notification is `16`, so update the z-index of $drawer-z-index so that its value is slightly smaller than 16
=> fix(TDOPS-5103): Fix the notification is covered by detail drawer

.changeset/wicked-points-cough.md, packages/components/src/Layout/Layout.component.js
Add a theme props to Layout component so that the parent app can directly send it to the theme provider
=> feat(TDOPS-5212): Components - Add a theme props to Layout component

.changeset/hungry-beers-clap.md, packages/components/src/Badge/Badge.module.scss
Components badge separator now has the right color
=> fix(TDOPS-5105): Components badge separator now has the right color

.changeset/silver-feet-exercise.md, packages/flow-designer/src/reducers/flow.reducer.test.ts, packages/flow-designer/src/reducers/flow.reducer.ts
Fix 'TypeError: node.getNodeType is not a function' error when using flowDesignerReducer with portActions
Fix the typo
=> fix(TFD-15974): Fix calculate port position with portId action

.changeset/dirty-geckos-eat.md, packages/faceted-search/src/components/Badges/BadgeDate/__snapshots__/BadgeDate.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeNumber/__snapshots__/BadgeNumber.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js, packages/faceted-search/src/components/Badges/BadgeOverlay/__snapshots__/BadgeOverlay.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeSlider/__snapshots__/BadgeSlider.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap, packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
This PR enforces always showing the tooltip for the faceted badge overlay. As it is implemented at the moment, we only show the tooltip if there's an icon on the overlay. However, [in this ticket](https://jira.talendforge.org/browse/TDP-12538) we are facing the challenge of truncating the overlay text and present the full text to the user using the tooltip. (check image below) 
=> chore(TDP-12538): always show tooltip on faceted badge overlay

.changeset/smooth-dodos-dance.md, packages/faceted-search/src/components/Badges/BadgeMenu/BadgeMenu.module.scss, packages/faceted-search/src/components/Badges/BadgeMenu/BadgeMenuForm.component.js, packages/faceted-search/src/components/Badges/BadgeMenu/BadgeMenuForm.component.test.js
Add "Selected" toggle on BadgeMenu.
- When no item is selected, "Selected" toggle won't display;
- When one item is selected, "Selected" toggle displays, when click on it, only selected item will be shown, and the button label changes to "Show all";
- When click on "Show all", all items will be shown.
[Figma link](https://www.figma.com/file/W99QEz0JcjAOWjVzJxdq7o/TDOPS-4789%3A-Replace-static-filters-with-faceted-search-filters-in-Management-tab?type=design&node-id=1-179&mode=design&t=lX2iHl15lmD1MhU2-0)
=> feat(faceted-search/BadgeMenu): "Show selected" toggle on BadgeMenu

.changeset/silver-crews-smell.md, packages/components/src/Notification/Notification.module.scss, packages/components/src/Notification/Notification.stories.js
Notification container now has a max height to handle long and multiple notifications not overflowing the screen
=> fix(TDOPS-1878): Notification container max height and overflow

.changeset/plenty-ducks-impress.md, packages/components/src/MultiSelect/ItemOption.module.scss
This PR fixes the checkbox mark on `MultiSelect` component. For more information on what's trying to fix please have a look at [this ticket](https://jira.talendforge.org/browse/TDP-12616).
Correct checkbox mark `top` position.
=> fix(TDP-12616): fix checkbox mark style on multi-select

.changeset/spotty-cups-judge.md, packages/components/src/CollapsiblePanel/CollapsiblePanel.module.scss, packages/components/src/CollapsiblePanel/CollapsiblePanel.stories.js
Collapsible panel does not handle the text overflow for all cases in the header.
For example, when you have a simple header with a label and one action, the whole in a very tiny space, you got a multiline label that exit the panel header.
https://jira.talendforge.org/browse/TFD-16296
The goal is to prevent the overflow with a nice ellipsis and the whole text in a tooltip.
A story has been added to show the case in storybook.
=> fix(TFD-16296): Add ellipsis on collapsible panel

.changeset/brave-birds-report.md, packages/http/README.md, packages/http/src/config.test.ts, packages/http/src/config.ts, packages/http/src/http.common.test.ts, packages/http/src/http.common.ts, packages/http/src/http.types.ts
Current interceptors do not have access to request, which is useful in some situation (e.g to intercept only get methods). 
Current interceptors can't identify precisely specific calls (e.g some function send an http request but based on business logic we want to ignore 404 responses on this request to not warn user).
Current interceptors return void so they can't modify the response based on some business logic, or trigger another http call before resolve. 
You can have more information in the readme.
=> feat(TDP-12106): rework http interceptors to access request object and return promise

.github/actions/setup-node/action.yml, .github/workflows/changeset.yml, .github/workflows/dependencies.yml, .github/workflows/design-system-component-testing.yml, .github/workflows/icons.yml, .github/workflows/pr-lint.yml, .github/workflows/pr-playground.yml, .github/workflows/pr-test.yml, .github/workflows/surge-cleanup.yml, .github/workflows/tests-cron.yml, .github/workflows/visual-testing.yml, .github/workflows/yarn-deduplicate.yml
we are on node 18 with a duplicate setup in every workflow
upgrade to node 20 and factorize all that
upgrade github actions behind it
=> chore(CI): upgrade to node 20

.changeset/tender-jokes-join.md, packages/components/src/FormatValue/FormatValue.component.js, packages/components/src/FormatValue/__snapshots__/FormatValue.test.js.snap
When the cell value had leading spaces, they were being replaced by an icon (as intended) but the content was not being returned.
Returned the content along with the whitespace icon when there were leading whitespaces
=> fix(TDC-7364): FormatValue component - fix content not appearing

.changeset/unlucky-cats-fold.md, packages/icons/.storybook/main.js, tools/scripts-config-storybook-lib/.storybook-templates/main.js, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
Currently icons are added multiple times
Fix the issue and use directly icon from talend/icons/dist... instead of unpkg
=> fix(UNTRACKED): chromatic visual non regression

packages/design-system/src/components/Tabs/Primitive/TabPanel.tsx, packages/design-system/src/components/Tabs/Primitive/TabsProvider.tsx, packages/design-system/src/components/Tabs/Tabs.test.tsx, packages/design-system/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, packages/design-system/src/components/Tabs/index.ts, packages/design-system/src/components/Tabs/variants/Tabs.tsx, packages/design-system/src/stories/navigation/Tabs.stories.tsx
Current merged Tabs API need you to import a lot of components:
```javascript
import { Tabs, TabPanel, Tab, TabsProvider } from '@talend/design-system'
```
Simplify by aggregating primitives and add support for previous api:
```javascript
import { Tabs } from '@talend/design-system'
```
=> feat: restore design system Tabs api

.changeset/little-suns-reply.md, packages/components/src/Notification/Notification.module.scss, packages/components/src/Notification/Notification.stories.js
Notification can have long words that will not overflow , see https://jira.talendforge.org/browse/TDOPS-762
=> fix(TDOPS-762): notification can have long words that will not overflow

.changeset/twelve-games-provide.md, packages/design-system/src/stories/form/Field/Input/Password.stories.tsx, packages/forms/src/UIForm/fields/Text/PasswordWidget/index.js, packages/forms/src/UIForm/fields/Text/Text.component.js, packages/forms/src/UIForm/fields/Text/Text.component.test.js, packages/forms/stories/json/fields/core-text.json
The link is missing under a Password field
- link props should be passed instead of React Node 
- an extra import/export of For,.Password removed 
=> fix(TDOPS-5409/forms): Link render below Password/Text field

.changeset/nasty-birds-cheat.md, packages/design-system/src/components/Modal/Modal.module.scss, packages/design-system/src/components/Modal/Modal.test.tsx, packages/design-system/src/components/Modal/Modal.tsx, packages/design-system/src/components/Modal/Primitives/DialogBackdrop.tsx
fix design system modal accessibility as aria-hidden is always true
reduce dom complexity and use aria-modal
=> fix(ARCH-662): fix design system modal accessibility

.changeset/serious-toes-remember.md, packages/design-system/src/components/Form/Field/Input/Input.ToggleSwitch.tsx
ToggleSwitch not working after RHF upgrade
Revert the changes made on ToggleSwitch -> checkbox state change on click
=> fix(TDOPS-5582/designSystem): checkbox state change on click

.github/workflows/dependencies.yml
replace reviewer with @talend/frontend-admins for GHA Upgrade dependencies
=> fix GHA Upgrade dependencies reviewer

.vscode/settings.json
Having the VS code configuration for all TUI packages referring the root .prettierrc.js leads to errors while running prettier in subfolder where there is another .prettierrc.js file.
Only the root one is taken into account and doing it so, the typescript loader is not working in packages like design-system or stepper where typescript is used.
```
["ERROR" - 11:21:53] Error formatting document.
SyntaxError: Unexpected token, expected "," (12:34)
```
Remove the pointer to the root configuration for prettierrc in the vscode configuration
=> fix: prettier configuration for subpackages

.changeset/blue-kings-switch.md, packages/design-system/src/components/Tooltip/Tooltip.cy.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx
fix tooltip display when empty title
=> fix(TDOPS-5671): fix tooltip display when empty title

.changeset/green-drinks-remain.md, packages/components/src/AppGuidedTour/AppGuidedTour.component.js, packages/components/src/AppGuidedTour/AppGuidedTour.stories.js, packages/components/src/GuidedTour/GuidedTour.component.js, packages/components/src/GuidedTour/GuidedTour.module.scss, packages/components/src/GuidedTour/GuidedTour.stories.js, packages/components/src/GuidedTour/README.md, packages/containers/src/GuidedTour/__snapshots__/GuidedTour.test.js.snap
We had no way to track user clicks on guided-tour modal. 
This backward-compatible PR provides a new parameter on `GuidedTour` component : `tourId` to be used in pendo `data-feature` attribute. 
If you pass `tourId="my-tour"` then you'll get access to: 
- `guidedtour.my-tour.last`
- `guidedtour.my-tour.next`
- `guidedtour.my-tour.prev`
To do so I had to pass custom next and previous buttons. I chose design-system ones. 
I've also updated the close button color to match with other buttons. 
Before
After
=> feat(TDP-12694): add pendo trackers to guided-tour actions

.changeset/nine-coats-lie.md, packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx, tools/scripts-config-storybook-lib/.storybook-templates/preview.js
We can't override some specific token using the theme provider
Allow to pass some css variables, for instance :
```
tokensOverride: {
"--coral-color-accent-background-strong": "red"
}
```
=> feat: allow token override with theme provider

.changeset/little-mangos-allow.md, .changeset/tidy-peas-dress.md, tools/scripts-config-cdn/cdn.js, tools/scripts-config-jest/__tests__/utils.test.js, tools/scripts-config-jest/utils.js
=> fix(TDP-12694): jest and cdn script configs broken after pnpm use-case

.changeset/famous-adults-cough.md, packages/design-system/src/components/Message/Primitive/MessagePrimitive.tsx, packages/design-system/src/components/Message/Primitive/MessageStyles.module.scss, packages/design-system/src/components/Message/__snapshots__/Message.test.tsx.snap, packages/design-system/src/stories/messaging/Message.stories.tsx
- The size of a message fit the container width while before, it has a max width of `28rem`
- add a new prop `titleInfo` that allow to display an information message aside the title
- add new prop `additionalIconAction` to allow to display an additional button icon instead (there was only the dropdown action available before)
- rename prop `additionalActions` to `additionalDropdownActions` to make the API more explicit
- remove the shadow on the message to make it more consistent with the rest of the design and integrate better in the page
=> feat: message upgrade

.changeset/flat-maps-dream.md, tools/scripts-config-react-webpack/config/webpack.config.common.js
=> fix: prevent display log of  sass loader warnings

.changeset/bright-laws-shave.md, packages/cmf/package.json, tools/scripts-cmf/package.json
CMF Add missing dependency: commander
=> fix: CMF Add missing dependency: commander

.changeset/curvy-monkeys-act.md, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
There are some translation issues when using directlty the BadgeCheckboxesForm component.
Let's use `useTranslation` in the `BadgeCheckboxesForm.component.js`
=> fix(TDOPS-1186): useTranslation

.changeset/quiet-grapes-speak.md, tools/scripts-core/src/scripts/lint.js
talend-script lint is not working in jenkins
=> fix: talend-script lint is not working in jenkins

.changeset/swift-flies-rescue.md, packages/design-system/src/components/IconsProvider/IconsProvider.module.scss, packages/design-system/src/components/IconsProvider/IconsProvider.tsx
If sr-only class is not loaded in global, the injected icon provider are not visually hidden
=> fix: don't rely on global sr-only classname to hide the icons from the IconsProvider

.changeset/nervous-yaks-repair.md, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js, packages/components/src/VirtualizedList/VirtualizedList.stories.js
=> fix: empty date is not working in CellDateTime

.changeset/dry-donkeys-study.md, tools/scripts-config-react-webpack/config/webpack.config.js
Currently patch for hoistNonReactStatics is only available when app use initiator
Add it also when app not use initiator
=> fix: Add fix for hoistNonReactStatics available when not using dynamic-cdn-webpack-plugin

.changeset/two-fans-taste.md, tools/scripts-config-react-webpack/config/icons.js
webpack can't access to the icons on windows.
Fix the issue with `/` and `\`.
Use `path.join`
=> fix(webpack): getTalendIconsPath

.changeset/perfect-frogs-argue.md, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.js, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.test.js
After upgrade dependency `cldr-dates-full`, in timezone data there's an unexpected key "long" in some zones, for example, Dublin:
```
"Dublin": {
"long": {
"daylight": "Irish Standard Time"
}
} 
```
Need to handle this in TimezoneList component of react-forms. "long" should not be added into timezone name.
=> fix(TDOPS-5889/TimezoneList): fix timezone name

.changeset/kind-games-kneel.md, packages/components/src/SubHeaderBar/SubHeader.stories.js, packages/components/src/SubHeaderBar/TitleSubHeader/SubTitle.component.js, packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.module.scss, packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/SubTitle.test.js.snap
Allow subheader subtitle to display long labels
=> fix(TDOPS-5872): Allow subheader subtitle to display long labels

.changeset/hot-suits-argue.md, packages/components/src/Notification/Notification.module.scss
Notification long messages should break on words and not characters
=> fix(TDOPS-5733): Notification long messages should break on words

.changeset/spotty-coats-admire.md, packages/design-system/src/components/Link/Link.tsx
The prop `hideExternal` doesn't work on Link as it's not passed to Linkable.
Do not destructure `hideExternal` and pass it to `Linkable` in the `rest`.
=> fix(TDOPS-5794): hideExternal on Link

.changeset/dirty-pears-appear.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.module.scss, packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.module.scss
Faceted search container no longer takes more then 100% width
=> fix(TDOPS-5873): Fix faceted search container width

.changeset/long-wasps-switch.md, packages/design-system/src/components/InlineEditing/InlineEditing.test.tsx, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
https://jira.talendforge.org/browse/DFD-563
Add optional prop data-testid as a prefix
=> fix(DFD-563): Add data-testid prefix for inline editing

.changeset/nice-colts-fly.md, packages/containers/package.json, packages/containers/src/ActionIconToggle/ActionIconToggle.stories.js, packages/containers/src/Form/Form.stories.js, packages/containers/src/SelectObject/SelectObject.module.scss, packages/dataviz/package.json, packages/dataviz/src/components/BarChart/ColoredBar/ColoredBar.component.module.scss, packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.module.scss, packages/dataviz/src/components/BarChart/_bar-chart.scss, packages/dataviz/src/components/BoxPlot/BoxPlot.component.module.scss, packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.component.module.scss, packages/dataviz/src/components/GeoChart/GeoChart.module.scss, packages/dataviz/src/components/KeyValueTooltip/KeyValueTooltip.component.module.scss, packages/dataviz/src/components/LineChart/LineChart.module.scss, packages/dataviz/src/components/RangeFilter/RangeFilter.component.module.scss, packages/dataviz/src/components/RangeFilter/handlers/DateTimeRangeHandler/DateTimeInputField.component.module.scss, packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberInputField.component.module.scss, packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberRangeHandler.tsx, packages/design-system/package.json
Remove bootstrap theme from container and dataviz packages
=> chore(TDOPS-5724): remove bootstrap theme from container and dataviz packages

.changeset/sharp-crabs-join.md, packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js, packages/forms/src/UIForm/fieldsets/Array/ArrayItem.module.scss, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
The ArrayItem use the old trash icon, and has a "border" added on the left side that is not useful.
Update to the new trash icon and remove the border.
=> chore(DFD-491): Update ArrayItem styles

.changeset/chilled-bears-speak.md, packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
=> chore: add "section" as an option to the "as" list of possible values 

.changeset/healthy-cobras-allow.md, packages/components/src/ListView/Items/Item/Item.component.js, packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap, packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
Fix ListView checkboxes alignement that had twice the checkbox classname
=> fix(TDOPS-5968): ListView checkboxes alignement

.changeset/serious-bees-worry.md, packages/components/src/HeaderBar/HeaderBar.module.scss, packages/components/src/Layout/Layout.module.scss
Layout and HeaderBar components still use old values for z-indexes.
With the usage of design tokens, some calculations were broken.
Notification center popover has now an empty state, impacted by HeaderBar styles.
Fix the issues 😬 
=> fix(DFD-491): Fix header bar and layout styles

.changeset/late-shirts-jam.md, packages/faceted-search/src/components/Badges/BadgeDate/__snapshots__/BadgeDate.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeNumber/__snapshots__/BadgeNumber.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js, packages/faceted-search/src/components/Badges/BadgeOverlay/__snapshots__/BadgeOverlay.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeSlider/__snapshots__/BadgeSlider.component.test.js.snap, packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap, packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Fix faceted search tooltip and replace it with a title to avoid wrong popover placement
=> fix(faceted-search): replace badge tooltip with a title

.changeset/nice-balloons-flash.md, packages/design-system/src/components/Skeleton/variations/SkeletonSized.tsx, packages/design-system/src/stories/feedback/Skeleton.stories.tsx
The skeleton "sized" variant only allowed for fixed values for the width and height props
Changed the width and height props from number to string so it can height receive fixed or dynamic values
=> chore: changed skeleton "sized" variant props type

.changeset/fast-seahorses-protect.md, packages/components/src/EditableText/InlineForm.component.js, packages/components/src/EditableText/InlineForm.component.test.js, packages/design-system/src/components/InlineEditing/InlineEditing.test.tsx, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx, packages/design-system/src/components/InlineEditing/__snapshots__/InlineEditing.test.tsx.snap, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js, packages/faceted-search/src/components/Badges/BadgeDate/BadgeDateForm.component.js, packages/faceted-search/src/components/Badges/BadgeMenu/BadgeMenuForm.component.js, packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js, packages/faceted-search/src/components/Badges/BadgePeriod/BadgePeriodForm.component.js, packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js, packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js, packages/faceted-search/src/helpers/usage.helpers.js, packages/faceted-search/src/helpers/usage.helpers.test.js, packages/utils/src/getDataAttrFromProps.test.ts, packages/utils/src/getDataAttrFromProps.ts, packages/utils/src/index.ts
add data attributes from props for InlineEdit
https://jira.talendforge.org/browse/TDOPS-5510
=> fix(TDOPS-5510/inlineEdit): add data attributes from props

.changeset/loud-humans-wonder.md, packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
=> fix: sort option not interactive with legacy list while in expanded view

.changeset/cyan-cars-fix.md, packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/Drawer.module.scss, packages/components/src/Drawer/Drawer.stories.js, packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap, packages/components/src/WithDrawer/__snapshots__/withDrawer.test.js.snap
Fix drawer empty footer and remove bootstrap styles
=> fix(Components): fix drawer empty footer and remove bootstrap styles

.changeset/three-jobs-repeat.md, packages/design-system/src/components/Stack/StackItem.module.scss, packages/design-system/src/components/Stack/StackItem.tsx, packages/design-system/src/stories/layout/Stack.stories.tsx
Allow StackItem to have a isFullWidth option
=> feat(DS): Allow StackItem to have a isFullWidth option

.changeset/swift-parents-type.md, packages/design-system/src/components/Form/Field/Textarea/Textarea.tsx
fix textarea color when on error
=> fix(DS): fix textarea color when on error

.changeset/cuddly-files-pump.md, packages/components/src/List/List.component.js, packages/components/src/List/List.module.scss, packages/components/src/List/__snapshots__/List.test.js.snap
=> fix: element overlapping box shadow in large mode for the list

.changeset/three-books-join.md, packages/dataviz/src/components/GeoChart/GeoChart.component.tsx
Colors defined as css var exported from scss are not correctly parsed in javascript - this makes the chart black.
Convert css variable into css color expression that can be passed to D3 rgb function.
=> fix(TDP-12810): fix GeoChart colors

.changeset/lovely-bulldogs-accept.md, packages/design-system/src/components/Form/Affix/variations/AffixButton.tsx, packages/design-system/src/components/Form/Affix/variations/AffixSelect.tsx, packages/design-system/src/components/Form/Primitives/Input/Input.tsx, packages/design-system/src/components/Form/Primitives/InputWrapper/InputWrapper.tsx, packages/design-system/src/components/Form/Primitives/Select/SelectNoWrapper.tsx
No datatest-id at all
Add it from a props
=> feat(DFD-632): AffixSelect data-testid

.changeset/good-planes-scream.md, packages/design-system/src/components/Form/Primitives/Select/SelectNoWrapper.tsx
Select component should handle required attribute
=> fix(DS): Select component should handle required attribute

.changeset/four-islands-brake.md, packages/design-system/src/components/Stack/Primitive/StackPrimitive.test.tsx, packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
=> chore: add data-test attr on stacks

.changeset/thin-nails-search.md, packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
=> fix: make checkbox badge with values work again (without fetching the tags all the time)

.changeset/smart-crews-beam.md, packages/utils/package.json
Lodash is still loaded all along with the current babel build
Let's move to typescript as this package is in typescript
=> fix: build process to use TypeScript instead of Babel

.changeset/orange-fishes-walk.md, packages/design-system/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/design-system/src/components/Loading/Loading.tsx, packages/design-system/src/components/Loading/__snapshots__/Loading.test.tsx.snap
fix design system loading icon on safari browser
=> fix(TMC-26227): fix design system loading icon on safari browser

.changeset/wise-owls-sing.md, packages/jsfc/src/validate.js, packages/jsfc/src/validate.test.js
Fix input number validation to display correct error msg
=> fix(TMC-27327): Fix input number validation to display correct error msg

.changeset/blue-frogs-rush.md, packages/design-system/src/components/Accordion/Accordion.cy.tsx, packages/design-system/src/components/Accordion/Primitive/CollapsiblePanel.tsx, packages/design-system/src/components/Accordion/Primitive/CollapsiblePanelHeader.tsx, packages/design-system/src/stories/navigation/Accordion.mdx, packages/design-system/src/stories/navigation/Accordion.stories.tsx, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
This PR updates `CollapsiblePanel` to support multiple actions passed as prop instead of just one.
For more info: https://jira.talendforge.org/browse/TUX-1228
Update the component props and their type.
=> chore(TUX-1228): update CollapsiblePanel to support multiple actions

.changeset/quick-bugs-exercise.md, packages/components/src/ObjectViewer/JSONLike/JSONLike.module.scss, packages/components/src/ObjectViewer/List/List.module.scss, packages/components/src/ObjectViewer/Table/Table.module.scss
Fix JSON object viewer style on safari with word-break
=> fix(TMC-26238): Fix JSON object viewer style on safari with word-break

.changeset/quick-jeans-allow.md, packages/design-system/src/components/Accordion/Primitive/CollapsiblePanelHeader.tsx, packages/design-system/src/components/Accordion/Primitive/types.ts
Actions passed to `CollapsiblePanel` which are used in the header, have very limitative props (`callback`, `icon`, `tooltip`) making it impossible to pass props like `id`, `data-feature` and so on.
=> fix(TUX-1228): allow more props to be passed to each CollapsiblePanel action

.changeset/poor-grapes-tie.md, packages/design-system/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/design-system/src/components/Loading/Loading.tsx, packages/design-system/src/components/Loading/__snapshots__/Loading.test.tsx.snap, packages/design-system/src/stories/feedback/Loading.stories.tsx
=> feat(TDP-12824): Design system Loading to have defined size available

.changeset/wet-flowers-beg.md, tools/scripts-config-jest/test-setup.js
Avoid warning spam when mocking missing lib for jest
=> fix(jest-config): avoid warning spam when mocking missing lib for jest

.changeset/lucky-spiders-fix.md, .changeset/wet-badgers-turn.md, packages/components/src/Drawer/Drawer.module.scss, packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.module.scss
fix small styling issues 
- components Drawer z-index overlapping with headerbar
- add gap to TextModeArrayTemplate from UI-Form
=> fix: fix small styling issues on Drawer and UI-Form TextModeArrayTemplate

.changeset/fifty-rocks-fly.md, packages/design-system/src/components/Form/Primitives/Field/Field.tsx, packages/design-system/src/components/InlineMessage/Primitive/InlineMessagePrimitive.tsx
Transmit DS Field data-test attributes to related description
=> feat(DS): transmit DS Field data-test attributes to related description

.changeset/wicked-balloons-sell.md, packages/design-system/src/components/Tooltip/Tooltip.tsx
Flashing tooltip on some approach gestures
https://jira.talendforge.org/browse/DFD-914
See internal floating portal issue: 
https://github.com/floating-ui/floating-ui/issues/2435
=> fix(DFD-914): Fix flashing tooltip on some gesture

.changeset/metal-horses-attend.md, packages/components/src/ActionBar/ActionBar.component.js, tools/eslint-plugin/src/rules/use-bootstrap-class.js, tools/eslint-plugin/tests/src/rules/use-bootstrap-class.test.js, tools/scripts-config-eslint/.eslintrc.json
We want to remove bootstrap form our codebase.
We identify usage by hand so we may miss usages.
Start by adding eslint rule to track classnames call with bootstrap in arguments
=> feat(eslint): warning on bootstrap class

.changeset/neat-queens-film.md, packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap, packages/containers/src/Form/__snapshots__/Form.test.js.snap, packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap, packages/forms/src/UIForm/fields/Text/Text.component.js, packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Columns/__snapshots__/Columns.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Fieldset/__snapshots__/Fieldset.component.test.js.snap, packages/forms/src/UIForm/fieldsets/Tabs/__snapshots__/Tabs.component.test.js.snap
Fix missing `aria-describedby` attribute after upgrading  `@talend/react-forms` to `14.0.1` , this causes some unit test of Rule fail in the UI-EE repo.
=> fix(TDS-7317): fix missing aria-describedby attribute

.changeset/yellow-melons-double.md, packages/components/src/DateTimePickers/shared/error-messages.js
fix wording on date range error message
=> fix(TMC-27480): fix wording on date range error message

.changeset/thin-apes-tie.md, packages/design-system/src/components/Dropdown/Dropdown.test.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/Primitive/DropdownLink.tsx, packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Dropdown link item to accept "as" property using RouterLink
=> fix: Dropdown link item to accept "as" property using RouterLink

.changeset/neat-games-juggle.md
a change has been done in script-config-jest on this PR without a correct changeset: https://github.com/Talend/ui/pull/5272/files#diff-8410d00747d7736cab28dfc962dc3dc3b982118a5b57ef81da9a91be5dd88633
this PR will add it
=> fix(TMC-27845): add missing changeset for script-config-jest

.changeset/fast-eels-sell.md, packages/design-system/src/components/Form/Field/Select/Select.tsx
TDS, semantic form, user has to click on select field twice to open dropdown.
It's caused by select element being recreated rather than updated on every change.
https://www.loom.com/share/1dbb5105d15b46f6a40df068bd5b0107?sid=c91a10f7-43ba-45dc-ae6f-3f27f61c5ef0
Move `SelectField` component definition out of Select.
=> Fix(TDS-7331/forms): Select field being re-created instead of updated

.changeset/warm-scissors-judge.md, fork/json-schema-form-core/package.json, fork/json-schema-form-core/webpack.config.js
path-browserify has been added by mistake in json-schema-form-core
like other packages set the config to false
=> fix(TMC-28189): remove wrong config in json-schema-form-core

.changeset/dirty-elephants-dream.md, packages/forms/src/UIForm/fields/Text/Text.component.js
When editing a variable name for a rule, after the input component loses the focus, the page crashes and shows the error: `the onFinish is not a function`
Checking the `onFinish` and `onChange` func before invoking it.
=> fix(TDC-7476/form): check onFinish and onChange before invoking for the Text component

.changeset/slimy-tigers-bow.md, packages/components/src/DateTimePickers/shared/error-messages.js
There is an issue within TDS where switching the application's language from English to French does not update the error messages for the date range field accordingly. 
This problem arises because react-components are initialized in App loading page, and the `getDefaultT()` function is invoked at the global level, which leads to the creation of a distinct i18next instance separate from the one used by TDS.
The invocation of `getDefaultT()` has been deferred, ensuring that it is called only when required, rather than at the global scope during initial loading. As a result, when getDefaultT() is eventually called, it accesses the fully initialized i18next instance instead creating its own. …
=> fix(TDS-7339/Date): Language switch does not update Date Field error messages

.changeset/metal-plants-hear.md, packages/design-system/src/components/RatioBar/RatioBar.module.scss
Quality Bar line too thick
Revert change here: https://github.com/Talend/ui/commit/8bf0dd56f6950de2a9d6b31e31323902e5cd3ad8#diff-82768ed6cf399b1b75fb523ba86d9881a330198170a872110b4514b2d2ec9a0aL6
should be a mistake.
=> fix(TDS-7338/QualityBar): fix bar line height

.changeset/eleven-moles-perform.md, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js, packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.test.js
When the values are changed in EnumerationForm, it doesn't use the newest value to run the validation
https://jira.talendforge.org/browse/DGT-307
Using the new values instead of old value to validate.
=> fix(DGT-307/form):  fix EnumerationForm doesn't use the newest value to validate value

.changeset/large-apes-compare.md, packages/components/src/AppGuidedTour/AppGuidedTour.component.js, packages/components/src/AppGuidedTour/AppGuidedTour.test.js
When closing Guided Tour, the latest step is temporarily changing to 1st step
https://jira.talendforge.org/browse/TDC-7452
Stay on the last page when clicking "Let me try" button.
=> fix(TDC-7452/Tour): Fix tour is changing to first step when closing

.changeset/many-camels-agree.md, packages/design-system/src/components/QualityBar/QualityRatioBar.utils.ts
QualityBar percentages being rounded to 0
Setting a minimum value so that the percentage for invalid and empty values are not 0%
=> fix(DGT-528): Fix the rounding issue of QualityBar percentages

.changeset/tasty-bikes-fix.md, packages/components/src/AppGuidedTour/AppGuidedTour.component.js
When the tour is reopened, the value of `currentStep` is not reset to 0.
This bug is caused by this [PR](https://github.com/Talend/ui/pull/5311) ,this fix reset the currentStep to 0 when tour is reopened again.
https://jira.talendforge.org/browse/TDC-7496
=> fix(TDC-7496/tour): Reset currentStep to 0 when tour is reopened

.changeset/warm-pumas-grin.md, packages/design-system/src/components/ThemeProvider/ThemProviderWithoutGlobals.tsx, packages/design-system/src/components/ThemeProvider/ThemeProviderWithoutGlobals.tsx, packages/design-system/src/components/ThemeProvider/index.ts
=> feat: add ThemeProvider that don't use globals

.changeset/five-ears-guess.md, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js, packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
Dates are incorrectly displayed during the DST window for few regions
https://jira.talendforge.org/browse/TMC-27619
Allow tz conversion based upon the sourceTz for cells in List pages
=> fix(TMC-27619/cellDate): enable tz conversion with sourceTz

.changeset/wicked-hotels-thank.md, packages/faceted-search/package.json
not possible to import files not named index.js when import go deeper in lib folder
adapt package config for faceted-search (change exports for lib folder)
=> fix(TMC-28189): adapt package config for faceted-search

.changeset/purple-poets-tan.md, fork/react-bootstrap/package.json, packages/icons/package.json
After running `postinstall` on ui-ee, there is no `lib-esm` folder for `@talend/react-bootstrap` and `@talend/icons` packages, this causes  `Module not found` error when running upgrade dependencies 
https://jira.talendforge.org/browse/TDS-7385
=> fix(TDS-7385/esm): fix module not found error for @talend/react-bootstrap and @talend/icons

.changeset/seven-boats-battle.md, packages/containers/tsconfig.esm.json, packages/containers/tsconfig.json
containers package only have an index.d.ts file containing compiler options instead of real things
adapt the ts configuration to correctly build with right declaration files
=> fix(containers): Fix tsconfig to have right d.ts files

.changeset/green-geckos-sip.md, packages/components/package.json, packages/containers/package.json, packages/design-system/package.json, packages/utils/package.json
Exports doesn't allow deep imports, but app are using them.
Use a wildcard to allow all deep imports.
=> fix: Fix exports to allow deep imports

.changeset/chilled-files-rest.md, packages/components/src/TabBar/Tabs.stories.js, packages/components/src/Tag/Tag.component.js
Beta tag is not available under the Tag component
add beta styled tag to the Tag component
=> feat(TMC-28838/tags): add beta styled tag to the Tag component

.changeset/honest-clouds-think.md, tools/scripts-core/src/scripts/build-lib.js
Allow Talend script to build .css files
=> fix(TMC-28977): Allow Talend script to build .css files

.changeset/fluffy-colts-sleep.md, packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js, packages/faceted-search/src/components/QuickSearchInput/QuickSearchInput.component.js, packages/faceted-search/stories/facetedSearch.stories.js
Now you can pass typeahead props to QuickSearchInput.
One use case can be loading async suggestions.
Story: http://5367.talend.surge.sh/storybook-one/?path=/story/faceted-search-main--with-quick-search-asynchronous-suggestions
=> feat(FacetedSearch): Add Typeahead props to QuickSearchInput

.changeset/large-hotels-nail.md, tools/eslint-plugin/src/rules/use-bootstrap-class.js
Improve bootstrap classes warning for eslint
=> chore(eslint): improve bootstrap classes warning for eslint

.changeset/itchy-onions-refuse.md, packages/containers/src/ComponentForm/kit/index.js
Some project need to use some functions from the defaultRegistry. 
Export them to be able to reach them with a `ComponentForm.kit.defautRegistry`
=> fix(containers): Expose defaultRegistry through ComponentForm.kit

.changeset/eighty-dryers-itch.md, packages/components/src/DateTimePickers/DateTimeRange/Manager/Manager.component.js, packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.test.js
InputDateTimeRangePicker component gets wrong error message for multiple errors.
To reproduce:
1.Init component with start time and end time, there is no error message.
2. Remove the date from date field for the end time, it shows "Date is required", it is ok.
3. Remove the time from time field for the start time, it shows "Time is required", it is ok.
4. Refill the time field for the start time, it shows "Start date should comes before end date", it should show the remaining error "Date is required".
=> fix(DGHT-180): fix InputDateTimeRangePicker gets wrong error message for multiple errors

.changeset/thick-peas-rest.md, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Change InlineEdit tooltip position on buttons to prevent z-index issues depending on implementation
=> fix(TMC-29525): inlineedit tooltip position on subheader

.changeset/strange-students-collect.md, tools/scripts-config-eslint/.eslintrc.json
currently the ignorePattern ignore all index.js instead of only at root level
fix it using ./
=> fix(eslint-config): ignorePattern only at root level for index.js

.changeset/hot-kiwis-talk.md, packages/containers/src/SidePanel/SidePanel.connect.js
After migrating TMC from sub domain to new domain app.int.cloud.talend.com/tmc, it uses basename (/tmc)
In order to open Side panel links in new browser window correctly, need to include base name in "href",
as it is passed down to link element in html, so, having something like "/tmc/projects".
But if using base name in href, selected item is not computed correctly, as base name is always added, so, we end up
with something like "/tmc/tmc/projects", and, selected item is not highlighted
https://jira.talendforge.org/browse/TMC-29660
https://jira.talendforge.org/browse/TMC-29799
- Add base name to href in actions
- When computing selected item, add base name only if it is not already in …
=> fix(TMC-29799): highlighting selected item in side panel and opening link in new tab

.changeset/fuzzy-dancers-move.md, packages/design-system/src/components/Form/Primitives/Textarea/Textarea.module.scss, packages/design-system/src/components/Form/Primitives/Textarea/Textarea.tsx, packages/design-system/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/design-system/src/stories/form/Field/Textarea/Input.Textarea.stories.tsx
fix DS textarea row property and static css height
remove css min-height 
put default textarea with 3 rows to match old css value
=> fix(TMC-25993): fix DS textarea row property and static css height

.changeset/shiny-mirrors-fail.md, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js, packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
Change default UIForm collapsible panel title to use schema title by default
=> feat(TMC-25993): change default UIForm collapsible panel title

.changeset/purple-mails-run.md, packages/design-system/src/components/StatusBubble/Primitive/StatusBubblePrimitive.module.scss, packages/design-system/src/components/StatusBubble/Primitive/StatusBubblePrimitive.test.tsx, packages/design-system/src/components/StatusBubble/Primitive/StatusBubblePrimitive.tsx, packages/design-system/src/components/StatusBubble/StatusBubble.tsx, packages/design-system/src/components/StatusBubble/index.ts, packages/design-system/src/components/StatusBubble/variations/StatusBubbleBeta.tsx, packages/design-system/src/components/StatusBubble/variations/StatusBubbleError.tsx, packages/design-system/src/components/StatusBubble/variations/StatusBubbleInformation.tsx, packages/design-system/src/components/StatusBubble/variations/StatusBubbleSuccess.tsx, packages/design-system/src/components/StatusBubble/variations/StatusBubbleWarning.tsx, packages/design-system/src/index.ts, packages/design-system/src/stories/feedback/StatusBubble.mdx, packages/design-system/src/stories/feedback/StatusBubble.stories.tsx, packages/forms/src/UIForm/fields/Date/DateTime.component.test.js, packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.test.js
Implement Status bubble component
Figma Design - https://www.figma.com/design/hMYM9HGXajJpWdGwRb5ITR/branch/DmxDVcxaHYID3NsHwznCRF/Coral?node-id=128-1788&node-type=frame&t=B062rscYn1FRFLMv-0 
=> feat(TMC-2505/webapp): implement status bubble component

.changeset/eight-worms-clean.md, .changeset/tricky-cobras-fold.md, package.json, packages/cmf-router/package.json, packages/cmf/package.json, packages/cmf/src/matchPath.js, packages/containers/package.json, packages/containers/src/AboutDialog/AboutDialog.stories.js, packages/design-system/package.json, packages/playground-vite/package.json, packages/playground/package.json, tools/scripts-config-storybook-lib/.storybook-templates/msw/mockServiceWorker.js, tools/scripts-config-storybook-lib/.storybook-templates/preview.js, tools/scripts-config-storybook-lib/package.json, tools/scripts-locales/package.json, tools/scripts-publish-local/package.json, yarn.lock
Resolve Dependabot alerts in the project.
This PR will fix:
https://github.com/Talend/ui/security/dependabot/242
https://github.com/Talend/ui/security/dependabot/241
https://github.com/Talend/ui/security/dependabot/237
https://github.com/Talend/ui/security/dependabot/216
https://github.com/Talend/ui/security/dependabot/215
https://github.com/Talend/ui/security/dependabot/245
Dependencies upgraded:
"cross-spawn": "^7.0.3" => "^7.0.6"
"path-to-regexp": "^3.30" => "^8.2.0"
"msw": "^1.3.5" => "^2.6.6"
"msw-storybook-addon": "^1.10.0" => "^2.0.4"
"browser-sync": "^2.29.3" => "^3.0.3"
Changes:
1. Adapt breaking changes of `path-to-regexp` in [matchPath.js](https://github.com/Talend/ui/pull/5463/files#diff-9d42ef84cc247b6764270ba8786951da2cd8e50 …
=> chore(DGHT-287): Fix Dependabot alerts

.changeset/shy-coats-invite.md, packages/design-system/src/components/Drawer/Primitive/PrimitiveDrawer.module.scss, packages/design-system/src/components/Drawer/Primitive/PrimitiveDrawer.tsx, packages/design-system/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap, packages/design-system/src/stories/navigation/FloatingDrawer.stories.tsx
Handle FloatingDrawer overflow
=> fix(TMC-1657): handle FloatingDrawer overflow

.changeset/spotty-ads-cheer.md, packages/design-system/src/components/InlineEditing/InlineEditing.test.tsx, packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx, packages/design-system/src/stories/form/InlineEditing.stories.tsx
Handle required property in InlineEdit
=> fix(InlineEdit): handle required property in InlineEdit

.changeset/shiny-toes-relate.md, packages/design-system/src/components/Drawer/Primitive/PrimitiveDrawer.module.scss, packages/design-system/src/stories/navigation/FloatingDrawer.stories.tsx
Fix DS drawer overflow for title container
=> fix(TMC-1657): Fix DS drawer overflow for title container

.changeset/breezy-ways-care.md, .changeset/yellow-days-divide.md, packages/cmf-router/package.json, packages/cmf-router/src/sagaRouter.md, packages/cmf-router/src/sagaRouter.test.js, packages/cmf/__tests__/matchPath.test.js, packages/cmf/package.json, packages/cmf/src/matchPath.js, yarn.lock
BREAKING CHANGE: Upgraded path-to-regexp from 3.x to 8.x
This upgrade was necessary to resolve security vulnerabilities. The new version introduces two breaking changes that require updates to your application:
1. Optional Path Parameter Syntax Change
- Old syntax: `/resources/:id?`
- New syntax: `/resources{/id}`
This change is required because in path-to-regexp 8.x, the `?` character is reserved for query parameters and will throw a parsing error when used at the end of a path.
2. Root Path Matching Behavior Change
- In v3.x, root path `/` would match any path starting with `/`
- In v8.x, root path `/` only matches exactly `/`
- To match both root and child paths, use the wildcard pattern `/{*path}`
Example migration:
```javascript
// …
```
=> chore(sagaRouter): upgrade `path-to-regexp`

.changeset/wicked-frogs-bathe.md, packages/components/src/DateTimePickers/DateRange/Picker/__snapshots__/Picker.component.test.js.snap, packages/components/src/DateTimePickers/Time/time-extraction.js, packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap, packages/faceted-search/src/components/Badges/BadgeDate/__snapshots__/BadgeDateForm.component.test.js.snap
Fix https://github.com/Talend/ui/security/code-scanning/2700 by restricting character set and amount of characters in the regexes to parse times
Copilot was used to change the regexes. I manually tested them in js console.
=> fix(security): Re-write regexes to fix re-dos threat

.changeset/early-mirrors-cover.md, packages/components/src/Drawer/Drawer.component.js, packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap, packages/components/src/WithDrawer/__snapshots__/withDrawer.test.js.snap, packages/forms/src/FormSkeleton.module.scss, packages/forms/src/UIForm/UIForm.module.scss
Improve absolute footer buttons compatibility
=> fix(TMC-160): Improve absolute footer buttons compatibility

.changeset/pink-groups-flash.md, packages/design-docs/package.json, packages/design-system/package.json, packages/forms/package.json, packages/storybook-one/package.json, yarn.lock
=> chore(deps): Revert rhf to 7.53.1
