README.md

no badge to travis
no link to the generator talend
badge to display current global status
link to access the documentation of generator-talend

docs: add travis badge + generator-talend local link

---

README.md

bootstrap-theme isn't mention on the import section of the README.
bootstrap-theme is mention on the import section of the README.

docs(theme): Adds theme to import list

---

CONTRIBUTING.md

[guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) github editor didn't give me option on commit message
**What is the current behavior?**
No example in docs
New example in docs for naming branches!

Docs(contribution): added branch naming examples

---

packages/components/src/ObjectViewer/Table/Table.component.js
packages/components/src/ObjectViewer/Table/Table.scss

If you hover the table view you have font-weight increase to 700;
This behavior comes from table-hover of bootstrap theme.
This effect is removed only for the case of ObjectViewer component.

fix(components/object-viewer): remove style on hover

---

README.md

The README has an outdated TODO section
Removes TODO section since tests and storybooks are back.
Moves the import task to issues.

docs(README): Removes todo section

---

packages/containers/src/List/List.container.js
packages/containers/src/List/List.test.js

The action creator on list title is called with only the id of the item
it's called with event, data, context as all the other action creator.
If you have used it you just have to update your action creator
```javascript
function myactioncreator(id) {}
```
```javascript
function myactioncreator(event, data, context) {
const id = data.id;
}
```
AFAIK only TFD …

fix(containers/list): api call of action creator

---

.travis/after_success_static.sh

We ran static server only if we were on `master`, my bad.
We run static server only if we are on PR.

chore(http-server): fix conditional execution

---

BREAKING_CHANGES_LOG.md
packages/cmf/__tests__/action.test.js
packages/cmf/src/action.js
packages/components/BREAKING_CHANGES_LOG.md
packages/components/src/List/ItemTitle/ItemTitle.component.js
packages/components/src/List/ItemTitle/ItemTitle.test.js
packages/containers/.storybook/config.js
packages/containers/examples/ExampleAction.js
packages/containers/src/Action/Action.component.js
packages/containers/src/Actions/Actions.component.js
packages/containers/src/SidePanel/SidePanel.container.js
packages/containers/src/actionAPI.js
packages/containers/src/mock.settings.json

all action props are spread on the button tag... but type exists on a button.
So we have warning to said button type is invalid.
This also has an other problem we don't know what to dispatch so we also dispatch stuff like icon, ... button props in redux.
put all action data in the payload attribute
action has special attributes
* actionCreator
* model
* payload (new, has the type for redux, and all static stuff)
If this PR contains a breaking change, please describe the …

fix: action structure should be in payload

---

output/cmf.eslint.txt
output/components.eslint.txt
packages/components/src/List/ItemTitle/ItemTitle.component.js
packages/components/src/List/ItemTitle/ItemTitle.test.js

the previous breaking change on list title was not documented and useless.
don't update your code your handler will work again in 0.61.1

revert(components/list): item title onclick pass just the item

---

packages/forms/__tests__/__snapshots__/Form.test.js.snap
packages/forms/src/templates/FieldTemplate.js

The label is not red when the form has an error.
The label is now red when the form has an error to highlight the error. This change is approved by Maxime. The guidelines will be updated with this change.

fix(form): add control-label to the label

---

packages/containers/package.json
packages/containers/src/Notification/Notification.container.js
packages/containers/src/Notification/Notification.test.js
packages/containers/src/Notification/index.js
packages/containers/src/Notification/pushNotification.js
packages/containers/yarn.lock

If you want to use Notification you have to write your own reducer and know the structure.
just import the component and use the reducer
```javascript
import { Notification } from 'react-talend-containers';
...
Notification.push(state, { message: 'hello world' });
```
You have a new peer depednencies : 'bson-objectid'

fix(containers/notifications): add reducer

---

output/cmf.eslint.txt
output/components.eslint.txt
packages/logging/src/errorTransformer.js

Reporting logs goes infinite cycle of calling itself, because of typo in sources
Works as intended

Fix(logging): fixed nasty memory leak which can hang the process

---

packages/containers/src/List/List.container.js

- [x ] The commit(s) message(s) follows our
When clicking on remove filter it was only modifying the visibility of the input. In addition, the filter was still in place.
Now whether the search in toolbar is toggled, the filter is cleared.
- [x ] No

fix(container): clearing the search input when clicking on remove filter

---

output/cmf.eslint.txt
output/components.eslint.txt
packages/components/src/List/Toolbar/Filter/Filter.component.js
packages/components/src/List/Toolbar/Filter/Filter.test.js

- [x ] The commit(s) message(s) follows our
There was no management of esc key, the test was there to check it but there was an issue with the fact that the defaultProps was initialized at the begining of all test so the jest function were the same for all the test.
The test were fixed and the esc key was added to the keydown event
- [x ] No
**Other …

fix(component): adding esc key management in filter keydown

---

output/components.sasslint.txt
packages/components/src/Drawer/Drawer.scss

https://jira.talendforge.org/browse/TFD-763
some component can appear over the drawer when they shouldn't be visible
add a z-index of 500 so all component are seen under the drawer except for the Dialog.

fix(TFD-763/Drawer): z-index

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/cmf/src/reducers/index.js

The current collection reducer is undefined. Only a console.error is printed ... (thanks redux)
fix the import path

fix(cmf): import collection reducer from default

---

packages/components/src/List/DisplayTable/DisplayTable.component.js
packages/components/src/List/DisplayTable/DisplayTable.scss
packages/components/src/List/DisplayTable/__snapshots__/DisplayTable.snapshot.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap

On List Table display with actions, there was a double scroll.
The problem was that the actions are in `position: absolute` aligned on the right. But when the List is big enough to trigger a scroll, the actions remain on the right of the **initial position of the tr**.
So on the last tr, the actions was under the viewport, that enable the second scrollbar.
Hover on the last row : the actions are not on the row --> impossible to click
There is an horizontal scroll du to the long text, but it doesn't appear :/
This …

fix(Components): list table double vertical scroll

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/containers/src/ConfirmDialog/ConfirmDialog.test.js
packages/containers/src/ConfirmDialog/showHideConfirmDialog.js

as the state path is now different when using cmfConnect, there was an issue while trying to access to the previous confirm dialog path
it now works again

fix(container): fixing confirm dialog state path

---

packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
packages/components/stories/ActionDropdown.js

No possibility to add icon to dropdown's menu item
There is possible to add icon to droopdown's menu item

feat(ActionDropdown): add icon to menu item

---

packages/components/src/TreeView/TreeView.component.js
packages/components/src/TreeView/TreeView.test.js
packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
packages/components/stories/TreeView.js

TreeView renders children and does not pass all required properties to them. Resulting any TreeViewItem fails to render badge with counter, when { withCounter: true } option is on.
Fixed, just provide a showCounter flag on item you want badge on.

fix(components/treeview): badge invisible on depth>1

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Drawer/Drawer.component.js
packages/components/src/Layout/TwoColumns/TwoColumns.component.js
packages/components/src/WithDrawer/WithDrawer.component.js

Currently we have a lot of PropTypes warnings in the browser console.
PropTypes for Drawer component fixed, so now most of warnings should gone.

fix(components/Drawer): proptypes warnings

---

output/forms.eslint.txt
packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js

When select item with ctrl or shift key, and another in edit, the edited item is not reseted
When select item with ctrl or shift key, and another in edit, the edited item is reseted

fix(forms): Enumeration component : fix deselect edit mode

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.test.js
packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap

I can't apply custom style in drawer component when it's stacked.
I can select it using '.tc-drawer.stacked'

fix(components/Drawer): add global classname when stacked

---

packages/cmf/__tests__/registry.test.js
packages/cmf/src/registry.js

At the moment if you register undefined in a key nothing happens ...
And because with javascript when you are doing a wrong import in an existing file you have undefined as value .. it's a nightmare to follow.
If you register undefined it throws an exception.

chore(cmf): throw if register undefined

---

packages/forms/src/Form.js

If a form is defined action without onclick it throw exception.
But for submit action it s a non sens to define onclick because you have defined onSubmit.
no need for that

fix(forms): handleActionOnClick return noop

---

output/components.sasslint.txt
packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.scss
packages/components/src/Layout/TwoColumns/TwoColumns.scss
packages/components/src/Layout/__snapshots__/Layout.test.js.snap
packages/components/src/WithDrawer/WithDrawer.component.js
packages/components/src/WithDrawer/withDrawer.scss

sibling stacked drawer up to three now have an offset of 2%
drawer are using all horizontal space available of a parent minus 15px;
drawer use all horizontal space available of a parent
if a drawer has simbling they are rendered with a 2% offset

fix(components): stacked drawer use 100% of container horizontal space

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js

when connected to handler, delete an item reset the list to default state & make some ux issue ( as the searched items are not refresh but the search seems reset )
we don't go back to default state when we are in search state

fix(form/enumeration): delete a value when search don't reinit to default state

---

packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
packages/components/stories/ActionDropdown.js
packages/components/yarn.lock

MenuItem for divider will render children inside. That cause warning
MenuItem for divider have no extra data

fix(components/ActionDropdown): fix divider in menu

---

packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap

Two scrollbars
http://talend.surge.sh/components/?selectedKind=Drawer&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
Second scrollbar removed.

fix(components/Drawer): removed second scrollbar from drawer

---

packages/cmf/__tests__/__snapshots__/cmfConnect.test.js.snap
packages/cmf/__tests__/actions/__snapshots__/componentsActions.test.js.snap
packages/cmf/__tests__/cmfConnect.test.js
packages/cmf/__tests__/middlewares/__snapshots__/http.test.js.snap
packages/cmf/package.json
packages/cmf/src/cmfConnect.js
packages/cmf/yarn.lock

To use dispatchActionCreator you have to inject the context in your component which can be cumbersome.
The unittest around this was a false positive
Fix the tests and make it work.
Update some dev dependencies

fix(cmf/dispatchActionCreator): context not mandatory

---

packages/cmf/__tests__/settings.test.js
packages/cmf/src/settings.js

When attachRef is called with obj as a primitive not being an object, for example a string, said string was convert to an object before being returned.
triggering following problems, if a action creator id was present at the root of the configuration given to attachRefs the id was transformed into an object, being not resolvable by the action resolver.
detect if obj given to attachRef is indeed an object and not another primitive, return passed parameter to caller.

fix(cmf): attachRef behavior

---

packages/cmf/__tests__/route.test.js
packages/cmf/src/route.js

issue related to #422
If the component is connected the `view` props is not injected.
so the cmf settings view is not injected.
If the component is connected using cmfConnect, create a simple factory component `WithView` which inject the view as a props into the connected component.

fix(CMF): router inject view props if the component is cmfConnected

---

packages/components/src/HeaderBar/HeaderBar.scss
packages/components/yarn.lock

The color of search result items is white so they are invisible on white background
The color of search result items is black

fix(components/HeaderBar): fix color of search results

---

packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
packages/components/stories/HeaderBar.js

On HeaderBar dropdown buttons have no possibility to use onSelect property
There is possibility to set onSelect property for ActionDropdown in HeaderBar

feat(components/HeaderBar): add onSelect to dropdown menuItems

---

packages/components/src/Drawer/Drawer.scss

The guidelines said drawer title in uppercase, but the source code doesn't apply this style.
Add css text-transform uppercase

fix(TFD-1152/Drawer): set title to uppercase

---

packages/cmf/src/mock/settings.js
packages/containers/src/SidePanel/SidePanel.container.js
packages/containers/src/SidePanel/SidePanel.test.js

Currently the side panel only matches the highlighted link based on the
routerReplace settings.
It now matches on the routerPush.

feat(containers/SidePanel): Adds routerPush matching

---

packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
packages/components/stories/SidePanel.js

Need to add onClick and active props to each item of SidePanel
Have onSelect and selected props for whole SidePanel

feat(components/SidePanel): add onSelect to items

---

packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap

headerbar can't be customized
extra props can't be passed to sub components
let the abillity to customize internal components using a renderer props
extra props are passed using spread operations

feat(HeaderBar): add customization support

---

packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
packages/components/src/List/Toolbar/SelectSortBy/__snapshots__/SelectSortBy.test.js.snap
packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap

fix: remove semicolon from the rendering

---

packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap

SidePanel.selected.propType  is string
SidePanel.selected.propType is object

fix(components/SidePanel): fix propTypes

---

packages/cmf/__tests__/actions/settingsAction.test.js
packages/cmf/src/actions/settingsActions.js

the current fetch settings use a stock fetch API, so we don't have the default options to send cookies.
Use the http action provided by cmf to fetch the settings;

fix(cmf/settings/TFD-1318): fetch settings using http action

---

packages/components/src/HttpError/HttpError.scss

Error code is before SVG with opacity, we can imagine SVG are transparent.
Move error code backward

fix(components/httperror): move error code backward

---

packages/components/src/List/Toolbar/Pagination/Pagination.component.js
packages/components/yarn.lock

Incorrect calculation of startIndex for the last page
startIndex for the last page is correct

fix(components/Pagination): fix last page click

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/CollapsiblePanel/CollapsiblePanel.scss

IE 11 does not align toggle button to center
Let's remove `display: flex` for that button
Will fix https://jira.talendforge.org/browse/TDP-3757

fix(components/collapsiblepanel): Align toggle button for IE11

---

packages/components/src/Icon/Icon.scss

There is a IE11/Win7 bug with mount/unmount of `<use>` elements.
The result is that the mouse click events are blocked.
https://stackoverflow.com/questions/29932780/what-would-cause-click-events-to-stop-working-in-internet-explorer-11
Add a css property on `<use>` tag seems to "fix" the problem ¯\_(ツ)_/¯

fix(Icon): fix <use> issue on IE11/Win7

---

packages/components/src/WithDrawer/WithDrawer.component.js
packages/components/src/WithDrawer/withDrawer.test.js

with drawer map drawer with a key generated from sequence.
meaning that  when a drawer in second position get unmounted and replaced, the animation is triggered and then canceled with the new same level drawer mounted.
if a route is available, it is used as key, variable elements in routes are not taken into account, so for the same route with different parameter the drawer doesn't get animated.

fix(components/drawer): fix key generation if a route is available

---

packages/components/src/Status/Status.scss

There is no more space between the icon and the label in the status component.
This was asked in a comment in TDP-3757
I added 5 px of margin-right

fix(components/status): add space between icon and label

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.component.js
packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.test.js

* No boolean rendering
* Properties order is wrong
* Adds boolean renderer
* Fixes ordering

fix(components): Fixes JSONSchemaRenderer order + boolean rendering

---

packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
packages/forms/src/widgets/DatalistWidget/__snapshots__/DatalistWidget.test.js.snap

The datalist can't be selected with a css selector.
Adds a class to the datalist widget.

chore(forms): Adds class to DataList widget

---

packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
packages/components/src/Actions/__snapshots__/Actions.test.js.snap
packages/components/src/Badge/__snapshots__/Badge.snap.test.js.snap
packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap
packages/components/src/Enumeration/Header/__snapshots__/headerInput.snapshot.test.js.snap
packages/components/src/Enumeration/Header/__snapshots__/headerSelected.snapshot.test.js.snap
packages/components/src/Enumeration/Items/Item/__snapshots__/item.snapshot.test.js.snap
packages/components/src/Enumeration/Items/Item/__snapshots__/itemEdit.snapshot.test.js.snap
packages/components/src/Enumeration/Items/__snapshots__/items.snapshot.test.js.snap
packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
packages/components/src/List/Content/Item/__snapshots__/Item.snapshot.test.js.snap
packages/components/src/List/DisplayLarge/__snapshots__/DisplayLarge.test.js.snap
packages/components/src/List/DisplayTable/__snapshots__/DisplayTable.snapshot.test.js.snap
packages/components/src/List/DisplayTile/__snapshots__/DisplayTile.test.js.snap
packages/components/src/List/Toolbar/Filter/__snapshots__/Filter.snapshot.test.js.snap
packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap
packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
packages/components/src/Progress/__snapshots__/Progress.test.js.snap
packages/components/src/TooltipTrigger/TooltipTrigger.component.js
packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap
packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/components/yarn.lock

Just clean #478
Remove onClur, onClick, onMouseOut which was null or noop
Update snapshots
Removed aria-describedby with had the uuid which is not meaningful, and which was overriden in audio description by the content of children.

fix(components/TooltipTrigger): noop props and aria-describedby with uuid content

---

packages/forms/src/Form.js

Form ref could be null
Avoid error while accessing to form ref state by testing if it is defined

fix(forms): avoid undefined ref

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/cmf/__tests__/componentState.test.js
packages/cmf/src/componentState.js
packages/containers/src/Notification/Notification.connect.js
packages/containers/src/Notification/Notification.test.js

using dispatchProps.setState trought a setTimeout/setInterval etc function type who mess with javascript pile, to update component state using current state can create some problems since there is no guaranty that the state used trough the setTimeout setInterval is in sync with the latest version in redux.
dispatchProps.setState can accept now a mutator function receiving the latest state available. This being done a redux-thunk middleware.
Those mutator function accept only one parameter (previousState) and must return a new state

feat(cmf): component.setState now accept mutator function

---

packages/components/src/AppHeaderBar/__snapshots__/AppHeaderBar.snapshot.test.js.snap
packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
packages/components/src/Typeahead/Typeahead.component.js
packages/components/src/Typeahead/Typeahead.test.js
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/components/yarn.lock

onBlur is called before onClick when clicking on an list item ; so the click event is not trigged.
Using onMouseDown solves this issue. The click action is now called before the blur one.

fix(components/typeahead): use onmousedown instead of onclick

---

output/forms.eslint.txt
packages/forms/src/Form.js
packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js
packages/forms/src/templates/FieldTemplate.js
packages/forms/src/templates/LabelTemplate.js
packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.js
packages/forms/src/widgets/RadioOrSelectWidget.js

The columns widget throw error in production because SchemaField.proptypes is undefined
add proptypes only if env is not production

fix(forms): declare proptypes only if not in production

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/cmf/src/actions/collectionsActions.js
packages/cmf/src/componentState.js
packages/cmf/src/reducers/componentsReducers.js

in CMF some message where implemented so that some unhealthy operation may come to attention of the developpers, we choose to throw so that the dev will not ignore them.
Problem those operation have 0 inpact on app operation, but may throw in production for nothing
Add a check of environnement on those messages so that it doesn't throw on production.

feat(cmf): some message will not throw on Production

---

packages/components/src/Typeahead/Typeahead.component.renderers.js
packages/components/stories/Typeahead.js

If the title or the description is undefined: `Cannot read property 'split' of undefined`
`emphasise()` returns an empty string if trying to highlight an undefined string.

fix(components/typeahead): don't fail on undefined text

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js
packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.scss
packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.test.js
packages/components/src/Actions/ActionSplitDropdown/__snapshots__/ActionSplitDropdown.test.js.snap
packages/components/src/Actions/__snapshots__/Actions.test.js.snap
packages/components/src/VirtualizedList/ListTable/ListTable.scss
packages/components/stories/ActionSplitDropdown.js

feat(components/actionsplitdropdown): should be able to display icons

---

packages/components/src/List/Toolbar/Pagination/Pagination.component.js
packages/components/src/List/Toolbar/Pagination/Pagination.snapshot.test.js
packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
packages/components/yarn.lock

When there is no items the pages count is 1/0
Don't show pagination navigation when there is less than 2 pages

fix(TUX-262): show pagination navigation only when necessary

---

packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
packages/components/stories/TreeView.js

- TreeView has max-depth limitation,
- counter aligned left.
- no max-depth limitation,
- counter aligned right.

fix(TIPAAS-10587): fix TreeView style

---

packages/theme/package.json

links point to the old repository
update links to UI

docs: update talend bootstrap theme links

---

packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.scss

Magic numbers in #582
Use vars 
Try to fit a little more to forms style : add padding to the dd (~ input) instead of dt (~ label)

fix : use vars and try to align a little more with forms style

---

.storybook/webpack.config.js
packages/components/.storybook/webpack.config.js
packages/containers/.storybook/webpack.config.js
packages/forms/.storybook/webpack.config.js

Components/Forms/Containers storybook webpack config has a lot in common. For now this code is duplicated.
Extract the common configuration.

chore(storybook): extract common webpack config

---

packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
packages/components/stories/List.js

Old List to VirtualizedList does not pass selection props
Map List selection props to VirtualizedList selection props

feat(List): map selection to virtualized list

---

packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
packages/components/stories/List.js

With #625, we added the mapping from List to VirtualizedList for selection feature.
But the selection callback was not the right one (onSelect mapped, but onToggle is the one).
OnSelect props is deprecated, we will remove it when we remove the withContent version of List.
Map onToggle for selection

fix(VirtualizedList) : map onToggle instead of onSelect for selection

---

packages/components/src/ActionBar/ActionBar.scss
packages/components/src/Drawer/Drawer.scss

According to guideline:
http://guidelines.talend.com/document/92132#/navigation-layout/toolbars
> Background color of toolbars is $concrete
Some buttons not visible enough with current background.
Fixed scss variable

fix(components/ActionBar/DrawerFooter): use $concrete for bgcolor

---

packages/cmf/README.md
packages/cmf/__tests__/expression.test.js
packages/cmf/src/expression.js
packages/containers/src/actionAPI.js

expressions are powerfull but when a component exists adding support to it need to really understand how it works.
Now you can just add api.expressions.withExpressions(Component, ['disabled']) so you have your component which will support expression on `disabled` props
actionAPI expose a evalExpression api which has been refactored to use CMF api.

feat(cmf): add withExpression component factory

---

packages/components/src/HeaderBar/HeaderBar.scss

Header full logo has width 75px, but it should be 85px
update the width of full logo according to guidelines
http://guidelines.talend.com/document/92132#/navigation-layout/app-header

Fix(components/header): correct full logo width

---

output/containers.eslint.txt
packages/containers/src/Form/Form.container.js
packages/containers/src/Form/__snapshots__/Form.test.js.snap
packages/containers/yarn.lock

Fields definition could not be customized by a props
Fields can be customized by a props now.

feat(containers): Form add a way to customize fields

---

output/forms.eslint.txt
packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
packages/forms/src/widgets/DatalistWidget/DatalistWidget.test.js

When receiving a new value by props, the widget kept rendering what it had stored in state.
State was not updated with new value when receiving value on props
Set value in state on componentWillReceiveProps lifecycle hook

fix(forms): datalistWidget not setting value when receiving new value props

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/forms/src/fields/ArrayField.js
packages/forms/src/templates/ArrayFieldTemplate.js
packages/forms/src/templates/ArrayFieldTemplate.scss

Adding elements to an array forces the user to scroll to fill the newly added item.
Collapse all previous items when adding a new one.

feat(forms): Collapse previous array items on add

---

packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js

When there is no titleProps passed to List, the mapping from List to VirtualizedList crashes.
Test for titleProps to be defined.

fix(List): check for an optional props definition

---

docs/README.md
docs/_config.yml

The doc is broken.
I don't know why we have this change, but we lost the context (`/ui/`) in the generated links.
Changed configuration to add context in the site url

doc(CMF): fix gh-pages serving context

---

packages/containers/.storybook/config.js

Storybook is broken
```
VM299 preview.bundle.js:87914 Uncaught ReferenceError: regeneratorRuntime is not defined
at Object.defineProperty.value (VM167 preview.bundle.js:87914)
at __webpack_require__ (VM167 preview.bundle.js:677)
at fn (VM167 preview.bundle.js:88)
at Object.isArray (VM167 preview.bundle.js:25892)
at __webpack_require__ (VM167 preview.bundle.js:677)
at fn (VM167 preview.bundle.js:88)
at Object.<anonymous> (VM167 preview.bundle.js:3548)
at __webpack_require__ (VM167 preview.bundle.js:677)
at fn (VM167 preview.bundle.js:88)
at Object.__webpack_exports__.a (VM167 preview.bundle.js:85604)
```
Add babel-polyfill
**[ ] This PR …

fix(Containers): import babel-polyfill in storybook

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
packages/components/src/Status/Status.component.js
packages/components/src/Status/Status.scss
packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap

[Aria role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_status_role) is missing on `Status` component
http://guidelines.talend.com/document/135457#/export-history

feat(components/status): ARIA role

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Typeahead/Typeahead.scss
packages/components/stories/Typeahead.js

With right position, the typeahead results were on the right. So sometimes, outside of the window.
#44 
Fix it with css

fix(Typeahead): display result with right position

---

packages/forms/src/UIForm/utils/properties.js
packages/forms/src/UIForm/utils/properties.test.js

When nested properties are not provided in uiSpecs, on nested input change it crashes.
Create the nested properties on mutation.

fix(UIForms): create properties nested objects when mutated

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js

In MultiSelectTag widget, current tags should not appear in the suggestions list.
When component receive new value props, the suggestions list is updated.

fix(UIForms): MultiSelectTag suggestions update on value update

---

packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
packages/containers/src/SidePanel/SidePanel.container.js

add a displayname by default on sidepanel. without it, with minification process, the sidepanel entry is something like "t" or another letter. this is not very convenient to get to store it in local storage
add a displayname

fix(webapp): add displayName on SidePanel

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Icon/Icon.component.js

on some use case of Icon component, rendering was broken
fixed in the Icon component a missing part of css classname
This can not be tested since import and nested import returning undefined doesn't throw at compile time.
This because dynamic import and the non willingness of TC-39 to force this to be wrapped into a promise.

fix(icon): fix icon rendering

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/containers/examples/ExampleObjectViewer.js
packages/containers/src/ObjectViewer/ObjectViewer.container.js

Not all props given to the objectViewerContainer are passed down to the ObjectViewer object
props are given back to the ObjectViewer component

feat(container/ObjectViewer): add tupleName support on container

---

output/cmf.eslint.txt
packages/cmf/src/cmfConnect.js

getCollection is recreated on  each call to getStateToProps, the problem being that each time a connected component is rendered, this props ref is not equal to the one on precedent call, preventing connect to do its shallow equal performance job.
getCollection is now a single ref pointer, and state is provided to it via a module scoped value refreshed on each call to getStateToProps

fix(cmf): cmfConnect perfs

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
packages/components/src/Drawer/Drawer.scss
packages/components/src/WithDrawer/withDrawer.scss

when wrapping a drawer powered component into another one adding some dom,
modal stacking effect were lost
changing the specificity of those css selector solves above problem

fix(component/drawer): make css selector a bit less specific

---

packages/cmf/__tests__/cmfConnect.test.js
packages/cmf/__tests__/settings.test.js
packages/cmf/src/cmfConnect.js
packages/cmf/src/settings.js

Currently when we want to configure component we apply the view props to it so we can add settings and voila.
but when the component is called by a library you have to add the view to the call so you can add your own configuration.
Now if you cmfConnect a component 'MyComponent' it will get the view 'MyComponent:default' if you do not provide any view props to it.
If it's connected with a componentId, default will be replace by this one.
If a props componentId is passed to the component it also will be used.

feat(cmf): auto use view from component name and id

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/theme.sasslint.txt
version.js

the stack part of the script was targeting the old talend package naming
upgraded talend package names

chores(version.js): update package name and doc

---

packages/cmf/__tests__/sagaRouter/router.test.js
packages/cmf/src/sagaRouter/index.js
packages/cmf/src/sagaRouter/router.js

You can't import sagaRouter from cmf, but only the initSagaRouter exposed as `sagaRouter`...
sometimes in the code it's used as routerSaga. (naming !)
expose sagaRouter as it is.
rename routerSaga to sagaRouter every where.

fix(cmf): sagaRouter import

---

packages/components/src/Icon/Icon.component.js

onClick isn't really required on all Icons. But the proptypes says so. That creates a ton of proptypes warnings.
Remove the isRequired from the Icon onClick prop.

chore(Proptypes): Removes isRequired from Icon onClick prop

---

BREAKING_CHANGES_LOG.md
packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/utils/getPropsFrom.js
packages/components/src/utils/getPropsFrom.test.js
packages/components/stories/HeaderBar.js
packages/containers/.storybook/config.js

HeaderBar/Brand use name property to render as label wich prevent to use CMFAction wich use name to resolve CMFAction from the registry.
Target property could not be passed down to an Action component
Add target to the whitelist.
Change headerBar Brand descriptor to label.
Name now can be used to resolve CMFAction from the registry. 
The brand element of the HeaderBar don't use name as label wich is conflicting with CMFAction name used for action resolution.

enhancement(component/Headerbar): small change

---

packages/sagas/package.json
packages/sagas/src/index.js
packages/sagas/yarn.lock

Pending constants were not exported.
Change that forgetting

fix(sagas): Export pending constants

---

packages/components/src/SidePanel/SidePanel.component.js

Side panel does not allow to reuse provided className for actions.
Make the component action className computed from the json setting action "className" property.

fix(component/SidePanel): Use provided className property instead of ignoring it

---

packages/forms/stories/index.js
packages/theme/src/theme/_forms.scss

Removing of the bullet points, and left align the text displayed. 
If more than one error message needs to be displayed, this will be done as today, on a separate line/ under each other.
Changes connected to:
-  http://guidelines.talend.com/document/92132#/ui-controls/input-field
-  https://jira.talendforge.org/browse/TPSVC-3545
Styling adjustment

feat(forms): update styles of error msg

---

.sass-lint.yml
.travis.yml
.travis/after_success_git.sh
.travis/after_success_prettier.sh
output/components.sasslint.txt
packages/components/.sass-lint.yml
packages/forms/.sass-lint.yml
packages/theme/.sass-lint.yml

The CI doesn't prettify modified files.
The CI prettify files, then push a new `test(ci): prettier` commit.

chores(ci): use the ci to prettify modified files

---

BREAKING_CHANGES_LOG.md
packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/SidePanel.test.js

Actions ids are base on the action's label. It cause problems with i18n (for example TDP onboarding uses theses IDs to target elements).
Actions can have a new `id` property.
Before this, action ids were ignored. Now, if an id is provided per action, it will be used instead of the label ; so it could break some QA tests.

feat(components/sidepanel): accept custom action ids

---

packages/components/.storybook/webpack.config.js
packages/components/stories/Dialog.css
packages/components/stories/Dialog.js

Thanks Fabien for the fix tip
No way to click on "show info" in the storybook of the dialog component
pointer-events: none in the css of the dialog for the story book

doc(components/Dialog): fix 'show info' button in storybook

---

output/containers.eslint.txt
packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/SidePanel.test.js
packages/containers/examples/index.js
packages/containers/src/SidePanel/SidePanel.connect.js

Add a check on `action.id` and `action.label` in the component
Add action.id and action.label in SidePanel mapStateToProps so the component has it.

fix(components/sidepanel): accept empty ids

---

packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap
packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
packages/components/src/VirtualizedList/NoRows/NoRows.component.js
packages/components/src/VirtualizedList/NoRows/__snapshots__/NoRows.test.js.snap

NoRows component use a translated label, but default value is not passed correctly.
i18n.t() accept an object as options, but in this component, the default value is passed as option
Pas an object `{ defaultValue }` instead

fix(VirtualizedList): no rows i18n default value

---

packages/components/src/ListView/Header/Header.component.js
packages/components/src/ListView/Header/HeaderInput.component.js
packages/components/src/ListView/Items/Items.component.js
packages/components/src/ListView/ListView.component.js

i18n.t() accept an object as options, but in those components, the default value is passed as option
Pas an object `{ defaultValue }` instead

fix: pass default values in option object

---

packages/forms/stories-core/index.js
packages/forms/stories/index.js

UIForms storybooks are broken because of i18n buttons that makes redux provider children to be multiple children, but it expects an only child.
Move the buttons.

fix: broken forms storybook

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/components/src/Actions/ActionButton/ActionButton.test.js
packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
packages/components/stories/Action.js

When we set the props InProgress with an overlay, the overlay shows

fix(components): disable the overlay when inProgress

---

packages/components/e2e/component-objects/pom.xml

Talend QA use selenium 2.35.0. With the initialisation in test-common-web module, current version, set to 3+ is problematic.
Downgrade.
Run the component-objects e2e tests on our storybook, everything is still fine.

chore(component-objects): downgrade selenium version to 2.35.0

---

output/containers.eslint.txt
packages/components/src/FilterBar/FilterBar.component.js
packages/containers/src/index.js

The search placeholder was only display when the input is not focused : 
Always display the placeholder.

fix(component/filterbar): always display placeholder

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/sagas.eslint.txt
output/theme.sasslint.txt
packages/components/src/SidePanel/SidePanel.scss

PR to keep icons on opened sidepanel on the same spot as on the docked panel.
This is request from Marielle.
Fix styles

fix(SidePanel): fix sidepanel icons position in opened state

---

.storybook/webpack.config.js
output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/sagas.eslint.txt
output/theme.sasslint.txt
packages/components/.storybook/webpack.config.js
packages/containers/.storybook/webpack.config.js

Storybook is broken because forms depends on components that import a css (not scss) file.
Forms storybook webpack config does not how to load that.
Set css loader config in common webpack config

fix(Storybook): common css file loader config

---

packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.component.js
packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.scss
packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.test.js
packages/components/src/VirtualizedList/CellTextIcon/__snapshots__/CellWithIcon.test.js.snap
packages/components/src/VirtualizedList/CellTextIcon/index.js
packages/components/src/VirtualizedList/utils/dictionary.js
packages/components/stories/List.js

We need to show icon right after the text in table cell like on the picture:
https://jira.talendforge.org/secure/attachment/132019/132019_screenshot-1.png
Custom Cell renderer

feat(List): add CellRenderer for showing text + icon

---

packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.test.js
packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap

For TMC, we need to have the possibility to extend the className of Drawer.Content
Currently, if we set a custom className on Drawer.Content, initial classes are deleted
Add className in Drawer.content's props

feat(Components): add className in props for drawer.content

---

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
packages/components/src/VirtualizedList/VirtualizedList.scss

WIN7/IE11 cannot compute width
Change display mode

fix(components/list): actions display mode

---

packages/forms/src/UIForm/fieldsets/Columns/README.md
packages/forms/stories-core/json/fields/core-buttons.json
packages/forms/stories-core/json/fields/core-checkbox.json
packages/forms/stories-core/json/fields/core-datalist.json
packages/forms/stories-core/json/fields/core-keyValue.json
packages/forms/stories-core/json/fields/core-listView.json
packages/forms/stories-core/json/fields/core-multiSelectTag.json
packages/forms/stories-core/json/fields/core-radios-or-select.json
packages/forms/stories-core/json/fields/core-radios.json
packages/forms/stories-core/json/fields/core-select.json
packages/forms/stories-core/json/fields/core-text.json
packages/forms/stories-core/json/fields/core-toggle.json
packages/forms/stories-core/json/fieldsets/core-arrays.json
packages/forms/stories-core/json/fieldsets/core-collapsibleFieldset.json
packages/forms/stories-core/json/fieldsets/core-columns.json
packages/forms/stories-core/json/fieldsets/core-fieldset.json
packages/forms/stories-core/json/fieldsets/core-tabs.json
packages/forms/stories-core/jsonStories.js

It's hard for someone that hasn't seen the code to find the documentation of fields/fieldsets in UIForms.
Add a link in corresponding storybooks

doc(Forms): doc links in storybooks

---

packages/cmf/__tests__/actions/http.test.js
packages/cmf/src/actions/http.js
packages/cmf/src/middlewares/http/index.md
packages/cmf/src/middlewares/http/middleware.js

documented httpError actionCreator is undefined
```javascript
return api.actions.http.httpError(error);
```
plus the name is not very understandable ...
Let's rename it to onError and same for other actions
Update the middleware accordingly

fix(cmf): http actionCreator now imported with actions.http

---

packages/cmf/src/mock/store.js
packages/containers/.storybook/config.js

surge/containers is broken claiming 
`TypeError: Cannot set property 'appheaderbar' of undefined`
it works

doc(container): fix surge

---

.sass-lint.yml
packages/components/.sass-lint.yml
packages/forms/.sass-lint.yml
packages/sagas/.sass-lint.yml
packages/theme/.sass-lint.yml

sass-lint waits for uppercase hex notation
Prettier changes colors for lowercase hex notation
Disable the sass-lint rule et let Prettier doing the trick
Related to https://github.com/Talend/tools/pull/64

chore: Prettier deals with hex-notation rule

---

packages/components/package.json
packages/containers/package.json
packages/forms/package.json

At install you see all JS copied in the lib folder but not the CSS.
It feels wrong to me when debugging build
Add verbose option to cpx in 
* components
* containers
* forms

chore: add -v to all cpx done at install

---

packages/containers/src/Form/Form.container.js
packages/containers/src/Form/Form.md
packages/containers/src/Form/Form.test.js

Overiding default ArrayFieldTemplate is no more available from the FormContainer, this was not spotted in regression testing in datastreams because the new default template was exactly the one we used.
add inside the render if a Form#ArrayFieldTemplate props is present and use it over the default ArrayFieldTemplate if available.

fix(containers/form): add back ArrayFieldTemplate customisation in container

---

packages/forms/src/UIForm/fieldsets/Columns/Columns.component.js
packages/forms/src/UIForm/fieldsets/Columns/Columns.component.test.js
packages/forms/src/UIForm/fieldsets/Columns/Columns.scss
packages/forms/src/UIForm/fieldsets/Columns/README.md
packages/forms/src/UIForm/fieldsets/Columns/__snapshots__/Columns.component.test.js.snap
packages/forms/stories-core/json/fieldsets/core-columns.json

*WARNING: this fix is only on UIForms, not the current forms*
Columns is only a box manager, but when we want a common title on top of a row of columns, the only solution is to set the title on the first columns.  
But doing that makes the columns inputs not aligned anymore.
Columns widget now accepts and displays a title, like any other "fieldset" widget.

feat(UIForms): add columns common title

---

output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/sagas.eslint.txt
output/theme.sasslint.txt
packages/components/src/SidePanel/SidePanel.scss

Dock icon is not rotated when sidepanel is docked
rotate it !

fix(components/Sidepanel): dock icon don't rotate anymore

---

packages/components/src/SidePanel/SidePanel.scss

The active element on side panel is bold.
The [guideline](https://company-57688.frontify.com/document/92132#/navigation-layout/side-panel-main-menu) says the reverse
Remove the bold style.

fix(SidePanel): non bold font on active

---

packages/containers/examples/ExampleList.js
packages/containers/src/List/List.container.js
packages/containers/src/List/__snapshots__/List.test.js.snap

`list.inProgress: true` is not working with List container.
pass `inProgress` from List container to List component.

fix(containers/List): pass `inProgress` from List container to List component

---

packages/components/src/SidePanel/SidePanel.scss

No animation when side panel becomes docked
Add smooth animation while switching between these two states

fix(components/SidePanel): smooth docked transition

---

packages/components/package.json
packages/containers/package.json
packages/forms/package.json
packages/generator/generators/react-cmf/templates/package.json
packages/theme/package.json
version.js
yarn.lock

Node v9 is not supported
Upgrade to the last one because node v9 is supported since v4.6.0

chore(node-sass): upgrade to support node v9

---

packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
packages/icons/src/svg/AWS-kinesis.svg

CSS errors when parsing the svg.
Fix the value set for the fill-rule attribute

fix(icons): fixing svg#g#fill-rules value for AWS-kinesis

---

BREAKING_CHANGES_LOG.md
packages/containers/src/index.js

With Form container in default export, we must have form as dependency on the project that import containers
Remove Form from default export and import it _à la_ lodash when you need it

chore(containers): remove Form from default export

---

packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss

Multi Select Tag Widget behaves wrong in IE.
1. Dropdown doesn't disappear on blur (styles doesn't work in IE). 
2. When you select item from dropdown blur it doen't trigger blur event.
1. Apply styles another way.
2. Force blur event inside onSelect callback.

TPSVC-4185: Fixed: [IE] Continue adding roles or groups doesn't work in user drawer in IE browser

---

packages/components/src/HeaderBar/HeaderBar.scss

If screen width is small, then item separator '|' move to the next line, which causes problem with headerbar height.
fix style

fix(HeaderBar): fixed position of header bar item separator

---

.travis.yml

Our continuous integration server is using the deprecated NodeJS 6 version to build and run test. 
Bump to NodeJS 8. Latest LTS version being 8.9.4 at this time.

chore(ci): Bump travis NodeJS version to latest LTS

---

output/components.eslint.txt
packages/components/src/HeaderBar/HeaderBar.component.js

displayName is improperly set, resulting when js minification + mangling to lose the name
making impossible for example to use cmf-settings on prod mode 
fix display name

fix(component/HeaderBar) :displayName

---

packages/containers/src/FilterBar/FilterBar.container.js
packages/containers/src/FilterBar/FilterBar.test.js

Some code on the filterBar container use a props name ***ActionCreator, with this PR -> #1097, this code to dispatch some specific value with the action creator is not working anymore
Rename the param to avoid trigger cmf manipulation of props
Breaking change on the filterBar container API 
Breaking change on the Slider container API
onFilterActionCreator override onFilterAction if defined
onToggleActionCreator override onToggleAction if defined

fix(container): change props on filterBar to fit ActionCreator new api

---

packages/cmf/src/cmfConnect.js

event.persist() return undefined, so the event is lost as it is now
https://reactjs.org/docs/events.html
persist the event, but return also return the event 

fix(cmf): persist event when using dispatchActionCreator

---

output/cmf-webpack-plugin.eslint.txt
output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/datagrid.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/sagas.eslint.txt
output/theme.sasslint.txt
packages/datagrid/src/components/DataGrid/DataGrid.component.js
packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
packages/datagrid/stories/datagrid.component.js

It show every time the message from ag-grid when no data is set
Allow a way to customize it by props

feat(datagrid): allow to customize the empty data message

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/components/src/Actions/ActionButton/ActionButton.scss
packages/components/src/Actions/ActionButton/ActionButton.test.js
packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap
packages/components/src/Skeleton/Skeleton.scss
packages/components/stories/Action.js
packages/containers/src/ActionButton/__snapshots__/ActionButton.test.js.snap

There is an inProgress state but loading state is not dev for action button
Implement it

feat(components): add skeleton on action button

---

packages/components/src/ActionList/ActionList.component.js
packages/components/src/ActionList/ActionList.scss
packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
packages/components/stories/ActionList.js
packages/components/stories/SidePanel.js
packages/theme/example/index.html
packages/theme/src/theme/_navs.scss
packages/theme/src/theme/_visual-helpers.scss

When using side panel with `<a>` tags, the colors is different than with buttons.
Align the styles, within the theme.
Removed duplicate/custom style in ActionList, and use the theme.

fix(SidePanel/theme): side panel + nav-pills style, with anchors

---

packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
packages/icons/src/svg/aws-kinesis.svg

aws-kinesis icon is not valid cause if the usage of the "none-zero" attribute value
Use the valid nonzero value

fix(icons): fix aws-kinesis none-zero attribute value

---

packages/cmf/src/component.js
packages/cmf/src/sagas/component.js

'register undefined as component' error is only threw on production environment. should throw it only on dev environment.
negative this invariant condition

fix(cmf): invariant condition for 'register undefined as component' error

---

output/theme.sasslint.txt
packages/theme/src/theme/_forms.scss

Filter bar styling not applied after the recent changes made from https://jira.talendforge.org/browse/TUI-87
Applying custom styles to search fields under form-group class

fix(theme): fix filter bar styling in forms

---

packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss

In Edge the icon in InputTitleSubHeader is not centered (preview at: SubHeaderBar -> with all)
Center it with `align-items: center`

fix(TFD-3270): Center InputTitleSubHeader icon in Edge

---

output/theme.sasslint.txt
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
packages/theme/src/theme/_forms.scss

Multiple borders for form input fields on focus
Apply border bottom styling for form input fields on focus

fix(forms): apply border styling for form input fields in focus

---

packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap

Before #1235, we're using button instead of Action so any extra `ActionButton` props like `type` or `icon` are not take into account
Just force CellTitle to the initial rendering.

fix(components/virtualizedlist): force button type and remove any icon

---

output/cmf-webpack-plugin.eslint.txt
output/cmf.eslint.txt
output/components.eslint.txt
output/components.sasslint.txt
output/containers.eslint.txt
output/datagrid.eslint.txt
output/forms.eslint.txt
output/forms.sasslint.txt
output/logging.eslint.txt
output/sagas.eslint.txt
output/theme.sasslint.txt
packages/forms/src/widgets/ListViewWidget/ListViewWidget.js
packages/forms/src/widgets/ListViewWidget/ListViewWidget.test.js

The ListView widget build a state.items from props.options
but when props.options changed nothing happens
use willReceveiProps deprecated hook to update the state

fix(forms/listview): update state when receive props

---

packages/components/src/HeaderBar/HeaderBar.scss

The HeaderBar dropdown carets have
* white borders (1px)
* white box-shadow (1px)
But browser renders them with a demarkation just under the border, making it appear like a double caret.
Remove box-shadow.

fix(components/HeaderBar): remove caret shadow

---

packages/components/src/Breadcrumbs/Breadcrumbs.scss
packages/components/stories/Breadcrumbs.js

Breadcrumbs first letter is always in uppercase.
Override this unwanted CSS rule.

fix(components/breadcrumbs): remove title case

---

packages/containers/src/FilterBar/FilterBar.container.js
packages/containers/src/FilterBar/FilterBar.test.js
packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap

The filterbar container was only using its state but in some case (when used inside of List) it needs to take the props.
https://jira.talendforge.org/browse/TDS-3254, this bug is also present on other apps.
Using props attribute when they are passed.

fix(containers/FilterBar): use props when passed

---

packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap

There is no tooltip on virtualizedlist's item title.
Add it.

fix(components/virtualizedlist): add tooltip on the item's title

---

packages/html-webpack-plugin/package.json

Dependencies is absolute, we still retrieve `@talend/react-components`@0.175.0
Prefer `peerDependencies` here

fix(html-webpack-plugin): change deps to peerDeps

---

packages/theme/src/theme/variations/_portal.scss

brand-primary color for portal doesn't fit new requirements
https://company-57688.frontify.com/document/92132#/design-principles/talend-7-designs
Change brand-primary for portal theme

TPSVC-4889: App header color for Portal

---

packages/cmf/__tests__/cmfConnect.test.js
packages/components/__mocks__/react-addons-css-transition-group.js
packages/forms/stories/index.js
packages/generator/generators/react-cmf/templates/src/app/components/App.container.js

Direct reference in our code to React.PropTypes is baring our route to react16 migration
Remove them, should remove some warning in test and live code.

chore: remove React.PropTypes in test or component

---

packages/theme/src/theme/_colors.scss

`$rio-grande` has changed in [guuideline](https://company-57688.frontify.com/document/92132#/design-principles/colors-in-ui) 
Update the color

feat(theme): update rio-grande color

---

packages/html-webpack-plugin/index.js
packages/html-webpack-plugin/index.test.js

`If` statement is missing
According to https://keithclark.co.uk/articles/loading-css-without-blocking-render/
Add `if` statement while `onload` is triggered

fix(html-webpack-plugin): change media for async loading

---

packages/components/src/AppLoader/constant.js

The appLoader spinner animation is broken during the application launch
Override default "box-sizing: content-box;" and set to "box-sizing: border-box;" for all the elements while the bootstrap.css is loading (Refer screenshots below)
http://1321.talend.surge.sh/components/?selectedKind=AppLoader&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

fix(components): app loader spinner styling

---

packages/components/src/ActionList/ActionList.scss
packages/components/src/SidePanel/SidePanel.scss
packages/components/stories/SidePanel.js

The side panel has a fix size for the moment. This causes readability issue when the labels are too long (ellipsis).
Make the side panel width ajusted to its content.

chore(SidePanel): make side panel's width ajusted to its content

---

packages/scripts/README.md
packages/scripts/package.json
packages/scripts/preset/README.md
packages/scripts/preset/config/webpack.config.js

Talend/script does not manage static app loader. To add it we have to :
- provide a custom webpack conf to insert the Talend html plugin with the right icon
- provide a custom webpack conf to pass the html logo from @talend/react-components
_**Waiting for #1335 to be merged and released**_
Now Talend/scripts depends on Talend html plugin
- it sets a default talend logo as loader icon
- it exposes an `appLoader` var in html template
Bonus
- Preset documentation has been improved.
- preset now accepts any html options and pass them to `html-webpack-plugin`

feat(scripts): customisable app loader

---

packages/scripts/package.json
packages/scripts/preset/config/webpack.config.dev.js

Linter is not integrated as webpack build
Webpack runs the linter as pre-loader, outputing the linter errors on each compilation.
This is only in dev mode and does not block the compilation.

feat(scripts): run eslint as pre-loader in dev mode

---

packages/scripts/preset/config/licence.js
packages/scripts/preset/config/webpack.config.js

Bundles generated by Talend/scripts don't insert Talend licence.
Use webpack banner plugin to insert it.

feat(scripts): insert licence banner in bundles

---

packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss

The SubHeaderBar edition button is not in the right color.
Current: $gallery
Expected: $silver
Change the button color

fix(Component/SubHeaderBar): edition button color

---

packages/scripts/preset/config/webpack.config.dev.js

The source map is the default webpack 4 dev mode source map: `eval`. But we want original files.
Switch the devtool to `source-map`

feat(Scripts): set source-map to map original files, not eval

---

packages/forms/src/Form.js

As we have an hybrid Form system, with the UIForm there are some propTypes validations errors, in some cases an object type is required and in some others an array.
Ref:
https://github.com/Talend/ui/blob/a65c99585e4c5b5debfc1ad92fd21b080a2b1a1e/packages/forms/src/UIForm/UIForm.container.js#L86
I changed the uiSchema propType validation to match an object or array type.

fix(Form): Change uiSchema propType to avoid type conflicts

---

packages/containers/src/Form/Form.container.js
packages/containers/src/Form/Form.test.js
packages/containers/src/Form/__snapshots__/Form.test.js.snap

In case of usage of UIForm, the props customValidation is not available.
Add the props customValidation in the form container

feat(Container): add CustomValidation props on Form container

---

packages/cmf/__tests__/action.test.js
packages/cmf/__tests__/cmfConnect.test.js
packages/cmf/src/mock/store.js

The current mock provided by CMF for testing purpose doesn't do deep copy.
So if you change a value in the provided mocked state it will change the reference for other tests which is not the expected behavior
use lodash cloneDeep.
You may have tests that fails after that. It's not considered as breaking changes.

fix(cmf/test): mock do a deepcopy

---

packages/cmf/scripts/cmf-settings.merge.js

PR #1345 introduced a breaking change. If the cmf.json destination is not provided, it breaks :/
Set back the destination optionnal

fix(cmf/merge): destination is optional again

---

output/cmf.eslint.txt
output/components.eslint.txt
output/containers.eslint.txt
output/datagrid.eslint.txt
output/forms.eslint.txt
output/logging.eslint.txt
packages/cmf-cqrs/package.json
packages/cmf-webpack-plugin/package.json
packages/cmf/package.json
packages/components/package.json
packages/containers/package.json
packages/datagrid/package.json
packages/forms/package.json
packages/generator/generators/react-cmf/templates/package.json
packages/generator/package.json
packages/icons/package.json
packages/logging/package.json
packages/sagas/package.json
version.js
yarn.lock

babel-eslint version has changed to use a wildcard `^8.0.2`.
But that introduce extra dependencies that interact with the eslint rules. That makes some valid patterns output a lint error.
Revert the version to the fixed one.

chore: revert babel-eslint version to fix it

---

packages/forms/src/UIForm/UIForm.container.js
packages/forms/src/UIForm/UIForm.container.test.js

Prevents component's state resetting (form data included), when any other property have changed.
Resetting only if the props related to the structure have changed.

fix(UIForm): resetting form structure if it didn't change

---

packages/components/src/CircularProgress/CircularProgress.component.js

currently it's not possible to have a different translation for the percent label
for exemple, we need to have a space before the %
add a new key  to make this possible

fix(components) : improve translation in circularProgress

---

packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js

Proptypes.obj is not a valid proptype
Proptypes.object is really better

fix(List): fix cellDictionary wrong proptype

---

packages/datagrid/src/components/DataGrid/DataGrid.component.js
packages/datagrid/src/components/DataGrid/DataGrid.test.js

When the component did update we refresh the raw in case the component has new rowdata for different states
Count if the row data contains different number of loading / loaded / not loaded row to redraw the cells

chore(datagrid): optim on componentDidUpdate

---

packages/forms/package.json
packages/forms/src/__snapshots__/Form.test.js.snap
packages/forms/src/fields/ArrayField.js
packages/forms/src/fields/ObjectField.js
version.js
yarn.lock

RJSF 1.0.0 introduce ajv as validator.
TCOMP v0 ( :( ) use strings for maxItems. This breaking change seems to have a great impact
Downgrade to the version just before 1.0.0, before the ajv PR.
We will have a warning because of the peer deps RJSF specifying react 15. But it should not be incompatible.

chore: downgrade react-jsonschema-form to not use ajv

---

packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
packages/components/src/Status/Status.component.js
packages/components/src/Status/Status.scss
packages/components/stories/CollapsiblePanel.js
packages/components/stories/Status.js

In TMC UI we need a warning status which indicate the operation is finished but with warnings.
Add 'warning' status to Status/CollapsiblePanel.

feat(components): Add 'warning' status to Status/CollapsiblePanel

---

packages/cmf/__tests__/expressions/index.test.js
packages/cmf/src/expressions/getIn.includes.js
packages/cmf/src/expressions/includes.js
packages/cmf/src/expressions/index.js
packages/cmf/src/expressions/index.md

Sometimes, information is not accessible with a getIn, as when we have a list in the store.
To provide access to this, i set here 2 new accessors to know if a value is present in a list in the store, theirs pretty names are :
- cmf.collections.includes
- cmf.components.includes

feat(cmf): add cmf.collection.includes expression

---

packages/theme/src/theme/_visual-helpers.scss

`focus` status is sometimes not visible on buttons (like in HeaderBar component) while they can have an `hover` visible status. This can be problematic when using keyboard navigation
Use `hover` rules on `focus` status

fix(a11y): Buttons get :hover styles on :focus

---

.prettierrc
output/theme.sasslint.txt
packages/theme/src/theme/_button-groups.scss

https://jira.talendforge.org/browse/TUI-147
Dropdown menu takes space even if it is closed.
That makes outiline surround it.
Set its display to none when it is closed to avoid taking any space

fix(theme): closed dropdown menu don't take space anymore

---

packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
packages/components/stories/ObjectViewer.js

in TMC, we have this report view design, in which we need to show additional warning and status label right next to item name.
Add a `tagged` prop, which should be a JSON object with jsonpath key and element value.
so ObjectViewer will render whatever element next to item name.

feat(ObjectViewer): add support for injecting element next to item

---

packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
packages/datagrid/src/components/DefaultCellRenderer/FormatValue.test.js

result different with the same expression
const regExp = /\n/g; 
console.log(regExp.test('dfdf\ndsfsdf')); // return true
console.log(regExp.test('dfdf\ndsfsdf'));// return false
console.log(regExp.test('dfdf\ndsfsdf')); // return true
If the regex has the global flag set, test() will advance the lastIndex of the regex. A subsequent use of test() will start the search at the substring of str specified by lastIndex (exec() will also advance the lastIndex property).
test works like exec and keep a pointer on the current found element
fix that

feat(datagrid): remove the global flag when using test

---

.travis.yml

In travis, react 15 matrix, we have to
* run `./version.js` to update react version
* run `yarn install` to fetch the new dependencies versions
But version.js required dependencies. A first solution was to run `yarn install` before `./version.js`, implying 2 `yarn install` in the process.
Fetch only necessary `version.js` dependencies via a simple `npm install`, before running the script.

chore(travis): avoid 2 heavy yarn install

---

packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
packages/datagrid/src/components/DefaultCellRenderer/FormatValue.test.js

Uncaught TypeError: Cannot read property 'match' of undefined when you show an empty value in a cell.
fix this error

fix(datagrid): error when the value is null

---

packages/cmf/__tests__/sagas/http.test.js
packages/cmf/src/sagas/http.js

if you override one time the default config doing 
`yield call(http.get, `${API.streams}/${streamId}/logs`, {
headers: {
Accept: 'text/plain',
'Content-Type': 'text/plain',
},
});`
instead of having this applied only for this call it will be applied to all subsequent call using `call(http.get)`
lodash merge is mutating the target object reference given to it, before returning it, crass but no big deal most of the time.
But here we where using it inside a curryed function that first take the default config and on subsequent call will try to merge temp override, issue being that the default config being mutated what was a one time application, was a whole app lifecycle application.
Solution …

fix(cmf):handleDefaultHttpConfiguration

---

packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.test.js
packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
packages/components/src/DateTimePickers/IconButton/IconButton.component.js
packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.test.js
packages/components/src/DateTimePickers/pickers/MonthPicker/__snapshots__/MonthPicker.test.js.snap
packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js
packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js
packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.test.js
packages/components/src/DateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap
packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.component.js
packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.test.js
packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
packages/components/stories/DateTimePicker.js

Widget interaction to get the month and year on which the calendar (final date picker) will be based.
DOING IT !

feat(component/step2): selection of the calendar 

---

packages/eslint-config/README.md
packages/eslint-config/api-test-jasmine.yaml
packages/eslint-config/package.json

The jasmine config's `extends` attribute has a faulty path.
Fix the path, duh.

fix(eslint-config): update link in API team's test configs

---

packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.test.js
packages/components/src/DateTimePickers/pickers/DatePicker/DayPickerAction/DayPickerAction.component.js
packages/components/src/DateTimePickers/pickers/DatePicker/DayPickerAction/DayPickerAction.scss
packages/components/src/DateTimePickers/pickers/DatePicker/DayPickerAction/DayPickerAction.test.js
packages/components/src/DateTimePickers/pickers/DatePicker/DayPickerAction/__snapshots__/DayPickerAction.test.js.snap
packages/components/src/DateTimePickers/pickers/DatePicker/__snapshots__/DatePicker.test.js.snap
packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js
packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
yarn.lock

Fully manage the calendar display dynamically.
Do some stuff and things with lots of date-fns magic.
- Throw the ingredients (props) needed to display the right calendar based on month and year previously cooked (selected)
- Achieve some black magic to invoke the right weeks
- Give back the selected/picked date as wanted

feat(component/step3): calendar management

---

packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
packages/components/src/SubHeaderBar/SubHeaderBar.scss

in TMC UI -> Add new engine page, where we use the SubHeaderBar component, the sub title text has been truncated whereas enough space on the right side.
related jira: https://jira.talendforge.org/browse/TMC-12988
make the title/left part extend to full width when there's no center or right actions.

feat(components/SubHeaderBar): make the title/left part extend to full width when no center/right actions

---

packages/components-kit/package.json

current release of component kit use react 16.
move it into peer deps

fix(kit): move react from deps to peer

---

packages/components/src/Actions/ActionFile/ActionFile.component.js
packages/components/src/Actions/ActionFile/ActionFile.scss
packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
packages/containers/src/ActionFile/__snapshots__/ActionFile.test.js.snap

actionFile button does not have any box-shadow or hover effects
Use default btn style for actionFile. 
Before / after:

fix(components): Add actionFile shadow and hover effects

---

output/components.eslint.txt
packages/components/src/Breadcrumbs/Breadcrumbs.component.js
packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap

There were duplicate contents and some non-accessible buttons
Fix #1558 according to https://w3c.github.io/aria-practices/#breadcrumb

chore(components/breadcrumb): a11y

---

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
packages/components/src/VirtualizedList/CellTitle/CellTitleInput.component.js
packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleInput.test.js.snap

In List, with long item title, the edition is not optimised. Instead it becomes painful to use because the input doesn't take all the available space.
Make the input take all the available space.

fix(List): input size optimisation

---

packages/components/src/AppLoader/AppLoader.component.js
packages/components/src/AppLoader/__snapshots__/AppLoader.test.js.snap
packages/components/src/AppLoader/constant.js

AppLoader has `aria-busy=true` and `aria-atomic=true`.
The first one is wrong because the component/container is not loading, it's the app that is loading, and will replace the current component/container.
The second one is wrong because nothing changes in it, so screen readers don't need it. So in fact it is useless.
Remove them, and add `role=status` instead. Coupled with the current aria-label, it's understandable that the app is loading.

fix(AppLoader): wrong a11y attributes

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap

* ActionButton: there is no indication that is opens a popup
* ActionIconToggle: there is no indication that the button is active or not
* ActionButton: add `aria-haspopup` attribute
* ActionIconToggle: add `aria-pressed` attribute

feat(ActionsButton/ActionIconToggle): add aria attributes

---

packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
packages/components/src/Dialog/Dialog.component.js
packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap

Dialog missing
* role
* aria-modal
* aria-labelledby
* aria-describedby
* role=dialog
* aria-modal=true
* if we have a header: aria-labelledby use the header id. We suppose we have only 1 modal at a time, so no id generation needed
* for `aria-labelledby` (in case of no header) and `aria-describedby`, we can't guess user input, but all rest props are spread to the modal. So the user must manage that in its project

feat(Dialog): improve a11y

---

packages/datagrid/README.md
packages/datagrid/src/components/DataGrid/DataGrid.component.js
packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
packages/datagrid/src/components/DataGrid/DataGrid.test.js
packages/datagrid/stories/datagrid.component.js

- javascript error when props loading is true because ag-grid is not loaded
- custom function to force the redrawRows
fix that
after
```javascript
<DataGrid forceRedrawRows={
(props, prevProps) => 
// add your condition to force the redrawsRows when componentDidUpdate is called
return true;
} 
/>
```

fix(datagrid): fix redrawsRows when the datagrid is not showed

---

output/components.eslint.txt
output/theme.sasslint.txt
packages/components/src/FilterBar/FilterBar.component.js
packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/HeaderBar/HeaderBar.scss
packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap
packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
packages/components/src/Typeahead/Typeahead.component.js
packages/components/src/Typeahead/Typeahead.snapshot.test.js
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/components/stories/Typeahead.js
packages/theme/src/theme/_navbar.scss
packages/theme/src/theme/_navbar.search.scss

* FilterBar: missing search roles
* HeaderBar > search: role=search on form, which is wrong. We should not override form implicit role, and search role should be on button/input
* Typeahead: no roles props
* Typeahead: allow to pass roles on input and toggle button
* FilterBar and HeaderBar: set role=search on toggle button and role=searchbox
* HeaderBar: remove role from form and fix style

feat(Search): improve a11y

---

packages/components/src/ConfirmDialog/ConfirmDialog.component.js
packages/components/src/ConfirmDialog/ConfirmDialog.test.js
packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
packages/components/src/Progress/Progress.component.js
packages/components/src/Progress/Progress.test.js
packages/components/src/Progress/__snapshots__/Progress.test.js.snap
packages/components/stories/Progress.js

Progress component doesn't implement aria.
* aria attributes on infinite progress (role=status + aria-busy)
* aria attributes on definite progress (role=progressbar + aria-(valuenow, valuemin, valuemax))
* make tooltip required to add it in aria-label
* ConfirmDialog accepts a props.progressLabel to be passed as tooltip

feat(Progress): improve a11y

---

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss

In List title actions dropdowns, when entries are long, it overflows on the right of the screen
Since the actions are on the right, let's aligne the dropdowns on the right in Large display

fix(List): cell title dropdown position

---

packages/containers/src/ComponentForm/ComponentForm.component.js
packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
packages/containers/src/Form/Form.test.js
packages/forms/src/FormSwitcher.js
packages/forms/src/FormSwitcher.test.js

FormSwitcher is ineffective because its api is not the same as Form component which was the previous form entry point. It means that it introduces a breaking change.
Align api with old entry point, so switcher works with old props shape

fix(Forms): FormSwitcher has the same api as underlying forms

---

output/containers.eslint.txt
packages/containers/examples/ExampleBreadcrumbs.js
packages/containers/examples/index.js
packages/containers/src/Breadcrumbs/Breadcrumbs.connect.js
packages/containers/src/Breadcrumbs/Breadcrumbs.test.js
packages/containers/src/Breadcrumbs/index.js
packages/containers/src/index.js

https://jira.talendforge.org/browse/TDP-5280
We need a container Breadcrumbs to order to be able to dispatch an actionCreator when clicking on an item of the Breadcrumbs

feat(Container): Add a Breadcrumbs Container

---

packages/forms/stories/json/listView.json

Migration > ListView in storybook is broken
Fix widget name

fix(storybook) Typo in the widget name for listView storybook

---

packages/forms/src/UIForm/fields/ListView/ListView.component.js

When using the search field of the ListView form field, available options can disappear when quickly pressing "Escape" key after typing a search value (debounce timeout is not cleared so search is performed).
Clear debounce timeout when pressing "Escape" key

fix(ListView) ListView behavior when quickly pressing escape

---

packages/containers/src/Form/Form.container.js
packages/containers/src/Form/Form.test.js
packages/containers/src/Form/__snapshots__/Form.test.js.snap

loading props isn't spread to the component Form
fix that

fix(containers): spread loading props to the component Form

---

packages/forms/src/Form.js

Sometimes when we merge form states in react-jsonschema-form it can fail and get the old state. This is because the callback to `onChange` does not make sure that setState has finished before it runs. 
This bug happens especially if the app is busy doing many things, but sometimes it will work fine. 
the `onChange` https://github.com/mozilla-services/react-jsonschema-form/blob/v0.51.0/src/components/Form.js#L104 
is calling `setState`: https://github.com/mozilla-services/react-jsonschema-form/blob/v0.51.0/src/utils.js#L560
Pass the prop `safeRenderCompletion` in all cases. It will run the `onChange` in `setState`'s callback, where we can know for sure that the state has been updated. …

fix(forms): Add safeRenderCompletion for safe state change

---

packages/components/src/PieChart/PieChartIcon.component.js
packages/components/src/PieChart/PieChartIcon.test.js
packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap

- On loading state, no busy indication or text-alternative
- Svg chart has no way to accept text-alternative
- Add `aria-busy` and loading aria-label
- Spread extra props into svg instead of span container
Extra props provided to the component are now spread on the svg element, not the span container.
Example:
```
import PieChart from '@talend/react-components/lib/PieChart';
<PieChart aria-label='My text alternative' />
```
Before
```
<span arial-label='My text alternative'>
<svg></svg>
<span></span>
</span>
```
After
```
<span>
<svg arial-label='My text alternative'></svg>
<span></span> …
```

feat(PieChart): improve a11y

---

packages/components/.storybook/preview-head.html

It's not possible to scroll in the stories anymore.
Regression du to wrong cleanup in stories style, so Layout style `<body>` making it impossible to scroll.
Restore scroll

fix(storybook): restore scroll

---

packages/components/src/SidePanel/SidePanel.component.js
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap

- Collapse button has no text. Instead the meaningful text is on the container div
- Move the text to the button, hide it and make it appear as tooltip and aria-label.

feat(SidePanel): improve a11y

---

packages/components/src/EditableText/EditableText.component.js
packages/components/src/EditableText/EditableText.scss
packages/components/src/Skeleton/Skeleton.component.js
packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap

- inProgress: no text alternative of the visual heartbeat animation
- wording part is a button but handles only a double click. There is no possibility to perform a double click without a mouse. That is ok because we have the pencil but we end up with a button with no indication that does nothing with a keyboard.
- add aria attributes on inProgress state
- wording part is a span with double click
- removed a bunch of useless css and reshape the style
(Bonus)
- removed extra space in skeleton text alternative

feat(EditableText): improve a11y

---

output/forms.eslint.txt
packages/forms/.storybook/preview-head.html
packages/forms/src/UIForm/FormTemplate/DefaultFormTemplate.component.js
packages/forms/src/UIForm/FormTemplate/TextModeFormTemplate.component.js
packages/forms/src/UIForm/FormTemplate/index.js
packages/forms/src/UIForm/README.md
packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/UIForm.component.test.js
packages/forms/src/UIForm/UIForm.container.js
packages/forms/src/UIForm/UIForm.scss
packages/forms/src/UIForm/Widget/Widget.component.js
packages/forms/src/UIForm/Widget/Widget.component.test.js
packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.js
packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.test.js
packages/forms/src/UIForm/fields/FieldTemplate/displayMode/__snapshots__/TextMode.component.test.js.snap
packages/forms/src/UIForm/fields/FieldTemplate/index.js
packages/forms/src/UIForm/fields/Text/TextTextMode.component.js
packages/forms/src/UIForm/fields/Text/displayMode/TextMode.component.js
packages/forms/src/UIForm/fields/Text/displayMode/TextMode.component.test.js
packages/forms/src/UIForm/fields/Text/displayMode/__snapshots__/TextMode.component.test.js.snap
packages/forms/src/UIForm/fields/Text/index.js
packages/forms/src/UIForm/fields/TextArea/displayMode/TextMode.component.js
packages/forms/src/UIForm/fields/TextArea/displayMode/TextMode.component.test.js
packages/forms/src/UIForm/fields/TextArea/displayMode/__snapshots__/TextMode.component.test.js.snap
packages/forms/src/UIForm/fields/TextArea/index.js
packages/forms/src/UIForm/utils/widgets.js
packages/forms/stories-core/jsonStories.js

With old forms, to display the info in text format we had JSONSchemaRenderer component.
Adapting JSONSchemaRenderer to the new format is not a good solution as fieldsets widgets (tabs, arrays, etc) would have to be implemented again, even if we have common styles with the form.
The approach here is to introduce display mode.
- to provide specific implementations of each widgets for a `text` display mode.
- they are registered in the widget dictionary with the key `{widgetId}_{displayMode)`. Example `checkbox_text` for text display mode.
- UIForm will select the right widget based on a `props.displayMode` (form global mode) or `uiSchema.displayMode` (property specific mode)
- storybook has …

feat(Forms): text display mode

---

output/cmf.eslint.txt
packages/cmf/__tests__/actions/http.test.js
packages/cmf/__tests__/middlewares/__snapshots__/http.test.js.snap
packages/cmf/__tests__/middlewares/http.test.js
packages/cmf/src/actions/http.js
packages/cmf/src/middlewares/http/middleware.js

In case of file upload the file name is sent in the response headers so we need to have access to it in onResponse callback, might also be usefull in other cases.
adding headers as a parameter of onActionResponse callback.

chore(cmf/middleware): passing headers to onActionresponse

---

packages/forms/src/UIForm/fields/Text/Text.component.js
packages/forms/src/UIForm/fields/Text/Text.component.test.js
packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap

When defining a hidden input in uiSchema, the input is not displayed, but its attached label and form-group are visible.
Render only the hidden input.

fix(UIForms): hidden input don't have labels anymore

---

packages/scripts/preset/config/webpack.config.prod.js
packages/scripts/scripts/build.js
packages/scripts/scripts/start.js

No progress shown in dev mode for webpack. When the processing is long you get this bad "what is happening" feeling.
Enable progress by default in dev mode and make it configurable through talend-script config.

chore(scripts/webpack): Ensure talend script enable webpack progress mode in dev mode

---

packages/forms/src/UIForm/README.md

While trying to make a custom widget, I've found a small error in the samples.
Correct the typo.

doc(UIForm): import error in the samples

---

packages/components/src/List/List.scss
packages/components/src/List/__snapshots__/List.test.js.snap
packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
packages/components/src/VirtualizedList/ListTable/ListTable.component.js
packages/components/src/VirtualizedList/ListTable/ListTable.scss
packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap

This reverts commit d4e2257e420f14899dd0c14a286b1d3a610eda4a.
#1665 introduce issues
* no ellispsis anymore
* weird extra space on hover
Revert for now

Revert "feat(components): new list style (#1665)"

---

packages/components/src/ListView/Items/Items.scss

ListView sometimes gets useless scrollbars (content still fits container)
Plus, those scrollbars don't allow to browse the full content of ListView
Remove auto overflow CSS rule

fix(ListView) Remove useless scrollbars

---

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss

In the cell title actions focus of button overlap focus on button line.
Fix it adding a margin on cell-title-actions

fix(components/VirtualizedList): fix focus outline

---

packages/components/src/EditableText/EditableText.component.js

proptypes definition on EditableText requested that onEdit should be a boolean value, while the name and usage suggest that it is a function
fix proptypes and make it required since there is no internal check for onEdit existance.

fix(component): remove two proptypes warnings

---

packages/components/src/ConfirmDialog/ConfirmDialog.component.js
packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
packages/containers/src/DeleteResource/DeleteResource.container.js
packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap

When click outside delete modal, there will be js errors about onClick not a function.
Pass `onHide` handler from DeleteResource. when click outside modal, it'll hide.

fix(containers/DeleteResource): Add onHide handler

---

output/containers.eslint.txt
packages/containers/src/ComponentForm/kit/flatten.js
packages/containers/src/ComponentForm/kit/flatten.test.js

Component kit `flatten(payload)` was not including arrays and objects.
So during triggers, it is not possible to send complex items, with their key.
```
const payload = {
a: [{ b: 'lol', c: 'mdr' }]
}
flatten(payload);
{
a[0].b: 'lol',
a[0].c: 'mdr',
}
```
Include add an option to include arrays and objects
```
const payload = {
a: [{ b: 'lol', c: 'mdr' }]
}
flatten(payload, true);
{
a: [{ b: 'lol', c: 'mdr' }],
a[0]: { b: 'lol', c: 'mdr' },
a[0].b: 'lol',
a[0].c: 'mdr',
}
```

fix(ComponentKit): include objects and arrays in payload flatten

---

packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
packages/components/src/VirtualizedList/HeaderIcon/HeaderIcon.component.js
packages/components/src/VirtualizedList/HeaderIcon/HeaderIcon.scss
packages/components/src/VirtualizedList/HeaderIcon/__snapshots__/HeaderIcon.component.test.js.snap
packages/icons/src/filters/colormapping.svg
packages/icons/src/filters/grayscale.svg

There are one tooltip on the header with a name but there isn't no tooltip on the icon.
add title on the header icon

fix(list): add title on header icon

---

packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
packages/components/src/TabBar/TabBar.component.js
packages/components/src/TabBar/TabBar.test.js
packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.js
packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.test.js
packages/forms/src/UIForm/fieldsets/Tabs/Tabs.scss
packages/forms/src/UIForm/fieldsets/Tabs/__snapshots__/Tabs.component.test.js.snap

* Tabs widget use react-bootstrap tabs that doesn't implement all accessibility gestures
* tab with error holds the info only with red color. Need text aternative.
* use components TabBar
* add text alternative to tabs with error

feat(UIForm): improve tabs widget a11y

---

packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/UIForm.component.test.js

In case of we use a trigger to manage validation of some fields (e.g. specific validation rules in an array), during the onSubmit, we need to keep errors added and merge them with errors founded during the onSubmit.
keep existing errors

feat(uiform): keep the errors provide by triggers during onSubmit

---

output/components.eslint.txt
packages/components/src/List/Toolbar/SelectAll/SelectAll.component.js
packages/components/src/List/Toolbar/SelectAll/SelectAll.scss
packages/components/src/List/Toolbar/SelectAll/__snapshots__/SelectAll.snapshot.test.js.snap
packages/components/src/List/Toolbar/Toolbar.scss
packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap

The select all checbox is not aligned with the content
align the content

fix(List/TUI-135): align select all

---

README.md
packages/cmf-cqrs/README.md
packages/cmf-webpack-plugin/README.md
packages/cmf/README.md
packages/components/README.md
packages/containers/README.md
packages/forms/README.md
packages/generator/README.md
packages/icons/README.md
packages/logging/README.md
packages/sagas/README.md
packages/theme/README.md

In packages, we have precision about not following semver before 1.0.
Now we are in 1.0 but we will allow exceptions, depending on the case.
Added precision about future versionning.

doc: add versions precision in readme files

---

.travis.yml

Browserstack licence expired. 
Waiting for browserstack licence renewal, in the meantime, disable the e2e tests.

chore: disable e2e tests

---

output/containers.eslint.txt
packages/containers/src/ComponentForm/kit/createTriggers.js
packages/containers/src/ComponentForm/kit/createTriggers.test.js
packages/containers/src/ComponentForm/kit/flatten.js
packages/containers/src/ComponentForm/kit/flatten.test.js

Component trigger extract parameters to pass to the trigger call, based on param keys.
This extraction includes only native parameters, but objects and arrays are not included. Keys that point to them are associated to undefined.
Include complex items in parameters extraction

fix(ComponentForm): extract complex items in trigger parameters

---

output/containers.eslint.txt
packages/containers/src/ComponentForm/kit/createTriggers.js
packages/containers/src/ComponentForm/kit/flatten.js
packages/containers/src/ComponentForm/kit/flatten.test.js

#1732 included a regression, as flatten function is exposed and used.
The default result of flatten include objects sub flatten part, but should not, it is only used in trigger param extraction.
Restore the previous default result, and condition the objects sub-part inclusion.

fix(ComponentForm): flatten use option to include objects

---

packages/components/src/TabBar/TabBar.component.js
packages/components/src/TabBar/TabBar.test.js
packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap

#1722 introduced a regression on TabBar.
There are 3 ways to manage children in TabBar : 
- user pass children props, it is displayed everytime
- user pass children in items definition, they are set in tab panels. react-bootstrap manages the display
- no children at all, user manage the display under the tabs
The second is broken, because we test if there is a children prop.
Check if we have children attribute in items to see if we display the tab panel

fix(TabBar): children from item definition are displayed again

---

packages/theme/src/theme/_variables.scss

Button info is used almost everywhere. But it's not really accessible in common contexts, like a grey background, which is the case in a lot of our components.
Switch color to `$st-tropaz`

fix(Theme): button info color

---

packages/cmf-cqrs/package.json
packages/cmf-webpack-plugin/package.json
packages/cmf/package.json
packages/components/package.json
packages/containers/package.json
packages/datagrid/package.json
packages/forms/package.json
packages/jsfc/package.json
packages/logging/package.json
packages/sagas/package.json
packages/theme/package.json

We need to know the main file, but for the source files, in packages. With this info we will be able to use the library without having to run prepublish after every change. 
This is still in testing phase, but here's the related PR why we need this: https://github.com/Talend/ui/pull/1646
Add a "mainSrc" field, which should not disturb anything else. 

feat(development): add mainSrc field in package.json

---

packages/components/src/Inject/Inject.component.js
packages/components/src/Inject/Inject.md
packages/components/src/Inject/Inject.test.js
packages/containers/src/AboutDialog/AboutDialog.container.js
packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js

When you use the Inject API with an array React complains to not have keys on it
Add key when use array. (build it using component/componentId)

chore(components/Inject.getReactElement): remove key warning

---

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
packages/components/src/VirtualizedList/RowLarge/RowLarge.scss

The title text is still visible under the actions
Add a background

fix(components): bad display on actions hover on title

---

packages/containers/src/DeleteResource/sagas.js
packages/containers/src/DeleteResource/sagas.test.js

No event dispatched for failed delete request.
Dispatch an `DIALOG_BOX_DELETE_RESOURCE_ERROR` event with error messages when request went wrong.

fix(containers/DeleteResource): Dispatch error action when delete request failed

---

packages/components/src/Dialog/Dialog.scss

Paddings are not that good
Change them according to guidelines ( https://company-57688.frontify.com/document/92132#/modal/dialog-box )

fix(components): align dialog with guidelines

---

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap
packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
packages/components/src/VirtualizedList/RowSelection/RowSelection.scss

Background issue while hovering selected/active items :
In fact the issue is that the background doesn't apply to the whole item anymore
The selector used until now are not working anymore, updating them.
we should have this : 

fix(List): removing hover style on actions on selected/active items

---

packages/components/src/Dialog/Dialog.scss

Some padding on the confirm dialog as side effect on the toolbar
fix the toolbar

fix(components): fix action bar padding

---

packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.test.js
packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
packages/datagrid/stories/sample.json

when the value is null, null is display in the cell
detect null and replace by empty value

fix(datagrid): null value in cell

---

output/components.sasslint.txt
packages/components/src/Typeahead/Typeahead.component.renderers.js
packages/components/src/Typeahead/Typeahead.scss
packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap

This magnifier used to look bigger but from several weeks it looks smaller (since #1592)
Just revert the size if it not used from any other component

fix(components/typeahead): icon style

---

packages/components/src/AboutDialog/AboutDialog.component.js
packages/components/stories/AboutDialog.js

The cloud version of our app has a single quote before the year (Spring '18), however that single quote is escaped in i18next interpolation and then we try to display it within react dynamic content.
And so we end up with : 
Skip the escape part of i18next interpolation for that specific case.

fix(AboutDialog): dot not escape single quote

---

packages/containers/src/HeaderBar/HeaderBar.actions.js
packages/containers/src/HeaderBar/HeaderBar.container.js

HeaderBar container does not react properly on `productsUrl` prop change. `componentDidUpdate` takes old props as argument, not new props (there is a misconception in current code).
Fix `componentDidUpdate`

fix(Container) HeaderBar component update

---

packages/components/src/Layout/Layout.component.js
packages/components/src/Layout/Layout.scss
packages/components/src/Layout/OneColumn/OneColumn.component.js
packages/components/src/Layout/OneColumn/__snapshots__/OneColumn.test.js.snap
packages/components/src/Layout/SkipLinks/SkipLinks.component.js
packages/components/src/Layout/SkipLinks/SkipLinks.scss
packages/components/src/Layout/SkipLinks/SkipLinks.test.js
packages/components/src/Layout/SkipLinks/__snapshots__/SkipLinks.test.js.snap
packages/components/src/Layout/SkipLinks/index.js
packages/components/src/Layout/TwoColumns/TwoColumns.component.js
packages/components/src/Layout/TwoColumns/__snapshots__/TwoColumns.test.js.snap
packages/components/src/Layout/__snapshots__/Layout.test.js.snap
packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap

To provide skip links to all react projects using Talend/ui, we can add it into layout component.
So next upgrade will automatically bring them in the apps.
The choice of Layout is to control the ids, z-index and placement in 1 place.
Implement that, so it's free for the apps.

feat: skip links

---

packages/components/src/SubHeaderBar/SubHeaderBar.scss

Buttons label should always be in uppercase, it is not the case when they are inside a SubHeader component due to a CSS rules that cancels the `.btn`'s `text-transform` (was there to handle a specific case for TDC, see http://guidelines.talend.com/document/215501).
Remove the CSS `text-transform` cancellation.

fix(components/SubHeader): Button text-transform

---

packages/containers/src/HeaderBar/HeaderBar.container.js
packages/containers/src/HeaderBar/HeaderBar.test.js
packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap

App switcher hasn't analytics tag for each product
Generate them automatically

feat(containers): analytics tags for app switcher

---

packages/components/src/HeaderBar/HeaderBar.component.js

If I pass products as an empty array, app switcher will display "No options" and we want to render a simple span instead
Improve the check

fix(components): App switcher should not display no options

---

packages/components/src/ConfirmDialog/ConfirmDialog.component.js

There is a warning poping when a `ConfirmDialog` component is hidden but no `onHide` handler has been provided.
Only call the handler if it is provided (since prop is not marked as required).

fix(components/ConfirmDialog): onHide called only if provided

---

packages/cmf/__tests__/cmfConnect.test.js
packages/cmf/src/cmfConnect.js

A component cannot be `cmfConnect`ed with no parameter provided to `cmfConnect`, even if it has no `mapStateToProps`, `mapDispatchToProps`, etc
Provide a default value to the method.

fix(cmf): cmfConnect with no param

---

packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.md
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
packages/forms/src/UIForm/fields/InputDateTimePicker/InputDateTimePicker.component.js
packages/forms/src/UIForm/fields/InputDateTimePicker/InputDateTimePicker.test.js
packages/forms/src/UIForm/fields/InputDateTimePicker/README.md
packages/forms/src/UIForm/fields/InputDateTimePicker/WrongTypeError.js
packages/forms/src/UIForm/fields/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
packages/forms/src/UIForm/utils/validation.js
packages/forms/src/UIForm/utils/validation.test.js
packages/forms/stories-core/json/fields/core-inputDateTimePicker.json

Avoid loss of synchronicity between form property value and its `errorMessage`.
Having a not too bad way to handle errors. To just have at least a way to do it
Let spread all values not handled in the conversion, and have the form validation handle it.
Let the custom uiSchema `validationMessage` override all the error messages to avoid displaying an understandable message to the user.

fix(components/DatePicker) Widget error handling with UIForm - poc2

---

packages/containers/src/ComponentForm/ComponentForm.saga.test.js
packages/containers/src/ComponentForm/ComponentForm.sagas.js

When two ComponentForm are mounted at same time, on of those form definitionURL change will trigger definition fetch on those two forms creating interesting bugs
add a function to be used on any redux-saga take*(pattern) that can be used to check both that action.type and action.componentId match.

fix(ComponentForm): fix linked saga

---

output/forms.eslint.txt
packages/forms/src/UIForm/fields/Code/Code.component.js

Same issue as https://github.com/Talend/ui/pull/1796
tl;dr : Component yielding a warning in the console if using a fallback component if a dependencie, even if it is not used nor required.
Move the warning to the constructor of the fallback component.

chore(forms/Code): react-ace fallback warning on constructor

---

packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
packages/datagrid/stories/sample.json

When doc field isn't present, the headername has a prefix Data. doc is optional on the Avro spec. we fallback on the field name.
take the name of the field if doc isn't present in avro sample.

fix(datagrid): remove the prefix data in the header

---

packages/components/src/TooltipTrigger/TooltipTrigger.component.js
packages/components/src/TooltipTrigger/TooltipTrigger.test.js
packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap
packages/components/stories/Action.js
packages/components/stories/ActionIconToggle.js

fix this issue https://github.com/react-bootstrap/react-bootstrap/issues/2969 by inspiriting of https://github.com/react-bootstrap/react-bootstrap/pull/3251
when the click on the overlaytrigger, we force to hide the tooltip

fix(components): hiding the tooltip when the button is disabled

---

output/components.sasslint.txt
packages/components/src/ObjectViewer/Table/Table.scss

Object Viewer "Grid" mode have column title in uppercase, and in a bad font-weight.
Update style to cancel uppercase and update font-weight.

fix(ObjectViewer): Fix object viewer header style

---

packages/components/src/ActionBar/ActionBar.component.js
packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap

`ActionBar` wraps buttons with nav systematically
`ActionBar` wraps with div instead

fix(components): ActionBar wraps with div instead of nav

---

packages/cmf-cqrs/README.md
packages/components/README.md
packages/containers/README.md
packages/datagrid/README.md
packages/forms/README.md
packages/generator/README.md
packages/icons/README.md
packages/logging/README.md
packages/sagas/README.md
packages/theme/README.md

every package readme contains:
```
Before 1.0, `@talend/react-cmf-cqrs` do NOT follow semver version in releases.
You will find a [list of breaking changes here](https://github.com/Talend/ui/wiki/BREAKING-CHANGE).
Before 2.0, we will try not to introduce breaking changes, as possible.
After 2.0, we will only introduce breaking changes in major releases, and follow semver.
```
which is not anymore relevant.
just remove

doc: remove all breaking change log note

---

output/containers.eslint.txt
packages/containers/package.json
packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
packages/containers/src/SidePanel/SidePanel.connect.js

in #1766 we have removed the withouter HOC because no code was based on the router in the container.
But existing project use expressions.
rewrap it

fix(sidepanel): add withrouter

---

packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss

we can interact with the button when it is disabled
disable css style when the button is disabled

fix(components): disable the css when ActionIconToggle is disabled

---

packages/forms/src/UIForm/__snapshots__/widgets.json
packages/forms/stories/json/widgets.json
packages/theme/src/theme/_forms.scss

If you click on a readonly empty field the label will move up. This is confusing since you can't write anything anyway. 
Exclude readonly fields from the focus style on the label. 
storybook: Add an empty readonly in forms -> widgets

fix(forms): Exclude readonly fields from label focus style

---

packages/components/src/Layout/Layout.scss
packages/components/stories/Layout.js

The Layout component limits the body (100vh, 100vw).
But that is wrong, because the layout itself is already limited to those measures. And it introduce some side effect, for example with the dropdown.
Here it looks at the body bottom position to decide if it will switch to dropup. We scroll, the body (limited to 100vh) is out of the window, the dropdown consider it is in overflow and switch.
Remove the specific style on body, the layout already limits itself.

fix(Layout): do not touch the body style

---

packages/containers/src/ActionButton/ActionButton.connect.js

With UI 16.1, there has been a little regression on the action button. We dunnot pass the getComponent anymore but it is used by the overlay.
Simply add the missing props in the connect with the new api.

fix(Containers/ActionButton): add missing registry props

---

packages/cmf/src/localStorage.js

By default, local storage value is empty.
Test value before trying to use it.

fix(cmf/localstorage): empty local storage value

---

packages/components/src/Dialog/Dialog.scss

Uppercase is applied on modal title + font weight is [wrong](https://company-57688.frontify.com/document/92132#/modal/dialog-box).
Fix case and font weight.

fix(components/dialog): design adjustments

---

packages/components/src/VirtualizedList/ListGrid/ListGrid.test.js
packages/components/src/VirtualizedList/RendererSelector.test.js
packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap

Large display mode does not follow the [guidelines](https://company-57688.frontify.com/document/92132#/navigation-layout/list/list-views).
Change key font colour
Remove uppercase
Decrease padding between key and value

fix(components/list): large display adjustments

---

packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss

change color in the actions buttons (primary color to dove gray) to respect the guideline.
https://company-57688.frontify.com/document/92132#/navigation-layout/list
apply the new css

fix(components): apply dove-gray by default on actions on the list

---

output/containers.eslint.txt
packages/containers/src/SubHeaderBar/SubHeaderBar.selectors.js
packages/containers/src/SubHeaderBar/index.js

yarn start-containers produce the following error:
```
WARNING in ./src/SubHeaderBar/index.js 4:12-20
"export 'getQuery' was not found in './SubHeaderBar.selectors'
@ ./src/containers.js
@ ./src/index.js
@ ./src/register.js
@ ./.storybook/config.js
@ multi /Users/jmfrancois/github/talend/ui/node_modules/@storybook/core/dist/server/config/polyfills.js /Users/jmfrancois/github/talend/ui/node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```
remove the not existing selector from index.

fix(containers/SubHeaderBar): remove undefined selector

---

packages/containers/src/ComponentForm/ComponentForm.component.js
packages/containers/src/ComponentForm/ComponentForm.test.js

Currently, when we change a field in the form or whatever, we dispatch in redux the event.
The event contains the target ... the target contains the props ... component form props contains all the traductions as it's wrapped by i18n component 😢, in some project, we have like 12MB redux payload each time we update a field. My redux extension is broken with some few events.
As we don't use the content of the event, currently remove it. If for some future development we need something coming from the event, i advise to extract the information from the event & forward it to the payload, but not all the event himself 😃 
**[ ] This PR …

chore(container): remove componentForm events in redux payload

---

packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/UIForm.component.test.js

A div wrapper is rendered even if an empty `actions` is provided.
Don't render anything related to the footer buttons if an empty `actions` prop is provided.

fix(UIForm): Buttons wrapper rendered even if no actions

---

packages/components/src/utils/getPropsFrom.js
packages/components/src/utils/getPropsFrom.test.js

`form` prop is stripped when spreading prop from `ActionButton` to native `button` as it's not defined as a 'native attribute'.
Add the `form` attribute as a native one in the stripping config.

fix(Components): Missing possibility to have a 'form' prop on a ActionButton

---

packages/forms/src/UIForm/UIForm.container.js
packages/forms/src/UIForm/UIForm.container.test.js

The native event object is not spread in the `UIForm container` `onReset` callback.
Can be needed for custom reasons.
In my case, CMF with `ActionCreator` expect one to be persisted when the callback is fired.
Just spread the event object in the `UIForm container` `onReset`.

fix(UIForm): Missing event object spread in callback

---

packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap

by default, a button without type is set to submit. My datagrid is wrapped in a form, when i click on the header, my form is submitted
add type="button" to avoid it

fix(datagrid): add type button on the header

---

packages/datagrid/src/components/DataGrid/DataGrid.scss

when i scroll horizontally, the header has a bad color 
apply the background on the good css 

fix(datagrid): incorrect color after a horizontal scroll on the header

---

packages/components/src/ObjectViewer/JSONLike/JSONLike.scss

in IE11, flex items overflow the container
Use `flex: 1 1 auto` instead of `flex: 1 1 100%`

fix(components/ObjectViewer): fix ie11 flex issue

---

packages/components/src/ConfirmDialog/ConfirmDialog.test.js
packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
packages/components/src/Dialog/Dialog.component.js
packages/components/src/Dialog/Dialog.scss
packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
packages/components/src/EditableText/EditableText.component.js
packages/components/src/EditableText/EditableText.scss
packages/components/src/EditableText/EditableText.test.js
packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js

Dialogs and Subheader titles should be h1, without custom font style.
* fix the markup
* remove style
* editable text accepts now a componentClass props
The text mode style in EditableText has changed. We don't apply any default font style because you can insert any component you'd like.
To have the same rendering as before you must style yourself the text
```css
.tc-editable-text-wording {
color: $black;
font-size: 1.4rem;
font-weight: 900;
}
```

fix: SubHeader and Dialog headings

---

npm-audit/audit.json
packages/forms/src/UIForm/utils/properties.js
packages/forms/src/UIForm/utils/properties.test.js

Emptying an input (type something then remove it) of type "number" result to the following error : 
Whenever the field is required or not.
Convert empty string input value to `undefined` to avoid converting it to `NaN`.
The conversion occurs after each input `onChange`

fix(forms/number): Emptying number input result in NaN error

---

packages/forms/src/UIForm/fields/Text/Text.component.js
packages/forms/src/UIForm/fields/Text/Text.component.test.js
packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
packages/forms/stories-core/json/fields/core-text.json

restrict user input by using arrows on the text field input with type number
https://jira.talendforge.org/browse/TPSVC-7304
min and max attributes can solve this problems in native html way.
It allows manually set any number, but restrict setting numbers out of min and max boundaries.

fix(TPSVC-7304): add min and max attributes to text input

---

output/components.sasslint.txt
packages/components/src/Datalist/Datalist.scss
packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
packages/components/src/Typeahead/Typeahead.component.renderers.js
packages/components/src/Typeahead/Typeahead.scss
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap

Typeahead doesn't display the dropdown anymore.
It's a regression, du to an unwanted css removal.
Restore that, when
- react-autowhatever opens it
- when there is no result (no result message)
- when it is searching (searching message)
Remove duplicated style in datalist css

fix(Typeahead): dropdown display

---

packages/components/src/Dialog/Dialog.scss
packages/theme/src/theme/_modals.scss

The new guideline on headings impacts Dialog boxes too.
But they have specific style defined in the theme and components.
Remove all those dialog title style, letting the headings style application.

feat(Dialog): remove specific title style

---

packages/forms/src/UIForm/customFormats.js
packages/forms/src/UIForm/customFormats.test.js

https://jira.talendforge.org/browse/TMC-15611
We have had a case where the Azure repository urls can have a space between its name, this was not handled by the RegEx to validate the GIT urls in the UIForm custom formats.
I added the % character to the validation RegEx so that we allow it for this case.

fix(frontend): TMC-15611 allow spaces (%20) on GIT url validation

---

packages/router/README.md
packages/router/src/index.js
packages/router/src/index.test.js
packages/router/src/route.js

@sgendre report he can t use registerFunctions.
add new routerFunctions entry in getRouter main function

feat(router): add support for registerFunctions

---

packages/cmf/src/bootstrap.md

`preReducers` entry has incomplete type documentation
Complete it 

doc(cmf/bootstrap): fix preReducers entry types

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/containers/src/HeaderBar/HeaderBar.sagas.js
packages/containers/src/HeaderBar/HeaderBar.sagas.test.js

https://dev.to/ben/the-targetblank-vulnerability-by-example
`target="_blank"` must be followed by `rel="noopener noreferrer"`
The ActionButton do not enforce that.
window.open must also be followed by
```
opened.opener = null;
opened.location = action.payload.url;
```
The HeaderBar is impacted
Fix HeaderBar
Enforce this pattern in ActionButton

fix: all target blank and window.open

---

packages/cmf/src/cmfModule.merge.js
packages/router/README.md
packages/router/package.json
packages/router/src/index.js
packages/router/src/index.test.js

today some of our modules add routerConfig. So if you want to integrate a module you have to merge thoses config with yours.
The configuration pass to getRouter has `history`, `sagaRouterConfig` and `routerFunctions`
This can be tricky to merge (does the external addon use one or the other)
add the same mechanism as cmfModule inside the router.
//before
```javascript
import getRouterModule from '@talend/react-cmf-router';
import { sagaRouterConfig as extRouterConfig } from 'ext-module';
import { sagaRouterConfig as myRouterConfig } from './sagaRouter';
const myRouterModule = getRouterModule({ sagaRouterConfig: { ... extRouterConfig, ... myRouterConfig} });
cmf.bootstrap({ modules: …
```

feat(router): support multiple config

---

packages/scripts/internationalization/common/xtm.js

i18n scripts get projects from xtm, but even the inactive projects are returned.
Pass a param to xtm request to get only active ones

fix(i18n): filter active projects from xtm

---

packages/containers/package.json
yarn.lock

If you try to update the package @talend/react-cmf-router you will have it twice.
This is due to the package.json dependencies of container.
Move it to peerDependencies so the project decide which version to use.

chore(container): fix dependency

---

packages/containers/src/index.js

get component is not here anymore by default with cmf connect
Add withCompoentRegistry to have content back 

fix(containers): add withComponentRegistry to RichLayout

---

packages/components/src/Drawer/Drawer.scss

Because of CSS weigth, theme style comes first. And Drawer close button color is set to gray.
Improve CSS weight to restore its color to white. 🎉 
Will fix [TUI-328](https://jira.talendforge.org/browse/TUI-328)

fix(components/Drawer): close button color

---

packages/scripts/internationalization/README.md
packages/scripts/internationalization/common/xtm.js
packages/scripts/internationalization/scripts/download.js
packages/scripts/internationalization/scripts/upload.js

i18n scripts accept login/password as env var to login to XTM.
Replace that with token in en var

feat(scripts/i18n): accept token instead of password

---

packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
packages/forms/src/UIForm/fields/NestedListView/__snapshots__/NestedListView.test.js.snap

Warnings are poping in the console because some props are not provided to `<FieldTemplate />` in `<NestedListView />`.
Those are marked as required for a11y purposes.
Provide missing props the same way they are provided in other components.

chore(forms/NestedListView): Fix warnings

---

packages/icons/src/talendicons.font.js
packages/icons/src/talendicons.template.css

The `packages/icons/dist/talend-icons-webfont.css` file is badly generated as the build process misses to replace a selector.
Looking at the [documentation](https://www.npmjs.com/package/webfonts-loader#all-font-configuration-options) I saw that we were relying on a bad font configuration options. So I replaced it according to the documentation from the lib.

fix(icons) use baseSelector option to generate talend webicon css file properly

---

packages/components/src/Dialog/Dialog.scss
packages/components/stories/Dialog.js

The bottom of the modals' titles is cut off like so :
Update style 

fix(Dialog): Title cut off

---

output/theme.sasslint.txt
packages/theme/src/theme/_forms.scss

Guideline has evolved and we need to add an ellipsis on input value.
Add a ellispsis rule in the theme.

feat(theme): forms input ellipsis

---

packages/icons/src/talendicons.font.js

The format we use to generate the webfont files is incorrect and we generate things that the browser can't parse. See below screenshot:
Just changing the webfont generation file format:

fix(icons) generate webfont with [fontname].[ext] format

---

packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
packages/forms/stories-core/json/fields/core-resource-picker.json
packages/forms/stories-core/jsonStories.js

Validation fails on single selection (selected, then unselect => valid because an empty array is returned)
Return a single string if not multi

feat(form/resourcepicker): manage single selection

---

packages/components/src/Notification/Notification.scss

No animation in Notification due to a change #1972.
That's quite weird, because the 2 codes have a different behavior
```css
// css modules will transpile the name with the hash, and set it here.
// this uses tc-notification-slide-in as local variable (with transpiled name).
:global(.tc-notification-enter) {
animation: tc-notification-slide-in $tc-notification-animation-duration linear;
}
// this sets tc-notification-slide-in as global name.
// but animation names are transpiled, even if wrapped within a :global{} 
:global {
.tc-notification-enter {
animation: tc-notification-slide-in $tc-notification-animation-duration linear;
}
}
```
Use 1st format
**Please check if the PR fulfills these …

fix(Notification): animation

---

packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap

The QA members ask to have an ID missing in the Buttons of a default array template in UIForms.
I added the _id_ prop to the Action component inside the default array template in UIForms.

fix(frontend): missing ID in UIForm default array template Action

---

packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
packages/forms/stories-core/json/fields/core-datalist.json

On [frontify](https://company-57688.frontify.com/document/92132#/ui-controls/dropdowns), the user experience defined this behavior 
- type a filter
- when the user click outside without select a value
the input should be reseted
fix that by passing restricted to the component

fix(forms): handle restricted option on the widget Datalist

---

output/components.sasslint.txt
packages/components/src/Drawer/Drawer.scss
packages/components/src/Layout/Layout.scss
packages/theme/src/theme/_guidelines.scss

Since #1777, we cannot see `HeaderbBar` dropdowns while `Drawer` is opened anymore.
Adapt _z-index_ regarding the `Drawer` one.

fix(components/Headerbar): dropdowns with drawer

---

packages/cmf/src/sagas/index.md

The cmf http saga documentation describes options that are not cmf related.
Change this part to explain that you can pass any options that is given back to the app on http error dispatch.

fix(cmf): http saga options documentation

---

packages/containers/src/ComponentForm/ComponentForm.component.js
packages/containers/src/ComponentForm/ComponentForm.test.js
packages/forms/src/UIForm/UIForm.container.js
packages/forms/src/UIForm/UIForm.container.test.js

There is a breaking change introduced by #2024
The UIForm triggers is now handling the `properties` the trigger returns, overriding the current `properties`.
Before the PR, this was done only in ComponentForm.
* Revert this trigger `properties` return management from UIForm back to ComponentForm.
* we let the properties as modifier in UIForm
* another PR will set it back from ComponentForm to UIForm with a breaking change, scheduled for 3.x

fix(container/uiform): onTrigger update properties only if function

---

packages/scripts/webapp/preset/config/webpack.config.js

Some projects use the build timestamp as query params to download some settings.
Add the build timestamp via webpack configuration

feat(Scripts): add build timestamp

---

packages/scripts/webapp/preset/config/webpack.config.js

No loaders for images and svg
Add the loaders

feat(Scripts): add images and svg loaders

---

packages/cmf-webpack-plugin/src/index.js

cmf-webpack-plugin get the cmf merge config and modify it. But this modified config is not passed properly to the `merge()` function because of a typo.
Fix `options.cmfconfig` --> `props.cmfConfig` which is properly consumed by the merge function

fix(CMFWebpackPlugin): cmfConfig set properly (typo cmfconfig)

---

packages/scripts/package.json
packages/scripts/webapp/preset/config/webpack.config.dev.js

Talend/scripts has eslint loader in dev mode. But it makes it hard to read the console and takes more time to build.
Remove it from build. Eslint should be enforced via IDE plugins and CI run.

feat(Scripts): remove eslint from webpack build

---

packages/forms/src/UIForm/UIForm.container.js
packages/forms/src/UIForm/UIForm.container.test.js

UIForm trigger properties modifier calls onChange, but with only the properties.
That doesn't follow the classical onChange call.
Add the missing info

fix(UIForm): trigger properties modifier calls onChange with proper info

---

packages/scripts/webapp/preset/README.md
packages/scripts/webapp/preset/config/webpack.config.js

Some app don't use css modules, but talend/scripts default preset use css modules and there is no way to disable it.
Add an option to disable it in talend preset

feat(Scripts): option to disable css modules

---

packages/scripts/package.json
packages/scripts/webapp/preset/README.md
packages/scripts/webapp/preset/config/webpack.config.dev.js
packages/scripts/webapp/preset/config/webpack.config.prod.js

There is an incompatibility between cmf-webpack-plugin and copy-webpack-plugin.  
This is not new, and well documented in talend/scripts doc.
But most of the time, projects use settings in the way that it's incompatible. They will have to set `cmf: false` option, that doesn't make sense.
Change the default to not include the cmf plugin. To enable it, the cmf option need to be set to true.
But it's talend/scripts that is not in 1.0.

feat(Scripts): disable cmf webpack plugin by default

---

packages/forms/src/UIForm/fields/Select/displayMode/TextMode.component.js
packages/forms/src/UIForm/fields/Select/displayMode/TextMode.component.test.js
packages/forms/src/UIForm/fields/Select/displayMode/__snapshots__/TextMode.component.test.js.snap
packages/forms/src/UIForm/fields/Select/index.js
packages/forms/src/UIForm/utils/widgets.js
packages/forms/stories-core/customDisplayMode.js
packages/forms/stories-core/index.js

Issues on displayMode=text
* radios are not supported
* select is not supported
* button not supported
Add storybook with all field in text mode.
Add support for all existing fields
Demo: http://2057.talend.surge.sh/forms/?selectedKind=Core%20concepts&selectedStory=Core%20Concept%20displayMode%20text

fix(TUI-355/forms): improve displayMode=text

---

packages/scripts/webapp/preset/README.md
packages/scripts/webapp/preset/config/webpack.config.dev.js

In @talend/script talend preset, we define a devServer proxy, but it doesn't make sense, it's app specific.
Remove it. App will have to define their proxy in custom conf.

feat(Scripts): remove devServer proxy definition

---

packages/scripts/package.json
packages/scripts/webapp/preset/config/webpack.config.js

From non "/" path, the refresh produce a bad path for assets (style, ...), including the non root context.
Add the missing public path in webpack output config to produce url with / context.

fix(Scripts): output public path

---

packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap

we have regression with [Talend/ui#2022](https://github.com/Talend/ui/pull/2022). chrome don't handle flex on button element very well. The overflow hidden is not respected.
So, we remove button by div and restore accessibility action(press space and enter) to select the column

fix(datagrid): miss ellipsis on the large header

---

packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
packages/components/src/List/Toolbar/Toolbar.scss

Visual Regression from #2012, display menu in toolbar are in lower case
This is du to the svg element before the test, the first-letter is not applied.
Restore capitalize + add specific first letter in sort menu that has no icon.

fix(List): toolbar menu text capitalisation

---

output/components.sasslint.txt
packages/datagrid/src/components/DataGrid/DataGrid.component.js

js errors occurs when the user clicks on the header and no onFocusColumn defined on the Datagrid props
fix that

fix(datagrid): js error when onFocusColumns is not defined

---

packages/scripts/package.json
packages/scripts/webapp/preset/config/.eslintrc

When using immutableJS, List and Map give a lint error because they are not used with new.
Exclude them from the lint rule.

fix(Scripts): eslint remove List and Map from mandatory new

---

packages/scripts/package.json
yarn.lock

There is a security issue with handlebar (https://npmjs.com/advisories/755).
We need to upgrade to 4.0.13+
- Talend/scripts: remove karma-coverage (which is not used) that caused a dependency to handlebars 4.0.1.
- yarn.lock: force resolution to 4.1.0. Yarn was not resolving all the versions with a unique compatible version.

chore(TUI-370/Scripts): remove unused karma-coverage - security issue

---

packages/components/src/Datalist/Datalist.component.js

If we have datalist with multiSection: true, and a section with an empty-line title '' then it treating titlemap like it regular single-section title map.
Added additional undefined check.

fix(Datalist): updated datalist titlemapping function title check

---

packages/scripts/webapp/preset/config/babel-resolver.js

* Adding a custom .babelrc file fails because node relies on the file extension to parse js or json.
* Babel accepts `.babelrc` (json), `.babelrc.json`, `babelrc.config.js`, but we consider only `.babelrc` file.
* Add a specific case to load `.babelrc` file
* support the 3 types of user custom files

fix(Scripts): custom .babelrc file load

---

packages/components/src/GuidedTour/GuidedTour.component.js
packages/components/stories/GuidedTour.js

I tried to inject `div` into `p`
Render valid html by wrapping it with a `div`

fix(components/GuidedTour): valid html

---

packages/scripts/package.json
packages/scripts/webapp/preset/config/webpack.config.js

Index.html is excluded from html loader, but the path to exclude it is slash separated, that makes it windows incompatible.
Use `path.join()`.

fix(Scripts): use path to build file path forw windows compat

---

packages/scripts/webapp/preset/README.md

When trying to enable eslint in the IDE (with talend-scripts eslint config) the `extends` path will try to fetch an npm module prefixed with `eslint-config-` resulting in `@talend/eslint-config-scripts/preset/config/.eslintrc` (which doesn't exist). 
Update documentation to use relative path into node_modules to get the correct path `./node_modules/@talend/scripts/webapp/preset/config/.eslintrc`

fix(scripts): Update path for eslint in IDE

---

packages/components/src/OverlayTrigger/OverlayTrigger.component.js

Tooltip not displayed for actions with overlay on mouse over
https://jira.talendforge.org/browse/TUI-380
**Cause:**
The OverlayTriggerComponent is created to show PopOver on click **{ trigger: 'click' }** so the events 
onMouseOver and onFocus provided from TooltipTrigger is overridden by the Bootstrap OverlayTrigger.
**Solution:**
Attach those events manually to the OverlayTrigger
**Demo:**
Action with popover ->
http://2139.talend.surge.sh/components/?selectedKind=Action&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

fix(TUI-380): Tooltip not shown for actions with overlay

---

talend-i18n.json

Talend/ui XTM project name has changed
Update it in talend-i18n config

chore(i18n): update talend-i18n project name

---

packages/containers/src/HeaderBar/HeaderBar.sagas.js
packages/containers/src/HeaderBar/HeaderBar.sagas.test.js

`HeaderBar`'s `handleOpenProduct` breaks after it's used once under Edge. This causes the applications list in the header bar to only work once (saga is killed due to the error).
Remove the instruction that breaks under Edge, it doesn't seem to be useful and is not impeding the new window's opening.
Fix was picked from https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ (courtesy of @jmfrancois) but the instruction is not mentionned there.

fix(containers/HeaderBar): Broken saga on Edge

---

packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
packages/forms/stories-core/json/fields/core-datalist.json

This reverts commit cc7a1fc3c44f07bf833dc55412c64b006baf8c76.
This behavior is not requested by UX guideline, and introduces issues in all form containing datalists.
Revert

Revert "fix(forms): handle restricted option on the widget Datalist (#2029)

---

packages/components/src/ActionBar/ActionBar.component.js
packages/components/src/ActionBar/ActionBar.scss
packages/components/stories/ActionBar.js

Add app specific multi-select actions.
if app specifical actions provided, show them right to common multi-select actions with a divider
add prop `appMultiSelectActions` of actions list.

feat(ActionBar): Mass Actions: add support for app multi-select actions

---

packages/scripts/webapp/preset/config/jest.config.js

Windows users can't launch unit tests anymore, due to wrong value for testRegex in jest.config.js.
Fix regex.

Fix(scripts):  testRegex in jest.config.js for Windows users

---

packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.test.js
packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBoxes.test.js.snap

Currently checkboxes onFinish receive a boolean as a value instead of the array of value like the onChange callback which results in the following error: 
passing the array of checked values as value for onFinish

chore(Forms): fixing validation when using array type with checkboxes

---

packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/UIForm.component.test.js
packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
packages/forms/stories-core/customHoverSubmitStory.js
packages/forms/stories-core/index.js

We need to detect hover on the UIForm submit button (this trigger a preview on TDP).
Add `onSubmitEnter` and `onSubmitLeave` props.

feat(forms): add hover handlers for the submit button

---

packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
packages/components/src/VirtualizedList/CellDatetime/__snapshots__/CellDatetime.test.js.snap

When a datetime cell shows a relative date it'd be useful to show the full date inside a tooltip.
Wrap the tooltip in the relative date div.

feat(component): TMC-13918 show full date in a tooltip when base date is relative in a column cell

---

packages/containers/src/Form/Form.container.js

linked to #2206, the condition was not the good
need to return nextprops data when it's not equal
thanks @lmaillet for the feedback
add `!`before the `isEqual`

fix(container/Form): fix deep equal check in derivedStateFromProps

---

packages/forms/src/UIForm/UIForm.container.js

In order to filter filtered properties on the project side (to avoid breaking changes on TUI), we've to pass the mergedSchema to props.onSubmit. The goal is to implement #2204 on TDP. Container was missing from my previous commit.
Pass the mergedSchema to props.onSubmit and close #2204.

fix(form): call onSubmit with mergedSchema

---

packages/components/src/List/ListComposition/DisplayMode/DisplayModeToggle.scss
packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.test.js
packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
packages/components/stories/ListComposition/ListComposition.js

Toolbar and display mode in list composition are not up to date.
Using what have been done in https://github.com/Talend/ui/pull/2162, in this pr we are gonna update the display mode
[Frontify](http://guidelines.talend.com/document/92132#/navigation-layout/list-toolbar)
Display mode is now represent by icon and toolbar is on a unique line.

feat(ListComposition/DisplayMode):  update design

---

packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss

toolbar could shrink in composition mode
Also with an action bar inside, the action bar padding create a 40px left padding to get the first button
change the paddings & the flex-grow

fix(toolbar): update composition list toolbar size

---

packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.component.js
packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.scss
packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.test.js
packages/components/src/VirtualizedList/RowCollapsiblePanel/__snapshots__/RowCollapsiblePanel.test.js.snap
packages/components/stories/ListComposition/ListComposition.js

"Collapsible panel" mode of lists currently does not support having unloaded data in a row (it shows an empty element).
As for the "table" mode, assume that if data is missing, it is being loaded (used for infinite scroll feature) and show its loading state (built with skeletons).
See guidelines here : https://company-57688.frontify.com/document/92132#/navigation-layout/expandable-collapsible-panels/skeleton-loading (_Skeleton loading_ section)

feat(components/VirtualizedList): Loading state for collapsible panel

---

packages/components/src/ActionIntercom/Intercom.component.js

In a local environment we used the intercom component without an email. This worked fine, but only until you closed and reopened the widget. Then all messages sent **to** the user were not received anymore. 
In fact Intercom uses email as identifier and without this it will not be able to do the connection between the user in the app and the user in Intercom. name was provided but is not used as identifier. 
However there were no errors or warnings about this, and found no clear info about it in the docs. 
Lets at least make the prop required so we have some indication that we must have it. 

fix(components): make email a required prop

---

output/components.eslint.txt
packages/components/src/GridLayout/Grid.component.js
packages/components/src/GridLayout/Tile/Tile.scss

Tile content wasn't shrinking which made it overflow from the tile container.
In addition we're changing compact type to horizontal, because the vertical one does'nt allow us to place an element under a blank space.
setting min-height to 0

fix(GridLayout): issue with shrink when content is bigger than tile and changing compact type

---

.travis.yml

`oracleJDK8` is not supported anymore in travis.
Use openJDK to stay in jdk 8

chore(ci): use openJDK8 instead of oracleJDK8

---

npm-audit/html-webpack-plugin.json
npm-audit/router.json
packages/components/src/Notification/Notification.component.js
packages/components/src/Notification/Notification.test.js

_It refers to a TCCUI topic._
Notifications have a timer (except errors). At the end of the timer, the notification disappears. But when the user hovers on it, the timer stops.
On mouse/focus out, the timer doesn't start again.
On mouse/focus out, the timer should start from the paused state, closing the toaster when time is up.
Note that errors notifications are out of this rule if the notification center is not in use.

feat(components/notification): pause/resume when mouse is entering/leaving

---

packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js

Since this PR https://github.com/Talend/ui/pull/2199/files, title edition does not work anymore.
Spread args to `onSubmit` and other handlers.

fix(components/subheaderbar): title edition does not work

---

packages/components/src/ActionIntercom/Intercom.component.js
packages/components/src/ActionIntercom/Intercom.component.test.js

The intercom button switch the icon from bubbles to a cross when it's open.
But the intercom window already has a cross.
To avoid the double cross, UX team ask us to remove the cross from the button as the one in intercom window is not controlled by us.
The icon doesn't change on open/close, it's still the bubbles.

fix(Intercom): remove cross from button to avoid double cross

---

packages/containers/src/ComponentForm/ComponentForm.actions.js
packages/containers/src/ComponentForm/ComponentForm.saga.test.js
packages/containers/src/ComponentForm/ComponentForm.sagas.js

When we have the submit result action, we have the response from the backend. Except this response is {id, requestId} and any information on the form. 
spread formData on the action

feat(forms/TDC-876): pass formData in the result action

---

packages/components/src/HeaderBar/HeaderBar.component.js

When headerbar rerenders it will _always_ rerender the Intercom too. This is a problem because in the Intercom component it will disconnect and reconnect with the new config object, resulting in unnecessary network requests (and rerenders). 
This is the useEffect that will always be triggered since `config` has changed https://github.com/Talend/ui/blob/master/packages/components/src/ActionIntercom/Intercom.component.js#L19
Memoize the `config` prop before sending it, so it doesn't create a new object if the config is the same

fix(components): Prevent intercom from rerendering with same props

---

output/containers.eslint.txt
packages/containers/src/DeleteResource/sagas.js
packages/containers/src/DeleteResource/sagas.test.js

when the webapp catches the action DELETE_SUCESSFUl, we haven't no information about the model
pass the model to the action

feat(Containers/DeleteResource): pass action property to sucessful action

---

packages/components/src/MultiSelect/MultiSelect.container.js

searchTerm is not cleared when the form props change, so it's misleading for a user that is switching between multiple entity with the same type and so same form.
Automatically clear the searchTerm when the dropdown close.

fix(component/MultiSelect): clear searchTerm on dropdown close

---

packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss

http://guidelines.talend.com/document/92132#/navigation-layout/sub-header/details
> Edition
> The user can edit the file title by clicking on the 'edit icon' which is visible on hover. 
Added a display none on the icon

fix(components/SubHeaderBar): subheader edit icon should only be visible when hover on title

---

packages/components/src/ListView/ListView.component.js
packages/components/src/Typeahead/Typeahead.component.js
packages/components/src/VirtualizedList/NoRows/NoRows.component.js

There is no translation for the default value of the Typehead component
Add one & share the translation with same content

fix(component): add missing translation

---

packages/components/stories/Enumeration.js
packages/components/stories/GuidedTour.js
packages/components/stories/HeaderBar.js
packages/components/stories/List.js
packages/components/stories/ListView.js
packages/components/stories/SidePanel.js
packages/components/stories/config/i18n.js
packages/containers/examples/ExampleDeleteResource.js
packages/containers/examples/ExampleList.js
packages/containers/examples/config/i18n.js
packages/datagrid/stories/config/i18n.js
packages/datagrid/stories/datagrid.component.js
packages/datagrid/stories/datagrid.container.js
packages/forms/.storybook/config.js
packages/forms/stories-core/index.js

There is an issue with react-i18next, described here : https://github.com/i18next/react-i18next/issues/750#issuecomment-508092824
Some stories use i18next provider, others don't, which introduce a bug, trying to destructure undefined.
Remove react-i18next provider from stories, and configure i18next, exposing the configuration.

fix: stories with i18n, removing provider

---

packages/forms/src/UIForm/fields/CheckBox/README.md
packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js
packages/forms/stories-core/json/fields/core-checkbox.json

UIForm does not deal with data-feature for each field
Be able to render data-feature attribute for Checkbox from `uiSchema`

feat(forms/checkbox): data-feature

---

packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.test.js
packages/components/stories/Drawer.js

On drawer, cancel button style also applies to the cross in the header.
And if you set a className on the cancel Action, it will override the default className from the Action in the header, and theme will not be applied.
Do not override theme in the Cancel action component, even if user add className in the CancelAction.

fix(drawer): do not override theme for cancel Action

---

packages/components/package.json
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
packages/components/stories/DatePicker.js

Datepicker has `position: absolute` so it's quickly hidden when its parents have fixed height
Choose `position: fixed` to deal with parents overflow
To do so, I added a new dependency : [Popper.js](https://popper.js.org)
https://github.com/FezVrasta/react-popper
https://bundlephobia.com/result?p=react-popper@1.3.3

feat(components/datepicker): fixed position

---

packages/components/src/Typeahead/Typeahead.component.js

The import is importing as if it's a named export, when in fact it's a default export
Change to "deafult import"

fix(components/Typeahead): import I18N_DOMAIN_COMPONENTS

---

packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js

Translation team had an issue understanding if a key is singular or plural.
In ObjectViewer, we have a key: `TC_OBJECT_VIEWER_NB_CHILDREN`. It contains a `count` variable, i18next-scanner will extract 2 keys:
- `TC_OBJECT_VIEWER_NB_CHILDREN`
- `TC_OBJECT_VIEWER_NB_CHILDREN_plural`
It's quite confusing that the singular version is `children`. Furthermore, the default value contains `children`
Set the key and default translation to singular, so we'll have 2 keys : 
- `TC_OBJECT_VIEWER_NB_CHILD`
- `TC_OBJECT_VIEWER_NB_CHILD_plural`

chore: set key and default translation to singular

---

packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.scss

The background of the order buttons is gray, it should be white
n.b : cannot be seen on mac/chrome but on others

fix(Resourcepicker): order chooser color

---

output/forms.eslint.txt
packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap

If actions are passed to an `UIForm`, `onSubmitEnter` is ignored.
If `onSubmitEnter` is given to the `UIForm`, add it to the submit action.

fix(forms): onSubmitEnter should be passed all of the time

---

packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap

Generated ids for forms buttons contain form id twice
Remove duplicate

fix(forms): forms buttons ids generation

---

packages/components/src/TooltipTrigger/TooltipTrigger.component.js
packages/forms/src/UIForm/Widget/Widget.component.js
packages/forms/src/UIForm/Widget/Widget.component.scss

Form tooltip triggers are displayed as `inline-block` which it breaks Form layout
In the forms, display them as `block`

fix(forms): display tooltips as block

---

packages/components/src/DateTimePickers/DateTime/Input/Input.component.js
packages/components/src/DateTimePickers/DateTime/Input/Input.component.test.js
packages/components/src/DateTimePickers/DateTime/Input/__snapshots__/Input.component.test.js.snap
packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js
packages/components/src/DateTimePickers/DateTime/Manager/__snapshots__/Manager.component.test.js.snap
packages/components/src/DateTimePickers/DateTime/date-extraction.js
packages/components/src/DateTimePickers/DateTime/date-extraction.test.js
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap

Update `Input.component.js` with new prop 'type', so it can render a date input or time input conditionally.
Next steps:
Add InputTimePicker.
Update context Manager to handle input change and picker change for date/time.

feat(TimePicker): update input component

---

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss

In the List component, when the main column (title column) doesn't have any action associated, the label isn't centered.
See https://jira.talendforge.org/browse/TPSVC-10683
Problem can be seen here : http://talend.surge.sh/components/?path=/story/list--title-without-click
Remove `height: 100%;` from `.main-title`.
Fixed problem : http://2333.talend.surge.sh/components/?path=/story/list--title-without-click

fix(List): list title cell not centered

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.scss

https://jira.talendforge.org/browse/TMC-18302
Previously TooltipTrigger used overlay, now after refactoring there is a div wrapper which is always rendered, and the tooltip content which is rendered using portal
The problem is that cancel button is absolutely positioned, and the tooltip div wrapper is inline block, so as a result tooltip wrapper increases drawer title height, button itself is out of the flow, and when hovering over the button tooltip appears under the title
Absolutely position the tooltip div wrapper

fix(TMC-18302): issue with drawer title

---

packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
packages/components/stories/GridLayout.js

the picker button were not clickable when used in react-grid-layout because, mousedown is used for the drag feature whereas we use click in the picker.
stopping propagatin of the mousedown event

fix(DatePicker): stop propagation of mouse down in the whole picker

---

packages/components/src/Notification/Notification.scss
packages/theme/src/theme/_variables.scss

Notification is below the modal, popover
Set a z-index more hight to set the component Notification above the others

fix(Notification): set Notification above the other

---

packages/theme/src/theme/_breadcrumbs.scss
packages/theme/src/theme/_hyperlinks.scss
packages/theme/src/theme/_labels.scss
packages/theme/src/theme/_type.scss
packages/theme/src/theme/_variables.scss

Guideline only define 3 font sizes
https://company-57688.frontify.com/document/92132#/design-principles/font-styles/weights
To follow the guideline, update `$font-weight-bold` and create `$font-weight-semi-bold` and `$font-weight-regular`.

fix(Theme): follow guidelines on bold

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.test.js

_(This is part of a series of PR to improve api, and help to switch from List legacy component to List Composition)._
To help deal with selection, we had the container before. Let's drop that and externalize the selection management into a hook while composing the list.
Create a hook to deal with
- selection state
- item toggle management
- select all state
- select all toggle management
- predicate to check the selection status of an item
Those will be helpful to pass to the list parts props.

feat(ListComposition): collection selection hook

---

packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.test.js
packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap

We want to add a label props to allow more precise information on tooltip thant "delete"
Add the props and fix a typo on the delete default value delete => Delete
* [] Docs have been added / updated (for bug fixes / features)

chore(Badge): Add a props label to BadgeDelete

---

output/components.eslint.txt
packages/components/src/List/ListComposition/Manager/ListManager.component.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.test.js
packages/components/src/List/ListComposition/index.js

Collections always comes without actions. The actions are defined afterward, and List container insert them into the each item.
For list composition, let's avoid writing that too.
Create a hook to insert actions (also called title actions), and persistent actions.

feat(ListComposition): hook to insert actions into collection

---

packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.scss
packages/components/src/DateTimePickers/InputTimePicker/index.js
packages/components/src/DateTimePickers/hooks/useInputPickerHandlers.js
packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
packages/components/stories/DatePicker.js

Add InputTimePicker which can be used standalone.

feat(TimePicker): Add InputTimePicker

---

output/components.eslint.txt
packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
packages/components/src/VirtualizedList/utils/tablerow.js
packages/components/stories/ListComposition/ListComposition.js

The need: we want to add different attributes on cell title button, depending on the row data.
For example: a `data-feature` with value `folder.open` or `preparation.open` if the item is a folder or a preparation.
Allow the columnData prop to be a function

feat(VirtualizedList): title cell accepts functions as column data

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.test.js

In the list, each item can have specificities, and we want to activate/deactivate some item actions depending on the item.
Example: share action in shareable items, and not in other.
In hook that insert the actions in the items, allow to pass a function

feat(VirtualizedList): custom actions by item in collection actions hook

---

packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js

CellTitle columnData props can now be a function but the proptypes haven't been updated.
Fix the proptypes

fix(VirtualizedList): cell title propTypes

---

packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js

When a dropdown has not enough place on the bottom, it switches automatically to dropup.
But when there is no space on top, the menu is just not displayed
Do not switch to dropup when there is not enough space
Bonus: as I go through the file, I removed an access to key props that is not a prop, but an internal react prop. It is always undefined when we try to access to it.

fix(Dropdown): down to up is disabled when there is not enough space

---

packages/forms/src/UIForm/fields/Select/Select.component.js
packages/forms/src/UIForm/fields/Select/Select.component.test.js
packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
packages/forms/stories-core/json/fields/core-select.json

In an empty form, the placeholder of the select is not selected, nor visible, but the first element of the list is selected.
Add an empty value to the option with the placeholder in order to have this one selected.
Storybook example : http://2385.talend.surge.sh/forms/?path=/story/core-fields--core-select

fix(form): select placeholder

---

packages/components/src/List/ListComposition/SortBy/SortBy.component.js

After discussion with @nicomaligne and @jsomsanith-tlnd, the display of the condition to display the sortBy component need to be managed by the app and not by the component himself
Revert the change made in https://github.com/Talend/ui/pull/2365 for the sortby component

Revert(components): ListComposition SortBy render condition

---

versions/version.js

When using Talend/UI's `version.js` script to upgrade dependencies, sometimes dependency will downgrade because they have already been upgraded on project's side.
Highlight downgraded packages and provide a new option (`-u --upgrade-only`) to only perform upgrades.

chore(version.js): Upgrades only option + downgrades highlights

---

output/components.sasslint.txt
packages/components/src/Typeahead/Typeahead.component.renderers.js
packages/components/src/Typeahead/Typeahead.scss
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
packages/theme/src/theme/_variables.scss

https://jira.talendforge.org/browse/TMC-18455
After using popper, we have an issue with datalist positioning, if there are too many items that do not fit to screen, popper sets top position, although there are much more available space at the bottom (see on video attached to the jira)
The idea is to compute where is more available space and position items container accordingly, setting also max height so it won't go out from screen boundaries

fix(TMC-18455): data list positioning

---

packages/components/src/List/ListComposition/List.scss

The old list take the all available height , not the composition list
fix that

fix(components): the list doesn't take the all available height 

---

packages/components/src/AboutDialog/AboutDialog.component.js
packages/components/src/AboutDialog/AboutDialog.snapshot.test.js

About modal has a `2018` hard coded year in i18n default value.
Use current date

fix(About): year in copyright

---

packages/components/src/TabBar/TabBar.component.js

when the tab bar is in a drawer, all the page is scrolling to focus on the tab
prevent scroll

fix(components): scrolling with TabBar in drawer

---

packages/components/src/List/ListComposition/List.scss

We found a very specific bug in TDInventory. At specific resolution or when zooming in the browser we could have a flicking scrollbar.
Hide the overflow property on the list component.

fix(Components): overflow in list composition

---

packages/components/src/DateTimePickers/Date/Input/Input.component.js
packages/components/src/DateTimePickers/Date/Input/__snapshots__/Input.component.test.js.snap
packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
packages/components/src/DateTimePickers/Time/Input/Input.component.js
packages/components/src/DateTimePickers/Time/Manager/Manager.component.js
packages/components/src/DateTimePickers/Time/Manager/__snapshots__/Manager.component.test.js.snap
packages/components/src/DateTimePickers/shared/InputSizer/InputSizer.component.js
packages/components/src/DateTimePickers/shared/InputSizer/InputSizer.component.test.js
packages/components/src/DateTimePickers/shared/InputSizer/index.js

Apply styles of guideline.
Changes includes:
* add space between date picker and time picker
* set input width base on content

feat(DateTimePicker): styles

---

packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.js
packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.test.js
packages/forms/src/UIForm/fieldsets/Fieldset/__snapshots__/Fieldset.component.test.js.snap

Fieldset title and its items can be empty.
Adapt, improvise, overcome its markup.

fix(forms/fieldset): markup with empty title or items

---

packages/cmf/__tests__/onError.test.js
packages/cmf/src/onError.js

We have some errors on the console when the value on the settings is null
return empty string if the value is null
* [] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review

fix(cmf): trigger error on console when the value on the setting is null

---

packages/forms/src/UIForm/fieldsets/Array/Array.component.js
packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js

If a form schema have an array of select, we set default value as `''`. Problem, we have trouble with validation because we set a value that is not in enum.
Schema example:
```
{
"jsonSchema":{
"type":"object",
"properties":{
"Color":{
"type":"array",
"minItems": 1,
"items":{
"type":"string",
"enum":[
"White",
"Lemon",
"Khaki"
]
}
}
}
},
"uiSchema":[
{
"key":"Color",
"type":"array",
"items":[
{
"key":"Color[]",
"type":"select"
}
],
}
],
"properties":{
"Color":[]
}
}
```
When we click on Add element button, we set the first enum item as a value, if we have a single select.

fix(UIForm/Array): For single select, set default value as first enum item

---

packages/components/src/VirtualizedList/VirtualizedList.component.js

renaming controlled width
widthsOfColumns

chore(Component): renaming resizing variable in virtualized list

---

packages/forms/src/deprecated/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss

quick fixing this for project using semantic type, as migration to new form is in process.

fix(TSD-408): double scroll bar on deprecated multi tag select

---

packages/forms/src/UIForm/fields/Comparator/README.md
packages/forms/src/UIForm/fields/Text/Text.component.js
packages/forms/src/UIForm/fields/Text/Text.component.test.js
packages/forms/stories-core/json/fields/core-text.json

Cannot add step attribute to `input[type="number"]` at the moment.
Let's be able to add it like `min` and `max`

fix(forms): step attribute for input with type number

---

packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss

Force `display: block;` on svg.

fix(components/subheaderbar): icon not centered on ie

---

packages/components/src/List/ListComposition/index.js

`useCollectionSelection` is not exposed in ListComposition index, therefore it can't be used by _list composers_
Expose the hook like the other ones.

fix(components/ListComposition): Expose useCollectionSelection hook

---

packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js

- It's not possible to display a non string subtitle (for example, a link) without warning
- Changed the proptype to node

fix(components/titlesubheader): fix warning when using non string subtitle

---

packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.scss

http://guidelines.talend.com/document/92132#/ui-controls/date-time-picker-1561102408
change the padding of navigate button according to ux's design

feat(TCCUI65 date picker)improve the padding for arrow

---

packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss

http://guidelines.talend.com/document/92132#/ui-controls/date-time-picker-1561102408
move black border for focus, it will use the default accessbility style.

feat(TCCUI-65/date picker): move black border for date button focus

---

packages/cmf/__tests__/onError.test.js
packages/cmf/src/onError.js

issue with onError when value is undefined
manage this specific case and update test

fix(cmf): onError when value is undefined

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js

There is an error when a value in the list is null (not undefined)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
Manage the both case null and undefined with isNil

fix(component): ListComposition -error with filter hook when a value is null

---

packages/components/src/FilterBar/FilterBar.component.js
packages/components/src/FilterBar/FilterBar.test.js

Input form `FilterBar` is not reachable from E2E tests (Cypress)
Be able to pass `data-test` to the generated input

feat(components/FilterBar): data-test

---

output/components.eslint.txt
output/components.sasslint.txt
packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
packages/components/src/Status/Status.component.js
packages/components/src/Status/Status.scss
packages/components/src/Status/Status.snapshot.test.js
packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
packages/components/stories/CollapsiblePanel.js

In order to finish Task Execution live updates feature in TMC (updates come from server side),
we need a way to set execution status with a skeleton, as we don't know actual status at the moment.
Please take a look to mock-up:
https://jira.talendforge.org/secure/attachment/203492/image.png
I added 'skeleton' status to header props.

feat(components/CollapsiblePanel): add skeleton instead of status text

---

packages/components/src/DateTimePickers/shared/styles/mixins.scss

In the date picker, click to another day, the background have a little delay. We have the white text color and grey background at the beginning, it’s pretty annoying.
the reason is in the tertiary button, there is a transition to the background.
`transition: background 0.2s ease-in;`
I will try to add a transition to the color  of `selected` button.
`transition: color 0.2s ease-in;`

feat(date picker)add a transition to selected color

---

output/forms.eslint.txt
packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js

Since the introduction of an internal state which is used in the input checked attribute, the checkbox doesn't update anymore when changing properties in form.
Removing the state and use the "value" props for the input checked attribute

fix(Forms/SimpleCheckbox): using value props for checked attribute

---

output/components.sasslint.txt
packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.scss

With this pr #2413, the selector is incorrect on the ressource picker. The button to remove the current filter doesn't display
fix the selector

fix(components/ResourcePicker): display the button to remove the filter

---

output/components.eslint.txt
packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
packages/components/src/List/__snapshots__/List.test.js.snap
packages/components/src/ResourcePicker/__snapshots__/ResourcePicker.snap.test.js.snap
packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.component.js
packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.test.js
packages/components/src/VirtualizedList/CellCheckbox/__snapshots__/CellCheckbox.test.js.snap
packages/components/src/VirtualizedList/PropTypes.js
packages/components/src/VirtualizedList/VirtualizedList.component.js
packages/components/src/VirtualizedList/utils/__snapshots__/tablerow.test.js.snap
packages/components/src/VirtualizedList/utils/constants.js
packages/components/src/VirtualizedList/utils/tablerow.js
packages/components/stories/VirtualizedList.js

We are not able to display radio buttons in front of a row to indicate that only a single element is selectable.
Introduce a `selectionMode` which can take `SINGLE` or `MULTI` to the list.

feat(components/list): allow single selection

---

packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
packages/forms/src/UIForm/fields/Comparator/Comparator.component.test.js
packages/forms/src/UIForm/fields/Comparator/Comparator.scss
packages/forms/src/UIForm/fields/Comparator/__snapshots__/Comparator.component.test.js.snap
packages/forms/src/UIForm/fields/Comparator/displayMode/TextMode.component.js
packages/forms/src/UIForm/fields/Comparator/displayMode/__snapshots__/TextMode.test.js.snap
packages/forms/stories-core/json/fields/core-comparator-input.json

`Comparator` still uses the operator as a string
`Comparator` can use Talend icons

feat(forms/comparator): display icons

---

output/components.sasslint.txt
packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
packages/components/stories/CollapsiblePanel.js

When we nest CollapsiblePanel, we loose the border on nested component. This is make the usage unreadable, mostly on form.
The problem was introduced in this PR: [https://github.com/Talend/ui/pull/229](https://github.com/Talend/ui/pull/229) for this JIRA ticket: [https://jira.talendforge.org/browse/TUX-207](https://jira.talendforge.org/browse/TUX-207)
This was made for a TDP component.
Remove a global scss override, and create a story to show this specific usage.
Story: [http://2478.talend.surge.sh/components/?path=/story/collapsiblepanel--nested](http://2478.talend.surge.sh/components/?path=/story/collapsiblepanel--nested)
**[ ] This …

fix(CollapsiblePanel): Fix border with nested components

---

packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss

There is no border when the ActionIconToggle has the focus
Specify one

fix(ActionIconToggle): transparent border on focus

---

packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.component.js
packages/components/src/DateTimePickers/pickers/CalendarPicker/__snapshots__/CalendarPicker.test.js.snap
packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap

This is to fix 2 issues of date picker gesture:
* `YearPicker`: The arrows (up/down) should not be focusable. 
* `Today` button should be focusable when focus in picker popper, and not focusable when focus is outside of picker popper.

Fix(date picker): fix focus issue of date picker

---

packages/forms/src/UIForm/fields/Select/Select.component.js
packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap

In `<Select />` component, the `descriptionId` and `errorId` props are not passed to `<FieldTemplate />`, which is needed in propTypes (link: [https://github.com/Talend/ui/blob/master/packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js#L50](https://github.com/Talend/ui/blob/master/packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js#L50) ).
This is generate 2 warnings in console for each select in a forms. 
Just pass the two props with respective values.

fix(forms/Select): Add missing descriptionId / errorId props

---

packages/components/src/FocusManager/FocusManager.component.js

In `<FocusManager />` component, the prop definition is wrong for `divRef`. 
ref can be an object (when using `useRef` or `React.createRef()`) or a function (when using it as a callback).
Just fix prop declaration with a union.
This prevent some warning in console, specially in form which use this as an object (ex: https://github.com/Talend/ui/blob/master/packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js#L73)

fix(components/FocusManager): support ref as object in PropTypes

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js

When we use a hook named `useCollectionActions` from the List component, 
it fails if the collection is not yet available.
Use default value to avoid error

fix(components/list): default value for collection using useCollectionActions hook

---

packages/faceted-search/src/components/Badges/BadgeText/BadgeText.scss

In text badge, the resize of textarea do not work properly: 
- Textarea can be more larger than the popover
- Visual glitch appear
- Browser can shutdown on Windows > Chrome
As resize textarea do not take part of the guideline, we simply remove this feature.
Guideline: [https://company-57688.frontify.com/document/215501#/navigation-layout/filtering-search](https://company-57688.frontify.com/document/215501#/navigation-layout/filtering-search)

fix(faceted-search/BadgeTextArea): Disable resize on textarea

---

packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js

In faceted popover, when we need to choose a field, we have a search bar to help us.
Today, filtering is based on `attribute` string of badge definition, not on `label`.
Problem is, `attribute` can be really a technical key (like `product/name`). We need to filter by label, which is the value displayed to user in list below.
We also need to made label case insensitive because the `includes()` method is case sensitive.
- Filter by `label`, not `attribute`. 
- Make it case insensitive.
- Add some tests.

feat(faceted-search/AddFacetPopover): Filter badge by label, not attribute

---

packages/components/src/TooltipTrigger/TooltipTrigger.component.js

TPD needs to apply a custom style to tooltips, but raw css classes are not exposed.
Add row css classes.

feat(components/tooltiptrigger): expose css classes

---

packages/faceted-search/src/queryClient/tql.js
packages/faceted-search/src/queryClient/tql.test.js

Operator in and empty array throw a js exception.
Add a condition to remove any badge with [], to avoid problems.

fix(FacetedSearch): tql error on empty value array

---

packages/components/src/VirtualizedList/CellBoolean/BooleanColumn.component.js
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.component.js
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.scss
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.test.js
packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
packages/components/src/VirtualizedList/CellBoolean/index.js
packages/components/src/VirtualizedList/index.js
packages/components/stories/ListComposition/ListComposition.js
packages/components/stories/ListComposition/collection.js

There is no boolean column type in List Composition
Add it

feat(components/listcomposition): add boolean cell type

---

packages/components/src/List/ListComposition/SortBy/SortBy.scss

on Firefox, there's problem of alignment with sort by elements:

fix(ListComposition): fix alignment of sort by elements

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.test.js
packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap

We need to adjust tooltip label on add / remove filter:
- Add button: `Add filter`
- Delete button: `Remove filter`
Jira ticket: [https://jira.talendforge.org/browse/TDC-2947](https://jira.talendforge.org/browse/TDC-2947)
Just update the default value on label, fix tests and snapshots.

feat(faceted-search/labels): Update tooltip labels

---

packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
packages/forms/src/UIForm/fields/Toggle/Toggle.component.test.js
packages/forms/src/UIForm/fields/Toggle/__snapshots__/Toggle.component.test.js.snap

in order to call trigger when toggle value change we need it to be like checkbox and call onFinish after.
calling onFinish in the onChange event

chore(forms/Toggle): calling onFinish on change event

---

packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap

onSubmit execution in `BasicSearch` is conditioned based on badges length. We don't want that anymore, it need to be done on the app side.
Remove the condition.

fix(faceted-search/BasicSearch): Do not contrain onSubmit trigger

---

packages/faceted-search/src/dictionary/operator.dictionary.js
packages/faceted-search/src/queryClient/tql.js
packages/faceted-search/src/queryClient/tql.test.js
packages/faceted-search/stories/facetedSearch.story.js

`notEqual` operator is available in operators dictionary as a standard one. 
Problem, when we try to use it in a text badge with the `createTqlQuery` adapter, it pop an error: ` TypeError: queryFunction is not a function`
This is because a mapping is missing in the tql converter function `getTqlClassOperatorsDictionary`
Just add the key / value in the mapping function, add some tests / improve story
Also take the opportunity of this PR to rename the `=` operator in `equal`. **Be aware that it's a breaking change and that's need some changes on app usage.**

fix(faceted-search/tql): Full support of operator notEqual

---

packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.connect.js
packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.test.js

We need to remove deprecated react 15 lifecycle methods.
This PR is only on cmf-cqrs package.
- Remove the call from `componentDidMount()`
- Remove the call from `componentWillReceiveProps()`
- Replace them with a call in `render()` instead. There is already a `componentShouldUpdate()` that checks if the props.acks has changed. So `render()` is only called on new props.acks, and will process them.

chore(CQRS): remove componentWillReceiveProps

---

packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss

since using flex box in the separator actions PR, a regression has been introduced : 
switching width only on hover and focus

fix(List): cell title actions makes the title unreadable

---

packages/components/src/DateTimePickers/LegacyDateTimePickers/generator.test.js
packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js
packages/components/stories/List.js
packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/queryClient/tql.js
packages/faceted-search/src/queryClient/tql.test.js

TQL creation do not works for badge numbers.
I write a wrong unit test which have value as a string instead of a number. With that, all is good.
But the badge number return a number, not a string.
The problem come from `isNotEmptyOrNull` function which do not return a boolean and not handle numbers for now.
Fix the `isNotEmptyOrNull` function and tests.

fix(faceted-search/queryClient): Fix TQL creation function with numbers

---

packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
packages/forms/src/UIForm/lang.js

Errors message for minimum and maximum items of arrays is too technical for user. We don't want to talk about `array` in message as it's an abstract notion.
We checked with the technical documentation team to use this new words: 
- `New element` > `Add`
- `Array is too short ({length}), minimum {minimum}` > `Minimum number of items: {minimum}`
- `Array is too long ({length}), maximum {maximum}` > `Maximum number of items: {maximum}`

feat(forms/lang): Update some array messages to be more readable

---

packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
packages/components/src/RichTooltip/RichLayout/RichLayout.test.js
packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
packages/components/stories/RichTooltip.js

The popover is visible in the list while the popover has the focus.
A button lost his focus if we set it to disabled. So the focus is lost on the popover.
Add a function to add the focus on the popover

feat(components): richlayout with forwardref

---

packages/components/src/SidePanel/SidePanel.scss

https://jira.talendforge.org/browse/TMC-18418
Firefiox does not handle % in calc, because of this simplebar does not work, as it expects height to be set
Tested in all browsers except Safari, would be nice if someone could help and test in it

fix(TMC-18418): simplebar-does-not-work-in-firefox

---

packages/cmf/__tests__/expressions/index.test.js
packages/cmf/src/expressions/allOf.js
packages/cmf/src/expressions/index.js
packages/cmf/src/expressions/index.md

When you try to check at least two permissions using _cmf expression_, you are stuck.
Let's introduce `allOf` two check several values from _cmf collections_

feat(cmf): allOf expression

---

packages/forms/src/UIForm/utils/validation.js

Defining an array, with complex items with conditions introduce a failure.
When the condition is within an array item, the system tries to resolve the key, injecting the index.
Example:
```javascript
const condition = {
'==': {
key: configuration.filters[].isDynamic,
value: true,
},
};
```
When the condition is evaluation on `configuration.filters[2]` object, it first resolves the condition key to have `configuration.filters[2].isDynamic`, then get the value from form data, and compare it to the condition value.
The issue is due to the call of shouldValidate (same function as shouldRender), where the item key is not passed. So resolving the condition key result in a failure, when we try to get the index from item key, which is undefined. …

fix(UIForm): pass array item key to resolve index in condition

---

packages/components/src/AppLoader/AppLoader.md
packages/containers/.storybook/webpack.config.js
packages/containers/examples/ExampleAppLoader.js
packages/containers/src/AppLoader/AppLoader.connect.js

I want to be able to customise the way we display the app loader.
Basically, I want to display it into a layout component.
I've added a new props onto the `AppLoader` container to be able to customise the way we display it, called `renderer`.
A new story, using the renderer props has been created too.

feat(containers/appLoader): add renderer props to allow customisation

---

packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js

[According to the guidelines](http://guidelines.talend.com/document/92132#/navigation-layout/list), the large mode should allow to display three row plus the title, but :
Increase to row height from 135px to 170px :  

fix(components/virtualizedlist): increase row height in large mode

---

packages/components/src/EditableText/EditableText.scss

In SubHeader when the title is too long the edit icon (the pen) disappears
https://jira.talendforge.org/browse/TFD-8758
the icon is always shown even if the title is long

fix(TFD-8758):  Edit icon disappears when the artifact title is too long

---

packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js
packages/faceted-search/src/components/facetedSearch.propTypes.js
packages/faceted-search/stories/facetedSearch.story.js

badges_per_facet => badgePerFacet
entities_per_badge => entitiesPerBadge
These values are used for now in the code, so the change is non breaking

chore(FacetedSearch): change some field, snake case to camel case

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/dictionary/operator.dictionary.js
packages/faceted-search/src/queryClient/tql.js
packages/faceted-search/src/queryClient/tql.test.js

It's more idiomatic english to use equals (or is equal). Fixing the operator key.

fix(FacetedSearch): Change equal key operator to equals

---

packages/components/package.json
versions/dependencies.js
yarn.lock

The following PR:
https://github.com/Talend/ui/pull/2479/files#diff-8ee2343978836a779dc9f8d6b794c3b2R13727
has added the package `timezone-support` in two different versions.
Effect:
* downgrade our version to align with `date-fns-timezone` one.
* update version script so every project who would like to directly integrate will be aligned.

fix(components): align timezone-support version

---

packages/theme/src/theme/_visual-helpers.scss

Theme uses `:global` which it works when you import it using css-modules loader but not with CSS.
Remove css-modules scope usage

feat(theme): avoid using css-modules

---

output/components.eslint.txt
packages/components/src/AboutDialog/AboutDialog.component.js
packages/components/src/ResourcePicker/ResourcePicker.component.js
packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
packages/components/src/Table/Header/TableSortHeader.js
packages/components/src/Toggle/Checkbox.component.js
packages/components/src/Toggle/Checkbox.js
packages/components/src/Toggle/index.js
packages/components/src/TreeView/TreeView.component.js

Some component rely on other getting them from the index.
This is not friendly with code-splitting
Replace theses import with direct import to it.
This PR is a subpart of #2607 

fix(component): imports

---

packages/components/src/GridLayout/Grid.component.js
packages/components/src/GridLayout/Grid.scss
packages/components/stories/GridLayout.js

It's not possible to disable drag n drop in the grid
Allow to disable drag n drop with a new `isDraggable` prop.

feat(component/grid): allow to disable drag n drop

---

output/components.eslint.txt
packages/components/src/GridLayout/Grid.component.js

I introduced `  5:8  error  'classNames' is defined but never used  no-unused-vars` with my last PR #2613 .
Remove the useless `classnames` import.

fix(components/grid): lint error

---

packages/forms/src/UIForm/fields/Select/Select.component.js
packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap

https://jira.talendforge.org/browse/TCCUI-112
removing the option if there's no placeholder

fix(TCCUI-112): removing empty options when there's no placeholder

---

packages/components/src/VirtualizedList/RowLarge/RowLarge.scss

When hovering RowLarge list item, a horizontal scrollbar appears
Let's hide their action list overflow

fix(components/virtualizedlist): horizontal scrollbar

---

packages/components/src/ActionList/ActionList.scss

PR #2585 removed the uppercase in components' css. But for SidePanel (that uses ActionsList), the items are buttons, and they inherit the buttons css, that transform the text into uppercase.
Set the text transform to `unset` for the side panel items.

fix: remove sidepanel uppercase

---

packages/components/src/ActionList/ActionList.scss

This reverts commit ef14354b6a847a7032e672cbbd4c4a7c85954f45.
We need more control on when to set this rule on each app.
Revert the side panel uppercase removal for now.

Revert "fix: remove sidepanel uppercase (#2627)"

---

packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
packages/components/stories/TreeView.js

https://jira.talendforge.org/browse/TMC-17837
In TMC plan steps are represented by tree view, now need to show corresponding icons if task does not use latest artifact version, or auto upgrade failed

feat(TMC-17837): add tooltip trigger in tree view item icon

---

packages/components/src/PieChart/PieChartButton.test.js
packages/components/src/PieChart/PieChartIcon.component.js
packages/components/src/PieChart/PieChartIcon.test.js
packages/components/src/PieChart/index.js
packages/components/stories/PieChart.js

Bigger pie charts are needed for the dataset overview
Add xlarge and xxlarge displays.

feat(components/piechart): new sizes

---

packages/components/src/Actions/ActionButton/ActionButton.component.js
packages/components/src/Actions/ActionButton/ActionButton.scss
packages/components/src/EditableText/EditableText.scss
packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap

When an EditableText is empty, the submit button is disabled and the display is suddenly broken like this : 
Remove the duplicated button styles (applied on span and button) by removing the span, who seems to be unnecessary.

fix(ActionButton): Remove styles and span

---

packages/components/src/ObjectViewer/ObjectViewer.component.js
packages/components/src/ObjectViewer/ObjectViewer.test.js
packages/components/src/ObjectViewer/convertDate.js

the existing code (made by myself) doesn't handle all the cases, then sometimes there is no conversion from timestamp to ISO String Date
https://jira.talendforge.org/browse/TFD-9265
fix the missing cases

fix(TFD-9265): convert date in sample view

---

packages/components/src/RichTooltip/RichLayout/RichLayout.scss
packages/components/stories/RichTooltip.js

the resource list should take all the width without a container to define it when we wrap it with the RichTooltip
apply flex-grow: 1 when the resource list is wrapped by the component

fix(RichTooltip): the resourceList should take all the width

---

packages/cmf/__tests__/bootstrap.test.js
packages/cmf/src/bootstrap.js
packages/cmf/src/bootstrap.md
packages/cmf/src/cmfModule.merge.js

It is impossible to take an element not in the document to render a CMF app
Add `root` option to bootstrap so you can render a CMF app where you want.

feat(cmf): add root option to target render element

---

packages/components/src/ActionList/ActionList.scss

some letters are cut off at the bottom : 
removing overflow hidden as now the component fits its content

fix(ActionList): make letters fully visible

---

packages/components/src/TreeView/FolderTreeView.stories.js
packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js

Currently the folder tree view component show the talend-folder as the default icon if the icon is not specified.
In some cases, we need to display folder and sub-folders without any icons.
https://jira.talendforge.org/browse/TCCUI-130
Ref:
https://jira.talendforge.org/browse/TMC-16719
Do not render Icon if specified with "icon: none".
http://2691.talend.surge.sh/components/?path=/story/data-tree-foldertreeview--without-icons
Any item in the tree structure can be displayed without icon by specifying the value 'none' for 'icon' property. 
{ 
...,
icon: 'none' 
}

feat(TCCUI-130): folder tree view without icons

---

packages/cmf/__tests__/sagas/http.test.js
packages/cmf/src/sagas/http.js

saga http don't handle the blob type

feat(cmf): handle blob type

---

packages/components/src/Slider/Slider.component.js
packages/components/src/Slider/Slider.stories.js

getTooltipContainer cannot be passed to the handle tooltip
Add getTooltipContainer prop to the Slider component

feat(components/slider): accept getTooltipContainer props

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js

When a filter have only one operator, the badge is always opened on FacetedSearch mount.
This bug comes from #2640 , when we pass over the operator overlay. The `initialOperatorOpened` is never set to false, because this is done on hiding the operator overlay. Because we don't display it, we never fired the hiding method
Like we dispatch an action `closeInitialOpened` to set `initialOperatorOpened` and `initialValueOpened` to false on hiding the operator overlay, we do the same on hiding the value overlay.

fix(faceted-search): Set initialOperatorOpened to false on hiding the value overlay

---

packages/containers/src/GuidedTour/GuidedTour.container.js

The app don't know when the guided tour is closed
send event when onRequestClose is called

feat(GuidedTour): send event when the guided tour is closed

---

packages/components/src/SidePanel/SidePanel.scss

The docked large sidepanel has a wrong width
The docked large panel is 7rem

fix(sidepanel): incorrect docked width

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/dictionary/operator.dictionary.js
packages/faceted-search/src/queryClient/tql.js
packages/faceted-search/src/queryClient/tql.test.js
packages/faceted-search/stories/badgesDefinitions.story.js

In faceted-search package, contains operator is used to check contains in string comparaison. This is great but this TQL operator is case sensitive, that may be annoying for end-user.
To avoid this, this PR implement the `containsIgnoreCase` in operator faceted search dictionary. It have the same label / icon that `contains` operator because at the end, we want to only serve one of these in app.

feat(TDC-3798): Implement containsIgnoreCase operator

---

.travis.yml
.travis/after_success_git.sh

We got some issues with our current audit scan like it's updating the pull request in kind of infinite loop.
Disable it while it's not working as it should be

chore(audit): temporary disable the CI job

---

packages/components/src/Typeahead/Typeahead.component.js
packages/components/src/Typeahead/Typeahead.component.renderers.js
packages/components/src/Typeahead/Typeahead.test.js
packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap

- triggering the logic on onMouseDown prevents onClick event to happen and so pendo can't catch the click
- use data-feature property of the event
- replace event
- use item data-feature property

fix(datalist): dropdown click and item data-feature

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/dictionary/helpers.dictionary.js
packages/faceted-search/src/dictionary/helpers.dictionary.test.js
packages/faceted-search/src/dictionary/operator.dictionary.js
packages/faceted-search/src/index.js

In badge text, we have the `contains` operator and recently the new `containsIgnoreCase`. But in a end-user perspective, it's the same. Due to that, we want to have an helper to remove the `contains` badge in a badge definition only if there is a `containsIgnoreCase` operator.
Even if it's an Inventory needs, it can be useful to have this helpers directly exposed by faceted-search package
- Create a function`filterBadgesDefinitionsWithOneContains` to filter badge text and remove `contains` operator if `containsIgnoreCase` is present.
- Expose this helpers directly in the `index.js` package.
- Add tests case
**[ ] This PR introduces a …

feat(TDC-3798): Expose helpers to filter badgeDefinitions operator

---

.storybook/i18n.js
.storybook/sortStories.js

Storybook does not work on IE11 anymore
Storybook does not transpile all imports and IE11 does not support arrow functions
https://github.com/storybookjs/storybook/issues/9242

fix: Storybook on IE11

---

packages/components/src/Typeahead/Typeahead.component.js
packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap

When you start typing and select a suggestion, `onBlur` event is triggered and the selection looks to be random.
Since `onClick` is [needed for usage tracking](https://github.com/Talend/ui/pull/2741), prevent `onMouseDown` event default behavior in order to let calling `onClick` before `onBlur`!

fix(components/datalist): onBlur is called before onClick

---

packages/cmf-cqrs/package.json
packages/cmf/package.json
packages/components/package.json
packages/containers/package.json
packages/datagrid/package.json
packages/faceted-search/package.json
packages/faceted-search/yarn.lock
packages/forms/package.json
packages/html-webpack-plugin/package.json
packages/local-libs-webpack-plugin/package.json
packages/local-libs-webpack-plugin/yarn.lock
packages/router/package.json
packages/router/yarn.lock
packages/sagas/package.json
packages/scripts/package.json
packages/stepper/package.json
packages/storybook-cmf/package.json
yarn.lock

We have security issues in containers package
Direct dependencies
* jest: upgrade ^24.7.1 --> ^24.9.0. After 4 levels of dependencies, it upgrade yargs-parser 11.1.1 --> 13.3.0
(this is done on all packages, not only containers)
Indirect dependencies exact versions
* react-dev-utils: resolve to ^9.1.0 (compatible with current ^9.0.0 that storybook-react depends on). This fix the inquirer@6.2.2 (exact version) that contains the issue.
* tar: resolve to 2.2.2 (compatible with current ^2.0.0)
After

fix(containers): dependencies vulnerabilities

---

packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.test.js

We can't have a data-feature attribute on button with BadgeDelete action.
We need this to have a better data-feature tagging plan in `faceted-search` package.
Passed the props from BadgeDelete to Action component

TDC-3820: Pass props data-feature in BadgeDelete

---

packages/theme/src/theme/_colors.scss

Regal-blue color has changed in guideline
Update the color value in the bootstrap theme

feat(theme): update regal-blue value

---

packages/icons/package.json
packages/theme/package.json
yarn.lock

Icons package has vulnerabilities
Direct dependencies
* svgo: upgrade 0.7.1 --> ^1.3.2. The switch from 0.x to 1.x is due to node requirement >= 4. 0.7.1 was relying on js-yaml 3.6.1 that has vulnerabilities. New version depends on js-yaml 3.13.1 that hasn't.
* webpack-cli: upgrade ^3.1.0 --> ^3.3.11 to upgrade yargs-parser 11.1.1 --> 13.1.2 (3 level of dependencies) 
* webpack: upgrade ^4.19.0 --> ^4.42.1. This impacts theme and icons packages. This removes a vulnerability with serialize-javascript v1.7.0
Indirect dependencies exact versions
* webpack: v4.x is now resolved with 4.42.1 (same as icons and theme packages). This removes a vulnerability with serialize-javascript v1.7.0. It …

fix(icons): dependencies vulnerabilities

---

output/components.eslint.txt
packages/components/src/GridLayout/Grid.component.js

columns and breakpoints props cannot be overridden
allow new columns and breakpoints props

feat(components/gridlayout): authorize to override columns and breakpoints props

---

packages/components/package.json
packages/containers/package.json
packages/datagrid/package.json
packages/faceted-search/package.json
packages/forms/package.json
packages/scripts/package.json
packages/stepper/package.json
packages/theme/package.json
yarn.lock

`Sass-loader v7.2.0` depends on `clone-deep v4.0.1` that depends on `kind-of v6.0.2`.
Upgrade sass-loader to v7.3.1
(This has no incidence on bundles, it is used to lad our style in storybook)

fix: sass-loader transitive vulnerability

---

packages/router/package.json
packages/router/yarn.lock

There are security issues in the router dependencies
Direct dependencies
* babel: upgrade ^7.8.3 --> ^7.8.4. This removes dependency issues from mixin-deep v1.3.1 and set-value v0.4.3
* lodash: upgrade ^4.17.11 --> ^4.17.15
* cmf: upgrade to 5.1.1
Indirect dependencies exact version
* minimist: resolve to 1.2.5 (compatible with the current 1.x)
* lodash.merge: resolve to 4.6.2 (compatible with current ^4.6.1)
* acorn: resolve ^6.0.1 to 6.4.1
After

fix(router): dependencies vulnerabilities

---

packages/html-webpack-plugin/.eslintrc
packages/html-webpack-plugin/index.test.js
packages/html-webpack-plugin/jest.config.js
packages/html-webpack-plugin/package.json
packages/html-webpack-plugin/talend-scripts.json
packages/html-webpack-plugin/yarn.lock

The custom @talend/html-webpack-plugin has security issues due to tools (eslint, jest, ...). 
Use `@talend/scripts-core`. This is an easy one, it uses only the test script, and is an isolated package
After

chore(html-webpack-plugin): use @talend/scripts

---

packages/cmf-webpack-plugin/package.json
packages/cmf-webpack-plugin/src/index.js
packages/cmf-webpack-plugin/talend-scripts.json
yarn.lock

Migration to talend/scripts: cmf-wbepack-plugin
* use @talend/scripts to build/lint (no tests, lint is not working on master :D )
* fix lint errors

chore(cmf-webpack-plugin): use @talend/scripts

---

packages/components/src/GuidedTour/GuidedTour.component.js

When resolving the dependencies, it take the latest version of reactour in your application.
In the latest minor version, there were a change on some behaviour 
https://github.com/elrumordelaluz/reactour/pull/243/files#diff-b694de960bb460757a01ebeb7eb1a339R7
So if there is a `maskClassName` props defined for the Tour component, the opacity is gone and the render looks like that :
Remove the class as we don't use it anyway

fix(guided-tour): no opacity on background

---

packages/components/src/ActionList/ActionList.component.js

Do we like tooltips ? Yes ✅ 
Do we like double tooltips ? Nooo :x:
As we already use the tooltip trigger on the actions in the sidepanel, the label on the li has no utility. This component (the ActionList) seems to be used only in the sidepanel.
This label was there for an elipsis we don't have anymore.

fix(sidepanel): double tooltip

---

packages/components/package.json
packages/components/test/styleMock.js
packages/containers/package.json
packages/containers/talend-scripts.json
packages/containers/test/styleMock.js
packages/datagrid/package.json
packages/forms/package.json
test-setup.js
yarn.lock

Migration to talend/scripts: components
* customise some eslint rules
This PR does not fix everything. This will be for future PRs
* fix lint errors
* fix tests

chore(containers): use @talend/scripts for build

---

packages/datagrid/.eslintrc
packages/datagrid/babel.config.js
packages/datagrid/package.json
packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
packages/datagrid/src/components/datagrid.component.stories.js
packages/datagrid/src/containers/DataGrid/DataGrid.container.js
packages/datagrid/src/containers/datagrid.container.stories.js
packages/datagrid/talend-scripts.json
packages/datagrid/test/styleMock.js

Migration to talend/scripts: datagrid
* customise some eslint rules
This PR does not fix everything. This will be for future PRs
* fix lint errors
* fix tests

chore(datagrid): use @talend/scripts for build

---

output/components.eslint.txt
packages/components/src/AppGuidedTour/AppGuidedTour.component.js
packages/components/src/AppGuidedTour/AppGuidedTour.test.js
packages/components/src/AppGuidedTour/DemoContentStep.component.js
packages/components/src/AppGuidedTour/DemoContentStep.component.test.js
packages/components/src/AppGuidedTour/DemoContentStep.scss
packages/components/src/AppGuidedTour/__snapshots__/DemoContentStep.component.test.js.snap

The demo content can take a lot a time to importent the content.
Add a message to inform them that this step can take a lot a time

fix(GuidedTour): add loading message

---

packages/forms/babel.config.js
packages/forms/package.json
packages/forms/talend-scripts.json
yarn.lock

Migration to talend/scripts: forms
This PR does not fix everything. This will be for future PRs
* fix lint errors
* fix tests

feat(forms): use @talend/scripts for build

---

packages/icons/package.json
packages/icons/scripts/react.js
yarn.lock

Migration to talend/scripts: icons
* remove babel dependencies, and pull @talend/scripts-config-babel
* require babel config from @talend/scripts-config-babel, to be used in the script that generate the react bundle from svg files.

feat(icons): use @talend/scripts

---

packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
packages/components/src/DataViewer/RecordsViewer/Leaf/__snapshots__/RecordsViewerLeaf.test.js.snap
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss

https://jira.talendforge.org/browse/TFD-10234
With TPD using those components to display the preview, we need to add an option to display types of data to have the same functionality as before.
Add an option that add types display on each leaf. By default no enabled.

feat(TFD-10234): Add optionnal display of types

---

packages/stepper/babel.config.js
packages/stepper/package.json
packages/stepper/talend-scripts.json
packages/stepper/test/styleMock.js
yarn.lock

Migration to talend/scripts: stepper

chore(stepper): use @talend/scripts

---

packages/storybook-cmf/babel.config.js
packages/storybook-cmf/package.json
packages/storybook-cmf/talend-scripts.json

Migration to talend/scripts: storybook-cmf

chore(storybook-cmf): use @talend/scripts

---

packages/cmf/scripts/cmf-settings.i18n.test.js
packages/components/src/Skeleton/Skeleton.component.js
packages/datagrid/jest.config.js
packages/datagrid/src/components/DataGrid/DataGrid.component.js
packages/datagrid/src/components/DataGrid/DataGrid.test.js
packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.component.js
packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.test.js
packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultCellRenderer.test.js.snap
packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.component.js
packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.test.js
packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
test-setup.js

Datagrid tests fails with the @talend/script usage.
Fix them

chore(datagrid): fix tests with @talend/scripts

---

output/components.eslint.txt
packages/components/src/List/ListComposition/ListComposition.stories.js
packages/components/src/VirtualizedList/CellBoolean/BooleanColumn.component.js
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.component.js
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.scss
packages/components/src/VirtualizedList/CellBoolean/CellBoolean.test.js
packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap

On a TDC view (Custom Attributes) we have to show the booleans values with a icon this way.
Let's put that in common

feat(List): Boolean Cell with Icon

---

output/components.eslint.txt
packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js
packages/components/src/DateTimePickers/DateTime/datetime-extraction.js
packages/components/src/DateTimePickers/DateTime/datetime-extraction.test.js
packages/components/src/DateTimePickers/InputDateTimePicker/DateTimePicker.stories.js

1. Date value is not shown in the Date field if time is not specified.
2. Form submit doesn't show any error in such case.
The issue is only with the string DateTime input.
https://jira.talendforge.org/browse/TCCUI-135
show date value if specified without time and also throw error if validation fails
http://2800.talend.surge.sh/components/?path=/story/form-controls-datepicker-datetime--text-input

fix(TCCUI-135) - show date value if specified without time

---

packages/forms/__mocks__/data.js
packages/forms/src/UIForm/UIForm.component.js
packages/forms/src/UIForm/UIForm.component.test.js
packages/forms/src/UIForm/Widget/Widget.component.js

The separator is hard-coded to _ and it is annoying when the key property path contains values with _ within it.
The separator can be configured so a non-problematic value can be provided.

feat(forms): parameterize id concatenation separator

---

packages/components/src/DataViewer/Core/Tree/Tree.scss
packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.scss
packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
packages/components/src/DataViewer/RecordsViewer/Branch/RecordsViewerBranch.component.js
packages/components/src/DataViewer/RecordsViewer/Branch/__snapshots__/RecordsViewerBranch.test.js.snap
packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
packages/components/src/DataViewer/RecordsViewer/Leaf/__snapshots__/RecordsViewerLeaf.test.js.snap
packages/components/src/DataViewer/RecordsViewer/RecordsViewer.scss
packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.scss
packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.test.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss
packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/DefaultValueRenderer.test.js.snap
packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap
packages/components/src/DataViewer/Virtualized/TreeCellMeasurer/TreeCellMeasurer.component.js

In hierarchical view, if a value is too long for the line, it is shrink with an ellipsis and the full value is shown in a tooltip. The property name is shrink too in some cases.
We want to have another behaviour. The property name should never be truncated, and if the value is too long for the remaining space, it is shrink with an ellipsis. But we have a new button available on the line to expand the value and display it fully.

feat(components): Handle long values in RecordsViewer

---

packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
packages/components/src/Badge/Badge.component.js
packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
packages/components/src/ListView/ListView.component.js

Forms have snapshots changes because it now ouputs defaultProps.
Talend/scripts comes with a react-i18next mock that impacts enzyme selectors, because it changes the name of the components that are wrapped in withTranslation HOC.
This is a little refacto
- replacing some defaultProps with js default value. This is ok as the react team plans to deprecate default props in the future in favor of default values.
- replace some withTranslation HOC by useTranslation hook …

chore(components): some refacto for forms snapshots

---

packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperator.scss

https://jira.talendforge.org/browse/TMDM-14276
As with jira TMDM-14276, The Web UI has a display issue for IE11.
Add new CSS style that only effect IE11 and Edge to fix the issue. 
For the display effect, pls see the attachment in jira(https://jira.talendforge.org/browse/TMDM-14276)

fix(BadgeOperator/TMDM-14276) IE11 : Center icons faceted

---

output/components.eslint.txt
packages/containers/src/ComponentForm/ComponentForm.component.js
packages/containers/src/ComponentForm/ComponentForm.test.js

The container dispatches a event when the definitionURL changed. We want to save the data typed before by the user on the action ON_DEFINITION_URL_CHANGED.
pass the actual properties on the event 

feat(containers/forms): pass actual properties when change the definitionURL

---

packages/theme/src/theme/_visual-helpers.scss

We currently have a broken display on Safari. Buttons in the header bar or the side panel (at least) have a box-shadow effect that goes completly wild on Safari. We have white blocks over the content instead of a nice shadow effect.
There is some screenshots in the following Jira: https://jira.talendforge.org/browse/TFD-10461
You can see it yourself in SB with any of the themed story of the header bar (like http://localhost:6006/?path=/story/navigation-headerbar--%F0%9F%8E%A8-portal-headerbar)
The issue seems related to some huge values in the box-shadow definition, leading to this strange interpretation by Safari.
I have changed the values to have more relevant values and have the same …

fix(theme): Fix box-shadow on Safari

---

packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/README.md
packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
packages/forms/stories-core/json/fieldsets/core-collapsibleFieldset.json

https://jira.talendforge.org/browse/TMDM-14604
- `CollapsibleFieldset` not support description
- Reference widget `Message` to display description for `CollapsibleFieldset`

feat(CollapsibleFieldset/TMDM-14604): display description

---

packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
packages/components/src/Actions/ActionIconToggle/IconToggle.stories.js
packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
packages/components/src/List/Toolbar/DisplayModeToggle/__snapshots__/DisplayModeToggle.test.js.snap
packages/components/src/ResourceList/Toolbar/StateFilter/__snapshots__/StateFilter.snap.test.js.snap
packages/containers/src/ActionIconToggle/__snapshots__/ActionIconToggle.test.js.snap
packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.js

We should be able to show a little _tick_ on the action icon toggle.

feat(component/actionicontoggle): add tick

---

packages/components/src/DataViewer/DataViewer.stories.js
packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.test.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap

We can choose to display or not type of data. But we can't customise it.
Add the possibility to use a custom render to display types.

feat(component): Allow to customize RecordsViewer types render

---

packages/components/src/DataViewer/ModelViewer/ModelViewer.container.js
packages/components/src/DataViewer/ModelViewer/ModelViewer.parser.test.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.test.js
packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap

the schema provides a new property talend.component.label to show the label for a row
handle this property

feat(DataViewer): Dataset should leverage the new name in avro format

---

output/components.eslint.txt
packages/components/src/TabBar/TabBar.component.js
packages/components/src/TabBar/TabBar.scss

When we use the TabBar component in responsive mode, it use a Dropdown instead of a classic Nav.
But in this mode, the tab content is no longer displayed.
A gif can be seen in this Jira: https://jira.talendforge.org/browse/TFD-10784
The issue was caused by the fact that we don't have the Tab.Container when using Dropdown. Without the active key management it provides, tabs were not aware of it.
So I modified the component to always have this container.

fix(component): Fix TabBar with Dropdown

---

packages/components/jest.config.js
packages/components/src/AboutDialog/AboutDialog.snapshot.test.js
packages/components/src/ActionBar/ActionBar.snapshot.test.js
packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
packages/components/src/ActionIntercom/Intercom.component.test.js
packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
packages/components/src/Actions/ActionButton/ActionButton.test.js
packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
packages/components/src/DateTimePickers/Date/Picker/Picker.component.test.js
packages/components/src/DateTimePickers/DateRange/Picker/Picker.component.test.js
packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/DateTimePicker.test.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/YearPicker/YearPicker.test.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.component.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/index.js
packages/components/src/DateTimePickers/LegacyDateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.test.js
packages/components/src/DateTimePickers/pickers/CalendarPicker/__snapshots__/CalendarPicker.test.js.snap
packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js
packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap
packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js
packages/components/src/DateTimePickers/views/HeaderTitle/index.js
packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
packages/router/package.json
test-setup.js

Components tests must be adapted to talend/scripts jest/enzyme/mock versions
Fix a part of them

fix(Components): tests with @talend/scripts

---

packages/components/src/InlineMessage/InlineMessage.scss

https://jira.talendforge.org/browse/TCCUI-167
link has a large margin, so after discussion with ux size was changed to 1ch
Apply new link margin size from the guideline

fix(TCCUI-167): change link margin size

---

packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.test.js
packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.js
packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js

We're doing a POC for using column chooser in one of the list in TMC([jira](https://jira.talendforge.org/browse/TMC-20889)). One issue I encounter is that there's no key in columns data submitted by column chooser when click 'Apply'. Without the key it's hard to identify the column.
Add key in columns data.
http://2838.talend.surge.sh/components/?path=/story/data-list-column-chooser--default

fix(components/ColumnChooser): add key in columns config

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.scss
packages/faceted-search/src/components/Badges/BadgeTags/BadgeTagsForm.component.js
packages/faceted-search/src/components/Badges/BadgeTags/index.js
packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.js
packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
packages/faceted-search/src/components/facetedSearch.propTypes.js
packages/faceted-search/src/dictionary/badge.dictionary.js
packages/faceted-search/stories/badgesDefinitions.story.js
packages/faceted-search/stories/facetedSearch.story.js

We want to add a new badge for handle tags with this specific behavior:
- An async callback to get the values on mount (handle by the host application, mock in storybook)
- An action button to show all or to show only selected values.
Screenshots can be find on the JIRA: [https://jira.talendforge.org/browse/TDC-3908](https://jira.talendforge.org/browse/TDC-3908)
Add the new badge in faceted-search package, based on the existing badges.

feat(TDC-3908): Add badge tags in faceted-search

---

packages/components/src/Drawer/Drawer.stories.js
packages/components/src/Layout/OneColumn/OneColumn.scss

Layout in 1-column mode doesn't contain its content well, the drawers is position is absolute and takes 100% of the page height instead of 100% of the main height.
2-column mode has a `position:relative` on the main box to contains that. Let's add it in 1-column mode too

fix(Layout): Drawer with layout 1 column

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js

There is a regression in last version: faceted-search: An error is up if there is no callbacks props to BasicSearch.
Just improve the condition before trying to access in a function from callbacks object.

fix(faceted-search): Avoid error when there is no callbacks props

---

packages/components/src/InlineMessage/InlineMessage.component.js
packages/components/src/InlineMessage/InlineMessage.scss
packages/components/src/InlineMessage/__snapshots__/InlineMessage.snapshot.test.js.snap

https://jira.talendforge.org/browse/TCCUI-167
Link margin is too big, so was changed in guidelines
Change link margin-left from 1ch to 0.35rem

fix(TCCUI-167): change link left margin according to guidelines

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/CRUDBadges.js

When adding a new badge and then deleting it in the faceted search component with IE11 or Edge, it throws an error. 
more details please check:
https://jira.talendforge.org/browse/TMDM-14668
Add checking for var index to ensure its value is valid for **setBadge** function.

fix(faceted-search): check badge existence before trying to set it

---

packages/containers/src/SidePanel/SidePanel.connect.js

On Mac if we try to use the shortcut CMD+Click to open the link to another tab, it does not work.
in the function onClick add a condition to not execute preventDefault and stopPropagation if the metakey or the ctrlkey is set to true

fix(containers/SidePanel): improve management of metakey and ctrlkey

---

output/components.eslint.txt
packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap

Delete icon is present even if no filters are applied
Hide it when there are no filters 

fix(faceted): hide delete icon if no filters

---

packages/containers/src/ActionButton/ActionButton.connect.js
packages/containers/src/ActionButton/ActionButton.test.js
packages/containers/src/ActionButton/__snapshots__/ActionButton.test.js.snap
packages/containers/src/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
packages/containers/src/Badge/Badge.test.js
packages/containers/src/EditableText/__snapshots__/EditableText.test.js.snap
packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap
packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
packages/containers/src/Redirect/__snapshots__/Redirect.test.js.snap
packages/containers/src/SidePanel/__snapshots__/SidePanel.test.js.snap
packages/containers/src/SubHeaderBar/SubHeaderBar.container.js
packages/containers/src/SubHeaderBar/SubHeaderBar.test.js
packages/containers/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap

_WARNING: this is to merge to jsomsanith/chore/talend_scripts because of eslint rules at root. It conflicts with talend/scripts config and breaks the lint. Let's move all packages to @talend/scripts before the merge to master._
Containers tests with @talend/scripts fail
Fix them

chore(container): use @talend/scripts for tests

---

.travis/after_success_lint.sh

In talend/scripts branch, the CI loops because it outputs the run time that changes everytime. It's due to router lint, that prints all the logs in a file.
Use eslint `-o` option to output the lint result instead

fix(router): linter ci loops

---

packages/components/src/Actions/ActionFile/ActionFile.component.js
packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap

data-feature attribute is not forwarded to label
```
<Action
displayMode="file"
data-feature="preparation.import"
/>
```

fix(ActionFile): data-feature attribute is not forwarded

---

packages/components/src/AppSwitcher/AppSwitcher.component.js
packages/components/src/AppSwitcher/AppSwitcher.component.test.js

The AppSwitcher is not visible if a label is not defined
More details here: https://talend.slack.com/archives/C2N95B1KN/p1593508240037100

Fix(Components): AppSwitcher not visible if label not defined

---

packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.js
packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.test.js

The function used to discover childs schema is returning the wrong schema part for arrays containing objects.
It goes too much deep and returns only a part of the expected schema.
An array has an `items` property in his type, defining the type of his elements.
An object has a `fields` property in his type, defining the type of his properties.
If you take the hierarchical view, when you display an array of object.
The first branch is an array, if you want the type of his childs (the elements), you need to take the `items` property. Here it go deeper and takes the `fields` property of the element. That's the bug.
Remove wrong cases.
**[ …

fix(component): Remove wrong ways to discover schema

---

packages/components/src/AppSwitcher/AppSwitcher.component.js
packages/components/src/HeaderBar/HeaderBar.component.js

AppSwitcher no longer opens apps.
Action and ActionDropdown are not used via Inject

fix(components/AppSwitcher): Inject missing

---

packages/components/src/Slider/Slider.component.js
packages/components/src/Slider/Slider.scss
packages/components/src/Slider/Slider.stories.js

The slider component currently only supports highlighting of its track to a specific index from a start point on left of the scale. In the future, the slider will be used to select values of a specific index only or starting from an index up to an end value. In these cases, the slider component needs to be able to highlight the relevant part of its track based on the usage/context scenario.
The slider will now support additional usage contexts through the addition of two parameters. These parameters will activate modifier CSS classes which change the visual appearance of the slider track. The change is a visual one only and the functional behaviour of the slider is unchanged. The new …

feat(TDC-1501/components/slider): add support for new operator modes

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.test.js

The `isSelected` method exposed by the hook may throw an error when using lazy loaded list
This method is passed down to `react-virtualized` that uses this method to define wether or not an item is checked.
In the case of lazy loaded lists, there might be a case where this method is called on undefined entries (that case where I noticed the issue : reloading the whole collection but only reloading a specific chunk of the collection, meaning the collection looks like the following snippet 👇).
```
[
0: null,
... // (items 0 to 150 are not loaded)
150 : null,
151 : { my: 'item' },
152 : { my: 'item' },
...
]
```
Support unloaded items. …

fix(ListComposition): selection with lazy loaded list (2)

---

output/components.eslint.txt
packages/components/src/Datalist/Datalist.component.js
packages/components/src/Datalist/Datalist.component.test.js
packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
packages/components/src/Typeahead/Typeahead.component.js

https://jira.talendforge.org/browse/TCCUI-178
There is a regression with the datalist after the recent changes with the DataList component.
Suggestions are not displayed on click when the focus is already within the datalist
Regression from,
https://github.com/Talend/ui/pull/2753
and
https://github.com/Talend/ui/pull/2741
show suggestions when clicking on the datalist
http://2886.talend.surge.sh/components/?path=/story/form-controls-datalist--default-multisection

fix(TCCUI-178) - show suggestions when clicking on the datalist

---

package.json
yarn.lock

upgrade "lodash" version due to vulnerabilities in current one used (prototype pollution)
Update to the version 4.17.19

Fix(Security): Update version of lodash

---

package.json

With the github action PR to publish the packages, I removed by mistake the build-demo script, that is used in the action.
Restore it

chore: set back the build-demo npm script

---

packages/components/src/AppGuidedTour/AppGuidedTour.component.js
packages/components/src/AppGuidedTour/AppGuidedTour.stories.js
packages/components/src/AppGuidedTour/AppGuidedTour.test.js

It not possible to use the component without providing demo content steps
Make the props optional and hide the toggle if not provided

feat(AppGuidedTour): Make demo content optional

---

packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js

Unlike `ActionButton` or `ActionDropdown`, the `ActionIconToggle` component does not manage the ref to the button.
But for example, if you want to use this kind of button with a popover, the ref is needed to display the popover at the right place.
Add the missing `buttonRef` prop to `ActionIconToggle`, keeping the name used in other components.

fix(components): ActionIconToggle now handle the ref to the button

---

.github/workflows/release.yml

GH release action fails on building the demo because it doesn't resolve lerna: we don't install dependencies before
Install dependencies

chore: install dependencies before trying to build demo in gh release action

---

output/components.eslint.txt
packages/components/src/Slider/Slider.component.js
packages/components/src/Slider/index.js
packages/containers/src/Slider/__snapshots__/Slider.test.js.snap

`SLIDER_MODE` was not exported
`step` was not passed to `rc-slider`
It was not possible to hide the tooltip
Export `SLIDER_MODE`
Add `step` prop
Add `hideTooltip` prop

feat(components/slider): improve slider api

---

package.json
packages/faceted-search/yarn.lock
yarn.lock

The faceted search package has is own lifecycle, so it don't need to be part of the workspace configuration
Remove it from the yarn workspace

chore(faceted-search): remove it from yarn workspace

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.test.js
packages/faceted-search/stories/badgesDefinitions.story.js

Error messages were not embedded in slider facet
There was a bug when min and max are not 0 and 100
Fix the issue and embed error messages

feat(faceted): embed error messages in slider facet

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.js
packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js

With `echap`, it's possible to submit `null` 
Solve it by fallbacking on `defaultValue`

fix(faceted): fallback to default for slider facet

---

packages/datagrid/src/components/DataGrid/DataGrid.scss

https://jira.talendforge.org/browse/TFD-11323
In Safari, `height: 100%` is more strict than in other browsers. So all "levels" in the dom should have the `heigth` property to allow percentage to be properly computed. It does not take in account flex properties when height is used.
So the default style 
```
.ag-root-wrapper-body.ag-layout-normal {
flex: 1 1 auto;
height: 0;
min-height: 0;
}
```
is considered to have a heigth of 0. So children with `heigth: 100%` comes with a heigth of 0.
Chome and Firefox considers the flex heigth.
Add the `heigth` property to the missing internediate level.

fix(datagrid): Fix height calculation in Safari

---

packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js

When a lazy loaded list is filtered/sorted, the selection is supposed to be cleared, so we need a way to reset that selection.
Expose `setSelectedIds`.
Did not add test because that would equal testing `useState`'s setter.

feat(ListComposition/useCollectionSelection): Expose setSelectedIds

---

output/components.eslint.txt
packages/components/src/Enumeration/Enumeration.component.js
packages/components/src/Enumeration/Enumeration.stories.js
packages/components/src/Enumeration/Items/Items.component.js

In TMC we have a use case of Enumeration to custom actions base on item data. Currently Enumeration doesn't support custom actions, all items share actions props.
Let user pass in a function instead of array, which returns custom actions base on item data.
Story: http://2923.talend.surge.sh/components/?path=/story/form-controls-enumeration--with-custom-actions

feat(components/Enumeration): Support custom actions for Enumeration item

---

output/components.eslint.txt
packages/components/src/List/ListComposition/Manager/hooks/__snapshots__/useCollectionSort.hook.test.js.snap
packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.test.js

feat(components/list): use natural sort order

---

output/forms.eslint.txt
packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js

Datalist async tests are using a setTimeout trick
Use jest async tests

fix(forms/datalist): improve datalist async tests

---

packages/http/README.md

In the http package, documentation about using generator is a little bit wrong: We can't do an `import { http } from '@talend/http/generators'`, it's missing a `/lib`.
Just fix the Readme

fix(http): Fix import generator documentation

---

output/components.eslint.txt
packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/HeaderBar/HeaderBar.stories.js
packages/components/src/HeaderBar/HeaderBar.test.js

We want to be able to inject a custom Intercom component in the HeaderBar.
Accept a new prop `Intercom` that receives the rendered Intercom component. This prop has precedence over the `intercom` configuration object.

feat(components/HeaderBar): Accept custom Intercom component

---

packages/components/src/Badge/Badge.component.js
packages/components/src/Badge/Badge.scss
packages/components/src/Badge/Badge.stories.js
packages/components/src/Badge/BadgeComposition/BadgeDropdown/BadgeDropdown.component.js
packages/components/src/Badge/BadgeComposition/BadgeDropdown/BadgeDropdown.component.test.js
packages/components/src/Badge/BadgeComposition/BadgeDropdown/__snapshots__/BadgeDropdown.component.test.js.snap
packages/components/src/Badge/BadgeComposition/BadgeDropdown/index.js
packages/components/src/Badge/BadgeComposition/index.js

Enhance the Badge component to add support for dropdown
https://jira.talendforge.org/browse/TCCUI-188
add badge type dropdown
http://2937.talend.surge.sh/components/?path=/story/navigation-badge--default

feat(TCCUI-188): add badge type dropdown

---

packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/ColumnChooserHeader.component.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/__snapshots__/ColumnChooserHeader.component.test.js.snap
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/RowCheckbox.component.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/SelectAllColumnsCheckbox.component.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/SelectAllColumnsCheckbox.component.test.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/__snapshots__/SelectAllColumnsCheckbox.component.test.js.snap
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap

https://jira.talendforge.org/browse/TMC-22491
Update some labels in Column chooser
1. Title
Old: Modify columns
New: Select columns to display
2. Sub title
Old: x/x selected column
New: x/x selected
3. Label for main checkbox
Old: Columns
New: Select all

feat(components/Column Chooser): Column chooser label update

---

packages/theme/src/theme/_variables.scss

`$brand-primary` was customizable
Now, brand-primary is set to `$regal-blue` by default for all.
http://guidelines.talend.com/document/92132#/design-principles/colors-theme-in-apps

feat(theme): brand-primary is not customizable anymore

---

packages/components/src/HeaderBar/HeaderBar.component.js
packages/components/src/HeaderBar/HeaderBar.scss
packages/components/src/HeaderBar/HeaderBar.test.js

Intercom component is part of the header bar, which is an unordered list (ul).
When injecting a custom Intercom component, that component must include the proper list element tag (li) in order to not break semantics.
- Always include list element tag (li) around Intercom component (injected or default)
- Apply default Intercom styles only to default Intercom

feat(components/HeaderBar): Fix Intercom semantic

---

packages/components/src/Badge/Badge.component.js
packages/components/src/Badge/Badge.scss

The focus state border on Badge with dropdown needs to be improved to show the border on the whole Badge
https://jira.talendforge.org/browse/TCCUI-188
Add border on the whole badge and remove the outline from the dropdown element
http://2946.talend.surge.sh/components/?path=/story/navigation-badge--default

feat(TCCUI-188) - show border on focus

---

packages/components/src/AppGuidedTour/AppGuidedTour.component.js

the welcome step cannot be disabled
allow disabling welcome step by passing `false` to the `disabledWelcomeStep` prop

feat(component/guidedtour): allow to disable welcome step

---

packages/icons/src/svg/core/play.svg

The icon was not centered in its own container
https://jira.talendforge.org/browse/TFD-11084
The icon has been updated

feat(icon): update play.svg

---

output/components.eslint.txt
packages/components/src/RadarChart/RadarChart.component.js

Adds support for Pendo event tracking on clickable radar chart labels. Required as part of [TDC-4653](https://jira.talendforge.org/browse/TDC-4653)
Add the Pendo `data-feature` attribute to the `RadarChart.LabelWithClick` component.

feat(components/RadarChart): Event tracking support

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js

When a badge with a default operator is added (checkbox, text, ...), the value tooltip will pop on each time the faceted search will be mounted.
Set `initialOperatorOpened` and `initialValueOpened` to `false` when submitting the value.

fix(faceted-search): don't reopen the value tooltip for badges with default operator

---

packages/theme/src/theme/_variables.scss

Since few years, the body font color of our apps is no longer `$black` : 
Set `$text-color` to `$black`

fix(theme): body fonts should be black

---

packages/components/src/HeaderBar/HeaderBar.component.js
packages/containers/src/index.js

AppSwitcher wait for getComponent to exists in the props. Since #2952 it is cmfConnected so it removes the getComponent props passed by the HeaderBar which is not required now
with UI 5.20
With UI 5.21 (export reorg)
#2952 change:
remove getComponent props from HeaderBar
cmfConnect AppSwitcher withComponentRegistry to true

fix(TPSVC-15962/AppSwitcher): connect it with component registry

---

packages/forms/package.json
versions/dependencies.json

There is a breaking change in 5.22, the code of forms RHF wrappers are now exported in forms package index.
So any import from index makes the project execute the RHF wrappers code now.
But RHF is in peer dependencies, so projects that don't use RHF don't install it locally.
Move RHF from peer to dependency.

fix(forms): rhf from peer to dependencies

---

packages/forms/src/UIForm/utils/widgets.js

In ui-semantic, Enumeration is imported as a custom widget : 
`<UIForm
widgets={{enumeration: Enumeration}}
/>`
The import path was quite long : 
import Enumeration from '@talend/react-forms/lib/UIForm/fields/Enumeration/EnumerationWidget';
And lint now enforce that the path are not too long (lib/UiForm at most) which ends in error when the above import is encountered.
Loading it as a custom was done in order not to load all the widgets, but in fact all the others are imported in widgets.js, so why not this one ? 

chore(Enumeration): missing for widgets

---

packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.scss

Lists' columns choser should only show 5 columns, and make the columns list scrollable if more need to be shown.
Set a max-height on the containing element

feat(List/ColumnChoser): Max. 5 columns shown

---

packages/containers/6.0 - breaking changes.md
packages/containers/src/AboutDialog/index.js
packages/containers/src/Action/Action.connect.js
packages/containers/src/ActionBar/ActionBar.connect.js
packages/containers/src/ActionButton/ActionButton.connect.js
packages/containers/src/ActionButton/ActionButton.test.js
packages/containers/src/ActionDropdown/ActionDropdown.connect.js
packages/containers/src/ActionDropdown/ActionDropdown.test.js
packages/containers/src/ActionFile/ActionFile.connect.js
packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
packages/containers/src/ComponentForm/ComponentForm.component.js
packages/containers/src/ComponentForm/index.js
packages/containers/src/EditableText/index.js
packages/containers/src/FilterBar/index.js
packages/containers/src/GuidedTour/index.js
packages/containers/src/HeaderBar/index.js
packages/containers/src/List/index.js
packages/containers/src/SubHeaderBar/index.js
packages/containers/src/TabBar/index.js
packages/containers/src/cmfModule.js
packages/containers/src/index.js
packages/containers/src/register.js
yarn.lock

Exports will change in 6.0 to support UMD format for CDN.
Prepare that attaching sagas, constants, actions, selectors to their components.

chore(containers): reorganize exports to prepare 6.0

---

packages/containers/src/Notification/index.js

We added actions creators to Notification containers to be able to write `Notification.actions`.
But the content is undefined because we default import nothing as they are named exported.
`import * as actions from './Notification.actions'`
I changed the name from `actionCreators` to `actions` to align the names. It's not a breaking change because it never worked, so I guess never used, so it doesn't break any code.

fix(containers/notification): attach actions to Notification

---

output/components.eslint.txt
packages/components/src/RadarChart/RadarChart.component.js
packages/components/src/RadarChart/RadarChart.stories.js
packages/components/src/RadarChart/RadarChart.test.js

Evidence suggests that when interacting with a radar chart, users are likely to attempt to click on the individual axis dots. At present only interactive axis labels are supported by the RadarChart component. This requirement is tracked in [TDC-4796](https://jira.talendforge.org/browse/TDC-4796). 
Add a new functional component to the RadarChart which will render a clickable axis dot. The dot should be configured in the same way as the existing label component, to meet the contextual needs of an interactive element.

feat(components/RadarChart): Interactive RadarChart axis dots

---

packages/components/src/Drawer/Drawer.component.js
packages/components/src/Drawer/Drawer.stories.js
packages/components/src/Drawer/Drawer.test.js
packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap

On TPD, we need to have multiple actions in a drawer title
Allow to pass a renderProps to render actions

feat(drawer): allow to add actions in title

---

packages/forms/package.json
packages/forms/src/rhf/fields/Input/Input.stories.js
packages/forms/src/rhf/fields/Input/Input.test.js
packages/forms/src/rhf/fields/Input/RHFInput.component.js
versions/dependencies.json
yarn.lock

some feature available in v6 are needed for schema editor form rewrite
Here is the guide for migration from v5 to v6 : https://react-hook-form.com/migrate-v5-to-v6/
When migrating my poc to v6, i've encountered some change in how the library manages FieldArray. If you're using this feature, you might need to check that everything's all right.

chore(forms): upgrading react hook form to v6

---

packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.scss
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/ColumnChooserBody.component.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap

"Select all" should not be part of the scrollable section of the columns chooser
Wrap columns in a container with limited height + overflow management

feat(List/ColumnChoser): Select all non-scrollable

---

output/containers.eslint.txt
output/forms.eslint.txt
packages/containers/src/ActionFile/ActionFile.test.js
packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
packages/containers/src/ComponentForm/fields/MultiSelect/displayMode/TextMode.component.js
packages/containers/src/ComponentForm/fields/NameResolver/NameResolver.component.js
packages/containers/src/ComponentForm/fields/index.js
packages/containers/src/ComponentForm/kit/defaultRegistry.js
packages/forms/src/UIForm/Message/index.js
packages/forms/src/UIForm/fields/Button/SingleButton.component.js
packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
packages/forms/src/UIForm/fields/FieldTemplate/index.js
packages/forms/src/UIForm/index.js

There are some deep imports from modules to modules (ex: `@talend/react-components/lib/MyComponent/utils`).  
But to prepare libraries to CDN we need to import from index.  
A babel plugin allows us to write /lib/MyComponent and it transform it to import from index. But when it's too deep, the plugin doesn't work.
For forms library each part are exposed from a single Form object.
Fix the imports

chore: change deep imports to non deep to prepare cdn

---

packages/faceted-search/CHANGELOG.md
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
packages/faceted-search/stories/facetedSearch.story.js

TDP has badges without  label (= apply to everything)

chore(faceted-search): badges without label

---

packages/components/src/RadarChart/RadarChart.component.js
packages/components/src/RadarChart/RadarChart.test.js

`index` is not passed to the `DotWithClick` `onClick` callback
add it

feat(components/radarchart): pass index to the dotwithclick onclick callback

---

packages/components/src/RadarChart/RadarChart.component.js
packages/components/src/RadarChart/RadarChart.scss
packages/components/src/RadarChart/__snapshots__/RadarChart.test.js.snap

Default Recharts axis label positions are too close to the chart under some conditions. We want to increase the default spacing between chart labels and the chart. 
A bug the Recharts library prevents us from using the expected 'radius' prop to control the draw positions of the axis labels. Instead we use CSS to scale the axis label container and its contents by a small amount, outwards from its centre.

fix(TDC-4797/components/radarchart): Increase chart axis label spacing

---

packages/cmf/src/components/ErrorPanel/ErrorPanel.component.js

CMF apps fall in an infinite render loop when encountering an error.
Break the infinite loop between the `useState` and the `useEffect`.

fix(cmf): Avoid infinite rerender on error page

---

packages/components/src/VirtualizedList/VirtualizedList.stories.js
packages/datagrid/src/components/DataGrid/DataGrid.component.js

1. AGGrid has been updated in #2985 and there is a difference of behavior: when on the first row, and user presses up arrow, it goes in the `navigateToNextCell` is executed. Our handler fails in this case
```
this.gridAPI.getDisplayedRowAtIndex(nextCellPosition.rowIndex).setSelected(true, true);
// rowIndex = -1 we end up with Cannot read property 'setSelected' of undefined
```
2. VirtualizedList SB is failing because of wrong path to get constants
1. check if the index is positive
2. fix the paths

fix: datagrid keyboard regression and VirtualizedList story

---

packages/components/src/Badge/Badge.scss

Color applied to badge is override by .btn-link stype

fix(Badge): Colors are not applied to badge buttons

---

packages/datagrid/src/components/DataGrid/DataGrid.component.js

#3007 fix was not correct. To check if we have to handle datagrid keyboard navigation, we need to check if the next row index is positive.
Fix it

fix: datagrid keyboard navigation

---

output/components.eslint.txt
output/components.sasslint.txt
packages/faceted-search/CHANGELOG.md
packages/faceted-search/package.json
packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperator.scss
packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.js
packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
packages/faceted-search/src/dictionary/badge.dictionary.js
packages/faceted-search/src/hooks/facetedBadges.hook.js
packages/faceted-search/stories/facetedSearch.story.js
packages/faceted-search/yarn.lock

TDP & TDS need colored badges for their filter bars.
Color support is already implemented in the `Badge` component through the `type` props
A `displayType` property is added on the badge definition and forwarded to the `Badge` component

feat(faceted-search): Add colored badge support

---

packages/components/src/QualityBar/QualityBar.component.js
packages/components/src/QualityBar/QualityRatioBar.component.js
packages/components/src/RatioBar/index.js
packages/components/src/index.js

`@talend/react-components` index exports 3 components from RatioBar
- RatioBar
- RatioBarComponent
- RatioBarLine
To avoid too many exports in index, we try to limit it to 1 component by... component :) 
- export a single RatioBar
- attache composition to the component
```diff
-<RatioBarComposition>
+<RatioBar.Composition>
-<RatioBarLine>
+<RatioBar.Line>
```

chore: change RatioBar  composition pattern

---

packages/eslint-config/package.json

* update babel-eslint to 10.1.0
* update eslint to 7.12.1
* update eslint-config-airbnb to 18.2.0
* update eslint-plugin-import to 2.22.1
We want to use new syntaxes in Javascript such as [optional chaining](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Optional_chaining) and the previous version of `babel-eslint` doesn't allow those syntaxes.
I updated babel-eslint to the latest version.
I also updated other npm packages that we use in the API Team products: `eslint`, `eslint-config-airbnb`, and `eslint-plugin-import`.

chore: update eslint libraries

---

packages/components/src/List/ListComposition.stories.js
packages/components/src/List/ListComposition/collection.js
packages/components/src/VirtualizedList/CellIconText/CellIconText.component.js
packages/components/src/VirtualizedList/CellIconText/CellIconText.test.js
packages/components/src/VirtualizedList/CellIconText/__snapshots__/CellIconText.test.js.snap

List cells usually use raw text as `cellData` (especially to keep the default sort working)
enrich cellicontext api in order to use a `getIcon` function at the `columnData` level

feat(components/list): enrich cellicontext api

---

packages/containers/package.json
packages/router/package.json
packages/router/yarn.lock
yarn.lock

In router, the version of cmf is outdated and not compatible with cdn build.
Upgrade

chore(router): upgrade cmf dep

---

output/components.eslint.txt
packages/components/src/AppGuidedTour/AppGuidedTour.stories.js
packages/components/src/GuidedTour/GuidedTour.component.js
packages/components/src/GuidedTour/GuidedTour.stories.js

data-feature can't be added to the let me try button
add a new `lastStepNextButtonDataFeature` property

feat(components/guidedtour): add data-feature to the let me try button

---

packages/forms/src/widgets/fields/Input/Input.component.js
packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.component.js
packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.scss

Nothing shows that the value is required in RHF input (fieldtemplate) : 
adding the "*" to the fieldTemplate: 

chore(RHFInput): use required props to display required star

---

packages/components/src/AboutDialog/AboutDialog.component.js
packages/components/src/AboutDialog/AboutModal.stories.js

We have the version in the cloud product in this modal
Provide a way to remove it if not setup

fix(components/AboutModal): add optional version

---

output/components.eslint.txt
packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js
packages/components/src/List/ListComposition/collection.js

When you try to filter a List with accents or diacritics, you get exact results. 
Normalize input while filtering
https://jira.talendforge.org/browse/TCCUI-201

fix(ListComposition): filter without accents or diacritics

---

output/components.eslint.txt
packages/components/src/List/ListComposition.stories.js
packages/components/src/List/ListComposition/Manager/ListManager.component.js
packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js
packages/components/src/List/ListComposition/TextFilter/TextFilter.component.js
packages/components/src/List/ListComposition/TextFilter/TextFilter.component.test.js

By default, we perform a filter on each property of the resource we're currently listing
Be able to precise on which columns we accept to filter using `<TextFilter applyOn={[ 'some', 'columns', 'keys' ]} />`
https://jira.talendforge.org/browse/TCCUI-201

feat(ListComposition): filter on limited column list

---

packages/containers/.storybook/config.js

Containers storybook is ko because of a wrong use of mock import from cmf.
Fix the mock usage.

fix(containers): import in storybook initialisation

---

output/forms.eslint.txt
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap

Not possible to do something on blur
Adding onBlur to MultiSelectTag props

chore(forms/MultiSelectTag):  adding onBlur callback

---

output/components.eslint.txt
packages/components/src/List/ListComposition.stories.js
packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.test.js
packages/components/src/List/ListComposition/ColumnChooser/index.js
packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.test.js
packages/components/src/List/ListComposition/Manager/ListManager.component.js
packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
packages/components/src/List/ListComposition/VList/VList.component.js
packages/components/src/List/ListComposition/VList/VList.component.test.js
packages/components/src/List/ListComposition/index.js
packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserTable/ColumnChooserTable.component.js

Try to implement ColumnChooser in a list can be a _pain in the ass_
Be able to simply use `<List.ColumnChooser />` in the toolbar to get it for free

feat(components/ListComposition): ColumnChooser

---

packages/cmf/__tests__/cmfModule.merge.test.js
packages/cmf/package.json
packages/cmf/src/cmfModule.merge.js
packages/cmf/src/store.js
yarn.lock

We can't nest the reducer in the modules, so the shape of the store has every module at root level
Nest the reducers

feat(cmf): combine reducers in modules

---

output/forms.eslint.txt
packages/components/src/List/ListComposition/index.js

List constants are not exposed.
Expose them

chore: expose List constants and SelectAll

---

packages/components/src/List/ListComposition.stories.js
packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.test.js

In TMC, we used local storage to keep a record of visible columns, so user don't have to choose columns every time. we would like to have a callback when user submit column changes.
Call props.onSubmit if exist.

feat(components/ColumnChooser): call props.onSubmit if exist

---

output/datagrid.eslint.txt
packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.component.js
packages/datagrid/src/components/DefaultCellRenderer/index.js
packages/datagrid/src/components/index.js
packages/datagrid/src/index.js

The following exports can t be accessed in project using UMD distribution
```javascript
import DATAGRID_PROPTYPES from '@talend/react-datagrid/lib/components/DataGrid/DataGrid.proptypes';
import AvroRenderer from '@talend/react-datagrid/lib/components/DefaultCellRenderer/AvroRenderer.component';
import theme from '@talend/react-datagrid/lib/components/DefaultCellRenderer/DefaultCell.scss';
```
add them
```javascript
import Datagrid from '@talend/react-datagrid';
const DATAGRID_PROPTYPES = Datagrid.components.DataGrid.propTypes;
const AvroRenderer = Datagrid.components.DefaultCellRenderer.AvroRenderer;
const theme = Datagrid.components.DefaultCellRenderer.theme;
```
**Please check if the PR …

fix(datagrid): add missing exports needed for integration

---

packages/containers/src/Form/Form.container.js

Forms related imports are duplicated if we use `MOZ_FORM`
Use already in-use import

fix(containers): use same Forms import

---

packages/components/src/DateTimePickers/index.js
packages/components/src/index.js

```javascript
import InputDateTimeRangePicker from '@talend/react-components/lib/DateTimePickers/InputDateTimeRangePicker';
```
```javascript
import { InputDateTimeRangePicker } from '@talend/react-components/lib/DateTimePickers';
```

fix(components/DateTimePicker): add missing exports

---

packages/forms/.storybook/config.js

IconsProvider is not well setup in forms so for example collapsible fieldset has no icon
fix the setup

fix(forms): icons provider

---

packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
packages/theme/src/theme/_variables.scss

According to the guideline, $jaffa -> #EA8330, is the color we should use for any warning text message and component as well 
TMC QAs opened an issue on the Promotion History collapsible panel wrong colors.
Fixed styles

fix(TMC-23400/CollapsiblePanel): warning colors update

---

output/forms.eslint.txt
packages/components/src/index.js
packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap

We used to import `OverlayTrigger` with its complete path
`@talend/react-components` index exports `OverlayTrigger` of React Bootstrap 
Since nobody seems to import our OverlayTrigger from the index, let's replace it.
Our component still uses React Bootstrap's OverlayTrigger under the hood!

fix(components/OverlayTrigger): import from index

---

packages/components/6.0 - breaking changes.md
packages/components/src/Icon/Icon.component.js
packages/components/src/Icon/Icon.stories.js
packages/components/src/IconsProvider/IconsProvider.component.js
packages/components/src/IconsProvider/README.md

The IconsProvider via context doesn't work in angular apps which has react->ng and ng->react layers. The context is broken.
Make it work without context
- the iconsProvider share a common list of fetching bundles
- the injectIcon() get the icon is it is already in dom, otherwise it waits for all bundles to be fetched to search again and inject the icon.

fix(IconsProvider): make it work without context 

---

packages/components/.storybook/config.js
packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
packages/components/src/HeaderBar/HeaderBar.scss
packages/components/src/HeaderBar/HeaderBar.stories.js
packages/components/src/Icon/Icon.scss

IconsProvider has changed and CSS selectors must change too
Adapt CSS selector for the HeaderBar related logo to preserve colors

fix(components/HeaderBar): Talend logo color
